{
  "name": "Dashboard_Financial_Kimball",
  "compatibilityLevel": 1606,
  "model": {
    "culture": "es-ES",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "es-ES",
    "tables": [
      {
        "name": "Dim_Tiempo",
        "columns": [
          {
            "name": "sk_tiempo",
            "dataType": "int64",
            "sourceColumn": "sk_tiempo",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "fecha",
            "dataType": "dateTime",
            "sourceColumn": "fecha",
            "summarizeBy": "none",
            "formatString": "dd/mm/yyyy"
          },
          {
            "name": "anio",
            "dataType": "int64",
            "sourceColumn": "anio",
            "summarizeBy": "none"
          },
          {
            "name": "mes",
            "dataType": "int64",
            "sourceColumn": "mes",
            "summarizeBy": "none"
          },
          {
            "name": "nombre_mes",
            "dataType": "string",
            "sourceColumn": "nombre_mes",
            "summarizeBy": "none"
          },
          {
            "name": "es_fin_de_mes",
            "dataType": "boolean",
            "sourceColumn": "es_fin_de_mes",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "Dim_Tiempo",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Origen = Sql.Database(ServidorSQL, BaseDatosSQL),",
                "    Tabla = Origen{[Schema=\"dbo\", Item=\"Dim_Tiempo\"]}[Data],",
                "    Columnas = Table.SelectColumns(Tabla, {\"sk_tiempo\", \"fecha\", \"anio\", \"mes\", \"nombre_mes\", \"es_fin_de_mes\"}),",
                "    Tipos = Table.TransformColumnTypes(Columnas, {{\"sk_tiempo\", Int64.Type}, {\"fecha\", type datetime}, {\"anio\", Int64.Type}, {\"mes\", Int64.Type}, {\"nombre_mes\", type text}, {\"es_fin_de_mes\", type logical}})",
                "in",
                "    Tipos"
              ]
            }
          }
        ]
      },
      {
        "name": "Dim_Anio",
        "columns": [
          {
            "name": "anio",
            "dataType": "int64",
            "sourceColumn": "anio",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "Dim_Anio",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Origen = Sql.Database(ServidorSQL, BaseDatosSQL),",
                "    Tiempo = Origen{[Schema=\"dbo\", Item=\"Dim_Tiempo\"]}[Data],",
                "    Anios = Table.Distinct(Table.SelectColumns(Tiempo, {\"anio\"})),",
                "    Tipos = Table.TransformColumnTypes(Anios, {{\"anio\", Int64.Type}})",
                "in",
                "    Tipos"
              ]
            }
          }
        ]
      },
      {
        "name": "Dim_Distrito",
        "columns": [
          {
            "name": "sk_distrito",
            "dataType": "int64",
            "sourceColumn": "sk_distrito",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "id_distrito_bk",
            "dataType": "int64",
            "sourceColumn": "id_distrito_bk",
            "summarizeBy": "none"
          },
          {
            "name": "nombre_distrito",
            "dataType": "string",
            "sourceColumn": "nombre_distrito",
            "summarizeBy": "none"
          },
          {
            "name": "region",
            "dataType": "string",
            "sourceColumn": "region",
            "summarizeBy": "none"
          },
          {
            "name": "poblacion",
            "dataType": "int64",
            "sourceColumn": "poblacion",
            "summarizeBy": "none"
          },
          {
            "name": "salario_promedio",
            "dataType": "double",
            "sourceColumn": "salario_promedio",
            "summarizeBy": "none",
            "formatString": "\"$\"#,0"
          },
          {
            "name": "tasa_desempleo",
            "dataType": "double",
            "sourceColumn": "tasa_desempleo",
            "summarizeBy": "none",
            "formatString": "0.00"
          },
          {
            "name": "tasa_criminalidad",
            "dataType": "double",
            "sourceColumn": "tasa_criminalidad",
            "summarizeBy": "none",
            "formatString": "0.00"
          },
          {
            "name": "es_imputado",
            "dataType": "boolean",
            "sourceColumn": "es_imputado",
            "summarizeBy": "none"
          },
          {
            "type": "calculated",
            "name": "Macro Region",
            "dataType": "string",
            "expression": "SWITCH(TRUE(), Dim_Distrito[region] = \"Prague\", \"Praga\", CONTAINSSTRING(Dim_Distrito[region], \"Moravia\"), \"Moravia\", \"Bohemia\")",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "Dim_Distrito",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Origen = Sql.Database(ServidorSQL, BaseDatosSQL),",
                "    Tabla = Origen{[Schema=\"dbo\", Item=\"Dim_Distrito\"]}[Data],",
                "    Columnas = Table.SelectColumns(Tabla, {\"sk_distrito\", \"id_distrito_bk\", \"nombre_distrito\", \"region\", \"poblacion\", \"salario_promedio\", \"tasa_desempleo\", \"tasa_criminalidad\", \"es_imputado\"}),",
                "    Tipos = Table.TransformColumnTypes(Columnas, {{\"sk_distrito\", Int64.Type}, {\"id_distrito_bk\", Int64.Type}, {\"nombre_distrito\", type text}, {\"region\", type text}, {\"poblacion\", Int64.Type}, {\"salario_promedio\", type number}, {\"tasa_desempleo\", type number}, {\"tasa_criminalidad\", type number}, {\"es_imputado\", type logical}})",
                "in",
                "    Tipos"
              ]
            }
          }
        ]
      },
      {
        "name": "Dim_Cliente",
        "columns": [
          {
            "name": "sk_cliente",
            "dataType": "int64",
            "sourceColumn": "sk_cliente",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "id_cliente_bk",
            "dataType": "int64",
            "sourceColumn": "id_cliente_bk",
            "summarizeBy": "none"
          },
          {
            "name": "sexo",
            "dataType": "string",
            "sourceColumn": "sexo",
            "summarizeBy": "none"
          },
          {
            "name": "edad_corte",
            "dataType": "int64",
            "sourceColumn": "edad_corte",
            "summarizeBy": "none"
          },
          {
            "name": "tipo_disposicion",
            "dataType": "string",
            "sourceColumn": "tipo_disposicion",
            "summarizeBy": "none"
          },
          {
            "name": "segmento_edad",
            "dataType": "string",
            "sourceColumn": "segmento_edad",
            "summarizeBy": "none",
            "sortByColumn": "Orden Segmento"
          },
          {
            "name": "arquetipo_demografico",
            "dataType": "string",
            "sourceColumn": "arquetipo_demografico",
            "summarizeBy": "none"
          },
          {
            "name": "calificacion_pago_desc",
            "dataType": "string",
            "sourceColumn": "calificacion_pago_desc",
            "summarizeBy": "none"
          },
          {
            "name": "Orden Segmento",
            "dataType": "int64",
            "sourceColumn": "Orden Segmento",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "type": "calculated",
            "name": "Cliente",
            "dataType": "string",
            "expression": "\"Cliente \" & Dim_Cliente[id_cliente_bk]",
            "summarizeBy": "none"
          },
          {
            "type": "calculated",
            "name": "Estado del Prestamo",
            "dataType": "string",
            "expression": "VAR e = CALCULATE(MAX(Dim_Estado_Prestamo[Estado]), CALCULATETABLE(Fact_Prestamos)) RETURN IF(ISBLANK(e), \"Sin préstamo\", e)",
            "summarizeBy": "none"
          },
          {
            "type": "calculated",
            "name": "Banda de Capacidad",
            "dataType": "string",
            "expression": "VAR b = CALCULATE(MAX(Fact_Prestamos[banda_capacidad]), CALCULATETABLE(Fact_Prestamos)) RETURN IF(ISBLANK(b), \"Sin préstamo\", b)",
            "summarizeBy": "none",
            "sortByColumn": "Orden Banda Cliente"
          },
          {
            "type": "calculated",
            "name": "Orden Banda Cliente",
            "dataType": "int64",
            "expression": "VAR o = CALCULATE(MAX(Fact_Prestamos[Orden Banda]), CALCULATETABLE(Fact_Prestamos)) RETURN IF(ISBLANK(o), 5, o)",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "type": "calculated",
            "name": "Alerta de Saturacion",
            "dataType": "string",
            "expression": "VAR i = [Indice Saturacion] RETURN SWITCH(TRUE(), ISBLANK(i), \"Sin órdenes\", i > 1, \"Crítica (> 1)\", i > 0.5, \"Alta (> 0.5)\", \"Normal\")",
            "summarizeBy": "none"
          },
          {
            "type": "calculated",
            "name": "Primera Oferta",
            "dataType": "string",
            "expression": "VAR x = CALCULATE(MAX(Recomendacion_Producto[producto]), Recomendacion_Producto[sistema] = \"Demográfico\", Recomendacion_Producto[posicion] = 1) RETURN IF(ISBLANK(x), \"Sin recomendación\", x)",
            "summarizeBy": "none"
          },
          {
            "type": "calculated",
            "name": "Prestamo Recomendado",
            "dataType": "string",
            "expression": "IF(CALCULATE(COUNTROWS(Capacidad_Prestamo)) = 0, \"Sin cuenta propia\", IF(CALCULATE(COUNTROWS(Capacidad_Prestamo), Capacidad_Prestamo[prestamo_recomendado] = TRUE()) > 0, \"Sí\", \"No\"))",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "Dim_Cliente",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Origen = Sql.Database(ServidorSQL, BaseDatosSQL),",
                "    Tabla = Origen{[Schema=\"dbo\", Item=\"Dim_Cliente\"]}[Data],",
                "    Columnas = Table.SelectColumns(Tabla, {\"sk_cliente\", \"id_cliente_bk\", \"sexo\", \"edad_corte\", \"tipo_disposicion\", \"segmento_edad\", \"arquetipo_demografico\", \"calificacion_pago_desc\"}),",
                "    Tipos = Table.TransformColumnTypes(Columnas, {{\"sk_cliente\", Int64.Type}, {\"id_cliente_bk\", Int64.Type}, {\"sexo\", type text}, {\"edad_corte\", Int64.Type}, {\"tipo_disposicion\", type text}, {\"segmento_edad\", type text}, {\"arquetipo_demografico\", type text}, {\"calificacion_pago_desc\", type text}}),",
                "    Orden = Table.AddColumn(Tipos, \"Orden Segmento\", each if Text.Contains([segmento_edad], \"Joven\") then 1 else if Text.Contains([segmento_edad], \"Mayor\") then 3 else if Text.Contains([segmento_edad], \"Adulto\") then 2 else 0, Int64.Type)",
                "in",
                "    Orden"
              ]
            }
          }
        ]
      },
      {
        "name": "Dim_Cuenta",
        "columns": [
          {
            "name": "sk_cuenta",
            "dataType": "int64",
            "sourceColumn": "sk_cuenta",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "id_cuenta_bk",
            "dataType": "int64",
            "sourceColumn": "id_cuenta_bk",
            "summarizeBy": "none"
          },
          {
            "name": "frecuencia_emision_estado",
            "dataType": "string",
            "sourceColumn": "frecuencia_emision_estado",
            "summarizeBy": "none"
          },
          {
            "name": "fecha_apertura",
            "dataType": "dateTime",
            "sourceColumn": "fecha_apertura",
            "summarizeBy": "none",
            "formatString": "dd/mm/yyyy"
          },
          {
            "name": "tiene_credito_externo",
            "dataType": "boolean",
            "sourceColumn": "tiene_credito_externo",
            "summarizeBy": "none"
          },
          {
            "name": "monto_credito_externo",
            "dataType": "double",
            "sourceColumn": "monto_credito_externo",
            "summarizeBy": "none",
            "formatString": "\"$\"#,0"
          },
          {
            "type": "calculated",
            "name": "Cuenta",
            "dataType": "string",
            "expression": "\"Cuenta \" & Dim_Cuenta[id_cuenta_bk]",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "Dim_Cuenta",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Origen = Sql.Database(ServidorSQL, BaseDatosSQL),",
                "    Tabla = Origen{[Schema=\"dbo\", Item=\"Dim_Cuenta\"]}[Data],",
                "    Columnas = Table.SelectColumns(Tabla, {\"sk_cuenta\", \"id_cuenta_bk\", \"frecuencia_emision_estado\", \"fecha_apertura\", \"tiene_credito_externo\", \"monto_credito_externo\"}),",
                "    Tipos = Table.TransformColumnTypes(Columnas, {{\"sk_cuenta\", Int64.Type}, {\"id_cuenta_bk\", Int64.Type}, {\"frecuencia_emision_estado\", type text}, {\"fecha_apertura\", type datetime}, {\"tiene_credito_externo\", type logical}, {\"monto_credito_externo\", type number}})",
                "in",
                "    Tipos"
              ]
            }
          }
        ]
      },
      {
        "name": "Dim_Estado_Prestamo",
        "columns": [
          {
            "name": "sk_estado_prestamo",
            "dataType": "int64",
            "sourceColumn": "sk_estado_prestamo",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "codigo_estado",
            "dataType": "string",
            "sourceColumn": "codigo_estado",
            "summarizeBy": "none"
          },
          {
            "name": "condicion",
            "dataType": "string",
            "sourceColumn": "condicion",
            "summarizeBy": "none"
          },
          {
            "name": "descripcion",
            "dataType": "string",
            "sourceColumn": "descripcion",
            "summarizeBy": "none"
          },
          {
            "type": "calculated",
            "name": "Estado",
            "dataType": "string",
            "expression": "SWITCH(Dim_Estado_Prestamo[codigo_estado], \"A\", \"A · Cerrado al día\", \"B\", \"B · Cerrado con deuda\", \"C\", \"C · Vigente al día\", \"D\", \"D · Vigente en mora\")",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "Dim_Estado_Prestamo",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Origen = Sql.Database(ServidorSQL, BaseDatosSQL),",
                "    Tabla = Origen{[Schema=\"dbo\", Item=\"Dim_Estado_Prestamo\"]}[Data],",
                "    Columnas = Table.SelectColumns(Tabla, {\"sk_estado_prestamo\", \"codigo_estado\", \"condicion\", \"descripcion\"}),",
                "    Tipos = Table.TransformColumnTypes(Columnas, {{\"sk_estado_prestamo\", Int64.Type}, {\"codigo_estado\", type text}, {\"condicion\", type text}, {\"descripcion\", type text}})",
                "in",
                "    Tipos"
              ]
            }
          }
        ]
      },
      {
        "name": "Dim_Orden",
        "columns": [
          {
            "name": "sk_orden_tipo",
            "dataType": "int64",
            "sourceColumn": "sk_orden_tipo",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "k_symbol_original",
            "dataType": "string",
            "sourceColumn": "k_symbol_original",
            "summarizeBy": "none"
          },
          {
            "name": "categoria_orden_traducida",
            "dataType": "string",
            "sourceColumn": "categoria_orden_traducida",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "Dim_Orden",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Origen = Sql.Database(ServidorSQL, BaseDatosSQL),",
                "    Tabla = Origen{[Schema=\"dbo\", Item=\"Dim_Orden\"]}[Data],",
                "    Columnas = Table.SelectColumns(Tabla, {\"sk_orden_tipo\", \"k_symbol_original\", \"categoria_orden_traducida\"}),",
                "    Tipos = Table.TransformColumnTypes(Columnas, {{\"sk_orden_tipo\", Int64.Type}, {\"k_symbol_original\", type text}, {\"categoria_orden_traducida\", type text}})",
                "in",
                "    Tipos"
              ]
            }
          }
        ]
      },
      {
        "name": "Fact_Prestamos",
        "columns": [
          {
            "name": "sk_prestamo",
            "dataType": "int64",
            "sourceColumn": "sk_prestamo",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "sk_tiempo",
            "dataType": "int64",
            "sourceColumn": "sk_tiempo",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "sk_cuenta",
            "dataType": "int64",
            "sourceColumn": "sk_cuenta",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "sk_cliente",
            "dataType": "int64",
            "sourceColumn": "sk_cliente",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "sk_distrito",
            "dataType": "int64",
            "sourceColumn": "sk_distrito",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "sk_estado_prestamo",
            "dataType": "int64",
            "sourceColumn": "sk_estado_prestamo",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "id_prestamo_bk",
            "dataType": "int64",
            "sourceColumn": "id_prestamo_bk",
            "summarizeBy": "none"
          },
          {
            "name": "monto_prestamo",
            "dataType": "double",
            "sourceColumn": "monto_prestamo",
            "summarizeBy": "none",
            "formatString": "\"$\"#,0"
          },
          {
            "name": "plazo_meses",
            "dataType": "int64",
            "sourceColumn": "plazo_meses",
            "summarizeBy": "none"
          },
          {
            "name": "pago_mensual",
            "dataType": "double",
            "sourceColumn": "pago_mensual",
            "summarizeBy": "none",
            "formatString": "\"$\"#,0"
          },
          {
            "name": "meses_transcurridos_al_corte",
            "dataType": "int64",
            "sourceColumn": "meses_transcurridos_al_corte",
            "summarizeBy": "none"
          },
          {
            "name": "saldo_pendiente_estimado",
            "dataType": "double",
            "sourceColumn": "saldo_pendiente_estimado",
            "summarizeBy": "none",
            "formatString": "\"$\"#,0"
          },
          {
            "name": "saldo_promedio_previo",
            "dataType": "double",
            "sourceColumn": "saldo_promedio_previo",
            "summarizeBy": "none",
            "formatString": "\"$\"#,0"
          },
          {
            "name": "ratio_cuota_saldo_previo",
            "dataType": "double",
            "sourceColumn": "ratio_cuota_saldo_previo",
            "summarizeBy": "none",
            "formatString": "0.00%"
          },
          {
            "name": "banda_capacidad",
            "dataType": "string",
            "sourceColumn": "banda_capacidad",
            "summarizeBy": "none",
            "sortByColumn": "Orden Banda"
          },
          {
            "name": "Orden Banda",
            "dataType": "int64",
            "sourceColumn": "Orden Banda",
            "summarizeBy": "none",
            "isHidden": true
          }
        ],
        "partitions": [
          {
            "name": "Fact_Prestamos",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Origen = Sql.Database(ServidorSQL, BaseDatosSQL),",
                "    Tabla = Origen{[Schema=\"dbo\", Item=\"Fact_Prestamos\"]}[Data],",
                "    Columnas = Table.SelectColumns(Tabla, {\"sk_prestamo\", \"sk_tiempo\", \"sk_cuenta\", \"sk_cliente\", \"sk_distrito\", \"sk_estado_prestamo\", \"id_prestamo_bk\", \"monto_prestamo\", \"plazo_meses\", \"pago_mensual\", \"meses_transcurridos_al_corte\", \"saldo_pendiente_estimado\", \"saldo_promedio_previo\", \"ratio_cuota_saldo_previo\", \"banda_capacidad\"}),",
                "    Tipos = Table.TransformColumnTypes(Columnas, {{\"sk_prestamo\", Int64.Type}, {\"sk_tiempo\", Int64.Type}, {\"sk_cuenta\", Int64.Type}, {\"sk_cliente\", Int64.Type}, {\"sk_distrito\", Int64.Type}, {\"sk_estado_prestamo\", Int64.Type}, {\"id_prestamo_bk\", Int64.Type}, {\"monto_prestamo\", type number}, {\"plazo_meses\", Int64.Type}, {\"pago_mensual\", type number}, {\"meses_transcurridos_al_corte\", Int64.Type}, {\"saldo_pendiente_estimado\", type number}, {\"saldo_promedio_previo\", type number}, {\"ratio_cuota_saldo_previo\", type number}, {\"banda_capacidad\", type text}}),",
                "    Orden = Table.AddColumn(Tipos, \"Orden Banda\", each if Text.Contains([banda_capacidad], \"Media-baja\") then 2 else if Text.Contains([banda_capacidad], \"Media-alta\") then 3 else if Text.Contains([banda_capacidad], \"Baja\") then 1 else if Text.Contains([banda_capacidad], \"Alta\") then 4 else 0, Int64.Type)",
                "in",
                "    Orden"
              ]
            }
          }
        ]
      },
      {
        "name": "Fact_Ordenes",
        "columns": [
          {
            "name": "sk_orden",
            "dataType": "int64",
            "sourceColumn": "sk_orden",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "sk_tiempo_apertura_cuenta",
            "dataType": "int64",
            "sourceColumn": "sk_tiempo_apertura_cuenta",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "sk_cuenta",
            "dataType": "int64",
            "sourceColumn": "sk_cuenta",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "sk_cliente",
            "dataType": "int64",
            "sourceColumn": "sk_cliente",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "sk_distrito",
            "dataType": "int64",
            "sourceColumn": "sk_distrito",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "sk_orden_tipo",
            "dataType": "int64",
            "sourceColumn": "sk_orden_tipo",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "id_orden_bk",
            "dataType": "int64",
            "sourceColumn": "id_orden_bk",
            "summarizeBy": "none"
          },
          {
            "name": "monto_orden",
            "dataType": "double",
            "sourceColumn": "monto_orden",
            "summarizeBy": "none",
            "formatString": "\"$\"#,0"
          }
        ],
        "partitions": [
          {
            "name": "Fact_Ordenes",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Origen = Sql.Database(ServidorSQL, BaseDatosSQL),",
                "    Tabla = Origen{[Schema=\"dbo\", Item=\"Fact_Ordenes\"]}[Data],",
                "    Columnas = Table.SelectColumns(Tabla, {\"sk_orden\", \"sk_tiempo_apertura_cuenta\", \"sk_cuenta\", \"sk_cliente\", \"sk_distrito\", \"sk_orden_tipo\", \"id_orden_bk\", \"monto_orden\"}),",
                "    Tipos = Table.TransformColumnTypes(Columnas, {{\"sk_orden\", Int64.Type}, {\"sk_tiempo_apertura_cuenta\", Int64.Type}, {\"sk_cuenta\", Int64.Type}, {\"sk_cliente\", Int64.Type}, {\"sk_distrito\", Int64.Type}, {\"sk_orden_tipo\", Int64.Type}, {\"id_orden_bk\", Int64.Type}, {\"monto_orden\", type number}})",
                "in",
                "    Tipos"
              ]
            }
          }
        ]
      },
      {
        "name": "Fact_Saldo_Cuenta_Mensual",
        "columns": [
          {
            "name": "sk_cuenta",
            "dataType": "int64",
            "sourceColumn": "sk_cuenta",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "sk_mes",
            "dataType": "int64",
            "sourceColumn": "sk_mes",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "sk_cliente",
            "dataType": "int64",
            "sourceColumn": "sk_cliente",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "sk_distrito",
            "dataType": "int64",
            "sourceColumn": "sk_distrito",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "saldo_fin_mes",
            "dataType": "double",
            "sourceColumn": "saldo_fin_mes",
            "summarizeBy": "none",
            "formatString": "\"$\"#,0"
          },
          {
            "name": "saldo_promedio_mes",
            "dataType": "double",
            "sourceColumn": "saldo_promedio_mes",
            "summarizeBy": "none",
            "formatString": "\"$\"#,0"
          },
          {
            "name": "num_movimientos_mes",
            "dataType": "int64",
            "sourceColumn": "num_movimientos_mes",
            "summarizeBy": "none"
          },
          {
            "name": "en_sobregiro",
            "dataType": "boolean",
            "sourceColumn": "en_sobregiro",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "Fact_Saldo_Cuenta_Mensual",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Origen = Sql.Database(ServidorSQL, BaseDatosSQL),",
                "    Tabla = Origen{[Schema=\"dbo\", Item=\"Fact_Saldo_Cuenta_Mensual\"]}[Data],",
                "    Columnas = Table.SelectColumns(Tabla, {\"sk_cuenta\", \"sk_mes\", \"sk_cliente\", \"sk_distrito\", \"saldo_fin_mes\", \"saldo_promedio_mes\", \"num_movimientos_mes\", \"en_sobregiro\"}),",
                "    Tipos = Table.TransformColumnTypes(Columnas, {{\"sk_cuenta\", Int64.Type}, {\"sk_mes\", Int64.Type}, {\"sk_cliente\", Int64.Type}, {\"sk_distrito\", Int64.Type}, {\"saldo_fin_mes\", type number}, {\"saldo_promedio_mes\", type number}, {\"num_movimientos_mes\", Int64.Type}, {\"en_sobregiro\", type logical}})",
                "in",
                "    Tipos"
              ]
            }
          }
        ]
      },
      {
        "name": "vw_PBI_Trans_Anual_Cuenta",
        "columns": [
          {
            "name": "sk_cuenta",
            "dataType": "int64",
            "sourceColumn": "sk_cuenta",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "sk_cliente",
            "dataType": "int64",
            "sourceColumn": "sk_cliente",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "sk_distrito",
            "dataType": "int64",
            "sourceColumn": "sk_distrito",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "categoria_analitica",
            "dataType": "string",
            "sourceColumn": "categoria_analitica",
            "summarizeBy": "none"
          },
          {
            "name": "anio",
            "dataType": "int64",
            "sourceColumn": "anio",
            "summarizeBy": "none"
          },
          {
            "name": "num_transacciones",
            "dataType": "int64",
            "sourceColumn": "num_transacciones",
            "summarizeBy": "none"
          },
          {
            "name": "monto_total",
            "dataType": "double",
            "sourceColumn": "monto_total",
            "summarizeBy": "none",
            "formatString": "\"$\"#,0"
          },
          {
            "name": "suma_cuadrados",
            "dataType": "double",
            "sourceColumn": "suma_cuadrados",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "saldo_promedio",
            "dataType": "double",
            "sourceColumn": "saldo_promedio",
            "summarizeBy": "none",
            "formatString": "\"$\"#,0"
          }
        ],
        "partitions": [
          {
            "name": "vw_PBI_Trans_Anual_Cuenta",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Origen = Sql.Database(ServidorSQL, BaseDatosSQL),",
                "    Tabla = Origen{[Schema=\"dbo\", Item=\"vw_PBI_Trans_Anual_Cuenta\"]}[Data],",
                "    Columnas = Table.SelectColumns(Tabla, {\"sk_cuenta\", \"sk_cliente\", \"sk_distrito\", \"categoria_analitica\", \"anio\", \"num_transacciones\", \"monto_total\", \"suma_cuadrados\", \"saldo_promedio\"}),",
                "    Tipos = Table.TransformColumnTypes(Columnas, {{\"sk_cuenta\", Int64.Type}, {\"sk_cliente\", Int64.Type}, {\"sk_distrito\", Int64.Type}, {\"categoria_analitica\", type text}, {\"anio\", Int64.Type}, {\"num_transacciones\", Int64.Type}, {\"monto_total\", type number}, {\"suma_cuadrados\", type number}, {\"saldo_promedio\", type number}})",
                "in",
                "    Tipos"
              ]
            }
          }
        ]
      },
      {
        "name": "Recomendacion_Cuenta",
        "columns": [
          {
            "name": "sk_cuenta",
            "dataType": "int64",
            "sourceColumn": "sk_cuenta",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "sk_cliente",
            "dataType": "int64",
            "sourceColumn": "sk_cliente",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "modelo",
            "dataType": "string",
            "sourceColumn": "modelo",
            "summarizeBy": "none"
          },
          {
            "name": "recomendacion_1",
            "dataType": "string",
            "sourceColumn": "recomendacion_1",
            "summarizeBy": "none"
          },
          {
            "name": "recomendacion_2",
            "dataType": "string",
            "sourceColumn": "recomendacion_2",
            "summarizeBy": "none"
          },
          {
            "name": "recomendacion_3",
            "dataType": "string",
            "sourceColumn": "recomendacion_3",
            "summarizeBy": "none"
          },
          {
            "name": "prestamo_cuota_maxima",
            "dataType": "double",
            "sourceColumn": "prestamo_cuota_maxima",
            "summarizeBy": "none",
            "formatString": "\"$\"#,0"
          },
          {
            "name": "prestamo_monto_maximo_36m",
            "dataType": "double",
            "sourceColumn": "prestamo_monto_maximo_36m",
            "summarizeBy": "none",
            "formatString": "\"$\"#,0"
          }
        ],
        "partitions": [
          {
            "name": "Recomendacion_Cuenta",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Origen = Sql.Database(ServidorSQL, BaseDatosSQL),",
                "    Tabla = Origen{[Schema=\"dbo\", Item=\"Recomendacion_Cuenta\"]}[Data],",
                "    Columnas = Table.SelectColumns(Tabla, {\"sk_cuenta\", \"sk_cliente\", \"modelo\", \"recomendacion_1\", \"recomendacion_2\", \"recomendacion_3\", \"prestamo_cuota_maxima\", \"prestamo_monto_maximo_36m\"}),",
                "    Tipos = Table.TransformColumnTypes(Columnas, {{\"sk_cuenta\", Int64.Type}, {\"sk_cliente\", Int64.Type}, {\"modelo\", type text}, {\"recomendacion_1\", type text}, {\"recomendacion_2\", type text}, {\"recomendacion_3\", type text}, {\"prestamo_cuota_maxima\", type number}, {\"prestamo_monto_maximo_36m\", type number}})",
                "in",
                "    Tipos"
              ]
            }
          }
        ]
      },
      {
        "name": "Dim_Producto",
        "columns": [
          {
            "name": "producto",
            "dataType": "string",
            "sourceColumn": "producto",
            "summarizeBy": "none",
            "sortByColumn": "orden"
          },
          {
            "name": "codigo",
            "dataType": "string",
            "sourceColumn": "codigo",
            "summarizeBy": "none"
          },
          {
            "name": "descripcion",
            "dataType": "string",
            "sourceColumn": "descripcion",
            "summarizeBy": "none"
          },
          {
            "name": "penetracion",
            "dataType": "double",
            "sourceColumn": "penetracion",
            "summarizeBy": "none",
            "formatString": "0.00%"
          },
          {
            "name": "orden",
            "dataType": "int64",
            "sourceColumn": "orden",
            "summarizeBy": "none",
            "isHidden": true
          }
        ],
        "partitions": [
          {
            "name": "Dim_Producto",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Origen = Sql.Database(ServidorSQL, BaseDatosSQL),",
                "    Tabla = Origen{[Schema=\"dbo\", Item=\"Dim_Producto\"]}[Data],",
                "    Columnas = Table.SelectColumns(Tabla, {\"producto\", \"codigo\", \"descripcion\", \"penetracion\", \"orden\"}),",
                "    Tipos = Table.TransformColumnTypes(Columnas, {{\"producto\", type text}, {\"codigo\", type text}, {\"descripcion\", type text}, {\"penetracion\", type number}, {\"orden\", Int64.Type}})",
                "in",
                "    Tipos"
              ]
            }
          }
        ]
      },
      {
        "name": "Recomendacion_Producto",
        "columns": [
          {
            "name": "sk_cuenta",
            "dataType": "int64",
            "sourceColumn": "sk_cuenta",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "sk_cliente",
            "dataType": "int64",
            "sourceColumn": "sk_cliente",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "sk_distrito",
            "dataType": "int64",
            "sourceColumn": "sk_distrito",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "sistema",
            "dataType": "string",
            "sourceColumn": "sistema",
            "summarizeBy": "none"
          },
          {
            "name": "producto",
            "dataType": "string",
            "sourceColumn": "producto",
            "summarizeBy": "none"
          },
          {
            "name": "posicion",
            "dataType": "int64",
            "sourceColumn": "posicion",
            "summarizeBy": "none"
          },
          {
            "name": "puntaje",
            "dataType": "double",
            "sourceColumn": "puntaje",
            "summarizeBy": "none",
            "formatString": "0.0000"
          },
          {
            "name": "es_descubrimiento",
            "dataType": "boolean",
            "sourceColumn": "es_descubrimiento",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "Recomendacion_Producto",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Origen = Sql.Database(ServidorSQL, BaseDatosSQL),",
                "    Tabla = Origen{[Schema=\"dbo\", Item=\"Recomendacion_Producto\"]}[Data],",
                "    Columnas = Table.SelectColumns(Tabla, {\"sk_cuenta\", \"sk_cliente\", \"sk_distrito\", \"sistema\", \"producto\", \"posicion\", \"puntaje\", \"es_descubrimiento\"}),",
                "    Tipos = Table.TransformColumnTypes(Columnas, {{\"sk_cuenta\", Int64.Type}, {\"sk_cliente\", Int64.Type}, {\"sk_distrito\", Int64.Type}, {\"sistema\", type text}, {\"producto\", type text}, {\"posicion\", Int64.Type}, {\"puntaje\", type number}, {\"es_descubrimiento\", type logical}})",
                "in",
                "    Tipos"
              ]
            }
          }
        ]
      },
      {
        "name": "Adopcion_Producto",
        "columns": [
          {
            "name": "sk_cuenta",
            "dataType": "int64",
            "sourceColumn": "sk_cuenta",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "sk_cliente",
            "dataType": "int64",
            "sourceColumn": "sk_cliente",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "sk_distrito",
            "dataType": "int64",
            "sourceColumn": "sk_distrito",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "producto",
            "dataType": "string",
            "sourceColumn": "producto",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "Adopcion_Producto",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Origen = Sql.Database(ServidorSQL, BaseDatosSQL),",
                "    Tabla = Origen{[Schema=\"dbo\", Item=\"Adopcion_Producto\"]}[Data],",
                "    Columnas = Table.SelectColumns(Tabla, {\"sk_cuenta\", \"sk_cliente\", \"sk_distrito\", \"producto\"}),",
                "    Tipos = Table.TransformColumnTypes(Columnas, {{\"sk_cuenta\", Int64.Type}, {\"sk_cliente\", Int64.Type}, {\"sk_distrito\", Int64.Type}, {\"producto\", type text}})",
                "in",
                "    Tipos"
              ]
            }
          }
        ]
      },
      {
        "name": "Capacidad_Prestamo",
        "columns": [
          {
            "name": "sk_cuenta",
            "dataType": "int64",
            "sourceColumn": "sk_cuenta",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "sk_cliente",
            "dataType": "int64",
            "sourceColumn": "sk_cliente",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "sk_distrito",
            "dataType": "int64",
            "sourceColumn": "sk_distrito",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "tiene_prestamo",
            "dataType": "boolean",
            "sourceColumn": "tiene_prestamo",
            "summarizeBy": "none"
          },
          {
            "name": "saldo_promedio",
            "dataType": "double",
            "sourceColumn": "saldo_promedio",
            "summarizeBy": "none",
            "formatString": "\"$\"#,0"
          },
          {
            "name": "cuota_prudente",
            "dataType": "double",
            "sourceColumn": "cuota_prudente",
            "summarizeBy": "none",
            "formatString": "\"$\"#,0"
          },
          {
            "name": "monto_maximo_12m",
            "dataType": "double",
            "sourceColumn": "monto_maximo_12m",
            "summarizeBy": "none",
            "formatString": "\"$\"#,0"
          },
          {
            "name": "monto_maximo_36m",
            "dataType": "double",
            "sourceColumn": "monto_maximo_36m",
            "summarizeBy": "none",
            "formatString": "\"$\"#,0"
          },
          {
            "name": "monto_maximo_60m",
            "dataType": "double",
            "sourceColumn": "monto_maximo_60m",
            "summarizeBy": "none",
            "formatString": "\"$\"#,0"
          },
          {
            "name": "tramo_monto_36m",
            "dataType": "string",
            "sourceColumn": "tramo_monto_36m",
            "summarizeBy": "none",
            "sortByColumn": "orden_tramo"
          },
          {
            "name": "orden_tramo",
            "dataType": "int64",
            "sourceColumn": "orden_tramo",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "puede_pagar_prestamo_tipico",
            "dataType": "boolean",
            "sourceColumn": "puede_pagar_prestamo_tipico",
            "summarizeBy": "none"
          },
          {
            "name": "prestamo_recomendado",
            "dataType": "boolean",
            "sourceColumn": "prestamo_recomendado",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "Capacidad_Prestamo",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Origen = Sql.Database(ServidorSQL, BaseDatosSQL),",
                "    Tabla = Origen{[Schema=\"dbo\", Item=\"Capacidad_Prestamo\"]}[Data],",
                "    Columnas = Table.SelectColumns(Tabla, {\"sk_cuenta\", \"sk_cliente\", \"sk_distrito\", \"tiene_prestamo\", \"saldo_promedio\", \"cuota_prudente\", \"monto_maximo_12m\", \"monto_maximo_36m\", \"monto_maximo_60m\", \"tramo_monto_36m\", \"orden_tramo\", \"puede_pagar_prestamo_tipico\", \"prestamo_recomendado\"}),",
                "    Tipos = Table.TransformColumnTypes(Columnas, {{\"sk_cuenta\", Int64.Type}, {\"sk_cliente\", Int64.Type}, {\"sk_distrito\", Int64.Type}, {\"tiene_prestamo\", type logical}, {\"saldo_promedio\", type number}, {\"cuota_prudente\", type number}, {\"monto_maximo_12m\", type number}, {\"monto_maximo_36m\", type number}, {\"monto_maximo_60m\", type number}, {\"tramo_monto_36m\", type text}, {\"orden_tramo\", Int64.Type}, {\"puede_pagar_prestamo_tipico\", type logical}, {\"prestamo_recomendado\", type logical}})",
                "in",
                "    Tipos"
              ]
            }
          }
        ]
      },
      {
        "name": "Evaluacion_Recomendador",
        "columns": [
          {
            "name": "modelo",
            "dataType": "string",
            "sourceColumn": "modelo",
            "summarizeBy": "none",
            "sortByColumn": "orden"
          },
          {
            "name": "familia",
            "dataType": "string",
            "sourceColumn": "familia",
            "summarizeBy": "none"
          },
          {
            "name": "rol",
            "dataType": "string",
            "sourceColumn": "rol",
            "summarizeBy": "none"
          },
          {
            "name": "hit_1",
            "dataType": "double",
            "sourceColumn": "hit_1",
            "summarizeBy": "none",
            "formatString": "0.00%"
          },
          {
            "name": "hit_3",
            "dataType": "double",
            "sourceColumn": "hit_3",
            "summarizeBy": "none",
            "formatString": "0.00%"
          },
          {
            "name": "mrr",
            "dataType": "double",
            "sourceColumn": "mrr",
            "summarizeBy": "none",
            "formatString": "0.000"
          },
          {
            "name": "hit_1_cola_larga",
            "dataType": "double",
            "sourceColumn": "hit_1_cola_larga",
            "summarizeBy": "none",
            "formatString": "0.00%"
          },
          {
            "name": "mrr_confirmacion",
            "dataType": "double",
            "sourceColumn": "mrr_confirmacion",
            "summarizeBy": "none",
            "formatString": "0.000"
          },
          {
            "name": "orden",
            "dataType": "int64",
            "sourceColumn": "orden",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "elegido",
            "dataType": "boolean",
            "sourceColumn": "elegido",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "Evaluacion_Recomendador",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Origen = Sql.Database(ServidorSQL, BaseDatosSQL),",
                "    Tabla = Origen{[Schema=\"dbo\", Item=\"Evaluacion_Recomendador\"]}[Data],",
                "    Columnas = Table.SelectColumns(Tabla, {\"modelo\", \"familia\", \"rol\", \"hit_1\", \"hit_3\", \"mrr\", \"hit_1_cola_larga\", \"mrr_confirmacion\", \"orden\", \"elegido\"}),",
                "    Tipos = Table.TransformColumnTypes(Columnas, {{\"modelo\", type text}, {\"familia\", type text}, {\"rol\", type text}, {\"hit_1\", type number}, {\"hit_3\", type number}, {\"mrr\", type number}, {\"hit_1_cola_larga\", type number}, {\"mrr_confirmacion\", type number}, {\"orden\", Int64.Type}, {\"elegido\", type logical}})",
                "in",
                "    Tipos"
              ]
            }
          }
        ]
      },
      {
        "name": "Asociacion_Producto",
        "columns": [
          {
            "name": "producto_origen",
            "dataType": "string",
            "sourceColumn": "producto_origen",
            "summarizeBy": "none"
          },
          {
            "name": "producto_destino",
            "dataType": "string",
            "sourceColumn": "producto_destino",
            "summarizeBy": "none"
          },
          {
            "name": "p_destino_dado_origen",
            "dataType": "double",
            "sourceColumn": "p_destino_dado_origen",
            "summarizeBy": "none",
            "formatString": "0.00%"
          },
          {
            "name": "lift",
            "dataType": "double",
            "sourceColumn": "lift",
            "summarizeBy": "none",
            "formatString": "0.00"
          },
          {
            "name": "cuentas_ambos",
            "dataType": "int64",
            "sourceColumn": "cuentas_ambos",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "Asociacion_Producto",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Origen = Sql.Database(ServidorSQL, BaseDatosSQL),",
                "    Tabla = Origen{[Schema=\"dbo\", Item=\"Asociacion_Producto\"]}[Data],",
                "    Columnas = Table.SelectColumns(Tabla, {\"producto_origen\", \"producto_destino\", \"p_destino_dado_origen\", \"lift\", \"cuentas_ambos\"}),",
                "    Tipos = Table.TransformColumnTypes(Columnas, {{\"producto_origen\", type text}, {\"producto_destino\", type text}, {\"p_destino_dado_origen\", type number}, {\"lift\", type number}, {\"cuentas_ambos\", Int64.Type}})",
                "in",
                "    Tipos"
              ]
            }
          }
        ]
      },
      {
        "name": "Regla_Capacidad",
        "columns": [
          {
            "name": "regla",
            "dataType": "string",
            "sourceColumn": "regla",
            "summarizeBy": "none"
          },
          {
            "name": "tramo",
            "dataType": "string",
            "sourceColumn": "tramo",
            "summarizeBy": "none",
            "sortByColumn": "orden"
          },
          {
            "name": "orden",
            "dataType": "int64",
            "sourceColumn": "orden",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "prestamos",
            "dataType": "int64",
            "sourceColumn": "prestamos",
            "summarizeBy": "none"
          },
          {
            "name": "impagos",
            "dataType": "int64",
            "sourceColumn": "impagos",
            "summarizeBy": "none"
          },
          {
            "name": "tasa_impago",
            "dataType": "double",
            "sourceColumn": "tasa_impago",
            "summarizeBy": "none",
            "formatString": "0.00%"
          },
          {
            "name": "auc",
            "dataType": "double",
            "sourceColumn": "auc",
            "summarizeBy": "none",
            "formatString": "0.000"
          }
        ],
        "partitions": [
          {
            "name": "Regla_Capacidad",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Origen = Sql.Database(ServidorSQL, BaseDatosSQL),",
                "    Tabla = Origen{[Schema=\"dbo\", Item=\"Regla_Capacidad\"]}[Data],",
                "    Columnas = Table.SelectColumns(Tabla, {\"regla\", \"tramo\", \"orden\", \"prestamos\", \"impagos\", \"tasa_impago\", \"auc\"}),",
                "    Tipos = Table.TransformColumnTypes(Columnas, {{\"regla\", type text}, {\"tramo\", type text}, {\"orden\", Int64.Type}, {\"prestamos\", Int64.Type}, {\"impagos\", Int64.Type}, {\"tasa_impago\", type number}, {\"auc\", type number}})",
                "in",
                "    Tipos"
              ]
            }
          }
        ]
      },
      {
        "name": "Composicion_Liquidez",
        "columns": [
          {
            "name": "concepto",
            "dataType": "string",
            "sourceColumn": "concepto",
            "summarizeBy": "none",
            "sortByColumn": "orden"
          },
          {
            "name": "orden",
            "dataType": "int64",
            "sourceColumn": "orden",
            "summarizeBy": "none",
            "isHidden": true
          }
        ],
        "partitions": [
          {
            "name": "Composicion_Liquidez",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Origen = #table(type table [concepto = text, orden = Int64.Type], {{\"Saldo neto al corte\", 1}, {\"Cartera vigente\", 2}})",
                "in",
                "    Origen"
              ]
            }
          }
        ]
      },
      {
        "name": "_Medidas",
        "columns": [
          {
            "name": "Medidas",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Medidas",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "_Medidas",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Origen = #table(type table [Medidas = text], {{\"Guía 07 v4\"}})",
                "in",
                "    Origen"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Num Prestamos",
            "expression": "COUNTROWS(Fact_Prestamos)",
            "description": "Préstamos otorgados (682)",
            "formatString": "#,0"
          },
          {
            "name": "Prestamos en Mora",
            "expression": "CALCULATE([Num Prestamos], Dim_Estado_Prestamo[codigo_estado] = \"D\")",
            "description": "Vigentes en mora, estado D (45)",
            "formatString": "#,0"
          },
          {
            "name": "Prestamos Vigentes",
            "expression": "CALCULATE([Num Prestamos], Dim_Estado_Prestamo[codigo_estado] IN {\"C\", \"D\"})",
            "description": "Estados C + D (448)",
            "formatString": "#,0"
          },
          {
            "name": "Prestamos Incumplidos",
            "expression": "CALCULATE([Num Prestamos], Dim_Estado_Prestamo[codigo_estado] = \"B\")",
            "description": "Cerrados con deuda, estado B (31)",
            "formatString": "#,0"
          },
          {
            "name": "Prestamos Cerrados",
            "expression": "CALCULATE([Num Prestamos], Dim_Estado_Prestamo[codigo_estado] IN {\"A\", \"B\"})",
            "description": "Estados A + B (234)",
            "formatString": "#,0"
          },
          {
            "name": "Prestamos con Impago",
            "expression": "CALCULATE([Num Prestamos], Dim_Estado_Prestamo[codigo_estado] IN {\"B\", \"D\"})",
            "description": "Estados B + D (76)",
            "formatString": "#,0"
          },
          {
            "name": "Tasa Mora Vigente",
            "expression": "IF([Prestamos Vigentes] > 0, DIVIDE([Prestamos en Mora] + 0, [Prestamos Vigentes]))",
            "description": "D / (C + D) = 10.04%; 0% (no vacío) si hay vigentes sin mora, p. ej. north Bohemia 0/41",
            "formatString": "0.00%"
          },
          {
            "name": "Tasa Incumplimiento",
            "expression": "IF([Prestamos Cerrados] > 0, DIVIDE([Prestamos Incumplidos] + 0, [Prestamos Cerrados]))",
            "description": "B / (A + B) = 13.25%",
            "formatString": "0.00%"
          },
          {
            "name": "Tasa Impago",
            "expression": "IF([Num Prestamos] > 0, DIVIDE([Prestamos con Impago] + 0, [Num Prestamos]))",
            "description": "(B + D) / total = 11.14%; es la tasa de P6 por banda de capacidad",
            "formatString": "0.00%"
          },
          {
            "name": "Mora Wilson Inferior",
            "expression": "VAR n = [Prestamos Vigentes] VAR p = DIVIDE([Prestamos en Mora] + 0, n) VAR c = DIVIDE(p + 1 / (2 * n), 1 + 1 / n) VAR m = DIVIDE(1, 1 + 1 / n) * SQRT(p * (1 - p) / n + 1 / (4 * n * n)) RETURN IF(n > 0, c - m)",
            "description": "Límite inferior de Wilson (z = 1) de mora",
            "formatString": "0.00%"
          },
          {
            "name": "Mora Wilson Superior",
            "expression": "VAR n = [Prestamos Vigentes] VAR p = DIVIDE([Prestamos en Mora] + 0, n) VAR c = DIVIDE(p + 1 / (2 * n), 1 + 1 / n) VAR m = DIVIDE(1, 1 + 1 / n) * SQRT(p * (1 - p) / n + 1 / (4 * n * n)) RETURN IF(n > 0, c + m)",
            "description": "Límite superior de Wilson (z = 1) de mora",
            "formatString": "0.00%"
          },
          {
            "name": "Incumplimiento Wilson Inferior",
            "expression": "VAR n = [Prestamos Cerrados] VAR p = DIVIDE([Prestamos Incumplidos] + 0, n) VAR c = DIVIDE(p + 1 / (2 * n), 1 + 1 / n) VAR m = DIVIDE(1, 1 + 1 / n) * SQRT(p * (1 - p) / n + 1 / (4 * n * n)) RETURN IF(n > 0, c - m)",
            "description": "Límite inferior de Wilson (z = 1) de incumplimiento",
            "formatString": "0.00%"
          },
          {
            "name": "Incumplimiento Wilson Superior",
            "expression": "VAR n = [Prestamos Cerrados] VAR p = DIVIDE([Prestamos Incumplidos] + 0, n) VAR c = DIVIDE(p + 1 / (2 * n), 1 + 1 / n) VAR m = DIVIDE(1, 1 + 1 / n) * SQRT(p * (1 - p) / n + 1 / (4 * n * n)) RETURN IF(n > 0, c + m)",
            "description": "Límite superior de Wilson (z = 1) de incumplimiento",
            "formatString": "0.00%"
          },
          {
            "name": "Impago Wilson Inferior",
            "expression": "VAR n = [Num Prestamos] VAR p = DIVIDE([Prestamos con Impago] + 0, n) VAR c = DIVIDE(p + 1 / (2 * n), 1 + 1 / n) VAR m = DIVIDE(1, 1 + 1 / n) * SQRT(p * (1 - p) / n + 1 / (4 * n * n)) RETURN IF(n > 0, c - m)",
            "description": "Límite inferior de Wilson (z = 1) de impago",
            "formatString": "0.00%"
          },
          {
            "name": "Impago Wilson Superior",
            "expression": "VAR n = [Num Prestamos] VAR p = DIVIDE([Prestamos con Impago] + 0, n) VAR c = DIVIDE(p + 1 / (2 * n), 1 + 1 / n) VAR m = DIVIDE(1, 1 + 1 / n) * SQRT(p * (1 - p) / n + 1 / (4 * n * n)) RETURN IF(n > 0, c + m)",
            "description": "Límite superior de Wilson (z = 1) de impago",
            "formatString": "0.00%"
          },
          {
            "name": "Tasa Mora Banco",
            "expression": "CALCULATE([Tasa Mora Vigente], REMOVEFILTERS(Dim_Distrito))",
            "description": "Referencia de P2: la tasa del banco, sin el filtro de distrito",
            "formatString": "0.00%"
          },
          {
            "name": "Tasa Impago Banco",
            "expression": "CALCULATE([Tasa Impago], REMOVEFILTERS(Fact_Prestamos[banda_capacidad], Fact_Prestamos[Orden Banda]))",
            "description": "Referencia de P6: impago de todas las bandas",
            "formatString": "0.00%"
          },
          {
            "name": "Tasa Incumplimiento Banco",
            "expression": "CALCULATE([Tasa Incumplimiento], REMOVEFILTERS(Dim_Cliente))",
            "description": "Referencia de P6: incumplimiento de todos los segmentos de edad",
            "formatString": "0.00%"
          },
          {
            "name": "Tasa Impago Banda Baja",
            "expression": "CALCULATE([Tasa Impago], KEEPFILTERS(Fact_Prestamos[banda_capacidad] = \"Baja\"))",
            "description": "Impago de la banda Baja (2.92%); KEEPFILTERS respeta los demás filtros",
            "formatString": "0.00%"
          },
          {
            "name": "Tasa Impago Banda Alta",
            "expression": "CALCULATE([Tasa Impago], KEEPFILTERS(Fact_Prestamos[banda_capacidad] = \"Alta\"))",
            "description": "Impago de la banda Alta (23.26%)",
            "formatString": "0.00%"
          },
          {
            "name": "Cartera Total",
            "expression": "SUM(Fact_Prestamos[monto_prestamo])",
            "description": "Monto original de todos los préstamos ($103,261,740)",
            "formatString": "\"$\"#,0"
          },
          {
            "name": "Cartera Vigente",
            "expression": "CALCULATE([Cartera Total], Dim_Estado_Prestamo[codigo_estado] IN {\"C\", \"D\"})",
            "description": "Monto original C + D ($80,296,176)",
            "formatString": "\"$\"#,0"
          },
          {
            "name": "Saldo por Cobrar Estimado",
            "expression": "CALCULATE(SUM(Fact_Prestamos[saldo_pendiente_estimado]), Dim_Estado_Prestamo[codigo_estado] IN {\"C\", \"D\"})",
            "description": "Capital pendiente estimado de la cartera vigente ($46,620,926)",
            "formatString": "\"$\"#,0"
          },
          {
            "name": "Monto Original en Riesgo",
            "expression": "CALCULATE([Cartera Total], Dim_Estado_Prestamo[codigo_estado] IN {\"B\", \"D\"})",
            "description": "Monto original de los préstamos B + D ($15,580,152)",
            "formatString": "\"$\"#,0"
          },
          {
            "name": "Monto Incumplido",
            "expression": "CALCULATE([Cartera Total], Dim_Estado_Prestamo[codigo_estado] = \"B\")",
            "description": "Monto original de los préstamos B",
            "formatString": "\"$\"#,0"
          },
          {
            "name": "Cuota Mensual",
            "expression": "SUM(Fact_Prestamos[pago_mensual])",
            "description": "Cuota mensual de los préstamos del contexto",
            "formatString": "\"$\"#,0"
          },
          {
            "name": "Clientes con Impago",
            "expression": "CALCULATE(DISTINCTCOUNT(Fact_Prestamos[sk_cliente]), Dim_Estado_Prestamo[codigo_estado] = \"B\")",
            "description": "Titulares con préstamo B (31): lista de denegación",
            "formatString": "#,0"
          },
          {
            "name": "Cartera Distritos Sobre Mora Banco",
            "expression": "VAR moraBanco = CALCULATE([Tasa Mora Vigente], REMOVEFILTERS(Dim_Distrito)) RETURN CALCULATE([Cartera Vigente], FILTER(VALUES(Dim_Distrito[nombre_distrito]), [Tasa Mora Vigente] > moraBanco))",
            "description": "CALCULATE + FILTER: cartera vigente de los distritos con mora sobre la del banco",
            "formatString": "\"$\"#,0"
          },
          {
            "name": "Distritos Sobre Mora Banco",
            "expression": "VAR moraBanco = CALCULATE([Tasa Mora Vigente], REMOVEFILTERS(Dim_Distrito)) RETURN COUNTROWS(FILTER(VALUES(Dim_Distrito[nombre_distrito]), [Tasa Mora Vigente] > moraBanco))",
            "description": "Distritos con tasa de mora vigente sobre la del banco",
            "formatString": "#,0"
          },
          {
            "name": "Region Mayor Mora",
            "expression": "VAR r = TOPN(1, FILTER(VALUES(Dim_Distrito[region]), [Prestamos Vigentes] > 0), [Tasa Mora Vigente], DESC) RETURN CONCATENATEX(r, Dim_Distrito[region] & \" · \" & FORMAT([Tasa Mora Vigente], \"0.0%\"), \", \")",
            "description": "north Moravia · 15.8%"
          },
          {
            "name": "Distrito Mayor Morosos",
            "expression": "VAR d = TOPN(1, FILTER(VALUES(Dim_Distrito[nombre_distrito]), [Prestamos en Mora] > 0), [Prestamos en Mora], DESC) RETURN CONCATENATEX(d, Dim_Distrito[nombre_distrito] & \" · \" & [Prestamos en Mora] & \" en mora\", \", \")",
            "description": "Hl.m. Praha · 4 en mora"
          },
          {
            "name": "Estado Prestamo",
            "expression": "IF([Num Prestamos] > 0, CALCULATE(CONCATENATEX(VALUES(Dim_Estado_Prestamo[Estado]), Dim_Estado_Prestamo[Estado], \", \"), Fact_Prestamos))",
            "description": "Estado del préstamo del cliente o de la cuenta (fichas)"
          },
          {
            "name": "Banda Capacidad",
            "expression": "IF([Num Prestamos] > 0, CONCATENATEX(VALUES(Fact_Prestamos[banda_capacidad]), Fact_Prestamos[banda_capacidad], \", \"))",
            "description": "Banda de capacidad de pago (ratio cuota / saldo previo)"
          },
          {
            "name": "Distrito Prestamo",
            "expression": "IF([Num Prestamos] > 0, CALCULATE(CONCATENATEX(VALUES(Dim_Distrito[nombre_distrito]), Dim_Distrito[nombre_distrito], \", \"), Fact_Prestamos))",
            "description": "Distrito de la cuenta del préstamo"
          },
          {
            "name": "Banda Capacidad Impago",
            "expression": "CALCULATE([Banda Capacidad], Dim_Estado_Prestamo[codigo_estado] = \"B\")",
            "description": "Banda del préstamo B (lista de P6)"
          },
          {
            "name": "Distrito Impago",
            "expression": "CALCULATE([Distrito Prestamo], Dim_Estado_Prestamo[codigo_estado] = \"B\")",
            "description": "Distrito del préstamo B (lista de P6)"
          },
          {
            "name": "Saldo Neto Corte",
            "expression": "VAR ultimoMes = CALCULATE(MAX(Dim_Tiempo[fecha]), Fact_Saldo_Cuenta_Mensual) RETURN CALCULATE(SUM(Fact_Saldo_Cuenta_Mensual[saldo_fin_mes]), FILTER(ALL(Dim_Tiempo), Dim_Tiempo[fecha] = ultimoMes))",
            "description": "Saldo al cierre del último mes del contexto ($197,140,434 en dic-1998)",
            "formatString": "\"$\"#,0"
          },
          {
            "name": "Cuentas Activas Corte",
            "expression": "VAR ultimoMes = CALCULATE(MAX(Dim_Tiempo[fecha]), Fact_Saldo_Cuenta_Mensual) RETURN CALCULATE(COUNTROWS(Fact_Saldo_Cuenta_Mensual), FILTER(ALL(Dim_Tiempo), Dim_Tiempo[fecha] = ultimoMes))",
            "description": "Cuentas con foto en el último mes del contexto (4,500 en dic-1998)",
            "formatString": "#,0"
          },
          {
            "name": "Cuentas en Sobregiro",
            "expression": "VAR ultimoMes = CALCULATE(MAX(Dim_Tiempo[fecha]), Fact_Saldo_Cuenta_Mensual) RETURN CALCULATE(CALCULATE(COUNTROWS(Fact_Saldo_Cuenta_Mensual), Fact_Saldo_Cuenta_Mensual[en_sobregiro] = TRUE()), FILTER(ALL(Dim_Tiempo), Dim_Tiempo[fecha] = ultimoMes))",
            "description": "Cuentas con saldo negativo al cierre del último mes (39 en dic-1998)",
            "formatString": "#,0"
          },
          {
            "name": "Saldo Promedio por Cuenta",
            "expression": "DIVIDE([Saldo Neto Corte], [Cuentas Activas Corte])",
            "description": "Saldo por cuenta activa: aísla el crecimiento por apertura de cuentas",
            "formatString": "\"$\"#,0"
          },
          {
            "name": "Saldo Promedio Banco",
            "expression": "CALCULATE([Saldo Promedio por Cuenta], REMOVEFILTERS(Dim_Distrito))",
            "description": "Referencia gris de D1",
            "formatString": "\"$\"#,0"
          },
          {
            "name": "Umbral Sobregiro",
            "expression": "IF(NOT ISBLANK([Saldo Neto Corte]), 0)",
            "description": "Línea en 0 de la ficha D2",
            "formatString": "\"$\"#,0.00"
          },
          {
            "name": "Saldo Neto Corte Total",
            "expression": "CALCULATE([Saldo Neto Corte], REMOVEFILTERS(Dim_Anio), REMOVEFILTERS(Dim_Tiempo))",
            "description": "Saldo al corte dic-1998, sin importar el año elegido",
            "formatString": "\"$\"#,0"
          },
          {
            "name": "Cartera Vigente Corte",
            "expression": "CALCULATE([Cartera Vigente], REMOVEFILTERS(Dim_Anio), REMOVEFILTERS(Dim_Tiempo))",
            "description": "Cartera vigente al corte, sin importar el año elegido",
            "formatString": "\"$\"#,0"
          },
          {
            "name": "Absorcion Vigente",
            "expression": "DIVIDE([Cartera Vigente Corte], [Saldo Neto Corte Total])",
            "description": "KPI de liquidez de la Carta v8: cartera vigente / saldo neto al corte (40.73%)",
            "formatString": "0.00%"
          },
          {
            "name": "Absorcion Cartera Total",
            "expression": "DIVIDE(CALCULATE([Cartera Total], REMOVEFILTERS(Dim_Anio), REMOVEFILTERS(Dim_Tiempo)), [Saldo Neto Corte Total])",
            "description": "Referencia histórica: cartera total / saldo neto (52.38%)",
            "formatString": "0.00%"
          },
          {
            "name": "Absorcion Banco",
            "expression": "CALCULATE([Absorcion Vigente], REMOVEFILTERS(Dim_Distrito))",
            "description": "Referencia de P3: absorción del banco",
            "formatString": "0.00%"
          },
          {
            "name": "Liquidez Libre",
            "expression": "[Saldo Neto Corte Total] - [Cartera Vigente Corte]",
            "description": "Saldo que no respalda cartera vigente ($116,844,258)",
            "formatString": "\"$\"#,0"
          },
          {
            "name": "Valor Composicion Liquidez",
            "expression": "SWITCH(SELECTEDVALUE(Composicion_Liquidez[concepto]), \"Saldo neto al corte\", [Saldo Neto Corte Total], \"Cartera vigente\", -[Cartera Vigente Corte])",
            "description": "Cascada de P3; el total es la liquidez libre",
            "formatString": "\"$\"#,0"
          },
          {
            "name": "Volumen Transaccionado",
            "expression": "SUM(vw_PBI_Trans_Anual_Cuenta[monto_total])",
            "description": "$6,257,862,197",
            "formatString": "\"$\"#,0"
          },
          {
            "name": "Num Transacciones",
            "expression": "SUM(vw_PBI_Trans_Anual_Cuenta[num_transacciones])",
            "description": "1,056,320",
            "formatString": "#,0"
          },
          {
            "name": "Ticket Promedio",
            "expression": "DIVIDE([Volumen Transaccionado], [Num Transacciones])",
            "description": "Monto promedio por movimiento",
            "formatString": "\"$\"#,0.00"
          },
          {
            "name": "Desv Est Transaccion",
            "expression": "VAR n = [Num Transacciones] VAR s = [Volumen Transaccionado] VAR sq = SUM(vw_PBI_Trans_Anual_Cuenta[suma_cuadrados]) RETURN IF(n > 1, SQRT(DIVIDE(sq - s * s / n, n - 1)))",
            "description": "σ muestral exacta desde la suma y la suma de cuadrados",
            "formatString": "\"$\"#,0.00"
          },
          {
            "name": "Ticket Limite Superior",
            "expression": "[Ticket Promedio] + [Desv Est Transaccion]",
            "description": "Promedio + 1σ",
            "formatString": "\"$\"#,0.00"
          },
          {
            "name": "Ticket Limite Inferior",
            "expression": "MAX(0, [Ticket Promedio] - [Desv Est Transaccion])",
            "description": "Promedio − 1σ (no negativo)",
            "formatString": "\"$\"#,0.00"
          },
          {
            "name": "EE Ticket",
            "expression": "DIVIDE([Desv Est Transaccion], SQRT([Num Transacciones]))",
            "description": "Error estándar (tooltip)",
            "formatString": "\"$\"#,0.00"
          },
          {
            "name": "Saldo Promedio Historico",
            "expression": "DIVIDE(SUMX(vw_PBI_Trans_Anual_Cuenta, vw_PBI_Trans_Anual_Cuenta[saldo_promedio] * vw_PBI_Trans_Anual_Cuenta[num_transacciones]), [Num Transacciones])",
            "description": "Saldo promedio de la cuenta ponderado por movimientos",
            "formatString": "\"$\"#,0"
          },
          {
            "name": "Compromiso Ordenes",
            "expression": "SUM(Fact_Ordenes[monto_orden])",
            "description": "Órdenes fijas mensuales ($21,229,041)",
            "formatString": "\"$\"#,0"
          },
          {
            "name": "Num Ordenes",
            "expression": "COUNTROWS(Fact_Ordenes)",
            "description": "6,471 órdenes",
            "formatString": "#,0"
          },
          {
            "name": "Pct Ordenes",
            "expression": "DIVIDE([Num Ordenes], CALCULATE([Num Ordenes], REMOVEFILTERS(Dim_Orden[categoria_orden_traducida])))",
            "description": "Participación de cada propósito",
            "formatString": "0.00%"
          },
          {
            "name": "Indice Saturacion",
            "expression": "DIVIDE([Compromiso Ordenes], CALCULATE([Saldo Promedio Historico], REMOVEFILTERS(Dim_Anio), REMOVEFILTERS(Dim_Tiempo), REMOVEFILTERS(vw_PBI_Trans_Anual_Cuenta[categoria_analitica])))",
            "description": "Órdenes mensuales / saldo promedio histórico de la cuenta (cuenta 2335: 2.14)",
            "formatString": "0.00"
          },
          {
            "name": "Cuentas Saturadas",
            "expression": "COUNTROWS(FILTER(VALUES(Dim_Cuenta[id_cuenta_bk]), [Indice Saturacion] > 0.5))",
            "description": "CALCULATE + FILTER: cuentas con índice > 0.5 (47)",
            "formatString": "#,0"
          },
          {
            "name": "Cuentas Sobre Saldo",
            "expression": "COUNTROWS(FILTER(VALUES(Dim_Cuenta[id_cuenta_bk]), [Indice Saturacion] > 1))",
            "description": "Cuentas cuyas órdenes superan su saldo promedio (1)",
            "formatString": "#,0"
          },
          {
            "name": "Cuentas con Credito Externo",
            "expression": "CALCULATE(DISTINCTCOUNT(Fact_Ordenes[sk_cuenta]), Dim_Cuenta[tiene_credito_externo] = TRUE())",
            "description": "Cuentas que pagan un préstamo a otra entidad (35)",
            "formatString": "#,0"
          },
          {
            "name": "Credito Externo Mensual",
            "expression": "CALCULATE([Compromiso Ordenes], Dim_Cuenta[tiene_credito_externo] = TRUE(), Dim_Orden[k_symbol_original] = \"UVER\")",
            "description": "Cuotas mensuales a otras entidades ($177,154)",
            "formatString": "\"$\"#,0"
          },
          {
            "name": "Indice Saturacion Alerta",
            "expression": "VAR i = [Indice Saturacion] RETURN IF(i > 0.5, i)",
            "description": "Solo cuentas en alerta",
            "formatString": "0.00"
          },
          {
            "name": "Compromiso Alerta",
            "expression": "IF([Indice Saturacion] > 0.5, [Compromiso Ordenes])",
            "description": "Solo cuentas en alerta",
            "formatString": "\"$\"#,0"
          },
          {
            "name": "Saldo Promedio Alerta",
            "expression": "IF([Indice Saturacion] > 0.5, CALCULATE([Saldo Promedio Historico], REMOVEFILTERS(Dim_Anio), REMOVEFILTERS(Dim_Tiempo), REMOVEFILTERS(vw_PBI_Trans_Anual_Cuenta[categoria_analitica])))",
            "description": "Solo cuentas en alerta",
            "formatString": "\"$\"#,0"
          },
          {
            "name": "Credito Externo Alerta",
            "expression": "IF([Indice Saturacion] > 0.5, [Credito Externo Mensual])",
            "description": "Solo cuentas en alerta",
            "formatString": "\"$\"#,0"
          },
          {
            "name": "Cliente Titular Alerta",
            "expression": "IF([Indice Saturacion] > 0.5, CALCULATE(SELECTEDVALUE(Dim_Cliente[Cliente]), Fact_Saldo_Cuenta_Mensual))",
            "description": "Solo cuentas en alerta"
          },
          {
            "name": "Cuenta Alerta",
            "expression": "IF([Indice Saturacion] > 0.5, CALCULATE(SELECTEDVALUE(Dim_Cuenta[Cuenta]), Fact_Saldo_Cuenta_Mensual))",
            "description": "Cuenta del titular en alerta"
          },
          {
            "name": "Titulo Distrito",
            "expression": "\"Distrito: \" & SELECTEDVALUE(Dim_Distrito[nombre_distrito], \"(varios)\") & \" (\" & SELECTEDVALUE(Dim_Distrito[region], \"varias regiones\") & \")\"",
            "description": "Título dinámico de D1"
          },
          {
            "name": "Region del Distrito",
            "expression": "SELECTEDVALUE(Dim_Distrito[region])",
            "description": "Región del distrito (tooltip del treemap de P2)"
          },
          {
            "name": "Poblacion Distrito",
            "expression": "SELECTEDVALUE(Dim_Distrito[poblacion])",
            "description": "Habitantes",
            "formatString": "#,0"
          },
          {
            "name": "Salario Promedio Distrito",
            "expression": "SELECTEDVALUE(Dim_Distrito[salario_promedio])",
            "description": "Salario promedio",
            "formatString": "\"$\"#,0"
          },
          {
            "name": "Desempleo Distrito 1995",
            "expression": "SELECTEDVALUE(Dim_Distrito[tasa_desempleo])",
            "description": "Tasa de desempleo 1995 (%)",
            "formatString": "0.00"
          },
          {
            "name": "Origen Indicadores",
            "expression": "IF(HASONEVALUE(Dim_Distrito[es_imputado]), IF(VALUES(Dim_Distrito[es_imputado]), \"Imputado (Informe 10)\", \"Fuente original\"))",
            "description": "Marca el distrito 69 con indicadores imputados"
          },
          {
            "name": "Cliente Ficha",
            "expression": "CALCULATE(SELECTEDVALUE(Dim_Cliente[Cliente]), Fact_Saldo_Cuenta_Mensual)",
            "description": "Titular de la cuenta (vale si se llega por cliente o por cuenta)"
          },
          {
            "name": "Cuenta Ficha",
            "expression": "CALCULATE(SELECTEDVALUE(Dim_Cuenta[Cuenta]), Fact_Saldo_Cuenta_Mensual)",
            "description": "Cuenta del titular"
          },
          {
            "name": "Titulo Cliente",
            "expression": "\"Ficha 360 · \" & COALESCE([Cliente Ficha], SELECTEDVALUE(Dim_Cliente[Cliente], \"(varios clientes)\")) & \" · \" & COALESCE([Cuenta Ficha], \"sin cuenta propia\")",
            "description": "Título dinámico de D2"
          },
          {
            "name": "Edad Cliente",
            "expression": "CALCULATE(SELECTEDVALUE(Dim_Cliente[edad_corte]), Fact_Saldo_Cuenta_Mensual)",
            "description": "Edad al 31/12/1998",
            "formatString": "#,0"
          },
          {
            "name": "Segmento Cliente",
            "expression": "CALCULATE(SELECTEDVALUE(Dim_Cliente[segmento_edad]), Fact_Saldo_Cuenta_Mensual)",
            "description": "Segmento de edad (3 grupos del Data Mart)"
          },
          {
            "name": "Arquetipo Cliente",
            "expression": "CALCULATE(SELECTEDVALUE(Dim_Cliente[arquetipo_demografico]), Fact_Saldo_Cuenta_Mensual)",
            "description": "Macro-región y segmento"
          },
          {
            "name": "Calificacion Cliente",
            "expression": "CALCULATE(SELECTEDVALUE(Dim_Cliente[calificacion_pago_desc]), Fact_Saldo_Cuenta_Mensual)",
            "description": "Buen / Mal pagador / Sin evaluar"
          },
          {
            "name": "Distrito Cuenta",
            "expression": "CALCULATE(SELECTEDVALUE(Dim_Distrito[nombre_distrito]), Fact_Saldo_Cuenta_Mensual)",
            "description": "Distrito de la cuenta"
          },
          {
            "name": "Cuota Maxima Prudente",
            "expression": "SUM(Recomendacion_Cuenta[prestamo_cuota_maxima])",
            "description": "Cuota que deja el ratio en la banda Baja (Informe 04)",
            "formatString": "\"$\"#,0"
          },
          {
            "name": "Monto Maximo Prudente",
            "expression": "SUM(Recomendacion_Cuenta[prestamo_monto_maximo_36m])",
            "description": "Monto a 36 meses con esa cuota (Informe 04)",
            "formatString": "\"$\"#,0"
          },
          {
            "name": "Recomendaciones Demograficas",
            "expression": "CALCULATE(COUNTROWS(Recomendacion_Producto), Recomendacion_Producto[sistema] = \"Demográfico\")",
            "description": "Productos en el top 3 del recomendador demográfico (el más preciso: Hit@1 66.0%)",
            "formatString": "#,0"
          },
          {
            "name": "Primera Opcion",
            "expression": "CALCULATE([Recomendaciones Demograficas], Recomendacion_Producto[posicion] = 1)",
            "description": "Veces que el producto es la primera recomendación",
            "formatString": "#,0"
          },
          {
            "name": "Recomendaciones kNN",
            "expression": "CALCULATE(COUNTROWS(Recomendacion_Producto), Recomendacion_Producto[sistema] = \"kNN perfil\")",
            "description": "Productos en el top 3 del kNN por perfil exógeno",
            "formatString": "#,0"
          },
          {
            "name": "Descubrimientos kNN",
            "expression": "CALCULATE([Recomendaciones kNN], Recomendacion_Producto[es_descubrimiento] = TRUE())",
            "description": "Ofertas del kNN que el demográfico no tiene en su top 3 (2,731)",
            "formatString": "#,0"
          },
          {
            "name": "Clientes con Recomendacion",
            "expression": "CALCULATE(DISTINCTCOUNT(Recomendacion_Producto[sk_cuenta]), Recomendacion_Producto[sistema] = \"Demográfico\")",
            "description": "Titulares con al menos una recomendación",
            "formatString": "#,0"
          },
          {
            "name": "Cuentas que ya lo Usan",
            "expression": "COUNTROWS(Adopcion_Producto)",
            "description": "Cuentas que ya usan el producto (adopción actual)",
            "formatString": "#,0"
          },
          {
            "name": "Titulares",
            "expression": "COUNTROWS(Capacidad_Prestamo)",
            "description": "Titulares (una cuenta cada uno: 4,500)",
            "formatString": "#,0"
          },
          {
            "name": "Penetracion Actual",
            "expression": "DIVIDE([Cuentas que ya lo Usan], [Titulares])",
            "description": "Cuentas que ya usan el producto / titulares del contexto",
            "formatString": "0.00%"
          },
          {
            "name": "Producto Mas Recomendado",
            "expression": "VAR x = TOPN(1, VALUES(Dim_Producto[producto]), [Primera Opcion], DESC) RETURN CONCATENATEX(x, Dim_Producto[producto] & \" · \" & FORMAT([Primera Opcion], \"#,0\"), \", \")",
            "description": "Primera recomendación más frecuente en el contexto"
          },
          {
            "name": "Recomendacion 1",
            "expression": "CALCULATE(SELECTEDVALUE(Recomendacion_Producto[producto]), Recomendacion_Producto[sistema] = \"Demográfico\", Recomendacion_Producto[posicion] = 1)",
            "description": "Primera recomendación del titular"
          },
          {
            "name": "Recomendacion 2",
            "expression": "CALCULATE(SELECTEDVALUE(Recomendacion_Producto[producto]), Recomendacion_Producto[sistema] = \"Demográfico\", Recomendacion_Producto[posicion] = 2)",
            "description": "Segunda recomendación del titular"
          },
          {
            "name": "Recomendacion 3",
            "expression": "CALCULATE(SELECTEDVALUE(Recomendacion_Producto[producto]), Recomendacion_Producto[sistema] = \"Demográfico\", Recomendacion_Producto[posicion] = 3)",
            "description": "Tercera recomendación del titular"
          },
          {
            "name": "Descubrimiento kNN",
            "expression": "CALCULATE(CONCATENATEX(VALUES(Recomendacion_Producto[producto]), Recomendacion_Producto[producto], \", \"), Recomendacion_Producto[sistema] = \"kNN perfil\", Recomendacion_Producto[es_descubrimiento] = TRUE())",
            "description": "Productos que el kNN añade para el titular"
          },
          {
            "name": "Acierto Elegido",
            "expression": "CALCULATE(MAX(Evaluacion_Recomendador[hit_1]), Evaluacion_Recomendador[modelo] = \"Demográfico (arquetipo)\")",
            "description": "Hit@1 del demográfico (66.0%, semilla 42)",
            "formatString": "0.00%"
          },
          {
            "name": "Acierto Popularidad",
            "expression": "CALCULATE(MAX(Evaluacion_Recomendador[hit_1]), Evaluacion_Recomendador[modelo] = \"Popularidad\")",
            "description": "Hit@1 de recomendar lo más popular (58.5%): la línea base",
            "formatString": "0.00%"
          },
          {
            "name": "Acierto Cola Larga kNN",
            "expression": "CALCULATE(MAX(Evaluacion_Recomendador[hit_1_cola_larga]), Evaluacion_Recomendador[modelo] = \"kNN usuario-usuario (perfil exógeno)\")",
            "description": "Hit@1 del kNN en productos poco comunes (37.2%)",
            "formatString": "0.00%"
          },
          {
            "name": "Acierto Cola Larga Popularidad",
            "expression": "CALCULATE(MAX(Evaluacion_Recomendador[hit_1_cola_larga]), Evaluacion_Recomendador[modelo] = \"Popularidad\")",
            "description": "Hit@1 de la popularidad en productos poco comunes (6.3%)",
            "formatString": "0.00%"
          },
          {
            "name": "Acierto Hit1",
            "expression": "SUM(Evaluacion_Recomendador[hit_1])",
            "description": "Hit@1 del modelo (gráfico comparativo)",
            "formatString": "0.00%"
          },
          {
            "name": "Acierto Cola Larga",
            "expression": "SUM(Evaluacion_Recomendador[hit_1_cola_larga])",
            "description": "Hit@1 en la cola larga (gráfico comparativo)",
            "formatString": "0.00%"
          },
          {
            "name": "MRR Modelo",
            "expression": "SUM(Evaluacion_Recomendador[mrr])",
            "description": "Rango recíproco medio",
            "formatString": "0.000"
          },
          {
            "name": "MRR Confirmacion",
            "expression": "SUM(Evaluacion_Recomendador[mrr_confirmacion])",
            "description": "MRR con la semilla 2026",
            "formatString": "0.000"
          },
          {
            "name": "Titulares sin Prestamo",
            "expression": "CALCULATE([Titulares], Capacidad_Prestamo[tiene_prestamo] = FALSE())",
            "description": "3,818",
            "formatString": "#,0"
          },
          {
            "name": "Prestamos Prudentes Recomendados",
            "expression": "CALCULATE([Titulares], Capacidad_Prestamo[prestamo_recomendado] = TRUE())",
            "description": "Titulares con préstamo en su top 3 (1,721)",
            "formatString": "#,0"
          },
          {
            "name": "Cuota Prudente Mediana",
            "expression": "CALCULATE(MEDIAN(Capacidad_Prestamo[cuota_prudente]), Capacidad_Prestamo[tiene_prestamo] = FALSE())",
            "description": "5.7% del saldo promedio, mediana de los titulares sin préstamo (1,873)",
            "formatString": "\"$\"#,0.00"
          },
          {
            "name": "Pueden Pagar Prestamo Tipico",
            "expression": "CALCULATE([Titulares], Capacidad_Prestamo[puede_pagar_prestamo_tipico] = TRUE())",
            "description": "Titulares sin préstamo cuya cuota prudente cubre la cuota mediana otorgada (71)",
            "formatString": "#,0"
          },
          {
            "name": "Monto Prudente Ofrecible 36m",
            "expression": "CALCULATE(SUM(Capacidad_Prestamo[monto_maximo_36m]), Capacidad_Prestamo[prestamo_recomendado] = TRUE())",
            "description": "Suma de montos máximos a 36 meses de los préstamos recomendados",
            "formatString": "\"$\"#,0"
          },
          {
            "name": "Saldo Promedio Oferta",
            "expression": "CALCULATE(SUM(Capacidad_Prestamo[saldo_promedio]), Capacidad_Prestamo[prestamo_recomendado] = TRUE())",
            "description": "Saldo promedio del titular con préstamo recomendado",
            "formatString": "\"$\"#,0"
          },
          {
            "name": "Cuota Prudente Oferta",
            "expression": "CALCULATE(SUM(Capacidad_Prestamo[cuota_prudente]), Capacidad_Prestamo[prestamo_recomendado] = TRUE())",
            "description": "Cuota prudente del titular con préstamo recomendado",
            "formatString": "\"$\"#,0"
          },
          {
            "name": "Monto 12m Oferta",
            "expression": "CALCULATE(SUM(Capacidad_Prestamo[monto_maximo_12m]), Capacidad_Prestamo[prestamo_recomendado] = TRUE())",
            "description": "Monto máximo a 12 meses",
            "formatString": "\"$\"#,0"
          },
          {
            "name": "Monto 36m Oferta",
            "expression": "CALCULATE(SUM(Capacidad_Prestamo[monto_maximo_36m]), Capacidad_Prestamo[prestamo_recomendado] = TRUE())",
            "description": "Monto máximo a 36 meses",
            "formatString": "\"$\"#,0"
          },
          {
            "name": "Monto 60m Oferta",
            "expression": "CALCULATE(SUM(Capacidad_Prestamo[monto_maximo_60m]), Capacidad_Prestamo[prestamo_recomendado] = TRUE())",
            "description": "Monto máximo a 60 meses",
            "formatString": "\"$\"#,0"
          },
          {
            "name": "AUC Regla",
            "expression": "MAX(Regla_Capacidad[auc])",
            "description": "AUC de la regla para predecir el impago",
            "formatString": "0.000"
          },
          {
            "name": "AUC Regla Elegida",
            "expression": "CALCULATE([AUC Regla], Regla_Capacidad[regla] = \"Carta v8: cuota / saldo previo\")",
            "description": "0.717",
            "formatString": "0.000"
          },
          {
            "name": "AUC Regla Anterior",
            "expression": "CALCULATE([AUC Regla], Regla_Capacidad[regla] = \"Anterior: cuota / salario del distrito\")",
            "description": "0.659",
            "formatString": "0.000"
          },
          {
            "name": "P Destino dado Origen",
            "expression": "SUM(Asociacion_Producto[p_destino_dado_origen])",
            "description": "De quienes tienen el producto de origen, % que también tiene el de destino",
            "formatString": "0.00%"
          },
          {
            "name": "Lift Asociacion",
            "expression": "SUM(Asociacion_Producto[lift])",
            "description": "Lift: > 1 van juntos más de lo esperado por azar",
            "formatString": "0.00"
          },
          {
            "name": "Regla Mas Fuerte",
            "expression": "VAR x = TOPN(1, FILTER(Asociacion_Producto, Asociacion_Producto[cuentas_ambos] >= 100), Asociacion_Producto[lift], DESC, Asociacion_Producto[p_destino_dado_origen], DESC) RETURN CONCATENATEX(x, Asociacion_Producto[producto_origen] & \" → \" & Asociacion_Producto[producto_destino] & \" · \" & FORMAT(Asociacion_Producto[p_destino_dado_origen], \"0.0%\"), \", \")",
            "description": "Par con mayor lift (al menos 100 cuentas), en la dirección de mayor P(j|i): Seguro → Transferencias 99.8%"
          },
          {
            "name": "Color Mora",
            "expression": "VAR x = [Tasa Mora Vigente] RETURN SWITCH(TRUE(), ISBLANK(x), \"#FFFFFF\", x < 0.05, \"#FBE3D3\", x < 0.10, \"#F2B48C\", x < 0.15, \"#E5813F\", \"#D55E00\")",
            "description": "Treemap de P2: escala secuencial blanco → bermellón por tasa de mora"
          },
          {
            "name": "Color Saturacion",
            "expression": "VAR x = [Indice Saturacion] RETURN IF(x > 1, \"#D55E00\", IF(x > 0.5, \"#E69F00\", \"#7F7F7F\"))",
            "description": "Dispersión de P5: bermellón > 1, naranja > 0.5, gris el resto"
          },
          {
            "name": "Color Modelo",
            "expression": "IF(SELECTEDVALUE(Evaluacion_Recomendador[elegido]) = TRUE(), \"#0072B2\", \"#BDBDBD\")",
            "description": "R1: modelos elegidos en azul, el resto en gris"
          },
          {
            "name": "Color Regla",
            "expression": "IF(SELECTEDVALUE(Regla_Capacidad[regla]) = \"Carta v8: cuota / saldo previo\", \"#0072B2\", \"#BDBDBD\")",
            "description": "R2: regla elegida en azul"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "bd0e598c-9e1f-5df2-b4a9-dece4bf6c23b",
        "fromTable": "Fact_Prestamos",
        "fromColumn": "sk_distrito",
        "toTable": "Dim_Distrito",
        "toColumn": "sk_distrito"
      },
      {
        "name": "248c2716-0a4f-59f4-ac42-5cd36102328e",
        "fromTable": "Fact_Prestamos",
        "fromColumn": "sk_cliente",
        "toTable": "Dim_Cliente",
        "toColumn": "sk_cliente"
      },
      {
        "name": "d4634a3d-ad2f-5c75-ba04-b8329906b9bd",
        "fromTable": "Fact_Prestamos",
        "fromColumn": "sk_cuenta",
        "toTable": "Dim_Cuenta",
        "toColumn": "sk_cuenta"
      },
      {
        "name": "976e6415-a353-5311-8f4e-0d3274455753",
        "fromTable": "Fact_Ordenes",
        "fromColumn": "sk_distrito",
        "toTable": "Dim_Distrito",
        "toColumn": "sk_distrito"
      },
      {
        "name": "17d8c796-1a9e-5615-b22f-365cb1bf31f7",
        "fromTable": "Fact_Ordenes",
        "fromColumn": "sk_cliente",
        "toTable": "Dim_Cliente",
        "toColumn": "sk_cliente"
      },
      {
        "name": "818da0c2-49e4-5838-bee1-0f9701dca364",
        "fromTable": "Fact_Ordenes",
        "fromColumn": "sk_cuenta",
        "toTable": "Dim_Cuenta",
        "toColumn": "sk_cuenta"
      },
      {
        "name": "f2074732-e5d5-5f6d-9acc-f654205d91e0",
        "fromTable": "Fact_Saldo_Cuenta_Mensual",
        "fromColumn": "sk_distrito",
        "toTable": "Dim_Distrito",
        "toColumn": "sk_distrito"
      },
      {
        "name": "97469a55-6f3d-5262-b4f1-befa3f5b0d18",
        "fromTable": "Fact_Saldo_Cuenta_Mensual",
        "fromColumn": "sk_cliente",
        "toTable": "Dim_Cliente",
        "toColumn": "sk_cliente"
      },
      {
        "name": "ae89b222-0031-5623-9f91-660cdd3b697d",
        "fromTable": "Fact_Saldo_Cuenta_Mensual",
        "fromColumn": "sk_cuenta",
        "toTable": "Dim_Cuenta",
        "toColumn": "sk_cuenta"
      },
      {
        "name": "9d1a745d-41a6-539a-9d04-ddee5340ad48",
        "fromTable": "vw_PBI_Trans_Anual_Cuenta",
        "fromColumn": "sk_distrito",
        "toTable": "Dim_Distrito",
        "toColumn": "sk_distrito"
      },
      {
        "name": "61c12dba-d7e2-59ad-83b3-d10201b57c7b",
        "fromTable": "vw_PBI_Trans_Anual_Cuenta",
        "fromColumn": "sk_cliente",
        "toTable": "Dim_Cliente",
        "toColumn": "sk_cliente"
      },
      {
        "name": "388c4909-4bac-5693-bc17-8515aee8c2af",
        "fromTable": "vw_PBI_Trans_Anual_Cuenta",
        "fromColumn": "sk_cuenta",
        "toTable": "Dim_Cuenta",
        "toColumn": "sk_cuenta"
      },
      {
        "name": "89ab726f-0338-52ff-903c-cdc3e1f90e66",
        "fromTable": "Fact_Prestamos",
        "fromColumn": "sk_estado_prestamo",
        "toTable": "Dim_Estado_Prestamo",
        "toColumn": "sk_estado_prestamo"
      },
      {
        "name": "83a841cf-ce39-5887-b353-71bad3eba2b7",
        "fromTable": "Fact_Prestamos",
        "fromColumn": "sk_tiempo",
        "toTable": "Dim_Tiempo",
        "toColumn": "sk_tiempo"
      },
      {
        "name": "84afc93d-7f20-5838-88f2-cae2e450178e",
        "fromTable": "Fact_Saldo_Cuenta_Mensual",
        "fromColumn": "sk_mes",
        "toTable": "Dim_Tiempo",
        "toColumn": "sk_tiempo"
      },
      {
        "name": "49fc8930-84cf-532f-977b-1ab6a60a7d49",
        "fromTable": "Fact_Ordenes",
        "fromColumn": "sk_orden_tipo",
        "toTable": "Dim_Orden",
        "toColumn": "sk_orden_tipo"
      },
      {
        "name": "bd7c2605-ba25-5a08-ac64-9727b5c1ee88",
        "fromTable": "Fact_Ordenes",
        "fromColumn": "sk_tiempo_apertura_cuenta",
        "toTable": "Dim_Tiempo",
        "toColumn": "sk_tiempo",
        "isActive": false
      },
      {
        "name": "51358d23-2ba7-5154-b878-d71cb5a2f711",
        "fromTable": "Dim_Tiempo",
        "fromColumn": "anio",
        "toTable": "Dim_Anio",
        "toColumn": "anio"
      },
      {
        "name": "7ca0d207-d191-5342-9736-1cdc48b7467a",
        "fromTable": "vw_PBI_Trans_Anual_Cuenta",
        "fromColumn": "anio",
        "toTable": "Dim_Anio",
        "toColumn": "anio"
      },
      {
        "name": "efd80b67-0898-59bc-90ff-675195b41fec",
        "fromTable": "Recomendacion_Cuenta",
        "fromColumn": "sk_cuenta",
        "toTable": "Dim_Cuenta",
        "toColumn": "sk_cuenta"
      },
      {
        "name": "97851357-e81b-5d0f-b0a2-7753c92f7913",
        "fromTable": "Recomendacion_Cuenta",
        "fromColumn": "sk_cliente",
        "toTable": "Dim_Cliente",
        "toColumn": "sk_cliente"
      },
      {
        "name": "a60b6783-d4c0-588e-bf58-d82a2e25f04e",
        "fromTable": "Recomendacion_Producto",
        "fromColumn": "sk_cuenta",
        "toTable": "Dim_Cuenta",
        "toColumn": "sk_cuenta"
      },
      {
        "name": "63d62597-0a9d-5fe4-a8e9-8714326367a8",
        "fromTable": "Recomendacion_Producto",
        "fromColumn": "sk_cliente",
        "toTable": "Dim_Cliente",
        "toColumn": "sk_cliente"
      },
      {
        "name": "98812add-6da7-507f-9296-2814e455a8de",
        "fromTable": "Recomendacion_Producto",
        "fromColumn": "sk_distrito",
        "toTable": "Dim_Distrito",
        "toColumn": "sk_distrito"
      },
      {
        "name": "1c5d7887-ec65-573c-928c-0804b2940ca3",
        "fromTable": "Adopcion_Producto",
        "fromColumn": "sk_cuenta",
        "toTable": "Dim_Cuenta",
        "toColumn": "sk_cuenta"
      },
      {
        "name": "a92c47ea-ea54-5ed1-90a0-043ff916fb82",
        "fromTable": "Adopcion_Producto",
        "fromColumn": "sk_cliente",
        "toTable": "Dim_Cliente",
        "toColumn": "sk_cliente"
      },
      {
        "name": "cef24360-56a5-5000-b0d1-ada96f7ffa2e",
        "fromTable": "Adopcion_Producto",
        "fromColumn": "sk_distrito",
        "toTable": "Dim_Distrito",
        "toColumn": "sk_distrito"
      },
      {
        "name": "1a46feaa-2f56-5f29-ba7b-f66818c3f017",
        "fromTable": "Capacidad_Prestamo",
        "fromColumn": "sk_cuenta",
        "toTable": "Dim_Cuenta",
        "toColumn": "sk_cuenta"
      },
      {
        "name": "0f29a033-b491-5aaa-8eda-f88285dd76b1",
        "fromTable": "Capacidad_Prestamo",
        "fromColumn": "sk_cliente",
        "toTable": "Dim_Cliente",
        "toColumn": "sk_cliente"
      },
      {
        "name": "790c1c98-dbd0-57b7-91bc-115b4517f4a2",
        "fromTable": "Capacidad_Prestamo",
        "fromColumn": "sk_distrito",
        "toTable": "Dim_Distrito",
        "toColumn": "sk_distrito"
      },
      {
        "name": "4d53a5c9-f3cf-5aec-a856-6a2db10999a5",
        "fromTable": "Recomendacion_Producto",
        "fromColumn": "producto",
        "toTable": "Dim_Producto",
        "toColumn": "producto"
      },
      {
        "name": "4c6520aa-4420-56a6-a956-86a931a723d8",
        "fromTable": "Adopcion_Producto",
        "fromColumn": "producto",
        "toTable": "Dim_Producto",
        "toColumn": "producto"
      }
    ],
    "expressions": [
      {
        "name": "ServidorSQL",
        "kind": "m",
        "expression": "\"(localdb)\\MSSQLLocalDB\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]"
      },
      {
        "name": "BaseDatosSQL",
        "kind": "m",
        "expression": "\"DM_Financial_Kimball_v2\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]"
      }
    ],
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      }
    ]
  }
}