{
  "compatibilityLevel": 1606,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Dim_Tiempo\",\"Dim_Anio\",\"Dim_Distrito\",\"Dim_Cliente\",\"Dim_Cuenta\",\"Dim_Estado_Prestamo\",\"Dim_Orden\",\"Fact_Prestamos\",\"Fact_Ordenes\",\"Fact_Saldo_Cuenta_Mensual\",\"vw_PBI_Trans_Anual_Cuenta\",\"Recomendacion_Cuenta\",\"Dim_Producto\",\"Recomendacion_Producto\",\"Adopcion_Producto\",\"Capacidad_Prestamo\",\"Evaluacion_Recomendador\",\"Asociacion_Producto\",\"Regla_Capacidad\",\"Composicion_Liquidez\",\"_Medidas\",\"ServidorSQL\",\"BaseDatosSQL\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "es-ES",
    "cultures": [
      {
        "name": "es-ES",
        "linguisticMetadata": {
          "content": {
            "Entities": {
              "asociacion_producto.producto_destino": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Asociacion_Producto",
                    "ConceptualProperty": "producto_destino"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "…también tiene": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "asociacion_producto.producto_origen": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Asociacion_Producto",
                    "ConceptualProperty": "producto_origen"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Si ya tiene…": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "capacidad_prestamo.tramo_monto_36m": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Capacidad_Prestamo",
                    "ConceptualProperty": "tramo_monto_36m"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Monto máximo a 36 meses": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "composicion_liquidez.concepto": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Composicion_Liquidez",
                    "ConceptualProperty": "concepto"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Concepto": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "dim_anio.anio": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Dim_Anio",
                    "ConceptualProperty": "anio"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Año de otorgamiento": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  },
                  {
                    "Año": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "dim_cliente.arquetipo_demografico": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Dim_Cliente",
                    "ConceptualProperty": "arquetipo_demografico"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Arquetipo": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "dim_cliente.cliente": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Dim_Cliente",
                    "ConceptualProperty": "Cliente"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Cliente": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  },
                  {
                    "Titular": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "dim_cliente.segmento_edad": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Dim_Cliente",
                    "ConceptualProperty": "segmento_edad"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Segmento de edad": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "dim_distrito.nombre_distrito": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Dim_Distrito",
                    "ConceptualProperty": "nombre_distrito"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Distrito": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "dim_distrito.region": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Dim_Distrito",
                    "ConceptualProperty": "region"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Región": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "dim_estado_prestamo.estado": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Dim_Estado_Prestamo",
                    "ConceptualProperty": "Estado"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Estado": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "dim_orden.categoria_orden_traducida": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Dim_Orden",
                    "ConceptualProperty": "categoria_orden_traducida"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Propósito": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "dim_producto.producto": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Dim_Producto",
                    "ConceptualProperty": "producto"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Producto": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "dim_tiempo.fecha": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Dim_Tiempo",
                    "ConceptualProperty": "fecha"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Mes": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "evaluacion_recomendador.modelo": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Evaluacion_Recomendador",
                    "ConceptualProperty": "modelo"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Modelo": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "fact_prestamos.banda_capacidad": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Fact_Prestamos",
                    "ConceptualProperty": "banda_capacidad"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Banda de capacidad (cuota / saldo previo)": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  },
                  {
                    "Banda de capacidad": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "recomendacion_cuenta.recomendacion_1": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Recomendacion_Cuenta",
                    "ConceptualProperty": "recomendacion_1"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "1.ª oferta": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "recomendacion_cuenta.recomendacion_2": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Recomendacion_Cuenta",
                    "ConceptualProperty": "recomendacion_2"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "2.ª": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "recomendacion_cuenta.recomendacion_3": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Recomendacion_Cuenta",
                    "ConceptualProperty": "recomendacion_3"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "3.ª": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "regla_capacidad.regla": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Regla_Capacidad",
                    "ConceptualProperty": "regla"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Regla": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.absorcion_banco": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Absorcion Banco"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Banco": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.absorcion_vigente": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Absorcion Vigente"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Absorción vigente": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.acierto_hit1": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Acierto Hit1"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Acierto (Hit@1)": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.arquetipo_cliente": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Arquetipo Cliente"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Arquetipo": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.auc_regla": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "AUC Regla"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "AUC": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.banda_capacidad": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Banda Capacidad"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Banda de capacidad": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.banda_capacidad_impago": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Banda Capacidad Impago"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Banda de capacidad": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.calificacion_cliente": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Calificacion Cliente"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Calificación de pago": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.cartera_total": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Cartera Total"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Monto": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  },
                  {
                    "Monto del préstamo": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.cartera_vigente": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Cartera Vigente"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Cartera vigente": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.compromiso_alerta": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Compromiso Alerta"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Órdenes mensuales": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.compromiso_ordenes": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Compromiso Ordenes"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Órdenes mensuales": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  },
                  {
                    "Monto mensual": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.credito_externo_alerta": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Credito Externo Alerta"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Crédito externo mensual": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.credito_externo_mensual": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Credito Externo Mensual"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Crédito externo mensual": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.cuenta_alerta": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Cuenta Alerta"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Cuenta": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.cuentas_en_sobregiro": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Cuentas en Sobregiro"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Cuentas en sobregiro": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.cuentas_que_ya_lo_usan": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Cuentas que ya lo Usan"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Ya lo usan": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.cuota_maxima_prudente": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Cuota Maxima Prudente"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Cuota préstamo máx.": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  },
                  {
                    "Cuota máx. préstamo": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.cuota_mensual": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Cuota Mensual"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Cuota": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.cuota_prudente_oferta": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Cuota Prudente Oferta"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Cuota máx.": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.descubrimiento_knn": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Descubrimiento kNN"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Además, ofrecer": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  },
                  {
                    "Además (kNN)": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.descubrimientos_knn": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Descubrimientos kNN"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Ofertas nuevas": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.desempleo_distrito_1995": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Desempleo Distrito 1995"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Desempleo 1995 (%)": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.distrito_cuenta": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Distrito Cuenta"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Distrito de la cuenta": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.distrito_impago": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Distrito Impago"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Distrito": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.edad_cliente": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Edad Cliente"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Edad": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.estado_prestamo": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Estado Prestamo"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Estado": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  },
                  {
                    "Préstamo": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.indice_saturacion": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Indice Saturacion"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Índice de saturación": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.indice_saturacion_alerta": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Indice Saturacion Alerta"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Índice de saturación": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.monto_12m_oferta": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Monto 12m Oferta"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "12 meses": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.monto_36m_oferta": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Monto 36m Oferta"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "36 meses": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.monto_60m_oferta": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Monto 60m Oferta"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "60 meses": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.monto_incumplido": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Monto Incumplido"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Monto del préstamo B": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.monto_maximo_prudente": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Monto Maximo Prudente"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Monto máx. (36 m)": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.monto_prudente_ofrecible_36m": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Monto Prudente Ofrecible 36m"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Monto a 36 meses": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.mora_wilson_inferior": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Mora Wilson Inferior"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Wilson inf.": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.mora_wilson_superior": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Mora Wilson Superior"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Wilson sup.": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.num_ordenes": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Num Ordenes"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Órdenes": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.num_prestamos": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Num Prestamos"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Préstamos otorgados": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  },
                  {
                    "Préstamos": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.origen_indicadores": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Origen Indicadores"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Indicadores": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.poblacion_distrito": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Poblacion Distrito"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Población": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.prestamos_en_mora": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Prestamos en Mora"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "En mora": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.prestamos_vigentes": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Prestamos Vigentes"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Vigentes (n)": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  },
                  {
                    "Vigentes": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.recomendacion_1": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Recomendacion 1"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "1.ª oferta": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  },
                  {
                    "Oferta principal": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.recomendacion_2": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Recomendacion 2"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "2.ª": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.recomendacion_3": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Recomendacion 3"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "3.ª": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.recomendaciones_demograficas": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Recomendaciones Demograficas"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Recomendado (top 3)": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.salario_promedio_distrito": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Salario Promedio Distrito"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Salario promedio": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.saldo_neto_corte": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Saldo Neto Corte"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Saldo neto al cierre": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  },
                  {
                    "Saldo al cierre": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.saldo_promedio_alerta": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Saldo Promedio Alerta"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Saldo promedio": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.saldo_promedio_banco": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Saldo Promedio Banco"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Banco": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.saldo_promedio_historico": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Saldo Promedio Historico"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Saldo promedio de la cuenta": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.saldo_promedio_oferta": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Saldo Promedio Oferta"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Saldo promedio": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.saldo_promedio_por_cuenta": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Saldo Promedio por Cuenta"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Saldo promedio por cuenta": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  },
                  {
                    "Distrito": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.segmento_cliente": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Segmento Cliente"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Segmento": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.tasa_impago": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Tasa Impago"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Tasa de impago (B o D)": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  },
                  {
                    "Tasa de impago": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.tasa_impago_banco": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Tasa Impago Banco"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Banco": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.tasa_incumplimiento": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Tasa Incumplimiento"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Tasa de incumplimiento": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.tasa_incumplimiento_banco": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Tasa Incumplimiento Banco"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Banco": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.tasa_mora_banco": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Tasa Mora Banco"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Banco": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.tasa_mora_vigente": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Tasa Mora Vigente"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Tasa de mora de la cosecha": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  },
                  {
                    "Tasa de mora": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  },
                  {
                    "Tasa": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  },
                  {
                    "Tasa de mora vigente": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.ticket_promedio": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Ticket Promedio"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Ticket promedio": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.titulares_sin_prestamo": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Titulares sin Prestamo"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Titulares sin préstamo": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.umbral_sobregiro": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Umbral Sobregiro"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Cero": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.valor_composicion_liquidez": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Valor Composicion Liquidez"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Monto": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.volumen_transaccionado": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Volumen Transaccionado"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Volumen": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "vw_pbi_trans_anual_cuenta.categoria_analitica": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "vw_PBI_Trans_Anual_Cuenta",
                    "ConceptualProperty": "categoria_analitica"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Categoría": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              }
            },
            "Language": "en-US",
            "Version": "2.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "ServidorSQL",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"(localdb)\\MSSQLLocalDB\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "0bd2eb17-40ee-4f8d-9b1d-eb1049350af9"
      },
      {
        "name": "BaseDatosSQL",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"DM_Financial_Kimball_v2\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "4e2be678-ed78-4ffb-9b93-0a7f78e73483"
      }
    ],
    "relationships": [
      {
        "name": "bd0e598c-9e1f-5df2-b4a9-dece4bf6c23b",
        "fromColumn": "sk_distrito",
        "fromTable": "Fact_Prestamos",
        "toColumn": "sk_distrito",
        "toTable": "Dim_Distrito"
      },
      {
        "name": "248c2716-0a4f-59f4-ac42-5cd36102328e",
        "fromColumn": "sk_cliente",
        "fromTable": "Fact_Prestamos",
        "toColumn": "sk_cliente",
        "toTable": "Dim_Cliente"
      },
      {
        "name": "d4634a3d-ad2f-5c75-ba04-b8329906b9bd",
        "fromColumn": "sk_cuenta",
        "fromTable": "Fact_Prestamos",
        "toColumn": "sk_cuenta",
        "toTable": "Dim_Cuenta"
      },
      {
        "name": "976e6415-a353-5311-8f4e-0d3274455753",
        "fromColumn": "sk_distrito",
        "fromTable": "Fact_Ordenes",
        "toColumn": "sk_distrito",
        "toTable": "Dim_Distrito"
      },
      {
        "name": "17d8c796-1a9e-5615-b22f-365cb1bf31f7",
        "fromColumn": "sk_cliente",
        "fromTable": "Fact_Ordenes",
        "toColumn": "sk_cliente",
        "toTable": "Dim_Cliente"
      },
      {
        "name": "818da0c2-49e4-5838-bee1-0f9701dca364",
        "fromColumn": "sk_cuenta",
        "fromTable": "Fact_Ordenes",
        "toColumn": "sk_cuenta",
        "toTable": "Dim_Cuenta"
      },
      {
        "name": "f2074732-e5d5-5f6d-9acc-f654205d91e0",
        "fromColumn": "sk_distrito",
        "fromTable": "Fact_Saldo_Cuenta_Mensual",
        "toColumn": "sk_distrito",
        "toTable": "Dim_Distrito"
      },
      {
        "name": "97469a55-6f3d-5262-b4f1-befa3f5b0d18",
        "fromColumn": "sk_cliente",
        "fromTable": "Fact_Saldo_Cuenta_Mensual",
        "toColumn": "sk_cliente",
        "toTable": "Dim_Cliente"
      },
      {
        "name": "ae89b222-0031-5623-9f91-660cdd3b697d",
        "fromColumn": "sk_cuenta",
        "fromTable": "Fact_Saldo_Cuenta_Mensual",
        "toColumn": "sk_cuenta",
        "toTable": "Dim_Cuenta"
      },
      {
        "name": "9d1a745d-41a6-539a-9d04-ddee5340ad48",
        "fromColumn": "sk_distrito",
        "fromTable": "vw_PBI_Trans_Anual_Cuenta",
        "toColumn": "sk_distrito",
        "toTable": "Dim_Distrito"
      },
      {
        "name": "61c12dba-d7e2-59ad-83b3-d10201b57c7b",
        "fromColumn": "sk_cliente",
        "fromTable": "vw_PBI_Trans_Anual_Cuenta",
        "toColumn": "sk_cliente",
        "toTable": "Dim_Cliente"
      },
      {
        "name": "388c4909-4bac-5693-bc17-8515aee8c2af",
        "fromColumn": "sk_cuenta",
        "fromTable": "vw_PBI_Trans_Anual_Cuenta",
        "toColumn": "sk_cuenta",
        "toTable": "Dim_Cuenta"
      },
      {
        "name": "89ab726f-0338-52ff-903c-cdc3e1f90e66",
        "fromColumn": "sk_estado_prestamo",
        "fromTable": "Fact_Prestamos",
        "toColumn": "sk_estado_prestamo",
        "toTable": "Dim_Estado_Prestamo"
      },
      {
        "name": "83a841cf-ce39-5887-b353-71bad3eba2b7",
        "fromColumn": "sk_tiempo",
        "fromTable": "Fact_Prestamos",
        "toColumn": "sk_tiempo",
        "toTable": "Dim_Tiempo"
      },
      {
        "name": "84afc93d-7f20-5838-88f2-cae2e450178e",
        "fromColumn": "sk_mes",
        "fromTable": "Fact_Saldo_Cuenta_Mensual",
        "toColumn": "sk_tiempo",
        "toTable": "Dim_Tiempo"
      },
      {
        "name": "49fc8930-84cf-532f-977b-1ab6a60a7d49",
        "fromColumn": "sk_orden_tipo",
        "fromTable": "Fact_Ordenes",
        "toColumn": "sk_orden_tipo",
        "toTable": "Dim_Orden"
      },
      {
        "name": "bd7c2605-ba25-5a08-ac64-9727b5c1ee88",
        "fromColumn": "sk_tiempo_apertura_cuenta",
        "fromTable": "Fact_Ordenes",
        "isActive": false,
        "toColumn": "sk_tiempo",
        "toTable": "Dim_Tiempo"
      },
      {
        "name": "51358d23-2ba7-5154-b878-d71cb5a2f711",
        "fromColumn": "anio",
        "fromTable": "Dim_Tiempo",
        "toColumn": "anio",
        "toTable": "Dim_Anio"
      },
      {
        "name": "7ca0d207-d191-5342-9736-1cdc48b7467a",
        "fromColumn": "anio",
        "fromTable": "vw_PBI_Trans_Anual_Cuenta",
        "toColumn": "anio",
        "toTable": "Dim_Anio"
      },
      {
        "name": "efd80b67-0898-59bc-90ff-675195b41fec",
        "fromColumn": "sk_cuenta",
        "fromTable": "Recomendacion_Cuenta",
        "toColumn": "sk_cuenta",
        "toTable": "Dim_Cuenta"
      },
      {
        "name": "97851357-e81b-5d0f-b0a2-7753c92f7913",
        "fromColumn": "sk_cliente",
        "fromTable": "Recomendacion_Cuenta",
        "toColumn": "sk_cliente",
        "toTable": "Dim_Cliente"
      },
      {
        "name": "a60b6783-d4c0-588e-bf58-d82a2e25f04e",
        "fromColumn": "sk_cuenta",
        "fromTable": "Recomendacion_Producto",
        "toColumn": "sk_cuenta",
        "toTable": "Dim_Cuenta"
      },
      {
        "name": "63d62597-0a9d-5fe4-a8e9-8714326367a8",
        "fromColumn": "sk_cliente",
        "fromTable": "Recomendacion_Producto",
        "toColumn": "sk_cliente",
        "toTable": "Dim_Cliente"
      },
      {
        "name": "98812add-6da7-507f-9296-2814e455a8de",
        "fromColumn": "sk_distrito",
        "fromTable": "Recomendacion_Producto",
        "toColumn": "sk_distrito",
        "toTable": "Dim_Distrito"
      },
      {
        "name": "1c5d7887-ec65-573c-928c-0804b2940ca3",
        "fromColumn": "sk_cuenta",
        "fromTable": "Adopcion_Producto",
        "toColumn": "sk_cuenta",
        "toTable": "Dim_Cuenta"
      },
      {
        "name": "a92c47ea-ea54-5ed1-90a0-043ff916fb82",
        "fromColumn": "sk_cliente",
        "fromTable": "Adopcion_Producto",
        "toColumn": "sk_cliente",
        "toTable": "Dim_Cliente"
      },
      {
        "name": "cef24360-56a5-5000-b0d1-ada96f7ffa2e",
        "fromColumn": "sk_distrito",
        "fromTable": "Adopcion_Producto",
        "toColumn": "sk_distrito",
        "toTable": "Dim_Distrito"
      },
      {
        "name": "1a46feaa-2f56-5f29-ba7b-f66818c3f017",
        "fromColumn": "sk_cuenta",
        "fromTable": "Capacidad_Prestamo",
        "toColumn": "sk_cuenta",
        "toTable": "Dim_Cuenta"
      },
      {
        "name": "0f29a033-b491-5aaa-8eda-f88285dd76b1",
        "fromColumn": "sk_cliente",
        "fromTable": "Capacidad_Prestamo",
        "toColumn": "sk_cliente",
        "toTable": "Dim_Cliente"
      },
      {
        "name": "790c1c98-dbd0-57b7-91bc-115b4517f4a2",
        "fromColumn": "sk_distrito",
        "fromTable": "Capacidad_Prestamo",
        "toColumn": "sk_distrito",
        "toTable": "Dim_Distrito"
      },
      {
        "name": "4d53a5c9-f3cf-5aec-a856-6a2db10999a5",
        "fromColumn": "producto",
        "fromTable": "Recomendacion_Producto",
        "toColumn": "producto",
        "toTable": "Dim_Producto"
      },
      {
        "name": "4c6520aa-4420-56a6-a956-86a931a723d8",
        "fromColumn": "producto",
        "fromTable": "Adopcion_Producto",
        "toColumn": "producto",
        "toTable": "Dim_Producto"
      }
    ],
    "sourceQueryCulture": "es-ES",
    "tables": [
      {
        "name": "Dim_Tiempo",
        "columns": [
          {
            "name": "sk_tiempo",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "cb9867af-3cbb-448f-92ec-83bfd05094d6",
            "sourceColumn": "sk_tiempo",
            "summarizeBy": "none"
          },
          {
            "name": "fecha",
            "dataType": "dateTime",
            "formatString": "dd/mm/yyyy",
            "lineageTag": "9ae1cde5-3422-46a3-9f41-65d6c7cd8854",
            "sourceColumn": "fecha",
            "summarizeBy": "none"
          },
          {
            "name": "anio",
            "dataType": "int64",
            "lineageTag": "18f53f9e-d48a-4675-a749-0aae4106d220",
            "sourceColumn": "anio",
            "summarizeBy": "none"
          },
          {
            "name": "mes",
            "dataType": "int64",
            "lineageTag": "7fdc89c3-8143-4c77-b479-8e35d14bf520",
            "sourceColumn": "mes",
            "summarizeBy": "none"
          },
          {
            "name": "nombre_mes",
            "dataType": "string",
            "lineageTag": "91b9167e-edb1-4e1c-94ba-908198efc833",
            "sourceColumn": "nombre_mes",
            "summarizeBy": "none"
          },
          {
            "name": "es_fin_de_mes",
            "dataType": "boolean",
            "lineageTag": "6d340131-f93b-4be6-beb4-c1c91b56258b",
            "sourceColumn": "es_fin_de_mes",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "b2503da4-1ec1-40a1-a3d0-df2761118c52",
        "partitions": [
          {
            "name": "Dim_Tiempo",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = Sql.Database(ServidorSQL, BaseDatosSQL),",
                "    Tabla = Origen{[Schema=\"dbo\", Item=\"Dim_Tiempo\"]}[Data],",
                "    Columnas = Table.SelectColumns(Tabla, {\"sk_tiempo\", \"fecha\", \"anio\", \"mes\", \"nombre_mes\", \"es_fin_de_mes\"}),",
                "    Tipos = Table.TransformColumnTypes(Columnas, {{\"sk_tiempo\", Int64.Type}, {\"fecha\", type datetime}, {\"anio\", Int64.Type}, {\"mes\", Int64.Type}, {\"nombre_mes\", type text}, {\"es_fin_de_mes\", type logical}})",
                "in",
                "    Tipos"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dim_Anio",
        "columns": [
          {
            "name": "anio",
            "dataType": "int64",
            "lineageTag": "5c264a61-118f-4b42-9b3e-92c0f99b07c8",
            "sourceColumn": "anio",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "b00a0b46-ade0-4a45-8e5a-b46952831db7",
        "partitions": [
          {
            "name": "Dim_Anio",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = Sql.Database(ServidorSQL, BaseDatosSQL),",
                "    Tiempo = Origen{[Schema=\"dbo\", Item=\"Dim_Tiempo\"]}[Data],",
                "    Anios = Table.Distinct(Table.SelectColumns(Tiempo, {\"anio\"})),",
                "    Tipos = Table.TransformColumnTypes(Anios, {{\"anio\", Int64.Type}})",
                "in",
                "    Tipos"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dim_Distrito",
        "columns": [
          {
            "name": "sk_distrito",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "f41be56d-842b-44ea-8073-9ec8f25c23bc",
            "sourceColumn": "sk_distrito",
            "summarizeBy": "none"
          },
          {
            "name": "id_distrito_bk",
            "dataType": "int64",
            "lineageTag": "66bb626c-39da-42b5-9815-95d7d8c4b8fa",
            "sourceColumn": "id_distrito_bk",
            "summarizeBy": "none"
          },
          {
            "name": "nombre_distrito",
            "dataType": "string",
            "lineageTag": "5743f522-4141-465d-b497-2fef90458890",
            "sourceColumn": "nombre_distrito",
            "summarizeBy": "none"
          },
          {
            "name": "region",
            "dataType": "string",
            "lineageTag": "923363fe-8efd-4fa5-94d5-21398e5c08f3",
            "sourceColumn": "region",
            "summarizeBy": "none"
          },
          {
            "name": "poblacion",
            "dataType": "int64",
            "lineageTag": "7a339359-a86b-4de1-9f6d-ef85941ee03c",
            "sourceColumn": "poblacion",
            "summarizeBy": "none"
          },
          {
            "name": "salario_promedio",
            "dataType": "double",
            "formatString": "\"$\"#,0",
            "lineageTag": "f07608e9-f9d0-4d0a-9a2d-597daee07946",
            "sourceColumn": "salario_promedio",
            "summarizeBy": "none"
          },
          {
            "name": "tasa_desempleo",
            "dataType": "double",
            "formatString": "0.00",
            "lineageTag": "7e39b498-0d06-4419-a8e1-ac46cbd2c17d",
            "sourceColumn": "tasa_desempleo",
            "summarizeBy": "none"
          },
          {
            "name": "tasa_criminalidad",
            "dataType": "double",
            "formatString": "0.00",
            "lineageTag": "acbbbe48-095a-4f57-85ea-3f45b81ee515",
            "sourceColumn": "tasa_criminalidad",
            "summarizeBy": "none"
          },
          {
            "name": "es_imputado",
            "dataType": "boolean",
            "lineageTag": "dfec8615-188a-49b2-b097-1e918e00268e",
            "sourceColumn": "es_imputado",
            "summarizeBy": "none"
          },
          {
            "name": "Macro Region",
            "dataType": "string",
            "expression": "SWITCH(TRUE(), Dim_Distrito[region] = \"Prague\", \"Praga\", CONTAINSSTRING(Dim_Distrito[region], \"Moravia\"), \"Moravia\", \"Bohemia\")",
            "lineageTag": "c4bc053e-5b67-4f5a-85c1-34f0928328ee",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "d8d0b693-08dd-4fdf-aac6-a072b63513eb",
        "partitions": [
          {
            "name": "Dim_Distrito",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = Sql.Database(ServidorSQL, BaseDatosSQL),",
                "    Tabla = Origen{[Schema=\"dbo\", Item=\"Dim_Distrito\"]}[Data],",
                "    Columnas = Table.SelectColumns(Tabla, {\"sk_distrito\", \"id_distrito_bk\", \"nombre_distrito\", \"region\", \"poblacion\", \"salario_promedio\", \"tasa_desempleo\", \"tasa_criminalidad\", \"es_imputado\"}),",
                "    Tipos = Table.TransformColumnTypes(Columnas, {{\"sk_distrito\", Int64.Type}, {\"id_distrito_bk\", Int64.Type}, {\"nombre_distrito\", type text}, {\"region\", type text}, {\"poblacion\", Int64.Type}, {\"salario_promedio\", type number}, {\"tasa_desempleo\", type number}, {\"tasa_criminalidad\", type number}, {\"es_imputado\", type logical}})",
                "in",
                "    Tipos"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dim_Cliente",
        "columns": [
          {
            "name": "sk_cliente",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "7eeaadbf-b175-4025-bb93-621c1565c0e7",
            "sourceColumn": "sk_cliente",
            "summarizeBy": "none"
          },
          {
            "name": "id_cliente_bk",
            "dataType": "int64",
            "lineageTag": "a78386de-d862-44a9-a337-863a612d9e1a",
            "sourceColumn": "id_cliente_bk",
            "summarizeBy": "none"
          },
          {
            "name": "sexo",
            "dataType": "string",
            "lineageTag": "3305cdc0-b74d-49a7-bfbe-199e726515df",
            "sourceColumn": "sexo",
            "summarizeBy": "none"
          },
          {
            "name": "edad_corte",
            "dataType": "int64",
            "lineageTag": "8be125cf-ea47-4a56-93e3-ab7aeb10064c",
            "sourceColumn": "edad_corte",
            "summarizeBy": "none"
          },
          {
            "name": "tipo_disposicion",
            "dataType": "string",
            "lineageTag": "f80ae9c1-98b9-4483-8a64-a439fb4333c5",
            "sourceColumn": "tipo_disposicion",
            "summarizeBy": "none"
          },
          {
            "name": "segmento_edad",
            "dataType": "string",
            "lineageTag": "7c6ec1a9-16fb-4587-8769-264b4babfba3",
            "sortByColumn": "Orden Segmento",
            "sourceColumn": "segmento_edad",
            "summarizeBy": "none"
          },
          {
            "name": "arquetipo_demografico",
            "dataType": "string",
            "lineageTag": "ce2bb576-b3ea-4539-838a-1cea0faed6bb",
            "sourceColumn": "arquetipo_demografico",
            "summarizeBy": "none"
          },
          {
            "name": "calificacion_pago_desc",
            "dataType": "string",
            "lineageTag": "488da148-fe09-4a35-97d9-5d15e21289aa",
            "sourceColumn": "calificacion_pago_desc",
            "summarizeBy": "none"
          },
          {
            "name": "Orden Segmento",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "c21b063e-b274-451b-a897-92087823a91b",
            "sourceColumn": "Orden Segmento",
            "summarizeBy": "none"
          },
          {
            "name": "Cliente",
            "dataType": "string",
            "expression": "\"Cliente \" & Dim_Cliente[id_cliente_bk]",
            "lineageTag": "de7a61ea-d467-4273-84b9-a9bc90706dba",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Estado del Prestamo",
            "dataType": "string",
            "expression": "VAR e = CALCULATE(MAX(Dim_Estado_Prestamo[Estado]), CALCULATETABLE(Fact_Prestamos)) RETURN IF(ISBLANK(e), \"Sin préstamo\", e)",
            "lineageTag": "3cf0bbf0-aa55-4026-9451-8e1f1d107e49",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Banda de Capacidad",
            "dataType": "string",
            "expression": "VAR b = CALCULATE(MAX(Fact_Prestamos[banda_capacidad]), CALCULATETABLE(Fact_Prestamos)) RETURN IF(ISBLANK(b), \"Sin préstamo\", b)",
            "lineageTag": "24fbf0ff-0265-4a25-97a8-198017dd1634",
            "sortByColumn": "Orden Banda Cliente",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Orden Banda Cliente",
            "dataType": "int64",
            "expression": "VAR o = CALCULATE(MAX(Fact_Prestamos[Orden Banda]), CALCULATETABLE(Fact_Prestamos)) RETURN IF(ISBLANK(o), 5, o)",
            "isHidden": true,
            "lineageTag": "4a6c7b8d-0b83-424a-970c-72e2d16e476e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Alerta de Saturacion",
            "dataType": "string",
            "expression": "VAR i = [Indice Saturacion] RETURN SWITCH(TRUE(), ISBLANK(i), \"Sin órdenes\", i > 1, \"Crítica (> 1)\", i > 0.5, \"Alta (> 0.5)\", \"Normal\")",
            "lineageTag": "05bfa7fb-1a82-4ecb-b115-1aa016912923",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Primera Oferta",
            "dataType": "string",
            "expression": "VAR x = CALCULATE(MAX(Recomendacion_Producto[producto]), Recomendacion_Producto[sistema] = \"Demográfico\", Recomendacion_Producto[posicion] = 1) RETURN IF(ISBLANK(x), \"Sin recomendación\", x)",
            "lineageTag": "38b3d558-e72b-4080-889b-d4648e6f8874",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Prestamo Recomendado",
            "dataType": "string",
            "expression": "IF(CALCULATE(COUNTROWS(Capacidad_Prestamo)) = 0, \"Sin cuenta propia\", IF(CALCULATE(COUNTROWS(Capacidad_Prestamo), Capacidad_Prestamo[prestamo_recomendado] = TRUE()) > 0, \"Sí\", \"No\"))",
            "lineageTag": "2a943e75-5ece-424b-8b0e-658353aa87a7",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "ad6a7810-17bb-4ebf-8ab9-f6beb6ec984a",
        "partitions": [
          {
            "name": "Dim_Cliente",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = Sql.Database(ServidorSQL, BaseDatosSQL),",
                "    Tabla = Origen{[Schema=\"dbo\", Item=\"Dim_Cliente\"]}[Data],",
                "    Columnas = Table.SelectColumns(Tabla, {\"sk_cliente\", \"id_cliente_bk\", \"sexo\", \"edad_corte\", \"tipo_disposicion\", \"segmento_edad\", \"arquetipo_demografico\", \"calificacion_pago_desc\"}),",
                "    Tipos = Table.TransformColumnTypes(Columnas, {{\"sk_cliente\", Int64.Type}, {\"id_cliente_bk\", Int64.Type}, {\"sexo\", type text}, {\"edad_corte\", Int64.Type}, {\"tipo_disposicion\", type text}, {\"segmento_edad\", type text}, {\"arquetipo_demografico\", type text}, {\"calificacion_pago_desc\", type text}}),",
                "    Orden = Table.AddColumn(Tipos, \"Orden Segmento\", each if Text.Contains([segmento_edad], \"Joven\") then 1 else if Text.Contains([segmento_edad], \"Mayor\") then 3 else if Text.Contains([segmento_edad], \"Adulto\") then 2 else 0, Int64.Type)",
                "in",
                "    Orden"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dim_Cuenta",
        "columns": [
          {
            "name": "sk_cuenta",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "d2f19177-daab-407c-96ce-bb79a1a911b5",
            "sourceColumn": "sk_cuenta",
            "summarizeBy": "none"
          },
          {
            "name": "id_cuenta_bk",
            "dataType": "int64",
            "lineageTag": "4ffae868-91f9-4945-907b-0a48e9e2b1b7",
            "sourceColumn": "id_cuenta_bk",
            "summarizeBy": "none"
          },
          {
            "name": "frecuencia_emision_estado",
            "dataType": "string",
            "lineageTag": "a145ef9c-b64d-4bb9-a362-c391cec2e61a",
            "sourceColumn": "frecuencia_emision_estado",
            "summarizeBy": "none"
          },
          {
            "name": "fecha_apertura",
            "dataType": "dateTime",
            "formatString": "dd/mm/yyyy",
            "lineageTag": "2757ae7e-10ce-4b07-8f2e-7518de42c850",
            "sourceColumn": "fecha_apertura",
            "summarizeBy": "none"
          },
          {
            "name": "tiene_credito_externo",
            "dataType": "boolean",
            "lineageTag": "75096b0f-c8e8-4c3a-ab72-8987e8f2a2f5",
            "sourceColumn": "tiene_credito_externo",
            "summarizeBy": "none"
          },
          {
            "name": "monto_credito_externo",
            "dataType": "double",
            "formatString": "\"$\"#,0",
            "lineageTag": "57751bac-44c1-437a-be99-8bbdee17794e",
            "sourceColumn": "monto_credito_externo",
            "summarizeBy": "none"
          },
          {
            "name": "Cuenta",
            "dataType": "string",
            "expression": "\"Cuenta \" & Dim_Cuenta[id_cuenta_bk]",
            "lineageTag": "2294678b-db86-413f-b925-a5ed67ac1087",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "9359f0db-97e2-448a-a719-5a231505372a",
        "partitions": [
          {
            "name": "Dim_Cuenta",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = Sql.Database(ServidorSQL, BaseDatosSQL),",
                "    Tabla = Origen{[Schema=\"dbo\", Item=\"Dim_Cuenta\"]}[Data],",
                "    Columnas = Table.SelectColumns(Tabla, {\"sk_cuenta\", \"id_cuenta_bk\", \"frecuencia_emision_estado\", \"fecha_apertura\", \"tiene_credito_externo\", \"monto_credito_externo\"}),",
                "    Tipos = Table.TransformColumnTypes(Columnas, {{\"sk_cuenta\", Int64.Type}, {\"id_cuenta_bk\", Int64.Type}, {\"frecuencia_emision_estado\", type text}, {\"fecha_apertura\", type datetime}, {\"tiene_credito_externo\", type logical}, {\"monto_credito_externo\", type number}})",
                "in",
                "    Tipos"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dim_Estado_Prestamo",
        "columns": [
          {
            "name": "sk_estado_prestamo",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "38eb8559-a83b-4c62-ae46-d64e72371158",
            "sourceColumn": "sk_estado_prestamo",
            "summarizeBy": "none"
          },
          {
            "name": "codigo_estado",
            "dataType": "string",
            "lineageTag": "8d27f184-a915-4df1-bef0-fc7196f4fe21",
            "sourceColumn": "codigo_estado",
            "summarizeBy": "none"
          },
          {
            "name": "condicion",
            "dataType": "string",
            "lineageTag": "b9b906bc-b1ac-4df2-8671-91461dcfc082",
            "sourceColumn": "condicion",
            "summarizeBy": "none"
          },
          {
            "name": "descripcion",
            "dataType": "string",
            "lineageTag": "89a46080-9227-4b1b-822d-8eadf606100f",
            "sourceColumn": "descripcion",
            "summarizeBy": "none"
          },
          {
            "name": "Estado",
            "dataType": "string",
            "expression": "SWITCH(Dim_Estado_Prestamo[codigo_estado], \"A\", \"A · Cerrado al día\", \"B\", \"B · Cerrado con deuda\", \"C\", \"C · Vigente al día\", \"D\", \"D · Vigente en mora\")",
            "lineageTag": "f1423587-b51b-478b-b95b-3bcb25107f29",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "0b15e5c9-05df-4c23-8d5e-5475be3bde49",
        "partitions": [
          {
            "name": "Dim_Estado_Prestamo",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = Sql.Database(ServidorSQL, BaseDatosSQL),",
                "    Tabla = Origen{[Schema=\"dbo\", Item=\"Dim_Estado_Prestamo\"]}[Data],",
                "    Columnas = Table.SelectColumns(Tabla, {\"sk_estado_prestamo\", \"codigo_estado\", \"condicion\", \"descripcion\"}),",
                "    Tipos = Table.TransformColumnTypes(Columnas, {{\"sk_estado_prestamo\", Int64.Type}, {\"codigo_estado\", type text}, {\"condicion\", type text}, {\"descripcion\", type text}})",
                "in",
                "    Tipos"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dim_Orden",
        "columns": [
          {
            "name": "sk_orden_tipo",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "f5d482a1-000e-4045-9ce3-b44274194932",
            "sourceColumn": "sk_orden_tipo",
            "summarizeBy": "none"
          },
          {
            "name": "k_symbol_original",
            "dataType": "string",
            "lineageTag": "e478943a-d201-4d6f-a4dd-150b236c9b80",
            "sourceColumn": "k_symbol_original",
            "summarizeBy": "none"
          },
          {
            "name": "categoria_orden_traducida",
            "dataType": "string",
            "lineageTag": "d977e085-3116-4cec-a916-a796351ee0dc",
            "sourceColumn": "categoria_orden_traducida",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "014eb1c2-e63c-465d-8e85-87e40e13339b",
        "partitions": [
          {
            "name": "Dim_Orden",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = Sql.Database(ServidorSQL, BaseDatosSQL),",
                "    Tabla = Origen{[Schema=\"dbo\", Item=\"Dim_Orden\"]}[Data],",
                "    Columnas = Table.SelectColumns(Tabla, {\"sk_orden_tipo\", \"k_symbol_original\", \"categoria_orden_traducida\"}),",
                "    Tipos = Table.TransformColumnTypes(Columnas, {{\"sk_orden_tipo\", Int64.Type}, {\"k_symbol_original\", type text}, {\"categoria_orden_traducida\", type text}})",
                "in",
                "    Tipos"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Fact_Prestamos",
        "columns": [
          {
            "name": "sk_prestamo",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "122e621a-3056-4e7f-95ca-d4244f02edf4",
            "sourceColumn": "sk_prestamo",
            "summarizeBy": "none"
          },
          {
            "name": "sk_tiempo",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "e48a7a32-c813-4c80-b28e-bd19524060ae",
            "sourceColumn": "sk_tiempo",
            "summarizeBy": "none"
          },
          {
            "name": "sk_cuenta",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "ddd5a707-f8e9-44bf-a188-0dcb737a4b71",
            "sourceColumn": "sk_cuenta",
            "summarizeBy": "none"
          },
          {
            "name": "sk_cliente",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "8f2e95b1-73a5-4703-b051-4c397ab8ab05",
            "sourceColumn": "sk_cliente",
            "summarizeBy": "none"
          },
          {
            "name": "sk_distrito",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "3371e4dc-72b9-420b-ae7f-af1c6a53cf7a",
            "sourceColumn": "sk_distrito",
            "summarizeBy": "none"
          },
          {
            "name": "sk_estado_prestamo",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "f6cf5484-dbdd-4616-a437-e4514cdd76b9",
            "sourceColumn": "sk_estado_prestamo",
            "summarizeBy": "none"
          },
          {
            "name": "id_prestamo_bk",
            "dataType": "int64",
            "lineageTag": "4d62ba7e-7b94-4443-9851-b027c358fb04",
            "sourceColumn": "id_prestamo_bk",
            "summarizeBy": "none"
          },
          {
            "name": "monto_prestamo",
            "dataType": "double",
            "formatString": "\"$\"#,0",
            "lineageTag": "b4025a77-ef57-4576-a628-ec5ccd97531d",
            "sourceColumn": "monto_prestamo",
            "summarizeBy": "none"
          },
          {
            "name": "plazo_meses",
            "dataType": "int64",
            "lineageTag": "74785361-70df-45dc-901d-5b7a973fd943",
            "sourceColumn": "plazo_meses",
            "summarizeBy": "none"
          },
          {
            "name": "pago_mensual",
            "dataType": "double",
            "formatString": "\"$\"#,0",
            "lineageTag": "496f83e7-9556-4662-9a4e-9095edd92f45",
            "sourceColumn": "pago_mensual",
            "summarizeBy": "none"
          },
          {
            "name": "meses_transcurridos_al_corte",
            "dataType": "int64",
            "lineageTag": "56be0532-4772-4aac-b410-455577130877",
            "sourceColumn": "meses_transcurridos_al_corte",
            "summarizeBy": "none"
          },
          {
            "name": "saldo_pendiente_estimado",
            "dataType": "double",
            "formatString": "\"$\"#,0",
            "lineageTag": "043ad365-c998-41ab-8b40-402030b98c9f",
            "sourceColumn": "saldo_pendiente_estimado",
            "summarizeBy": "none"
          },
          {
            "name": "saldo_promedio_previo",
            "dataType": "double",
            "formatString": "\"$\"#,0",
            "lineageTag": "90e4b80a-c37c-412f-a308-5f03642b6541",
            "sourceColumn": "saldo_promedio_previo",
            "summarizeBy": "none"
          },
          {
            "name": "ratio_cuota_saldo_previo",
            "dataType": "double",
            "formatString": "0.00%",
            "lineageTag": "e0416a3e-8664-4061-a716-bfe01ee1fdbe",
            "sourceColumn": "ratio_cuota_saldo_previo",
            "summarizeBy": "none"
          },
          {
            "name": "banda_capacidad",
            "dataType": "string",
            "lineageTag": "a60b21db-85cf-49ee-8d2f-ae0272d1f898",
            "sortByColumn": "Orden Banda",
            "sourceColumn": "banda_capacidad",
            "summarizeBy": "none"
          },
          {
            "name": "Orden Banda",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "027d5ac5-ba1e-403b-8aea-64950cf30a85",
            "sourceColumn": "Orden Banda",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "55ed4794-13d2-4cdf-b9d3-f3e5b93e85de",
        "partitions": [
          {
            "name": "Fact_Prestamos",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = Sql.Database(ServidorSQL, BaseDatosSQL),",
                "    Tabla = Origen{[Schema=\"dbo\", Item=\"Fact_Prestamos\"]}[Data],",
                "    Columnas = Table.SelectColumns(Tabla, {\"sk_prestamo\", \"sk_tiempo\", \"sk_cuenta\", \"sk_cliente\", \"sk_distrito\", \"sk_estado_prestamo\", \"id_prestamo_bk\", \"monto_prestamo\", \"plazo_meses\", \"pago_mensual\", \"meses_transcurridos_al_corte\", \"saldo_pendiente_estimado\", \"saldo_promedio_previo\", \"ratio_cuota_saldo_previo\", \"banda_capacidad\"}),",
                "    Tipos = Table.TransformColumnTypes(Columnas, {{\"sk_prestamo\", Int64.Type}, {\"sk_tiempo\", Int64.Type}, {\"sk_cuenta\", Int64.Type}, {\"sk_cliente\", Int64.Type}, {\"sk_distrito\", Int64.Type}, {\"sk_estado_prestamo\", Int64.Type}, {\"id_prestamo_bk\", Int64.Type}, {\"monto_prestamo\", type number}, {\"plazo_meses\", Int64.Type}, {\"pago_mensual\", type number}, {\"meses_transcurridos_al_corte\", Int64.Type}, {\"saldo_pendiente_estimado\", type number}, {\"saldo_promedio_previo\", type number}, {\"ratio_cuota_saldo_previo\", type number}, {\"banda_capacidad\", type text}}),",
                "    Orden = Table.AddColumn(Tipos, \"Orden Banda\", each if Text.Contains([banda_capacidad], \"Media-baja\") then 2 else if Text.Contains([banda_capacidad], \"Media-alta\") then 3 else if Text.Contains([banda_capacidad], \"Baja\") then 1 else if Text.Contains([banda_capacidad], \"Alta\") then 4 else 0, Int64.Type)",
                "in",
                "    Orden"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Fact_Ordenes",
        "columns": [
          {
            "name": "sk_orden",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "aeee87b5-8353-4e0d-ac35-31f75a90d0e8",
            "sourceColumn": "sk_orden",
            "summarizeBy": "none"
          },
          {
            "name": "sk_tiempo_apertura_cuenta",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "81b16550-14e1-4416-aede-2f47746f1039",
            "sourceColumn": "sk_tiempo_apertura_cuenta",
            "summarizeBy": "none"
          },
          {
            "name": "sk_cuenta",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "3193b6d3-52c5-4473-8960-e815b45509ed",
            "sourceColumn": "sk_cuenta",
            "summarizeBy": "none"
          },
          {
            "name": "sk_cliente",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "b8a97c9b-dd5f-4293-8258-172761e2308e",
            "sourceColumn": "sk_cliente",
            "summarizeBy": "none"
          },
          {
            "name": "sk_distrito",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "0b88194e-3e59-4dd6-8049-3ad3ddef7e15",
            "sourceColumn": "sk_distrito",
            "summarizeBy": "none"
          },
          {
            "name": "sk_orden_tipo",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "9584b785-8f7b-4c1d-a718-2afb6b41a40f",
            "sourceColumn": "sk_orden_tipo",
            "summarizeBy": "none"
          },
          {
            "name": "id_orden_bk",
            "dataType": "int64",
            "lineageTag": "4f20344f-24ba-43d0-a271-645da0296d9b",
            "sourceColumn": "id_orden_bk",
            "summarizeBy": "none"
          },
          {
            "name": "monto_orden",
            "dataType": "double",
            "formatString": "\"$\"#,0",
            "lineageTag": "65d38763-28f7-4695-a260-516c398581d9",
            "sourceColumn": "monto_orden",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "63469082-b64b-4f70-8776-333d8dc3b0a2",
        "partitions": [
          {
            "name": "Fact_Ordenes",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = Sql.Database(ServidorSQL, BaseDatosSQL),",
                "    Tabla = Origen{[Schema=\"dbo\", Item=\"Fact_Ordenes\"]}[Data],",
                "    Columnas = Table.SelectColumns(Tabla, {\"sk_orden\", \"sk_tiempo_apertura_cuenta\", \"sk_cuenta\", \"sk_cliente\", \"sk_distrito\", \"sk_orden_tipo\", \"id_orden_bk\", \"monto_orden\"}),",
                "    Tipos = Table.TransformColumnTypes(Columnas, {{\"sk_orden\", Int64.Type}, {\"sk_tiempo_apertura_cuenta\", Int64.Type}, {\"sk_cuenta\", Int64.Type}, {\"sk_cliente\", Int64.Type}, {\"sk_distrito\", Int64.Type}, {\"sk_orden_tipo\", Int64.Type}, {\"id_orden_bk\", Int64.Type}, {\"monto_orden\", type number}})",
                "in",
                "    Tipos"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Fact_Saldo_Cuenta_Mensual",
        "columns": [
          {
            "name": "sk_cuenta",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "09652805-0092-4b22-ba5a-a3f7c60be272",
            "sourceColumn": "sk_cuenta",
            "summarizeBy": "none"
          },
          {
            "name": "sk_mes",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "6238b922-c679-49c1-8af3-837f08a92bb1",
            "sourceColumn": "sk_mes",
            "summarizeBy": "none"
          },
          {
            "name": "sk_cliente",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "270f0d72-f8c6-492c-b573-a538e9a1afe1",
            "sourceColumn": "sk_cliente",
            "summarizeBy": "none"
          },
          {
            "name": "sk_distrito",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "6ce32097-9d31-4023-aed6-c38809d29892",
            "sourceColumn": "sk_distrito",
            "summarizeBy": "none"
          },
          {
            "name": "saldo_fin_mes",
            "dataType": "double",
            "formatString": "\"$\"#,0",
            "lineageTag": "ad13949d-2568-4c1a-89e7-1f23fefb6bd0",
            "sourceColumn": "saldo_fin_mes",
            "summarizeBy": "none"
          },
          {
            "name": "saldo_promedio_mes",
            "dataType": "double",
            "formatString": "\"$\"#,0",
            "lineageTag": "b0ba5c13-766b-4d91-9adb-8a553a329209",
            "sourceColumn": "saldo_promedio_mes",
            "summarizeBy": "none"
          },
          {
            "name": "num_movimientos_mes",
            "dataType": "int64",
            "lineageTag": "abfecfc0-6081-4a95-bc7b-854a47e1487c",
            "sourceColumn": "num_movimientos_mes",
            "summarizeBy": "none"
          },
          {
            "name": "en_sobregiro",
            "dataType": "boolean",
            "lineageTag": "effe54b3-639b-4f61-abda-d59921c3f8a7",
            "sourceColumn": "en_sobregiro",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "a2c35939-9b1a-4c92-a274-5554f2fc542e",
        "partitions": [
          {
            "name": "Fact_Saldo_Cuenta_Mensual",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = Sql.Database(ServidorSQL, BaseDatosSQL),",
                "    Tabla = Origen{[Schema=\"dbo\", Item=\"Fact_Saldo_Cuenta_Mensual\"]}[Data],",
                "    Columnas = Table.SelectColumns(Tabla, {\"sk_cuenta\", \"sk_mes\", \"sk_cliente\", \"sk_distrito\", \"saldo_fin_mes\", \"saldo_promedio_mes\", \"num_movimientos_mes\", \"en_sobregiro\"}),",
                "    Tipos = Table.TransformColumnTypes(Columnas, {{\"sk_cuenta\", Int64.Type}, {\"sk_mes\", Int64.Type}, {\"sk_cliente\", Int64.Type}, {\"sk_distrito\", Int64.Type}, {\"saldo_fin_mes\", type number}, {\"saldo_promedio_mes\", type number}, {\"num_movimientos_mes\", Int64.Type}, {\"en_sobregiro\", type logical}})",
                "in",
                "    Tipos"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "vw_PBI_Trans_Anual_Cuenta",
        "columns": [
          {
            "name": "sk_cuenta",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "25fa1f30-f329-4d72-b0db-e83e66724d18",
            "sourceColumn": "sk_cuenta",
            "summarizeBy": "none"
          },
          {
            "name": "sk_cliente",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "9c7f43e3-48cc-4185-a42c-95832c2480f9",
            "sourceColumn": "sk_cliente",
            "summarizeBy": "none"
          },
          {
            "name": "sk_distrito",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "6b32b119-6e5f-4b03-88ca-a6ee245262e6",
            "sourceColumn": "sk_distrito",
            "summarizeBy": "none"
          },
          {
            "name": "categoria_analitica",
            "dataType": "string",
            "lineageTag": "f0ce9d15-5501-490b-934c-d4ca73d60471",
            "sourceColumn": "categoria_analitica",
            "summarizeBy": "none"
          },
          {
            "name": "anio",
            "dataType": "int64",
            "lineageTag": "fb1fd5ab-0714-460b-bb1a-09ec7f5f85c6",
            "sourceColumn": "anio",
            "summarizeBy": "none"
          },
          {
            "name": "num_transacciones",
            "dataType": "int64",
            "lineageTag": "72f3c9fa-f5f3-4852-b544-0e3b7e0981e6",
            "sourceColumn": "num_transacciones",
            "summarizeBy": "none"
          },
          {
            "name": "monto_total",
            "dataType": "double",
            "formatString": "\"$\"#,0",
            "lineageTag": "f1095743-2927-4117-8126-1d8af331a56a",
            "sourceColumn": "monto_total",
            "summarizeBy": "none"
          },
          {
            "name": "suma_cuadrados",
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "c5312759-4496-4765-9574-697de67142ec",
            "sourceColumn": "suma_cuadrados",
            "summarizeBy": "none"
          },
          {
            "name": "saldo_promedio",
            "dataType": "double",
            "formatString": "\"$\"#,0",
            "lineageTag": "2f6db471-b66e-4789-a289-5e672baa9a0e",
            "sourceColumn": "saldo_promedio",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "d7c16be5-5859-4a34-93ac-408f52ebd2c7",
        "partitions": [
          {
            "name": "vw_PBI_Trans_Anual_Cuenta",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = Sql.Database(ServidorSQL, BaseDatosSQL),",
                "    Tabla = Origen{[Schema=\"dbo\", Item=\"vw_PBI_Trans_Anual_Cuenta\"]}[Data],",
                "    Columnas = Table.SelectColumns(Tabla, {\"sk_cuenta\", \"sk_cliente\", \"sk_distrito\", \"categoria_analitica\", \"anio\", \"num_transacciones\", \"monto_total\", \"suma_cuadrados\", \"saldo_promedio\"}),",
                "    Tipos = Table.TransformColumnTypes(Columnas, {{\"sk_cuenta\", Int64.Type}, {\"sk_cliente\", Int64.Type}, {\"sk_distrito\", Int64.Type}, {\"categoria_analitica\", type text}, {\"anio\", Int64.Type}, {\"num_transacciones\", Int64.Type}, {\"monto_total\", type number}, {\"suma_cuadrados\", type number}, {\"saldo_promedio\", type number}})",
                "in",
                "    Tipos"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Recomendacion_Cuenta",
        "columns": [
          {
            "name": "sk_cuenta",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "1d3d80cc-16ba-435f-b7ab-58d265a89582",
            "sourceColumn": "sk_cuenta",
            "summarizeBy": "none"
          },
          {
            "name": "sk_cliente",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "f94618b4-4549-4698-add0-64f4ddd75989",
            "sourceColumn": "sk_cliente",
            "summarizeBy": "none"
          },
          {
            "name": "modelo",
            "dataType": "string",
            "lineageTag": "640bfa77-ece9-491e-aae9-c7c2d8e6f36a",
            "sourceColumn": "modelo",
            "summarizeBy": "none"
          },
          {
            "name": "recomendacion_1",
            "dataType": "string",
            "lineageTag": "998305c7-709b-4f7c-b11d-5aa4d368e201",
            "sourceColumn": "recomendacion_1",
            "summarizeBy": "none"
          },
          {
            "name": "recomendacion_2",
            "dataType": "string",
            "lineageTag": "111fe58c-b3cf-429e-bfe6-3d31d504ce32",
            "sourceColumn": "recomendacion_2",
            "summarizeBy": "none"
          },
          {
            "name": "recomendacion_3",
            "dataType": "string",
            "lineageTag": "48fe9a90-9992-44c1-be24-72d1fb412a71",
            "sourceColumn": "recomendacion_3",
            "summarizeBy": "none"
          },
          {
            "name": "prestamo_cuota_maxima",
            "dataType": "double",
            "formatString": "\"$\"#,0",
            "lineageTag": "a584c27c-14ab-484b-bdac-6ca5c15be75d",
            "sourceColumn": "prestamo_cuota_maxima",
            "summarizeBy": "none"
          },
          {
            "name": "prestamo_monto_maximo_36m",
            "dataType": "double",
            "formatString": "\"$\"#,0",
            "lineageTag": "666a296a-5de0-44c2-aa0d-6641400ad1ed",
            "sourceColumn": "prestamo_monto_maximo_36m",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "52953c87-02ec-433c-aa01-a7b4b62c13fb",
        "partitions": [
          {
            "name": "Recomendacion_Cuenta",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = Sql.Database(ServidorSQL, BaseDatosSQL),",
                "    Tabla = Origen{[Schema=\"dbo\", Item=\"Recomendacion_Cuenta\"]}[Data],",
                "    Columnas = Table.SelectColumns(Tabla, {\"sk_cuenta\", \"sk_cliente\", \"modelo\", \"recomendacion_1\", \"recomendacion_2\", \"recomendacion_3\", \"prestamo_cuota_maxima\", \"prestamo_monto_maximo_36m\"}),",
                "    Tipos = Table.TransformColumnTypes(Columnas, {{\"sk_cuenta\", Int64.Type}, {\"sk_cliente\", Int64.Type}, {\"modelo\", type text}, {\"recomendacion_1\", type text}, {\"recomendacion_2\", type text}, {\"recomendacion_3\", type text}, {\"prestamo_cuota_maxima\", type number}, {\"prestamo_monto_maximo_36m\", type number}})",
                "in",
                "    Tipos"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dim_Producto",
        "columns": [
          {
            "name": "producto",
            "dataType": "string",
            "lineageTag": "29a44bec-04d2-498a-ac0e-ac509ae343a9",
            "sortByColumn": "orden",
            "sourceColumn": "producto",
            "summarizeBy": "none"
          },
          {
            "name": "codigo",
            "dataType": "string",
            "lineageTag": "e0021bc3-770a-443f-adac-f5d525183b47",
            "sourceColumn": "codigo",
            "summarizeBy": "none"
          },
          {
            "name": "descripcion",
            "dataType": "string",
            "lineageTag": "bc866a7b-f70d-4000-b005-5f130c7f8233",
            "sourceColumn": "descripcion",
            "summarizeBy": "none"
          },
          {
            "name": "penetracion",
            "dataType": "double",
            "formatString": "0.00%",
            "lineageTag": "8f4ed12d-defd-44b5-bc89-4b8e8c26202a",
            "sourceColumn": "penetracion",
            "summarizeBy": "none"
          },
          {
            "name": "orden",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "8ea5b3ca-095b-4398-aebb-bdb0366eeaa5",
            "sourceColumn": "orden",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "9ea92f5d-3e45-433b-b192-177072461a76",
        "partitions": [
          {
            "name": "Dim_Producto",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = Sql.Database(ServidorSQL, BaseDatosSQL),",
                "    Tabla = Origen{[Schema=\"dbo\", Item=\"Dim_Producto\"]}[Data],",
                "    Columnas = Table.SelectColumns(Tabla, {\"producto\", \"codigo\", \"descripcion\", \"penetracion\", \"orden\"}),",
                "    Tipos = Table.TransformColumnTypes(Columnas, {{\"producto\", type text}, {\"codigo\", type text}, {\"descripcion\", type text}, {\"penetracion\", type number}, {\"orden\", Int64.Type}})",
                "in",
                "    Tipos"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Recomendacion_Producto",
        "columns": [
          {
            "name": "sk_cuenta",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "b8c74251-676b-428a-a913-6e4a7630be15",
            "sourceColumn": "sk_cuenta",
            "summarizeBy": "none"
          },
          {
            "name": "sk_cliente",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "bdf8fefa-0231-4154-8665-7e3ee2d0f401",
            "sourceColumn": "sk_cliente",
            "summarizeBy": "none"
          },
          {
            "name": "sk_distrito",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "300b29a4-804d-41b0-b5dc-77f38e790f9f",
            "sourceColumn": "sk_distrito",
            "summarizeBy": "none"
          },
          {
            "name": "sistema",
            "dataType": "string",
            "lineageTag": "b9c72728-3c8a-496f-a704-3b93ab5f0fae",
            "sourceColumn": "sistema",
            "summarizeBy": "none"
          },
          {
            "name": "producto",
            "dataType": "string",
            "lineageTag": "fe276778-130f-4c0d-9564-6cb645219a93",
            "sourceColumn": "producto",
            "summarizeBy": "none"
          },
          {
            "name": "posicion",
            "dataType": "int64",
            "lineageTag": "2d060293-84a5-483c-a9e9-632f27c45d3b",
            "sourceColumn": "posicion",
            "summarizeBy": "none"
          },
          {
            "name": "puntaje",
            "dataType": "double",
            "formatString": "0.0000",
            "lineageTag": "43e84177-a2f8-40f1-bf0a-4af286a2c3e1",
            "sourceColumn": "puntaje",
            "summarizeBy": "none"
          },
          {
            "name": "es_descubrimiento",
            "dataType": "boolean",
            "lineageTag": "890e18a7-d480-458c-a0d4-fc18ddc0b88a",
            "sourceColumn": "es_descubrimiento",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "6039f222-5178-4386-8738-b199d96ce71a",
        "partitions": [
          {
            "name": "Recomendacion_Producto",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = Sql.Database(ServidorSQL, BaseDatosSQL),",
                "    Tabla = Origen{[Schema=\"dbo\", Item=\"Recomendacion_Producto\"]}[Data],",
                "    Columnas = Table.SelectColumns(Tabla, {\"sk_cuenta\", \"sk_cliente\", \"sk_distrito\", \"sistema\", \"producto\", \"posicion\", \"puntaje\", \"es_descubrimiento\"}),",
                "    Tipos = Table.TransformColumnTypes(Columnas, {{\"sk_cuenta\", Int64.Type}, {\"sk_cliente\", Int64.Type}, {\"sk_distrito\", Int64.Type}, {\"sistema\", type text}, {\"producto\", type text}, {\"posicion\", Int64.Type}, {\"puntaje\", type number}, {\"es_descubrimiento\", type logical}})",
                "in",
                "    Tipos"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Adopcion_Producto",
        "columns": [
          {
            "name": "sk_cuenta",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "506a6013-8a12-40a8-9b20-0fa7453687f2",
            "sourceColumn": "sk_cuenta",
            "summarizeBy": "none"
          },
          {
            "name": "sk_cliente",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "30ce18b4-c596-4b66-b848-26096a9b7c2a",
            "sourceColumn": "sk_cliente",
            "summarizeBy": "none"
          },
          {
            "name": "sk_distrito",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "35f51967-9d36-47f2-8fff-a40a5af229aa",
            "sourceColumn": "sk_distrito",
            "summarizeBy": "none"
          },
          {
            "name": "producto",
            "dataType": "string",
            "lineageTag": "d87ba3f1-56dd-4c5a-aeb9-93849e4d0682",
            "sourceColumn": "producto",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "f372a9f5-4613-48aa-81d3-6117cf21bae6",
        "partitions": [
          {
            "name": "Adopcion_Producto",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = Sql.Database(ServidorSQL, BaseDatosSQL),",
                "    Tabla = Origen{[Schema=\"dbo\", Item=\"Adopcion_Producto\"]}[Data],",
                "    Columnas = Table.SelectColumns(Tabla, {\"sk_cuenta\", \"sk_cliente\", \"sk_distrito\", \"producto\"}),",
                "    Tipos = Table.TransformColumnTypes(Columnas, {{\"sk_cuenta\", Int64.Type}, {\"sk_cliente\", Int64.Type}, {\"sk_distrito\", Int64.Type}, {\"producto\", type text}})",
                "in",
                "    Tipos"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Capacidad_Prestamo",
        "columns": [
          {
            "name": "sk_cuenta",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "9720ccb0-6b69-48ec-802e-ab637d321f1f",
            "sourceColumn": "sk_cuenta",
            "summarizeBy": "none"
          },
          {
            "name": "sk_cliente",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "e2721f51-911b-4e89-900c-c8995f8910ab",
            "sourceColumn": "sk_cliente",
            "summarizeBy": "none"
          },
          {
            "name": "sk_distrito",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "dc3a1d10-1947-4f35-8581-2b9086930b72",
            "sourceColumn": "sk_distrito",
            "summarizeBy": "none"
          },
          {
            "name": "tiene_prestamo",
            "dataType": "boolean",
            "lineageTag": "b5640639-f70e-4536-9ecc-d161b6072260",
            "sourceColumn": "tiene_prestamo",
            "summarizeBy": "none"
          },
          {
            "name": "saldo_promedio",
            "dataType": "double",
            "formatString": "\"$\"#,0",
            "lineageTag": "82b7c25c-64d6-4bfd-9391-e2bc040a81cf",
            "sourceColumn": "saldo_promedio",
            "summarizeBy": "none"
          },
          {
            "name": "cuota_prudente",
            "dataType": "double",
            "formatString": "\"$\"#,0",
            "lineageTag": "d782bc12-6eee-4c85-b62f-bd27c596657e",
            "sourceColumn": "cuota_prudente",
            "summarizeBy": "none"
          },
          {
            "name": "monto_maximo_12m",
            "dataType": "double",
            "formatString": "\"$\"#,0",
            "lineageTag": "c127578c-8f88-4b8c-aa64-0b77bfdacdfe",
            "sourceColumn": "monto_maximo_12m",
            "summarizeBy": "none"
          },
          {
            "name": "monto_maximo_36m",
            "dataType": "double",
            "formatString": "\"$\"#,0",
            "lineageTag": "2edd0cc8-c01e-4459-a6d4-8f6b79e213ad",
            "sourceColumn": "monto_maximo_36m",
            "summarizeBy": "none"
          },
          {
            "name": "monto_maximo_60m",
            "dataType": "double",
            "formatString": "\"$\"#,0",
            "lineageTag": "53193718-5e25-4bf0-aa4e-959a51ede8b3",
            "sourceColumn": "monto_maximo_60m",
            "summarizeBy": "none"
          },
          {
            "name": "tramo_monto_36m",
            "dataType": "string",
            "lineageTag": "350b6311-c51b-45e6-bca8-96575b608683",
            "sortByColumn": "orden_tramo",
            "sourceColumn": "tramo_monto_36m",
            "summarizeBy": "none"
          },
          {
            "name": "orden_tramo",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "4b5eefe2-4aed-4f65-8297-7da81acba3ed",
            "sourceColumn": "orden_tramo",
            "summarizeBy": "none"
          },
          {
            "name": "puede_pagar_prestamo_tipico",
            "dataType": "boolean",
            "lineageTag": "ee695157-99f3-474f-a22c-90393338e33a",
            "sourceColumn": "puede_pagar_prestamo_tipico",
            "summarizeBy": "none"
          },
          {
            "name": "prestamo_recomendado",
            "dataType": "boolean",
            "lineageTag": "439d821d-48bc-435c-8c90-ccce98825b80",
            "sourceColumn": "prestamo_recomendado",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "956e1f6e-6343-4b69-8393-c5b02634b125",
        "partitions": [
          {
            "name": "Capacidad_Prestamo",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = Sql.Database(ServidorSQL, BaseDatosSQL),",
                "    Tabla = Origen{[Schema=\"dbo\", Item=\"Capacidad_Prestamo\"]}[Data],",
                "    Columnas = Table.SelectColumns(Tabla, {\"sk_cuenta\", \"sk_cliente\", \"sk_distrito\", \"tiene_prestamo\", \"saldo_promedio\", \"cuota_prudente\", \"monto_maximo_12m\", \"monto_maximo_36m\", \"monto_maximo_60m\", \"tramo_monto_36m\", \"orden_tramo\", \"puede_pagar_prestamo_tipico\", \"prestamo_recomendado\"}),",
                "    Tipos = Table.TransformColumnTypes(Columnas, {{\"sk_cuenta\", Int64.Type}, {\"sk_cliente\", Int64.Type}, {\"sk_distrito\", Int64.Type}, {\"tiene_prestamo\", type logical}, {\"saldo_promedio\", type number}, {\"cuota_prudente\", type number}, {\"monto_maximo_12m\", type number}, {\"monto_maximo_36m\", type number}, {\"monto_maximo_60m\", type number}, {\"tramo_monto_36m\", type text}, {\"orden_tramo\", Int64.Type}, {\"puede_pagar_prestamo_tipico\", type logical}, {\"prestamo_recomendado\", type logical}})",
                "in",
                "    Tipos"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Evaluacion_Recomendador",
        "columns": [
          {
            "name": "modelo",
            "dataType": "string",
            "lineageTag": "f5727295-ff2b-4cf4-a31e-32aa486abd0f",
            "sortByColumn": "orden",
            "sourceColumn": "modelo",
            "summarizeBy": "none"
          },
          {
            "name": "familia",
            "dataType": "string",
            "lineageTag": "b0371f16-5fa1-4a18-97d1-391a6e7d7d07",
            "sourceColumn": "familia",
            "summarizeBy": "none"
          },
          {
            "name": "rol",
            "dataType": "string",
            "lineageTag": "0d540eab-d91b-40ee-bb11-abdbc3cc571b",
            "sourceColumn": "rol",
            "summarizeBy": "none"
          },
          {
            "name": "hit_1",
            "dataType": "double",
            "formatString": "0.00%",
            "lineageTag": "b413abe5-d4a9-44bb-8587-a35aa30ac914",
            "sourceColumn": "hit_1",
            "summarizeBy": "none"
          },
          {
            "name": "hit_3",
            "dataType": "double",
            "formatString": "0.00%",
            "lineageTag": "9dc4978c-0288-4c9f-92f0-f0dfb8307e13",
            "sourceColumn": "hit_3",
            "summarizeBy": "none"
          },
          {
            "name": "mrr",
            "dataType": "double",
            "formatString": "0.000",
            "lineageTag": "1104080d-6366-44a1-a1d1-61ed9e439b86",
            "sourceColumn": "mrr",
            "summarizeBy": "none"
          },
          {
            "name": "hit_1_cola_larga",
            "dataType": "double",
            "formatString": "0.00%",
            "lineageTag": "9460183a-af30-448e-bfb1-a05fa3e215c0",
            "sourceColumn": "hit_1_cola_larga",
            "summarizeBy": "none"
          },
          {
            "name": "mrr_confirmacion",
            "dataType": "double",
            "formatString": "0.000",
            "lineageTag": "5af54c03-b12c-4fa9-94d7-6b29793f10cd",
            "sourceColumn": "mrr_confirmacion",
            "summarizeBy": "none"
          },
          {
            "name": "orden",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "4675ba3f-741b-443f-8a9e-b570318864b5",
            "sourceColumn": "orden",
            "summarizeBy": "none"
          },
          {
            "name": "elegido",
            "dataType": "boolean",
            "lineageTag": "65106d49-17e6-4ac1-821d-191760edbb5a",
            "sourceColumn": "elegido",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "315942ed-98fc-4503-bea4-c660b4c1b26f",
        "partitions": [
          {
            "name": "Evaluacion_Recomendador",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = Sql.Database(ServidorSQL, BaseDatosSQL),",
                "    Tabla = Origen{[Schema=\"dbo\", Item=\"Evaluacion_Recomendador\"]}[Data],",
                "    Columnas = Table.SelectColumns(Tabla, {\"modelo\", \"familia\", \"rol\", \"hit_1\", \"hit_3\", \"mrr\", \"hit_1_cola_larga\", \"mrr_confirmacion\", \"orden\", \"elegido\"}),",
                "    Tipos = Table.TransformColumnTypes(Columnas, {{\"modelo\", type text}, {\"familia\", type text}, {\"rol\", type text}, {\"hit_1\", type number}, {\"hit_3\", type number}, {\"mrr\", type number}, {\"hit_1_cola_larga\", type number}, {\"mrr_confirmacion\", type number}, {\"orden\", Int64.Type}, {\"elegido\", type logical}})",
                "in",
                "    Tipos"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Asociacion_Producto",
        "columns": [
          {
            "name": "producto_origen",
            "dataType": "string",
            "lineageTag": "3bb40dcb-5394-4465-a3dd-4bdf12e70fa2",
            "sourceColumn": "producto_origen",
            "summarizeBy": "none"
          },
          {
            "name": "producto_destino",
            "dataType": "string",
            "lineageTag": "b5d1c5ea-96c4-41c4-9434-ea68fe0c08b6",
            "sourceColumn": "producto_destino",
            "summarizeBy": "none"
          },
          {
            "name": "p_destino_dado_origen",
            "dataType": "double",
            "formatString": "0.00%",
            "lineageTag": "380bca73-fc00-444c-996c-ca650838d29d",
            "sourceColumn": "p_destino_dado_origen",
            "summarizeBy": "none"
          },
          {
            "name": "lift",
            "dataType": "double",
            "formatString": "0.00",
            "lineageTag": "59cbf1f4-8fde-4055-9f5e-7d69bcc99d26",
            "sourceColumn": "lift",
            "summarizeBy": "none"
          },
          {
            "name": "cuentas_ambos",
            "dataType": "int64",
            "lineageTag": "335efbbd-e838-4c0d-9d63-720c272a224d",
            "sourceColumn": "cuentas_ambos",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "8d3cb404-6361-4a0d-8c37-127a034e8178",
        "partitions": [
          {
            "name": "Asociacion_Producto",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = Sql.Database(ServidorSQL, BaseDatosSQL),",
                "    Tabla = Origen{[Schema=\"dbo\", Item=\"Asociacion_Producto\"]}[Data],",
                "    Columnas = Table.SelectColumns(Tabla, {\"producto_origen\", \"producto_destino\", \"p_destino_dado_origen\", \"lift\", \"cuentas_ambos\"}),",
                "    Tipos = Table.TransformColumnTypes(Columnas, {{\"producto_origen\", type text}, {\"producto_destino\", type text}, {\"p_destino_dado_origen\", type number}, {\"lift\", type number}, {\"cuentas_ambos\", Int64.Type}})",
                "in",
                "    Tipos"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Regla_Capacidad",
        "columns": [
          {
            "name": "regla",
            "dataType": "string",
            "lineageTag": "798f8edb-4c6b-442e-836c-fc0ab0613e70",
            "sourceColumn": "regla",
            "summarizeBy": "none"
          },
          {
            "name": "tramo",
            "dataType": "string",
            "lineageTag": "b223b0a3-818e-48fa-a7fc-e8441891961f",
            "sortByColumn": "orden",
            "sourceColumn": "tramo",
            "summarizeBy": "none"
          },
          {
            "name": "orden",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "ab7aa2e1-a9bc-4e34-9f7c-8a9c629ca008",
            "sourceColumn": "orden",
            "summarizeBy": "none"
          },
          {
            "name": "prestamos",
            "dataType": "int64",
            "lineageTag": "a8601d3e-42a7-4999-8c09-1d9c4e7c99a2",
            "sourceColumn": "prestamos",
            "summarizeBy": "none"
          },
          {
            "name": "impagos",
            "dataType": "int64",
            "lineageTag": "19d4a3e8-e0d5-4c31-99d0-6f75b107322d",
            "sourceColumn": "impagos",
            "summarizeBy": "none"
          },
          {
            "name": "tasa_impago",
            "dataType": "double",
            "formatString": "0.00%",
            "lineageTag": "eb778112-596f-42ef-be4e-a600f2e625bd",
            "sourceColumn": "tasa_impago",
            "summarizeBy": "none"
          },
          {
            "name": "auc",
            "dataType": "double",
            "formatString": "0.000",
            "lineageTag": "d923e3b3-0c1c-421f-bff8-e644dc139080",
            "sourceColumn": "auc",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "5d91413f-1af0-42f7-9d27-290970a5a5d5",
        "partitions": [
          {
            "name": "Regla_Capacidad",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = Sql.Database(ServidorSQL, BaseDatosSQL),",
                "    Tabla = Origen{[Schema=\"dbo\", Item=\"Regla_Capacidad\"]}[Data],",
                "    Columnas = Table.SelectColumns(Tabla, {\"regla\", \"tramo\", \"orden\", \"prestamos\", \"impagos\", \"tasa_impago\", \"auc\"}),",
                "    Tipos = Table.TransformColumnTypes(Columnas, {{\"regla\", type text}, {\"tramo\", type text}, {\"orden\", Int64.Type}, {\"prestamos\", Int64.Type}, {\"impagos\", Int64.Type}, {\"tasa_impago\", type number}, {\"auc\", type number}})",
                "in",
                "    Tipos"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Composicion_Liquidez",
        "columns": [
          {
            "name": "concepto",
            "dataType": "string",
            "lineageTag": "ecf83225-0f39-4964-9d85-67db94929ef7",
            "sortByColumn": "orden",
            "sourceColumn": "concepto",
            "summarizeBy": "none"
          },
          {
            "name": "orden",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "12a9e8ec-0c55-44f4-afb6-3592748b912c",
            "sourceColumn": "orden",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "103ebd11-7af6-4923-b77a-40a8e25a4e27",
        "partitions": [
          {
            "name": "Composicion_Liquidez",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = #table(type table [concepto = text, orden = Int64.Type], {{\"Saldo neto al corte\", 1}, {\"Cartera vigente\", 2}})",
                "in",
                "    Origen"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "_Medidas",
        "columns": [
          {
            "name": "Medidas",
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "fd9d133a-6a9e-493b-8193-cfb456106bbd",
            "sourceColumn": "Medidas",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "5f1a7424-9523-4eb9-82d5-26a82269f941",
        "measures": [
          {
            "name": "Num Prestamos",
            "description": "Préstamos otorgados (682)",
            "expression": "COUNTROWS(Fact_Prestamos)",
            "formatString": "#,0",
            "lineageTag": "6f645516-9291-4a8f-b2e3-0cb5f363fefe"
          },
          {
            "name": "Prestamos en Mora",
            "description": "Vigentes en mora, estado D (45)",
            "expression": "CALCULATE([Num Prestamos], Dim_Estado_Prestamo[codigo_estado] = \"D\")",
            "formatString": "#,0",
            "lineageTag": "b1c5a7e3-b2b7-4024-aba1-5735bfe6ade9"
          },
          {
            "name": "Prestamos Vigentes",
            "description": "Estados C + D (448)",
            "expression": "CALCULATE([Num Prestamos], Dim_Estado_Prestamo[codigo_estado] IN {\"C\", \"D\"})",
            "formatString": "#,0",
            "lineageTag": "931c1c09-6958-4da2-9c41-b4ed4d58438a"
          },
          {
            "name": "Prestamos Incumplidos",
            "description": "Cerrados con deuda, estado B (31)",
            "expression": "CALCULATE([Num Prestamos], Dim_Estado_Prestamo[codigo_estado] = \"B\")",
            "formatString": "#,0",
            "lineageTag": "579adc13-96c1-42e3-957a-46a399305aa0"
          },
          {
            "name": "Prestamos Cerrados",
            "description": "Estados A + B (234)",
            "expression": "CALCULATE([Num Prestamos], Dim_Estado_Prestamo[codigo_estado] IN {\"A\", \"B\"})",
            "formatString": "#,0",
            "lineageTag": "82f0fbb0-f486-4377-983a-2d61a5018966"
          },
          {
            "name": "Prestamos con Impago",
            "description": "Estados B + D (76)",
            "expression": "CALCULATE([Num Prestamos], Dim_Estado_Prestamo[codigo_estado] IN {\"B\", \"D\"})",
            "formatString": "#,0",
            "lineageTag": "ca5ce098-d503-43e2-b975-e52a38716bbf"
          },
          {
            "name": "Tasa Mora Vigente",
            "description": "D / (C + D) = 10.04%; 0% (no vacío) si hay vigentes sin mora, p. ej. north Bohemia 0/41",
            "expression": "IF([Prestamos Vigentes] > 0, DIVIDE([Prestamos en Mora] + 0, [Prestamos Vigentes]))",
            "formatString": "0.00%",
            "lineageTag": "942b1f87-e2a7-42f5-9f87-00652601c29f"
          },
          {
            "name": "Tasa Incumplimiento",
            "description": "B / (A + B) = 13.25%",
            "expression": "IF([Prestamos Cerrados] > 0, DIVIDE([Prestamos Incumplidos] + 0, [Prestamos Cerrados]))",
            "formatString": "0.00%",
            "lineageTag": "0de464dc-bd68-41a9-bd82-7377c5982f51"
          },
          {
            "name": "Tasa Impago",
            "description": "(B + D) / total = 11.14%; es la tasa de P6 por banda de capacidad",
            "expression": "IF([Num Prestamos] > 0, DIVIDE([Prestamos con Impago] + 0, [Num Prestamos]))",
            "formatString": "0.00%",
            "lineageTag": "523fc55f-ba2e-48e0-8944-4db64978635f"
          },
          {
            "name": "Mora Wilson Inferior",
            "description": "Límite inferior de Wilson (z = 1) de mora",
            "expression": "VAR n = [Prestamos Vigentes] VAR p = DIVIDE([Prestamos en Mora] + 0, n) VAR c = DIVIDE(p + 1 / (2 * n), 1 + 1 / n) VAR m = DIVIDE(1, 1 + 1 / n) * SQRT(p * (1 - p) / n + 1 / (4 * n * n)) RETURN IF(n > 0, c - m)",
            "formatString": "0.00%",
            "lineageTag": "f0875d5c-7091-4028-a08f-20f7c9f3bfd0"
          },
          {
            "name": "Mora Wilson Superior",
            "description": "Límite superior de Wilson (z = 1) de mora",
            "expression": "VAR n = [Prestamos Vigentes] VAR p = DIVIDE([Prestamos en Mora] + 0, n) VAR c = DIVIDE(p + 1 / (2 * n), 1 + 1 / n) VAR m = DIVIDE(1, 1 + 1 / n) * SQRT(p * (1 - p) / n + 1 / (4 * n * n)) RETURN IF(n > 0, c + m)",
            "formatString": "0.00%",
            "lineageTag": "6f316772-d255-42c3-ac37-4c9b5bf3ff27"
          },
          {
            "name": "Incumplimiento Wilson Inferior",
            "description": "Límite inferior de Wilson (z = 1) de incumplimiento",
            "expression": "VAR n = [Prestamos Cerrados] VAR p = DIVIDE([Prestamos Incumplidos] + 0, n) VAR c = DIVIDE(p + 1 / (2 * n), 1 + 1 / n) VAR m = DIVIDE(1, 1 + 1 / n) * SQRT(p * (1 - p) / n + 1 / (4 * n * n)) RETURN IF(n > 0, c - m)",
            "formatString": "0.00%",
            "lineageTag": "81e33fae-f64f-403b-b943-f638131a2ec8"
          },
          {
            "name": "Incumplimiento Wilson Superior",
            "description": "Límite superior de Wilson (z = 1) de incumplimiento",
            "expression": "VAR n = [Prestamos Cerrados] VAR p = DIVIDE([Prestamos Incumplidos] + 0, n) VAR c = DIVIDE(p + 1 / (2 * n), 1 + 1 / n) VAR m = DIVIDE(1, 1 + 1 / n) * SQRT(p * (1 - p) / n + 1 / (4 * n * n)) RETURN IF(n > 0, c + m)",
            "formatString": "0.00%",
            "lineageTag": "660dfcbd-73da-49c4-8b39-3472c6e78fdb"
          },
          {
            "name": "Impago Wilson Inferior",
            "description": "Límite inferior de Wilson (z = 1) de impago",
            "expression": "VAR n = [Num Prestamos] VAR p = DIVIDE([Prestamos con Impago] + 0, n) VAR c = DIVIDE(p + 1 / (2 * n), 1 + 1 / n) VAR m = DIVIDE(1, 1 + 1 / n) * SQRT(p * (1 - p) / n + 1 / (4 * n * n)) RETURN IF(n > 0, c - m)",
            "formatString": "0.00%",
            "lineageTag": "7d1bbcab-602a-48ae-b1b4-b507e4b17f8e"
          },
          {
            "name": "Impago Wilson Superior",
            "description": "Límite superior de Wilson (z = 1) de impago",
            "expression": "VAR n = [Num Prestamos] VAR p = DIVIDE([Prestamos con Impago] + 0, n) VAR c = DIVIDE(p + 1 / (2 * n), 1 + 1 / n) VAR m = DIVIDE(1, 1 + 1 / n) * SQRT(p * (1 - p) / n + 1 / (4 * n * n)) RETURN IF(n > 0, c + m)",
            "formatString": "0.00%",
            "lineageTag": "e23c5a82-f522-452d-89ae-ba5ee2b1c7ba"
          },
          {
            "name": "Tasa Mora Banco",
            "description": "Referencia de P2: la tasa del banco, sin el filtro de distrito",
            "expression": "CALCULATE([Tasa Mora Vigente], REMOVEFILTERS(Dim_Distrito))",
            "formatString": "0.00%",
            "lineageTag": "bb3a828a-e942-4265-827a-3bdb4dfecdb5"
          },
          {
            "name": "Tasa Impago Banco",
            "description": "Referencia de P6: impago de todas las bandas",
            "expression": "CALCULATE([Tasa Impago], REMOVEFILTERS(Fact_Prestamos[banda_capacidad], Fact_Prestamos[Orden Banda]))",
            "formatString": "0.00%",
            "lineageTag": "d265c0c3-91b8-4571-9617-2ec5c0a3f425"
          },
          {
            "name": "Tasa Incumplimiento Banco",
            "description": "Referencia de P6: incumplimiento de todos los segmentos de edad",
            "expression": "CALCULATE([Tasa Incumplimiento], REMOVEFILTERS(Dim_Cliente))",
            "formatString": "0.00%",
            "lineageTag": "261d9a40-1958-4fa0-b9ab-ca0f802c8e55"
          },
          {
            "name": "Tasa Impago Banda Baja",
            "description": "Impago de la banda Baja (2.92%); KEEPFILTERS respeta los demás filtros",
            "expression": "CALCULATE([Tasa Impago], KEEPFILTERS(Fact_Prestamos[banda_capacidad] = \"Baja\"))",
            "formatString": "0.00%",
            "lineageTag": "97246fd0-8161-4fa5-8a22-dfe44ff5dc3b"
          },
          {
            "name": "Tasa Impago Banda Alta",
            "description": "Impago de la banda Alta (23.26%)",
            "expression": "CALCULATE([Tasa Impago], KEEPFILTERS(Fact_Prestamos[banda_capacidad] = \"Alta\"))",
            "formatString": "0.00%",
            "lineageTag": "be6b552e-e2ee-467d-a6a9-b181d9188783"
          },
          {
            "name": "Cartera Total",
            "description": "Monto original de todos los préstamos ($103,261,740)",
            "expression": "SUM(Fact_Prestamos[monto_prestamo])",
            "formatString": "\"$\"#,0",
            "lineageTag": "b4d95cac-214b-4544-906c-118c0e5ea4ba"
          },
          {
            "name": "Cartera Vigente",
            "description": "Monto original C + D ($80,296,176)",
            "expression": "CALCULATE([Cartera Total], Dim_Estado_Prestamo[codigo_estado] IN {\"C\", \"D\"})",
            "formatString": "\"$\"#,0",
            "lineageTag": "a4107a5e-4a37-41b5-8064-6f51703074c7"
          },
          {
            "name": "Saldo por Cobrar Estimado",
            "description": "Capital pendiente estimado de la cartera vigente ($46,620,926)",
            "expression": "CALCULATE(SUM(Fact_Prestamos[saldo_pendiente_estimado]), Dim_Estado_Prestamo[codigo_estado] IN {\"C\", \"D\"})",
            "formatString": "\"$\"#,0",
            "lineageTag": "c324070c-c82d-4e7d-9b4f-7735915e5149"
          },
          {
            "name": "Monto Original en Riesgo",
            "description": "Monto original de los préstamos B + D ($15,580,152)",
            "expression": "CALCULATE([Cartera Total], Dim_Estado_Prestamo[codigo_estado] IN {\"B\", \"D\"})",
            "formatString": "\"$\"#,0",
            "lineageTag": "115821c2-d6cc-45a9-a08a-53bd4f611ed7"
          },
          {
            "name": "Monto Incumplido",
            "description": "Monto original de los préstamos B",
            "expression": "CALCULATE([Cartera Total], Dim_Estado_Prestamo[codigo_estado] = \"B\")",
            "formatString": "\"$\"#,0",
            "lineageTag": "6929fa98-5365-47ac-86fa-d9e5e50608b9"
          },
          {
            "name": "Cuota Mensual",
            "description": "Cuota mensual de los préstamos del contexto",
            "expression": "SUM(Fact_Prestamos[pago_mensual])",
            "formatString": "\"$\"#,0",
            "lineageTag": "53ed815b-6f87-411e-9e67-3e2d4c895965"
          },
          {
            "name": "Clientes con Impago",
            "description": "Titulares con préstamo B (31): lista de denegación",
            "expression": "CALCULATE(DISTINCTCOUNT(Fact_Prestamos[sk_cliente]), Dim_Estado_Prestamo[codigo_estado] = \"B\")",
            "formatString": "#,0",
            "lineageTag": "59697bf0-3c27-4e2a-90d2-166d7c6d1d27"
          },
          {
            "name": "Cartera Distritos Sobre Mora Banco",
            "description": "CALCULATE + FILTER: cartera vigente de los distritos con mora sobre la del banco",
            "expression": "VAR moraBanco = CALCULATE([Tasa Mora Vigente], REMOVEFILTERS(Dim_Distrito)) RETURN CALCULATE([Cartera Vigente], FILTER(VALUES(Dim_Distrito[nombre_distrito]), [Tasa Mora Vigente] > moraBanco))",
            "formatString": "\"$\"#,0",
            "lineageTag": "19f2e412-77c0-4e12-948a-1eeaa98b5bad"
          },
          {
            "name": "Distritos Sobre Mora Banco",
            "description": "Distritos con tasa de mora vigente sobre la del banco",
            "expression": "VAR moraBanco = CALCULATE([Tasa Mora Vigente], REMOVEFILTERS(Dim_Distrito)) RETURN COUNTROWS(FILTER(VALUES(Dim_Distrito[nombre_distrito]), [Tasa Mora Vigente] > moraBanco))",
            "formatString": "#,0",
            "lineageTag": "a123a0d5-9008-4d8e-b43d-946eccffd984"
          },
          {
            "name": "Region Mayor Mora",
            "description": "north Moravia · 15.8%",
            "expression": "VAR r = TOPN(1, FILTER(VALUES(Dim_Distrito[region]), [Prestamos Vigentes] > 0), [Tasa Mora Vigente], DESC) RETURN CONCATENATEX(r, Dim_Distrito[region] & \" · \" & FORMAT([Tasa Mora Vigente], \"0.0%\"), \", \")",
            "lineageTag": "57f5c67d-4d62-40df-90b4-3d4f36bc513c"
          },
          {
            "name": "Distrito Mayor Morosos",
            "description": "Hl.m. Praha · 4 en mora",
            "expression": "VAR d = TOPN(1, FILTER(VALUES(Dim_Distrito[nombre_distrito]), [Prestamos en Mora] > 0), [Prestamos en Mora], DESC) RETURN CONCATENATEX(d, Dim_Distrito[nombre_distrito] & \" · \" & [Prestamos en Mora] & \" en mora\", \", \")",
            "lineageTag": "4ae04d20-9e88-489a-a668-c6107b57ce79"
          },
          {
            "name": "Estado Prestamo",
            "description": "Estado del préstamo del cliente o de la cuenta (fichas)",
            "expression": "IF([Num Prestamos] > 0, CALCULATE(CONCATENATEX(VALUES(Dim_Estado_Prestamo[Estado]), Dim_Estado_Prestamo[Estado], \", \"), Fact_Prestamos))",
            "lineageTag": "e6fa9470-056a-422a-a359-17e78d38895d"
          },
          {
            "name": "Banda Capacidad",
            "description": "Banda de capacidad de pago (ratio cuota / saldo previo)",
            "expression": "IF([Num Prestamos] > 0, CONCATENATEX(VALUES(Fact_Prestamos[banda_capacidad]), Fact_Prestamos[banda_capacidad], \", \"))",
            "lineageTag": "b2a1f8b2-5f41-4f68-b51c-c7357d11c822"
          },
          {
            "name": "Distrito Prestamo",
            "description": "Distrito de la cuenta del préstamo",
            "expression": "IF([Num Prestamos] > 0, CALCULATE(CONCATENATEX(VALUES(Dim_Distrito[nombre_distrito]), Dim_Distrito[nombre_distrito], \", \"), Fact_Prestamos))",
            "lineageTag": "fc6cfd89-1c7b-447f-b9d9-f47a5b98f839"
          },
          {
            "name": "Banda Capacidad Impago",
            "description": "Banda del préstamo B (lista de P6)",
            "expression": "CALCULATE([Banda Capacidad], Dim_Estado_Prestamo[codigo_estado] = \"B\")",
            "lineageTag": "ec7d069b-4861-4f8e-9cac-ad369caad498"
          },
          {
            "name": "Distrito Impago",
            "description": "Distrito del préstamo B (lista de P6)",
            "expression": "CALCULATE([Distrito Prestamo], Dim_Estado_Prestamo[codigo_estado] = \"B\")",
            "lineageTag": "0e1d9365-6d7e-4de7-b3cb-f5dffb1a749b"
          },
          {
            "name": "Saldo Neto Corte",
            "description": "Saldo al cierre del último mes del contexto ($197,140,434 en dic-1998)",
            "expression": "VAR ultimoMes = CALCULATE(MAX(Dim_Tiempo[fecha]), Fact_Saldo_Cuenta_Mensual) RETURN CALCULATE(SUM(Fact_Saldo_Cuenta_Mensual[saldo_fin_mes]), FILTER(ALL(Dim_Tiempo), Dim_Tiempo[fecha] = ultimoMes))",
            "formatString": "\"$\"#,0",
            "lineageTag": "0d1f9e2b-587a-42f1-b3a4-c46613e49723"
          },
          {
            "name": "Cuentas Activas Corte",
            "description": "Cuentas con foto en el último mes del contexto (4,500 en dic-1998)",
            "expression": "VAR ultimoMes = CALCULATE(MAX(Dim_Tiempo[fecha]), Fact_Saldo_Cuenta_Mensual) RETURN CALCULATE(COUNTROWS(Fact_Saldo_Cuenta_Mensual), FILTER(ALL(Dim_Tiempo), Dim_Tiempo[fecha] = ultimoMes))",
            "formatString": "#,0",
            "lineageTag": "06959639-808e-4ad7-bd9a-9d21bbb04ed9"
          },
          {
            "name": "Cuentas en Sobregiro",
            "description": "Cuentas con saldo negativo al cierre del último mes (39 en dic-1998)",
            "expression": "VAR ultimoMes = CALCULATE(MAX(Dim_Tiempo[fecha]), Fact_Saldo_Cuenta_Mensual) RETURN CALCULATE(CALCULATE(COUNTROWS(Fact_Saldo_Cuenta_Mensual), Fact_Saldo_Cuenta_Mensual[en_sobregiro] = TRUE()), FILTER(ALL(Dim_Tiempo), Dim_Tiempo[fecha] = ultimoMes))",
            "formatString": "#,0",
            "lineageTag": "93e0f8e8-147d-4c39-b23f-332f9fdab04f"
          },
          {
            "name": "Saldo Promedio por Cuenta",
            "description": "Saldo por cuenta activa: aísla el crecimiento por apertura de cuentas",
            "expression": "DIVIDE([Saldo Neto Corte], [Cuentas Activas Corte])",
            "formatString": "\"$\"#,0",
            "lineageTag": "1945ac73-01e1-4cef-afe3-9b8ec6539081"
          },
          {
            "name": "Saldo Promedio Banco",
            "description": "Referencia gris de D1",
            "expression": "CALCULATE([Saldo Promedio por Cuenta], REMOVEFILTERS(Dim_Distrito))",
            "formatString": "\"$\"#,0",
            "lineageTag": "84cc1245-1be8-44d8-9509-3b30b6baa355"
          },
          {
            "name": "Umbral Sobregiro",
            "description": "Línea en 0 de la ficha D2",
            "expression": "IF(NOT ISBLANK([Saldo Neto Corte]), 0)",
            "formatString": "\"$\"#,0.00",
            "lineageTag": "98e4799e-d420-4c85-949f-53e8f2355869"
          },
          {
            "name": "Saldo Neto Corte Total",
            "description": "Saldo al corte dic-1998, sin importar el año elegido",
            "expression": "CALCULATE([Saldo Neto Corte], REMOVEFILTERS(Dim_Anio), REMOVEFILTERS(Dim_Tiempo))",
            "formatString": "\"$\"#,0",
            "lineageTag": "108e68a4-53ed-4385-828e-c5dd556eb17a"
          },
          {
            "name": "Cartera Vigente Corte",
            "description": "Cartera vigente al corte, sin importar el año elegido",
            "expression": "CALCULATE([Cartera Vigente], REMOVEFILTERS(Dim_Anio), REMOVEFILTERS(Dim_Tiempo))",
            "formatString": "\"$\"#,0",
            "lineageTag": "f9b67bc6-6278-4796-9ec4-68ac10f6c948"
          },
          {
            "name": "Absorcion Vigente",
            "description": "KPI de liquidez de la Carta v8: cartera vigente / saldo neto al corte (40.73%)",
            "expression": "DIVIDE([Cartera Vigente Corte], [Saldo Neto Corte Total])",
            "formatString": "0.00%",
            "lineageTag": "d81e9fad-1e0d-4349-824a-9f04eb4d4f51"
          },
          {
            "name": "Absorcion Cartera Total",
            "description": "Referencia histórica: cartera total / saldo neto (52.38%)",
            "expression": "DIVIDE(CALCULATE([Cartera Total], REMOVEFILTERS(Dim_Anio), REMOVEFILTERS(Dim_Tiempo)), [Saldo Neto Corte Total])",
            "formatString": "0.00%",
            "lineageTag": "b602ecf9-a4f0-4977-911a-b9cb27585b33"
          },
          {
            "name": "Absorcion Banco",
            "description": "Referencia de P3: absorción del banco",
            "expression": "CALCULATE([Absorcion Vigente], REMOVEFILTERS(Dim_Distrito))",
            "formatString": "0.00%",
            "lineageTag": "ed5015f6-9493-4376-bf91-f7812f6faf81"
          },
          {
            "name": "Liquidez Libre",
            "description": "Saldo que no respalda cartera vigente ($116,844,258)",
            "expression": "[Saldo Neto Corte Total] - [Cartera Vigente Corte]",
            "formatString": "\"$\"#,0",
            "lineageTag": "9a7dd86d-bdd4-437f-9cc6-805ba5fbaa03"
          },
          {
            "name": "Valor Composicion Liquidez",
            "description": "Cascada de P3; el total es la liquidez libre",
            "expression": "SWITCH(SELECTEDVALUE(Composicion_Liquidez[concepto]), \"Saldo neto al corte\", [Saldo Neto Corte Total], \"Cartera vigente\", -[Cartera Vigente Corte])",
            "formatString": "\"$\"#,0",
            "lineageTag": "7f8c63c2-caf5-490f-b035-82e01669aa8f"
          },
          {
            "name": "Volumen Transaccionado",
            "description": "$6,257,862,197",
            "expression": "SUM(vw_PBI_Trans_Anual_Cuenta[monto_total])",
            "formatString": "\"$\"#,0",
            "lineageTag": "cc11b3a1-cb54-4dbe-8fed-fdd516c419ac"
          },
          {
            "name": "Num Transacciones",
            "description": "1,056,320",
            "expression": "SUM(vw_PBI_Trans_Anual_Cuenta[num_transacciones])",
            "formatString": "#,0",
            "lineageTag": "be6b3f0f-2097-43f5-8c68-fee54be64cda"
          },
          {
            "name": "Ticket Promedio",
            "description": "Monto promedio por movimiento",
            "expression": "DIVIDE([Volumen Transaccionado], [Num Transacciones])",
            "formatString": "\"$\"#,0.00",
            "lineageTag": "421f131d-ec6e-4d19-a3b8-eff95b403c3b"
          },
          {
            "name": "Desv Est Transaccion",
            "description": "σ muestral exacta desde la suma y la suma de cuadrados",
            "expression": "VAR n = [Num Transacciones] VAR s = [Volumen Transaccionado] VAR sq = SUM(vw_PBI_Trans_Anual_Cuenta[suma_cuadrados]) RETURN IF(n > 1, SQRT(DIVIDE(sq - s * s / n, n - 1)))",
            "formatString": "\"$\"#,0.00",
            "lineageTag": "323dbec5-1644-43c5-9738-df9242219160"
          },
          {
            "name": "Ticket Limite Superior",
            "description": "Promedio + 1σ",
            "expression": "[Ticket Promedio] + [Desv Est Transaccion]",
            "formatString": "\"$\"#,0.00",
            "lineageTag": "5dc80091-a45b-4e0c-9887-446c1de80ea3"
          },
          {
            "name": "Ticket Limite Inferior",
            "description": "Promedio − 1σ (no negativo)",
            "expression": "MAX(0, [Ticket Promedio] - [Desv Est Transaccion])",
            "formatString": "\"$\"#,0.00",
            "lineageTag": "a089144a-544b-4859-88ba-d647f3cbfdef"
          },
          {
            "name": "EE Ticket",
            "description": "Error estándar (tooltip)",
            "expression": "DIVIDE([Desv Est Transaccion], SQRT([Num Transacciones]))",
            "formatString": "\"$\"#,0.00",
            "lineageTag": "b1d09cad-23e7-4474-b7ef-1b24969e4dd1"
          },
          {
            "name": "Saldo Promedio Historico",
            "description": "Saldo promedio de la cuenta ponderado por movimientos",
            "expression": "DIVIDE(SUMX(vw_PBI_Trans_Anual_Cuenta, vw_PBI_Trans_Anual_Cuenta[saldo_promedio] * vw_PBI_Trans_Anual_Cuenta[num_transacciones]), [Num Transacciones])",
            "formatString": "\"$\"#,0",
            "lineageTag": "47c8365d-78bb-4316-b884-08701c32239d"
          },
          {
            "name": "Compromiso Ordenes",
            "description": "Órdenes fijas mensuales ($21,229,041)",
            "expression": "SUM(Fact_Ordenes[monto_orden])",
            "formatString": "\"$\"#,0",
            "lineageTag": "ea5993b7-96ee-4711-9aac-8f5d85a6aa69"
          },
          {
            "name": "Num Ordenes",
            "description": "6,471 órdenes",
            "expression": "COUNTROWS(Fact_Ordenes)",
            "formatString": "#,0",
            "lineageTag": "396e5354-f082-46ec-90db-56b8d32ee6e7"
          },
          {
            "name": "Pct Ordenes",
            "description": "Participación de cada propósito",
            "expression": "DIVIDE([Num Ordenes], CALCULATE([Num Ordenes], REMOVEFILTERS(Dim_Orden[categoria_orden_traducida])))",
            "formatString": "0.00%",
            "lineageTag": "72aee093-b782-4df5-a034-a193c70f7300"
          },
          {
            "name": "Indice Saturacion",
            "description": "Órdenes mensuales / saldo promedio histórico de la cuenta (cuenta 2335: 2.14)",
            "expression": "DIVIDE([Compromiso Ordenes], CALCULATE([Saldo Promedio Historico], REMOVEFILTERS(Dim_Anio), REMOVEFILTERS(Dim_Tiempo), REMOVEFILTERS(vw_PBI_Trans_Anual_Cuenta[categoria_analitica])))",
            "formatString": "0.00",
            "lineageTag": "953fced6-c67e-49d0-8b6b-daa87101ea25"
          },
          {
            "name": "Cuentas Saturadas",
            "description": "CALCULATE + FILTER: cuentas con índice > 0.5 (47)",
            "expression": "COUNTROWS(FILTER(VALUES(Dim_Cuenta[id_cuenta_bk]), [Indice Saturacion] > 0.5))",
            "formatString": "#,0",
            "lineageTag": "7d82fe7b-6dc2-442b-94ab-5d1b66b24a1f"
          },
          {
            "name": "Cuentas Sobre Saldo",
            "description": "Cuentas cuyas órdenes superan su saldo promedio (1)",
            "expression": "COUNTROWS(FILTER(VALUES(Dim_Cuenta[id_cuenta_bk]), [Indice Saturacion] > 1))",
            "formatString": "#,0",
            "lineageTag": "f7013306-e812-4f38-b590-f45788eb01e6"
          },
          {
            "name": "Cuentas con Credito Externo",
            "description": "Cuentas que pagan un préstamo a otra entidad (35)",
            "expression": "CALCULATE(DISTINCTCOUNT(Fact_Ordenes[sk_cuenta]), Dim_Cuenta[tiene_credito_externo] = TRUE())",
            "formatString": "#,0",
            "lineageTag": "00715c51-6232-4cc0-a4c9-30fde86b82e9"
          },
          {
            "name": "Credito Externo Mensual",
            "description": "Cuotas mensuales a otras entidades ($177,154)",
            "expression": "CALCULATE([Compromiso Ordenes], Dim_Cuenta[tiene_credito_externo] = TRUE(), Dim_Orden[k_symbol_original] = \"UVER\")",
            "formatString": "\"$\"#,0",
            "lineageTag": "f9f6245f-ddcc-423e-b462-34ebf1d39cfb"
          },
          {
            "name": "Indice Saturacion Alerta",
            "description": "Solo cuentas en alerta",
            "expression": "VAR i = [Indice Saturacion] RETURN IF(i > 0.5, i)",
            "formatString": "0.00",
            "lineageTag": "a82a8a6d-ec60-4a05-a2f1-8b7a38f06e7d"
          },
          {
            "name": "Compromiso Alerta",
            "description": "Solo cuentas en alerta",
            "expression": "IF([Indice Saturacion] > 0.5, [Compromiso Ordenes])",
            "formatString": "\"$\"#,0",
            "lineageTag": "57a58728-3339-43f2-92d0-d29b211fad2d"
          },
          {
            "name": "Saldo Promedio Alerta",
            "description": "Solo cuentas en alerta",
            "expression": "IF([Indice Saturacion] > 0.5, CALCULATE([Saldo Promedio Historico], REMOVEFILTERS(Dim_Anio), REMOVEFILTERS(Dim_Tiempo), REMOVEFILTERS(vw_PBI_Trans_Anual_Cuenta[categoria_analitica])))",
            "formatString": "\"$\"#,0",
            "lineageTag": "81353cad-5051-4cf1-ab5c-53f67e4971a5"
          },
          {
            "name": "Credito Externo Alerta",
            "description": "Solo cuentas en alerta",
            "expression": "IF([Indice Saturacion] > 0.5, [Credito Externo Mensual])",
            "formatString": "\"$\"#,0",
            "lineageTag": "293410fb-c316-4245-ad48-3622df117eb2"
          },
          {
            "name": "Cliente Titular Alerta",
            "description": "Solo cuentas en alerta",
            "expression": "IF([Indice Saturacion] > 0.5, CALCULATE(SELECTEDVALUE(Dim_Cliente[Cliente]), Fact_Saldo_Cuenta_Mensual))",
            "lineageTag": "e1a9400c-440f-4b61-a012-165c5b88afa4"
          },
          {
            "name": "Cuenta Alerta",
            "description": "Cuenta del titular en alerta",
            "expression": "IF([Indice Saturacion] > 0.5, CALCULATE(SELECTEDVALUE(Dim_Cuenta[Cuenta]), Fact_Saldo_Cuenta_Mensual))",
            "lineageTag": "60368f9e-9b2a-4125-9fed-5c11eb9f5762"
          },
          {
            "name": "Titulo Distrito",
            "description": "Título dinámico de D1",
            "expression": "\"Distrito: \" & SELECTEDVALUE(Dim_Distrito[nombre_distrito], \"(varios)\") & \" (\" & SELECTEDVALUE(Dim_Distrito[region], \"varias regiones\") & \")\"",
            "lineageTag": "29cb3734-e4d2-4fd1-ac11-80a8c29187f5"
          },
          {
            "name": "Region del Distrito",
            "description": "Región del distrito (tooltip del treemap de P2)",
            "expression": "SELECTEDVALUE(Dim_Distrito[region])",
            "lineageTag": "8379037c-02e3-46a7-8114-db955d6891d3"
          },
          {
            "name": "Poblacion Distrito",
            "description": "Habitantes",
            "expression": "SELECTEDVALUE(Dim_Distrito[poblacion])",
            "formatString": "#,0",
            "lineageTag": "0e6f1178-1f84-446e-a6c3-77cb0b650093"
          },
          {
            "name": "Salario Promedio Distrito",
            "description": "Salario promedio",
            "expression": "SELECTEDVALUE(Dim_Distrito[salario_promedio])",
            "formatString": "\"$\"#,0",
            "lineageTag": "39829bad-647d-40a1-83a1-fa9cb0786b2b"
          },
          {
            "name": "Desempleo Distrito 1995",
            "description": "Tasa de desempleo 1995 (%)",
            "expression": "SELECTEDVALUE(Dim_Distrito[tasa_desempleo])",
            "formatString": "0.00",
            "lineageTag": "5f7889be-4745-45d7-a096-18c05e68b647"
          },
          {
            "name": "Origen Indicadores",
            "description": "Marca el distrito 69 con indicadores imputados",
            "expression": "IF(HASONEVALUE(Dim_Distrito[es_imputado]), IF(VALUES(Dim_Distrito[es_imputado]), \"Imputado (Informe 10)\", \"Fuente original\"))",
            "lineageTag": "eb8826e3-6db8-4792-b21c-2552c1efdfd2"
          },
          {
            "name": "Cliente Ficha",
            "description": "Titular de la cuenta (vale si se llega por cliente o por cuenta)",
            "expression": "CALCULATE(SELECTEDVALUE(Dim_Cliente[Cliente]), Fact_Saldo_Cuenta_Mensual)",
            "lineageTag": "8a029304-b835-4da9-b232-9ea2e6ef6ee8"
          },
          {
            "name": "Cuenta Ficha",
            "description": "Cuenta del titular",
            "expression": "CALCULATE(SELECTEDVALUE(Dim_Cuenta[Cuenta]), Fact_Saldo_Cuenta_Mensual)",
            "lineageTag": "926f1367-d7a4-4fe8-83fb-e4460f26b57a"
          },
          {
            "name": "Titulo Cliente",
            "description": "Título dinámico de D2",
            "expression": "\"Ficha 360 · \" & COALESCE([Cliente Ficha], SELECTEDVALUE(Dim_Cliente[Cliente], \"(varios clientes)\")) & \" · \" & COALESCE([Cuenta Ficha], \"sin cuenta propia\")",
            "lineageTag": "57ba6e55-e531-4675-97d2-4bcee236720d"
          },
          {
            "name": "Edad Cliente",
            "description": "Edad al 31/12/1998",
            "expression": "CALCULATE(SELECTEDVALUE(Dim_Cliente[edad_corte]), Fact_Saldo_Cuenta_Mensual)",
            "formatString": "#,0",
            "lineageTag": "587ddee0-e400-4a12-ab6a-73c8dde36f0e"
          },
          {
            "name": "Segmento Cliente",
            "description": "Segmento de edad (3 grupos del Data Mart)",
            "expression": "CALCULATE(SELECTEDVALUE(Dim_Cliente[segmento_edad]), Fact_Saldo_Cuenta_Mensual)",
            "lineageTag": "7e4a1019-0689-497b-a6eb-7201ef15d48a"
          },
          {
            "name": "Arquetipo Cliente",
            "description": "Macro-región y segmento",
            "expression": "CALCULATE(SELECTEDVALUE(Dim_Cliente[arquetipo_demografico]), Fact_Saldo_Cuenta_Mensual)",
            "lineageTag": "9f764d7c-2324-41a3-af84-5f5443c40e2c"
          },
          {
            "name": "Calificacion Cliente",
            "description": "Buen / Mal pagador / Sin evaluar",
            "expression": "CALCULATE(SELECTEDVALUE(Dim_Cliente[calificacion_pago_desc]), Fact_Saldo_Cuenta_Mensual)",
            "lineageTag": "bb725657-4ea5-4d2b-8b57-d07c664681fc"
          },
          {
            "name": "Distrito Cuenta",
            "description": "Distrito de la cuenta",
            "expression": "CALCULATE(SELECTEDVALUE(Dim_Distrito[nombre_distrito]), Fact_Saldo_Cuenta_Mensual)",
            "lineageTag": "a9732848-1f51-4d79-87a0-7bc85dad20af"
          },
          {
            "name": "Cuota Maxima Prudente",
            "description": "Cuota que deja el ratio en la banda Baja (Informe 04)",
            "expression": "SUM(Recomendacion_Cuenta[prestamo_cuota_maxima])",
            "formatString": "\"$\"#,0",
            "lineageTag": "c9573f3a-add3-46b5-a4bb-9df058e13c25"
          },
          {
            "name": "Monto Maximo Prudente",
            "description": "Monto a 36 meses con esa cuota (Informe 04)",
            "expression": "SUM(Recomendacion_Cuenta[prestamo_monto_maximo_36m])",
            "formatString": "\"$\"#,0",
            "lineageTag": "18bacb0e-13f7-4a78-a04f-4f035a4af4d0"
          },
          {
            "name": "Recomendaciones Demograficas",
            "description": "Productos en el top 3 del recomendador demográfico (el más preciso: Hit@1 66.0%)",
            "expression": "CALCULATE(COUNTROWS(Recomendacion_Producto), Recomendacion_Producto[sistema] = \"Demográfico\")",
            "formatString": "#,0",
            "lineageTag": "097eb661-b322-425e-b33e-d6f536998ec1"
          },
          {
            "name": "Primera Opcion",
            "description": "Veces que el producto es la primera recomendación",
            "expression": "CALCULATE([Recomendaciones Demograficas], Recomendacion_Producto[posicion] = 1)",
            "formatString": "#,0",
            "lineageTag": "bdd30075-89d4-4534-a0ba-76e0bcea44de"
          },
          {
            "name": "Recomendaciones kNN",
            "description": "Productos en el top 3 del kNN por perfil exógeno",
            "expression": "CALCULATE(COUNTROWS(Recomendacion_Producto), Recomendacion_Producto[sistema] = \"kNN perfil\")",
            "formatString": "#,0",
            "lineageTag": "b4d2647a-85e9-4a99-a6d7-0fd1f4dad627"
          },
          {
            "name": "Descubrimientos kNN",
            "description": "Ofertas del kNN que el demográfico no tiene en su top 3 (2,731)",
            "expression": "CALCULATE([Recomendaciones kNN], Recomendacion_Producto[es_descubrimiento] = TRUE())",
            "formatString": "#,0",
            "lineageTag": "28e4f8a9-f86e-49ef-b80b-bc4b118d203d"
          },
          {
            "name": "Clientes con Recomendacion",
            "description": "Titulares con al menos una recomendación",
            "expression": "CALCULATE(DISTINCTCOUNT(Recomendacion_Producto[sk_cuenta]), Recomendacion_Producto[sistema] = \"Demográfico\")",
            "formatString": "#,0",
            "lineageTag": "111e8db7-ce54-4fe5-b814-3223e6691335"
          },
          {
            "name": "Cuentas que ya lo Usan",
            "description": "Cuentas que ya usan el producto (adopción actual)",
            "expression": "COUNTROWS(Adopcion_Producto)",
            "formatString": "#,0",
            "lineageTag": "6e464c53-c18e-43b0-bb9b-10ccf2b06461"
          },
          {
            "name": "Titulares",
            "description": "Titulares (una cuenta cada uno: 4,500)",
            "expression": "COUNTROWS(Capacidad_Prestamo)",
            "formatString": "#,0",
            "lineageTag": "4e631614-198a-432a-a511-f6faf7e37b97"
          },
          {
            "name": "Penetracion Actual",
            "description": "Cuentas que ya usan el producto / titulares del contexto",
            "expression": "DIVIDE([Cuentas que ya lo Usan], [Titulares])",
            "formatString": "0.00%",
            "lineageTag": "98f298fa-fe75-4fad-9382-161f1b0c95a5"
          },
          {
            "name": "Producto Mas Recomendado",
            "description": "Primera recomendación más frecuente en el contexto",
            "expression": "VAR x = TOPN(1, VALUES(Dim_Producto[producto]), [Primera Opcion], DESC) RETURN CONCATENATEX(x, Dim_Producto[producto] & \" · \" & FORMAT([Primera Opcion], \"#,0\"), \", \")",
            "lineageTag": "aef5a334-2518-42c8-a49a-649a83b2aac2"
          },
          {
            "name": "Recomendacion 1",
            "description": "Primera recomendación del titular",
            "expression": "CALCULATE(SELECTEDVALUE(Recomendacion_Producto[producto]), Recomendacion_Producto[sistema] = \"Demográfico\", Recomendacion_Producto[posicion] = 1)",
            "lineageTag": "10ad4916-aa76-4af7-977b-b288c66ea0f2"
          },
          {
            "name": "Recomendacion 2",
            "description": "Segunda recomendación del titular",
            "expression": "CALCULATE(SELECTEDVALUE(Recomendacion_Producto[producto]), Recomendacion_Producto[sistema] = \"Demográfico\", Recomendacion_Producto[posicion] = 2)",
            "lineageTag": "45817fe5-9467-4351-8d6e-098e7a5493d8"
          },
          {
            "name": "Recomendacion 3",
            "description": "Tercera recomendación del titular",
            "expression": "CALCULATE(SELECTEDVALUE(Recomendacion_Producto[producto]), Recomendacion_Producto[sistema] = \"Demográfico\", Recomendacion_Producto[posicion] = 3)",
            "lineageTag": "fb206396-903c-4bbe-b2d9-c4c4d9b5b2c4"
          },
          {
            "name": "Descubrimiento kNN",
            "description": "Productos que el kNN añade para el titular",
            "expression": "CALCULATE(CONCATENATEX(VALUES(Recomendacion_Producto[producto]), Recomendacion_Producto[producto], \", \"), Recomendacion_Producto[sistema] = \"kNN perfil\", Recomendacion_Producto[es_descubrimiento] = TRUE())",
            "lineageTag": "05cf969e-73f7-420b-8c46-8b368f0da812"
          },
          {
            "name": "Acierto Elegido",
            "description": "Hit@1 del demográfico (66.0%, semilla 42)",
            "expression": "CALCULATE(MAX(Evaluacion_Recomendador[hit_1]), Evaluacion_Recomendador[modelo] = \"Demográfico (arquetipo)\")",
            "formatString": "0.00%",
            "lineageTag": "905dd576-3c9d-4585-94e8-a5f4e27ac417"
          },
          {
            "name": "Acierto Popularidad",
            "description": "Hit@1 de recomendar lo más popular (58.5%): la línea base",
            "expression": "CALCULATE(MAX(Evaluacion_Recomendador[hit_1]), Evaluacion_Recomendador[modelo] = \"Popularidad\")",
            "formatString": "0.00%",
            "lineageTag": "9192ddca-05b1-4059-bec3-814b0f05baa4"
          },
          {
            "name": "Acierto Cola Larga kNN",
            "description": "Hit@1 del kNN en productos poco comunes (37.2%)",
            "expression": "CALCULATE(MAX(Evaluacion_Recomendador[hit_1_cola_larga]), Evaluacion_Recomendador[modelo] = \"kNN usuario-usuario (perfil exógeno)\")",
            "formatString": "0.00%",
            "lineageTag": "99c73eb1-3cd4-4177-b5fa-ec1939bae319"
          },
          {
            "name": "Acierto Cola Larga Popularidad",
            "description": "Hit@1 de la popularidad en productos poco comunes (6.3%)",
            "expression": "CALCULATE(MAX(Evaluacion_Recomendador[hit_1_cola_larga]), Evaluacion_Recomendador[modelo] = \"Popularidad\")",
            "formatString": "0.00%",
            "lineageTag": "057cebaf-b5c0-408b-8349-52e09a92cdbb"
          },
          {
            "name": "Acierto Hit1",
            "description": "Hit@1 del modelo (gráfico comparativo)",
            "expression": "SUM(Evaluacion_Recomendador[hit_1])",
            "formatString": "0.00%",
            "lineageTag": "e4b82582-93e6-44a5-b927-9482b0601120"
          },
          {
            "name": "Acierto Cola Larga",
            "description": "Hit@1 en la cola larga (gráfico comparativo)",
            "expression": "SUM(Evaluacion_Recomendador[hit_1_cola_larga])",
            "formatString": "0.00%",
            "lineageTag": "859c5e07-ac98-45d6-8db2-1697a6d341a7"
          },
          {
            "name": "MRR Modelo",
            "description": "Rango recíproco medio",
            "expression": "SUM(Evaluacion_Recomendador[mrr])",
            "formatString": "0.000",
            "lineageTag": "2431c87b-48e8-4070-8769-80a20410bb4e"
          },
          {
            "name": "MRR Confirmacion",
            "description": "MRR con la semilla 2026",
            "expression": "SUM(Evaluacion_Recomendador[mrr_confirmacion])",
            "formatString": "0.000",
            "lineageTag": "401aed0e-81da-4c51-8773-6105e4d4522e"
          },
          {
            "name": "Titulares sin Prestamo",
            "description": "3,818",
            "expression": "CALCULATE([Titulares], Capacidad_Prestamo[tiene_prestamo] = FALSE())",
            "formatString": "#,0",
            "lineageTag": "90a21789-b9e0-48e1-bd5d-e0aa29e56f51"
          },
          {
            "name": "Prestamos Prudentes Recomendados",
            "description": "Titulares con préstamo en su top 3 (1,721)",
            "expression": "CALCULATE([Titulares], Capacidad_Prestamo[prestamo_recomendado] = TRUE())",
            "formatString": "#,0",
            "lineageTag": "7a21efea-d2ba-43f7-86cc-cb662e0744c7"
          },
          {
            "name": "Cuota Prudente Mediana",
            "description": "5.7% del saldo promedio, mediana de los titulares sin préstamo (1,873)",
            "expression": "CALCULATE(MEDIAN(Capacidad_Prestamo[cuota_prudente]), Capacidad_Prestamo[tiene_prestamo] = FALSE())",
            "formatString": "\"$\"#,0.00",
            "lineageTag": "c7c81260-ecd5-4fe3-b7dd-cfef39a5b8fa"
          },
          {
            "name": "Pueden Pagar Prestamo Tipico",
            "description": "Titulares sin préstamo cuya cuota prudente cubre la cuota mediana otorgada (71)",
            "expression": "CALCULATE([Titulares], Capacidad_Prestamo[puede_pagar_prestamo_tipico] = TRUE())",
            "formatString": "#,0",
            "lineageTag": "d00beed3-ae4b-4d53-9861-509c06648ae4"
          },
          {
            "name": "Monto Prudente Ofrecible 36m",
            "description": "Suma de montos máximos a 36 meses de los préstamos recomendados",
            "expression": "CALCULATE(SUM(Capacidad_Prestamo[monto_maximo_36m]), Capacidad_Prestamo[prestamo_recomendado] = TRUE())",
            "formatString": "\"$\"#,0",
            "lineageTag": "4d6d4834-0bc5-441c-8598-e4f8af8bae78"
          },
          {
            "name": "Saldo Promedio Oferta",
            "description": "Saldo promedio del titular con préstamo recomendado",
            "expression": "CALCULATE(SUM(Capacidad_Prestamo[saldo_promedio]), Capacidad_Prestamo[prestamo_recomendado] = TRUE())",
            "formatString": "\"$\"#,0",
            "lineageTag": "9a8bea73-b49a-43cc-bb35-4029a827b0dd"
          },
          {
            "name": "Cuota Prudente Oferta",
            "description": "Cuota prudente del titular con préstamo recomendado",
            "expression": "CALCULATE(SUM(Capacidad_Prestamo[cuota_prudente]), Capacidad_Prestamo[prestamo_recomendado] = TRUE())",
            "formatString": "\"$\"#,0",
            "lineageTag": "9dfed6eb-9453-497f-b867-dc951572046a"
          },
          {
            "name": "Monto 12m Oferta",
            "description": "Monto máximo a 12 meses",
            "expression": "CALCULATE(SUM(Capacidad_Prestamo[monto_maximo_12m]), Capacidad_Prestamo[prestamo_recomendado] = TRUE())",
            "formatString": "\"$\"#,0",
            "lineageTag": "7e2aa73a-f26d-4800-b6e5-f3f0a200c798"
          },
          {
            "name": "Monto 36m Oferta",
            "description": "Monto máximo a 36 meses",
            "expression": "CALCULATE(SUM(Capacidad_Prestamo[monto_maximo_36m]), Capacidad_Prestamo[prestamo_recomendado] = TRUE())",
            "formatString": "\"$\"#,0",
            "lineageTag": "ff21b8f7-f6fd-4db9-9ecc-5efcd3be20d5"
          },
          {
            "name": "Monto 60m Oferta",
            "description": "Monto máximo a 60 meses",
            "expression": "CALCULATE(SUM(Capacidad_Prestamo[monto_maximo_60m]), Capacidad_Prestamo[prestamo_recomendado] = TRUE())",
            "formatString": "\"$\"#,0",
            "lineageTag": "4440450c-de25-4dba-a35d-3819a41ac761"
          },
          {
            "name": "AUC Regla",
            "description": "AUC de la regla para predecir el impago",
            "expression": "MAX(Regla_Capacidad[auc])",
            "formatString": "0.000",
            "lineageTag": "d86184be-2f20-4d93-bbed-3a722c5f3ae7"
          },
          {
            "name": "AUC Regla Elegida",
            "description": "0.717",
            "expression": "CALCULATE([AUC Regla], Regla_Capacidad[regla] = \"Carta v8: cuota / saldo previo\")",
            "formatString": "0.000",
            "lineageTag": "e76fe2d6-9e82-41b0-b1d0-0f36efe87d2d"
          },
          {
            "name": "AUC Regla Anterior",
            "description": "0.659",
            "expression": "CALCULATE([AUC Regla], Regla_Capacidad[regla] = \"Anterior: cuota / salario del distrito\")",
            "formatString": "0.000",
            "lineageTag": "d58aeb0c-63c2-4ca2-ba0c-8aabb78e34d4"
          },
          {
            "name": "P Destino dado Origen",
            "description": "De quienes tienen el producto de origen, % que también tiene el de destino",
            "expression": "SUM(Asociacion_Producto[p_destino_dado_origen])",
            "formatString": "0.00%",
            "lineageTag": "10ceadf1-cdbe-4401-9411-e5567b565302"
          },
          {
            "name": "Lift Asociacion",
            "description": "Lift: > 1 van juntos más de lo esperado por azar",
            "expression": "SUM(Asociacion_Producto[lift])",
            "formatString": "0.00",
            "lineageTag": "44118a35-50e3-4cc9-9368-4eee4cf18bb5"
          },
          {
            "name": "Regla Mas Fuerte",
            "description": "Par con mayor lift (al menos 100 cuentas), en la dirección de mayor P(j|i): Seguro → Transferencias 99.8%",
            "expression": "VAR x = TOPN(1, FILTER(Asociacion_Producto, Asociacion_Producto[cuentas_ambos] >= 100), Asociacion_Producto[lift], DESC, Asociacion_Producto[p_destino_dado_origen], DESC) RETURN CONCATENATEX(x, Asociacion_Producto[producto_origen] & \" → \" & Asociacion_Producto[producto_destino] & \" · \" & FORMAT(Asociacion_Producto[p_destino_dado_origen], \"0.0%\"), \", \")",
            "lineageTag": "2c4b0524-74e0-42dc-97a3-757a2fbde16a"
          },
          {
            "name": "Color Mora",
            "description": "Treemap de P2: escala secuencial blanco → bermellón por tasa de mora",
            "expression": "VAR x = [Tasa Mora Vigente] RETURN SWITCH(TRUE(), ISBLANK(x), \"#FFFFFF\", x < 0.05, \"#FBE3D3\", x < 0.10, \"#F2B48C\", x < 0.15, \"#E5813F\", \"#D55E00\")",
            "lineageTag": "54e8ad37-2889-4ee0-b464-a83891356b5c"
          },
          {
            "name": "Color Saturacion",
            "description": "Dispersión de P5: bermellón > 1, naranja > 0.5, gris el resto",
            "expression": "VAR x = [Indice Saturacion] RETURN IF(x > 1, \"#D55E00\", IF(x > 0.5, \"#E69F00\", \"#7F7F7F\"))",
            "lineageTag": "e477cfbf-aa26-4a41-bf71-9e6b6065c2ca"
          },
          {
            "name": "Color Modelo",
            "description": "R1: modelos elegidos en azul, el resto en gris",
            "expression": "IF(SELECTEDVALUE(Evaluacion_Recomendador[elegido]) = TRUE(), \"#0072B2\", \"#BDBDBD\")",
            "lineageTag": "17bd8026-6eb7-4e51-beb1-760c263d3e4d"
          },
          {
            "name": "Color Regla",
            "description": "R2: regla elegida en azul",
            "expression": "IF(SELECTEDVALUE(Regla_Capacidad[regla]) = \"Carta v8: cuota / saldo previo\", \"#0072B2\", \"#BDBDBD\")",
            "lineageTag": "0ee7179f-f64b-40bf-95cb-5818aa9b7cc7"
          }
        ],
        "partitions": [
          {
            "name": "_Medidas",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = #table(type table [Medidas = text], {{\"Guía 07 v4\"}})",
                "in",
                "    Origen"
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}