{
  "compatibilityLevel": 1606,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"m_distritos\",\"m_clientes\",\"m_cuentas\",\"m_anios\",\"m_meses\",\"m_prestamos\",\"m_ordenes\",\"m_trans_anual\",\"m_saldo_mensual\",\"m_recomendaciones\",\"m_dim_producto\",\"m_recomendacion_producto\",\"m_adopcion_producto\",\"m_capacidad_prestamo\",\"m_evaluacion_recomendador\",\"m_asociacion_producto\",\"m_regla_capacidad\",\"Composicion_Liquidez\",\"_Medidas\",\"MongoFinancial\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "es-ES",
    "cultures": [
      {
        "name": "es-ES",
        "linguisticMetadata": {
          "content": {
            "Entities": {
              "composicion_liquidez.concepto": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Composicion_Liquidez",
                    "ConceptualProperty": "concepto"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Concepto": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "m_anios.anio": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "m_anios",
                    "ConceptualProperty": "anio"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Año de otorgamiento": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  },
                  {
                    "Año": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "m_asociacion_producto.producto_destino": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "m_asociacion_producto",
                    "ConceptualProperty": "producto_destino"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "…también tiene": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "m_asociacion_producto.producto_origen": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "m_asociacion_producto",
                    "ConceptualProperty": "producto_origen"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Si ya tiene…": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "m_capacidad_prestamo.tramo_monto_36m": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "m_capacidad_prestamo",
                    "ConceptualProperty": "tramo_monto_36m"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Monto máximo a 36 meses": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "m_clientes.arquetipo_demografico": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "m_clientes",
                    "ConceptualProperty": "arquetipo_demografico"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Arquetipo": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "m_clientes.cliente": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "m_clientes",
                    "ConceptualProperty": "cliente"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Cliente": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  },
                  {
                    "Titular": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "m_clientes.segmento_edad": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "m_clientes",
                    "ConceptualProperty": "segmento_edad"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Segmento de edad": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "m_dim_producto.producto": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "m_dim_producto",
                    "ConceptualProperty": "producto"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Producto": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "m_distritos.nombre_distrito": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "m_distritos",
                    "ConceptualProperty": "nombre_distrito"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Distrito": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "m_distritos.region": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "m_distritos",
                    "ConceptualProperty": "region"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Región": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "m_evaluacion_recomendador.modelo": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "m_evaluacion_recomendador",
                    "ConceptualProperty": "modelo"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Modelo": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "m_meses.fecha_mes": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "m_meses",
                    "ConceptualProperty": "fecha_mes"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Mes": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "m_ordenes.categoria_orden": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "m_ordenes",
                    "ConceptualProperty": "categoria_orden"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Propósito": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "m_prestamos.banda_capacidad": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "m_prestamos",
                    "ConceptualProperty": "banda_capacidad"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Banda de capacidad (cuota / saldo previo)": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  },
                  {
                    "Banda de capacidad": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "m_prestamos.estado": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "m_prestamos",
                    "ConceptualProperty": "estado"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Estado": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "m_recomendaciones.recomendacion_1": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "m_recomendaciones",
                    "ConceptualProperty": "recomendacion_1"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "1.ª oferta": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "m_recomendaciones.recomendacion_2": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "m_recomendaciones",
                    "ConceptualProperty": "recomendacion_2"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "2.ª": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "m_recomendaciones.recomendacion_3": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "m_recomendaciones",
                    "ConceptualProperty": "recomendacion_3"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "3.ª": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "m_regla_capacidad.regla": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "m_regla_capacidad",
                    "ConceptualProperty": "regla"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Regla": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "m_trans_anual.categoria_analitica": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "m_trans_anual",
                    "ConceptualProperty": "categoria_analitica"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Categoría": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.absorcion_banco": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Absorcion Banco"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Banco": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.absorcion_vigente": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Absorcion Vigente"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Absorción vigente": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.acierto_hit1": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Acierto Hit1"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Acierto (Hit@1)": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.arquetipo_cliente": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Arquetipo Cliente"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Arquetipo": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.auc_regla": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "AUC Regla"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "AUC": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.banda_capacidad": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Banda Capacidad"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Banda de capacidad": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.banda_capacidad_impago": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Banda Capacidad Impago"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Banda de capacidad": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.calificacion_cliente": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Calificacion Cliente"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Calificación de pago": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.cartera_total": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Cartera Total"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Monto": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  },
                  {
                    "Monto del préstamo": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.cartera_vigente": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Cartera Vigente"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Cartera vigente": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.compromiso_alerta": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Compromiso Alerta"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Órdenes mensuales": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.compromiso_ordenes": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Compromiso Ordenes"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Órdenes mensuales": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  },
                  {
                    "Monto mensual": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.credito_externo_alerta": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Credito Externo Alerta"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Crédito externo mensual": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.credito_externo_mensual": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Credito Externo Mensual"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Crédito externo mensual": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.cuenta_alerta": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Cuenta Alerta"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Cuenta": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.cuentas_en_sobregiro": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Cuentas en Sobregiro"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Cuentas en sobregiro": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.cuentas_que_ya_lo_usan": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Cuentas que ya lo Usan"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Ya lo usan": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.cuota_maxima_prudente": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Cuota Maxima Prudente"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Cuota préstamo máx.": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  },
                  {
                    "Cuota máx. préstamo": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.cuota_mensual": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Cuota Mensual"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Cuota": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.cuota_prudente_oferta": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Cuota Prudente Oferta"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Cuota máx.": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.descubrimiento_knn": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Descubrimiento kNN"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Además, ofrecer": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  },
                  {
                    "Además (kNN)": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.descubrimientos_knn": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Descubrimientos kNN"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Ofertas nuevas": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.desempleo_distrito_1995": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Desempleo Distrito 1995"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Desempleo 1995 (%)": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.distrito_cuenta": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Distrito Cuenta"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Distrito de la cuenta": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.distrito_impago": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Distrito Impago"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Distrito": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.edad_cliente": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Edad Cliente"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Edad": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.estado_prestamo": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Estado Prestamo"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Estado": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  },
                  {
                    "Préstamo": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.indice_saturacion": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Indice Saturacion"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Índice de saturación": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.indice_saturacion_alerta": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Indice Saturacion Alerta"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Índice de saturación": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.monto_12m_oferta": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Monto 12m Oferta"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "12 meses": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.monto_36m_oferta": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Monto 36m Oferta"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "36 meses": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.monto_60m_oferta": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Monto 60m Oferta"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "60 meses": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.monto_incumplido": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Monto Incumplido"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Monto del préstamo B": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.monto_maximo_prudente": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Monto Maximo Prudente"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Monto máx. (36 m)": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.monto_prudente_ofrecible_36m": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Monto Prudente Ofrecible 36m"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Monto a 36 meses": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.mora_wilson_inferior": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Mora Wilson Inferior"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Wilson inf.": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.mora_wilson_superior": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Mora Wilson Superior"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Wilson sup.": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.num_ordenes": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Num Ordenes"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Órdenes": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.num_prestamos": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Num Prestamos"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Préstamos otorgados": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  },
                  {
                    "Préstamos": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.origen_indicadores": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Origen Indicadores"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Indicadores": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.poblacion_distrito": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Poblacion Distrito"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Población": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.prestamos_en_mora": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Prestamos en Mora"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "En mora": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.prestamos_vigentes": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Prestamos Vigentes"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Vigentes (n)": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  },
                  {
                    "Vigentes": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.recomendacion_1": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Recomendacion 1"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "1.ª oferta": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  },
                  {
                    "Oferta principal": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.recomendacion_2": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Recomendacion 2"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "2.ª": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.recomendacion_3": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Recomendacion 3"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "3.ª": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.recomendaciones_demograficas": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Recomendaciones Demograficas"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Recomendado (top 3)": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.salario_promedio_distrito": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Salario Promedio Distrito"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Salario promedio": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.saldo_neto_corte": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Saldo Neto Corte"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Saldo neto al cierre": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  },
                  {
                    "Saldo al cierre": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.saldo_promedio_alerta": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Saldo Promedio Alerta"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Saldo promedio": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.saldo_promedio_banco": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Saldo Promedio Banco"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Banco": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.saldo_promedio_historico": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Saldo Promedio Historico"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Saldo promedio de la cuenta": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.saldo_promedio_oferta": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Saldo Promedio Oferta"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Saldo promedio": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.saldo_promedio_por_cuenta": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Saldo Promedio por Cuenta"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Saldo promedio por cuenta": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  },
                  {
                    "Distrito": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.segmento_cliente": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Segmento Cliente"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Segmento": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.tasa_impago": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Tasa Impago"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Tasa de impago (B o D)": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  },
                  {
                    "Tasa de impago": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.tasa_impago_banco": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Tasa Impago Banco"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Banco": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.tasa_incumplimiento": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Tasa Incumplimiento"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Tasa de incumplimiento": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.tasa_incumplimiento_banco": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Tasa Incumplimiento Banco"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Banco": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.tasa_mora_banco": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Tasa Mora Banco"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Banco": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.tasa_mora_vigente": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Tasa Mora Vigente"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Tasa de mora de la cosecha": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  },
                  {
                    "Tasa de mora": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  },
                  {
                    "Tasa": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  },
                  {
                    "Tasa de mora vigente": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.ticket_promedio": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Ticket Promedio"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Ticket promedio": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.titulares_sin_prestamo": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Titulares sin Prestamo"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Titulares sin préstamo": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.umbral_sobregiro": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Umbral Sobregiro"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Cero": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.valor_composicion_liquidez": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Valor Composicion Liquidez"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Monto": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table_medidas.volumen_transaccionado": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Medidas",
                    "ConceptualProperty": "Volumen Transaccionado"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Volumen": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              }
            },
            "Language": "en-US",
            "Version": "2.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "MongoFinancial",
        "expression": [
          "let",
          "    Origen = Python.Execute(\"\"\"\"\"\"\"#(lf)==============================================================================#(lf)UNIVERSIDAD TÉCNICA DE AMBATO - Inteligencia de Negocios#(lf)AUTORES: Alison Marcela Cobos Taco / Henry Daniel Lagua Flores#(lf)==============================================================================#(lf)ARCHIVO: 26_powerbi_mongo_dashboard.py   (Guía 07 v4)#(lf)USO EN POWER BI: el script 30 lo incrusta en la consulta MongoFinancial del#(lf)                 proyecto Dashboard_Financial_Mongo.pbip. También se puede#(lf)                 ejecutar suelto para revisar las tablas.#(lf)#(lf)Construye, desde la base documental 'Financial' (cargada por el script 35 y#(lf)completada por el 42), las mismas tablas que el modelo Kimball, con los mismos#(lf)nombres de columnas, para que las medidas DAX sean idénticas:#(lf)#(lf)  m_distritos         77   (Dim_Distrito)#(lf)  m_clientes       5,369   (Dim_Cliente)#(lf)  m_cuentas        4,500   (Dim_Cuenta)#(lf)  m_anios              6   (Dim_Anio)#(lf)  m_meses             72   (meses de la foto de saldos)#(lf)  m_prestamos        682   (Fact_Prestamos)#(lf)  m_ordenes        6,471   (Fact_Ordenes)#(lf)  m_trans_anual   54,298   (vw_PBI_Trans_Anual_Cuenta: agregado en MongoDB con $group)#(lf)  m_saldo_mensual 185,615  (Fact_Saldo_Cuenta_Mensual)#(lf)  m_recomendaciones 4,500  (Recomendacion_Cuenta)#(lf)  Recomendadores del dashboard (páginas R1–R3, script 43):#(lf)  m_dim_producto 8 · m_recomendacion_producto 26,986 · m_adopcion_producto 8,604 ·#(lf)  m_capacidad_prestamo 4,500 · m_evaluacion_recomendador 8 · m_asociacion_producto 56 · m_regla_capacidad 7#(lf)==============================================================================#(lf)\"\"\"\"\"\"#(lf)import pandas as pd#(lf)import pymongo#(lf)#(lf)MONGO_URI = \"\"mongodb://localhost:27017/\"\"#(lf)DB_NAME = \"\"Financial\"\"#(lf)#(lf)client = pymongo.MongoClient(MONGO_URI)#(lf)db = client[DB_NAME]#(lf)#(lf)#(lf)def macro(region):#(lf)    return \"\"Praga\"\" if region == \"\"Prague\"\" else (\"\"Moravia\"\" if \"\"Moravia\"\" in str(region) else \"\"Bohemia\"\")#(lf)#(lf)#(lf)# ---- Dimensiones ----#(lf)m_distritos = pd.DataFrame([{#(lf)    \"\"id_distrito\"\": d[\"\"id_distrito\"\"], \"\"nombre_distrito\"\": d[\"\"nombre\"\"], \"\"region\"\": d[\"\"region\"\"], \"\"poblacion\"\": d[\"\"poblacion\"\"],#(lf)    \"\"salario_promedio\"\": d[\"\"salario_promedio\"\"], \"\"tasa_desempleo\"\": d[\"\"indicadores_1995\"\"][\"\"tasa_desempleo\"\"],#(lf)    \"\"tasa_criminalidad\"\": d[\"\"indicadores_1995\"\"][\"\"tasa_criminalidad\"\"], \"\"es_imputado\"\": d[\"\"auditoria\"\"][\"\"es_imputado\"\"],#(lf)} for d in db.distritos.find({})])#(lf)m_distritos[\"\"macro_region\"\"] = m_distritos.region.map(macro)#(lf)#(lf)filas_cli, filas_cta = [], {}#(lf)for c in db.FinancialMongo.find({}, {\"\"ordenes_recurrentes\"\": 0, \"\"prestamo_asociado\"\": 0}):#(lf)    filas_cli.append({#(lf)        \"\"id_cliente\"\": c[\"\"id_cliente\"\"], \"\"cliente\"\": f\"\"Cliente {c['id_cliente']}\"\", \"\"sexo\"\": c[\"\"datos_personales\"\"][\"\"sexo\"\"],#(lf)        \"\"edad_corte\"\": c[\"\"datos_personales\"\"][\"\"edad_al_corte_1998\"\"], \"\"tipo_disposicion\"\": c[\"\"datos_personales\"\"][\"\"tipo_disposicion\"\"],#(lf)        \"\"segmento_edad\"\": c[\"\"perfil_analitico\"\"][\"\"segmento_edad\"\"], \"\"arquetipo_demografico\"\": c[\"\"perfil_analitico\"\"][\"\"arquetipo_demografico\"\"],#(lf)        \"\"calificacion_pago\"\": c[\"\"evaluacion_crediticia\"\"][\"\"calificacion\"\"]})#(lf)    cta = c[\"\"cuenta\"\"]#(lf)    filas_cta[cta[\"\"id_cuenta\"\"]] = {\"\"id_cuenta\"\": cta[\"\"id_cuenta\"\"], \"\"frecuencia_extracto\"\": cta[\"\"frecuencia_extracto\"\"],#(lf)                                   \"\"fecha_apertura\"\": cta[\"\"fecha_apertura\"\"], \"\"tiene_credito_externo\"\": cta[\"\"tiene_credito_externo\"\"],#(lf)                                   \"\"monto_credito_externo\"\": cta[\"\"monto_credito_externo\"\"]}#(lf)m_clientes = pd.DataFrame(filas_cli)#(lf)# Columnas de orden de las categorías ordinales (Power BI ordena por ellas, no alfabéticamente)#(lf)m_clientes[\"\"orden_segmento\"\"] = m_clientes.segmento_edad.map(#(lf)    lambda s: 1 if \"\"Joven\"\" in s else (3 if \"\"Mayor\"\" in s else 2)).astype(\"\"int64\"\")#(lf)m_cuentas = pd.DataFrame(list(filas_cta.values()))#(lf)m_cuentas[\"\"fecha_apertura\"\"] = pd.to_datetime(m_cuentas.fecha_apertura)#(lf)m_anios = pd.DataFrame({\"\"anio\"\": range(1993, 1999)})#(lf)m_meses = pd.DataFrame({\"\"fecha_mes\"\": pd.date_range(\"\"1993-01-31\"\", \"\"1998-12-31\"\", freq=\"\"ME\"\")})#(lf)m_meses[\"\"anio\"\"] = m_meses.fecha_mes.dt.year#(lf)m_meses[\"\"mes\"\"] = m_meses.fecha_mes.dt.month#(lf)#(lf)# ---- Hechos ----#(lf)m_prestamos = pd.DataFrame([{#(lf)    \"\"id_prestamo\"\": p[\"\"id_prestamo\"\"], \"\"id_cuenta\"\": p[\"\"id_cuenta\"\"], \"\"id_cliente\"\": p[\"\"id_cliente\"\"], \"\"id_distrito\"\": p[\"\"id_distrito\"\"],#(lf)    \"\"fecha_otorgamiento\"\": p[\"\"condiciones\"\"][\"\"fecha_otorgamiento\"\"], \"\"anio\"\": p[\"\"anio\"\"], \"\"monto_prestamo\"\": p[\"\"condiciones\"\"][\"\"monto\"\"],#(lf)    \"\"plazo_meses\"\": p[\"\"condiciones\"\"][\"\"plazo_meses\"\"], \"\"pago_mensual\"\": p[\"\"condiciones\"\"][\"\"cuota_mensual\"\"],#(lf)    \"\"saldo_pendiente_estimado\"\": p[\"\"condiciones\"\"][\"\"saldo_pendiente_estimado\"\"],#(lf)    \"\"meses_transcurridos_al_corte\"\": p[\"\"condiciones\"\"][\"\"meses_transcurridos_al_corte\"\"],#(lf)    \"\"codigo_estado\"\": p[\"\"evaluacion_riesgo\"\"][\"\"codigo_estado\"\"], \"\"condicion\"\": p[\"\"evaluacion_riesgo\"\"][\"\"condicion\"\"],#(lf)    \"\"descripcion_estado\"\": p[\"\"evaluacion_riesgo\"\"][\"\"descripcion\"\"],#(lf)    \"\"saldo_promedio_previo\"\": p[\"\"capacidad_pago\"\"][\"\"saldo_promedio_previo\"\"],#(lf)    \"\"ratio_cuota_saldo_previo\"\": p[\"\"capacidad_pago\"\"][\"\"ratio_cuota_saldo_previo\"\"],#(lf)    \"\"banda_capacidad\"\": p[\"\"capacidad_pago\"\"][\"\"banda_capacidad\"\"],#(lf)} for p in db.prestamos.find({})])#(lf)m_prestamos[\"\"fecha_otorgamiento\"\"] = pd.to_datetime(m_prestamos.fecha_otorgamiento)#(lf)m_prestamos[\"\"orden_banda\"\"] = m_prestamos.banda_capacidad.map({\"\"Baja\"\": 1, \"\"Media-baja\"\": 2, \"\"Media-alta\"\": 3, \"\"Alta\"\": 4}).astype(\"\"int64\"\")#(lf)#(lf)m_ordenes = pd.DataFrame([{#(lf)    \"\"id_orden\"\": o[\"\"id_orden\"\"], \"\"id_cuenta\"\": o[\"\"id_cuenta\"\"], \"\"id_cliente\"\": o[\"\"id_cliente\"\"], \"\"id_distrito\"\": o[\"\"id_distrito\"\"],#(lf)    \"\"k_symbol\"\": o[\"\"categoria_pago\"\"][\"\"codigo\"\"], \"\"categoria_orden\"\": o[\"\"categoria_pago\"\"][\"\"descripcion\"\"], \"\"monto_orden\"\": o[\"\"monto_mensual\"\"],#(lf)} for o in db.ordenes.find({})])#(lf)#(lf)# Agregado anual por cuenta y categoría, calculado DENTRO de MongoDB#(lf)m_trans_anual = pd.json_normalize(list(db.transacciones.aggregate([#(lf)    {\"\"$group\"\": {\"\"_id\"\": {\"\"id_cuenta\"\": \"\"$id_cuenta\"\", \"\"anio\"\": \"\"$anio\"\", \"\"categoria_analitica\"\": \"\"$tipo_operacion_traducido\"\"},#(lf)                \"\"id_cliente\"\": {\"\"$first\"\": \"\"$id_cliente\"\"}, \"\"id_distrito\"\": {\"\"$first\"\": \"\"$id_distrito\"\"},#(lf)                \"\"num_transacciones\"\": {\"\"$sum\"\": 1}, \"\"monto_total\"\": {\"\"$sum\"\": \"\"$monto_transaccion\"\"},#(lf)                \"\"suma_cuadrados\"\": {\"\"$sum\"\": {\"\"$multiply\"\": [\"\"$monto_transaccion\"\", \"\"$monto_transaccion\"\"]}},#(lf)                \"\"saldo_promedio\"\": {\"\"$avg\"\": \"\"$saldo_cuenta\"\"}}}], allowDiskUse=True)))#(lf)m_trans_anual.columns = [c.replace(\"\"_id.\"\", \"\"\"\") for c in m_trans_anual.columns]#(lf)#(lf)m_saldo_mensual = pd.DataFrame(list(db.saldos_mensuales.find({}, {\"\"_id\"\": 0})))#(lf)m_saldo_mensual[\"\"fecha_mes\"\"] = pd.to_datetime(dict(year=m_saldo_mensual.anio, month=m_saldo_mensual.mes, day=1)) + pd.offsets.MonthEnd(0)#(lf)m_saldo_mensual[\"\"en_sobregiro\"\"] = m_saldo_mensual.en_sobregiro.astype(bool)#(lf)#(lf)m_recomendaciones = pd.DataFrame([{#(lf)    \"\"id_cuenta\"\": r[\"\"id_cuenta\"\"], \"\"id_cliente\"\": r[\"\"id_cliente\"\"], \"\"modelo\"\": r[\"\"modelo\"\"],#(lf)    \"\"recomendacion_1\"\": (r[\"\"recomendaciones\"\"] + [None] * 3)[0], \"\"recomendacion_2\"\": (r[\"\"recomendaciones\"\"] + [None] * 3)[1],#(lf)    \"\"recomendacion_3\"\": (r[\"\"recomendaciones\"\"] + [None] * 3)[2],#(lf)    \"\"prestamo_cuota_maxima\"\": r[\"\"prestamo_cuota_maxima\"\"], \"\"prestamo_monto_maximo_36m\"\": r[\"\"prestamo_monto_maximo_36m\"\"],#(lf)} for r in db.recomendaciones.find({})])#(lf)#(lf)# ---- Recomendadores del dashboard (script 43): mismas columnas que las tablas de Kimball ----#(lf)def coleccion(nombre):#(lf)    return pd.DataFrame(list(db[nombre].find({}, {\"\"_id\"\": 0})))#(lf)#(lf)#(lf)m_dim_producto = coleccion(\"\"dim_producto\"\")#(lf)m_recomendacion_producto = coleccion(\"\"recomendacion_producto\"\")#(lf)m_adopcion_producto = coleccion(\"\"adopcion_producto\"\")#(lf)m_capacidad_prestamo = coleccion(\"\"capacidad_prestamo\"\")#(lf)m_evaluacion_recomendador = coleccion(\"\"evaluacion_recomendador\"\")#(lf)m_asociacion_producto = coleccion(\"\"asociacion_producto\"\")#(lf)m_regla_capacidad = coleccion(\"\"regla_capacidad\"\")#(lf)#(lf)# El puente Python de Power BI no reconoce StringDtype (pandas >= 3) ni fechas en microsegundos#(lf)for df in (m_meses, m_distritos, m_clientes, m_cuentas, m_prestamos, m_ordenes, m_trans_anual, m_saldo_mensual, m_recomendaciones,#(lf)           m_dim_producto, m_recomendacion_producto, m_adopcion_producto, m_capacidad_prestamo, m_evaluacion_recomendador,#(lf)           m_asociacion_producto, m_regla_capacidad):#(lf)    for col in df.columns:#(lf)        if pd.api.types.is_string_dtype(df[col]) and not pd.api.types.is_object_dtype(df[col]):#(lf)            df[col] = df[col].astype(object)#(lf)        elif pd.api.types.is_datetime64_any_dtype(df[col]):#(lf)            df[col] = df[col].astype(\"\"datetime64[ns]\"\")   # resolución que espera el puente de Power BI#(lf)#(lf)client.close()#(lf)#(lf)print(\"\"Tablas MongoDB listas para Power BI:\"\")#(lf)for nombre in [\"\"m_distritos\"\", \"\"m_clientes\"\", \"\"m_cuentas\"\", \"\"m_anios\"\", \"\"m_meses\"\", \"\"m_prestamos\"\", \"\"m_ordenes\"\",#(lf)               \"\"m_trans_anual\"\", \"\"m_saldo_mensual\"\", \"\"m_recomendaciones\"\", \"\"m_dim_producto\"\", \"\"m_recomendacion_producto\"\",#(lf)               \"\"m_adopcion_producto\"\", \"\"m_capacidad_prestamo\"\", \"\"m_evaluacion_recomendador\"\", \"\"m_asociacion_producto\"\",#(lf)               \"\"m_regla_capacidad\"\"]:#(lf)    print(f\"\"  - {nombre:<26} {len(globals()[nombre]):>8,} filas\"\")#(lf)\")",
          "in",
          "    Origen"
        ],
        "kind": "m",
        "lineageTag": "f5b9ed27-40ca-4893-ae3a-eccd6c9b547e"
      }
    ],
    "relationships": [
      {
        "name": "ccfd1686-3f3d-54ff-92c3-909777769fb4",
        "fromColumn": "id_distrito",
        "fromTable": "m_prestamos",
        "toColumn": "id_distrito",
        "toTable": "m_distritos"
      },
      {
        "name": "dc395a79-c617-57dd-9974-7fe68c0212e8",
        "fromColumn": "id_cliente",
        "fromTable": "m_prestamos",
        "toColumn": "id_cliente",
        "toTable": "m_clientes"
      },
      {
        "name": "bfbef033-10b6-5ed6-b6b5-cf6c9a98602f",
        "fromColumn": "id_cuenta",
        "fromTable": "m_prestamos",
        "toColumn": "id_cuenta",
        "toTable": "m_cuentas"
      },
      {
        "name": "b5db8dde-0944-5db4-bb17-d1363237647c",
        "fromColumn": "id_distrito",
        "fromTable": "m_ordenes",
        "toColumn": "id_distrito",
        "toTable": "m_distritos"
      },
      {
        "name": "89407216-f1b9-5356-b36a-b25e2766f75e",
        "fromColumn": "id_cliente",
        "fromTable": "m_ordenes",
        "toColumn": "id_cliente",
        "toTable": "m_clientes"
      },
      {
        "name": "7b0de087-a93f-508c-9ec4-b1e688e13b82",
        "fromColumn": "id_cuenta",
        "fromTable": "m_ordenes",
        "toColumn": "id_cuenta",
        "toTable": "m_cuentas"
      },
      {
        "name": "acbc0c28-7838-51c5-ad2d-c28a2b5c3788",
        "fromColumn": "id_distrito",
        "fromTable": "m_trans_anual",
        "toColumn": "id_distrito",
        "toTable": "m_distritos"
      },
      {
        "name": "59e4f306-68b4-5338-b1db-dde585c17cef",
        "fromColumn": "id_cliente",
        "fromTable": "m_trans_anual",
        "toColumn": "id_cliente",
        "toTable": "m_clientes"
      },
      {
        "name": "021ab3cc-68f0-5844-8870-7664757bf485",
        "fromColumn": "id_cuenta",
        "fromTable": "m_trans_anual",
        "toColumn": "id_cuenta",
        "toTable": "m_cuentas"
      },
      {
        "name": "18eb1775-fc7a-54c5-b65b-caff6dac8d04",
        "fromColumn": "id_distrito",
        "fromTable": "m_saldo_mensual",
        "toColumn": "id_distrito",
        "toTable": "m_distritos"
      },
      {
        "name": "ef991d89-1861-571d-ae10-0675c7e70ad5",
        "fromColumn": "id_cliente",
        "fromTable": "m_saldo_mensual",
        "toColumn": "id_cliente",
        "toTable": "m_clientes"
      },
      {
        "name": "01c79f9c-9b80-5264-9c0f-71bfc1472d20",
        "fromColumn": "id_cuenta",
        "fromTable": "m_saldo_mensual",
        "toColumn": "id_cuenta",
        "toTable": "m_cuentas"
      },
      {
        "name": "3134aef8-9ae9-58bd-b3d0-322762c06c56",
        "fromColumn": "anio",
        "fromTable": "m_prestamos",
        "toColumn": "anio",
        "toTable": "m_anios"
      },
      {
        "name": "08e82454-92f8-512a-a7ed-4b560d010664",
        "fromColumn": "anio",
        "fromTable": "m_trans_anual",
        "toColumn": "anio",
        "toTable": "m_anios"
      },
      {
        "name": "9a2ab26c-0fe3-5704-abf1-888d3ab58885",
        "fromColumn": "fecha_mes",
        "fromTable": "m_saldo_mensual",
        "toColumn": "fecha_mes",
        "toTable": "m_meses"
      },
      {
        "name": "3493831f-136e-5d57-8175-8525d9bac77b",
        "fromColumn": "anio",
        "fromTable": "m_meses",
        "toColumn": "anio",
        "toTable": "m_anios"
      },
      {
        "name": "b5efc4fc-b6ba-5770-9c55-6ef5d4a3325b",
        "fromColumn": "id_cuenta",
        "fromTable": "m_recomendaciones",
        "toColumn": "id_cuenta",
        "toTable": "m_cuentas"
      },
      {
        "name": "a2208bfe-ae88-5b79-9765-8b0cf9d3cc23",
        "fromColumn": "id_cliente",
        "fromTable": "m_recomendaciones",
        "toColumn": "id_cliente",
        "toTable": "m_clientes"
      },
      {
        "name": "8866cd53-48cf-543e-b045-1a55ab527486",
        "fromColumn": "id_cuenta",
        "fromTable": "m_recomendacion_producto",
        "toColumn": "id_cuenta",
        "toTable": "m_cuentas"
      },
      {
        "name": "9ce5a379-b8f3-51fc-a539-453d04858c5b",
        "fromColumn": "id_cliente",
        "fromTable": "m_recomendacion_producto",
        "toColumn": "id_cliente",
        "toTable": "m_clientes"
      },
      {
        "name": "a6cc9434-d727-5ec6-af76-c8b0a433f27f",
        "fromColumn": "id_distrito",
        "fromTable": "m_recomendacion_producto",
        "toColumn": "id_distrito",
        "toTable": "m_distritos"
      },
      {
        "name": "9b3fc0a7-2502-5ef1-9733-69d6e9ebafdc",
        "fromColumn": "id_cuenta",
        "fromTable": "m_adopcion_producto",
        "toColumn": "id_cuenta",
        "toTable": "m_cuentas"
      },
      {
        "name": "cb62478a-1c11-5d3d-a26e-80e0f3bfa935",
        "fromColumn": "id_cliente",
        "fromTable": "m_adopcion_producto",
        "toColumn": "id_cliente",
        "toTable": "m_clientes"
      },
      {
        "name": "5f9d5e6b-5d2b-5e66-8d14-49b553bd4aad",
        "fromColumn": "id_distrito",
        "fromTable": "m_adopcion_producto",
        "toColumn": "id_distrito",
        "toTable": "m_distritos"
      },
      {
        "name": "2a2a4816-5936-5c00-a613-4182bf2b645e",
        "fromColumn": "id_cuenta",
        "fromTable": "m_capacidad_prestamo",
        "toColumn": "id_cuenta",
        "toTable": "m_cuentas"
      },
      {
        "name": "fe5044f4-0a1e-5826-aaca-f1b6a329d6fd",
        "fromColumn": "id_cliente",
        "fromTable": "m_capacidad_prestamo",
        "toColumn": "id_cliente",
        "toTable": "m_clientes"
      },
      {
        "name": "9be58e01-8d93-54bd-ba52-b52ba76274e4",
        "fromColumn": "id_distrito",
        "fromTable": "m_capacidad_prestamo",
        "toColumn": "id_distrito",
        "toTable": "m_distritos"
      },
      {
        "name": "3e66a75f-1732-5383-aa46-5f3e858b2374",
        "fromColumn": "producto",
        "fromTable": "m_recomendacion_producto",
        "toColumn": "producto",
        "toTable": "m_dim_producto"
      },
      {
        "name": "b28d83ff-bf22-5b43-947b-021f7e184b4a",
        "fromColumn": "producto",
        "fromTable": "m_adopcion_producto",
        "toColumn": "producto",
        "toTable": "m_dim_producto"
      }
    ],
    "sourceQueryCulture": "es-ES",
    "tables": [
      {
        "name": "m_distritos",
        "columns": [
          {
            "name": "id_distrito",
            "dataType": "int64",
            "lineageTag": "bd0a093a-1f7a-4a7d-ac83-9bec0d8d3090",
            "sourceColumn": "id_distrito",
            "summarizeBy": "none"
          },
          {
            "name": "nombre_distrito",
            "dataType": "string",
            "lineageTag": "37a5a4d0-bbe7-4cb2-a59b-fa698ef20833",
            "sourceColumn": "nombre_distrito",
            "summarizeBy": "none"
          },
          {
            "name": "region",
            "dataType": "string",
            "lineageTag": "d667daba-cc44-4906-b8bd-8b9bc7f40dee",
            "sourceColumn": "region",
            "summarizeBy": "none"
          },
          {
            "name": "poblacion",
            "dataType": "int64",
            "lineageTag": "1d46ce92-468d-4261-b0d1-687df4534be7",
            "sourceColumn": "poblacion",
            "summarizeBy": "none"
          },
          {
            "name": "salario_promedio",
            "dataType": "double",
            "formatString": "\"$\"#,0",
            "lineageTag": "e69f80c3-801c-4a5a-ac62-7c1e6c45720a",
            "sourceColumn": "salario_promedio",
            "summarizeBy": "none"
          },
          {
            "name": "tasa_desempleo",
            "dataType": "double",
            "formatString": "0.00",
            "lineageTag": "010378d8-1666-454b-9134-51c3f3a322d9",
            "sourceColumn": "tasa_desempleo",
            "summarizeBy": "none"
          },
          {
            "name": "tasa_criminalidad",
            "dataType": "double",
            "formatString": "0.00",
            "lineageTag": "2ff51fad-d46f-4a96-ad59-e43328851aea",
            "sourceColumn": "tasa_criminalidad",
            "summarizeBy": "none"
          },
          {
            "name": "es_imputado",
            "dataType": "boolean",
            "lineageTag": "d258915d-6e7c-4a0b-a8f4-3dec6e8e7a0e",
            "sourceColumn": "es_imputado",
            "summarizeBy": "none"
          },
          {
            "name": "macro_region",
            "dataType": "string",
            "lineageTag": "9a53f019-95d7-40cb-b323-25bcef6f4e5c",
            "sourceColumn": "macro_region",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "a93b89fc-b8f7-46a6-b440-33e0eaf91c5d",
        "partitions": [
          {
            "name": "m_distritos",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = MongoFinancial,",
                "    Tabla = Origen{[Name=\"m_distritos\"]}[Value],",
                "    Columnas = Table.SelectColumns(Tabla, {\"id_distrito\", \"nombre_distrito\", \"region\", \"poblacion\", \"salario_promedio\", \"tasa_desempleo\", \"tasa_criminalidad\", \"es_imputado\", \"macro_region\"}),",
                "    Tipos = Table.TransformColumnTypes(Columnas, {{\"id_distrito\", Int64.Type}, {\"nombre_distrito\", type text}, {\"region\", type text}, {\"poblacion\", Int64.Type}, {\"salario_promedio\", type number}, {\"tasa_desempleo\", type number}, {\"tasa_criminalidad\", type number}, {\"es_imputado\", type logical}, {\"macro_region\", type text}}, \"en-US\")",
                "in",
                "    Tipos"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "m_clientes",
        "columns": [
          {
            "name": "id_cliente",
            "dataType": "int64",
            "lineageTag": "1c2580a0-e04b-4d90-810e-294f7514f175",
            "sourceColumn": "id_cliente",
            "summarizeBy": "none"
          },
          {
            "name": "cliente",
            "dataType": "string",
            "lineageTag": "f9b2cf1d-84e3-4027-a9a5-6e08c08bb632",
            "sourceColumn": "cliente",
            "summarizeBy": "none"
          },
          {
            "name": "sexo",
            "dataType": "string",
            "lineageTag": "e8d2fbeb-b9ac-4361-b0e5-57a40e21ed76",
            "sourceColumn": "sexo",
            "summarizeBy": "none"
          },
          {
            "name": "edad_corte",
            "dataType": "int64",
            "lineageTag": "3105bc4d-9a56-47ed-9950-ff21d3ffa40a",
            "sourceColumn": "edad_corte",
            "summarizeBy": "none"
          },
          {
            "name": "tipo_disposicion",
            "dataType": "string",
            "lineageTag": "9a6730fa-f7b5-457c-ac99-0223c4eb7a38",
            "sourceColumn": "tipo_disposicion",
            "summarizeBy": "none"
          },
          {
            "name": "segmento_edad",
            "dataType": "string",
            "lineageTag": "a3647feb-4440-48a5-9b7c-696d3c629548",
            "sortByColumn": "orden_segmento",
            "sourceColumn": "segmento_edad",
            "summarizeBy": "none"
          },
          {
            "name": "arquetipo_demografico",
            "dataType": "string",
            "lineageTag": "1a8a8086-7c05-4c19-972c-3a8cb51e1d88",
            "sourceColumn": "arquetipo_demografico",
            "summarizeBy": "none"
          },
          {
            "name": "calificacion_pago",
            "dataType": "string",
            "lineageTag": "146dc6bd-675a-477f-b531-c79b508c5874",
            "sourceColumn": "calificacion_pago",
            "summarizeBy": "none"
          },
          {
            "name": "orden_segmento",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "a351fe63-4f40-4bf2-a959-d5c1b47c740f",
            "sourceColumn": "orden_segmento",
            "summarizeBy": "none"
          },
          {
            "name": "Estado del Prestamo",
            "dataType": "string",
            "expression": "VAR e = CALCULATE(MAX(m_prestamos[estado]), CALCULATETABLE(m_prestamos)) RETURN IF(ISBLANK(e), \"Sin préstamo\", e)",
            "lineageTag": "2fa1964a-1ed7-4a6e-8f79-54d607287d8a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Banda de Capacidad",
            "dataType": "string",
            "expression": "VAR b = CALCULATE(MAX(m_prestamos[banda_capacidad]), CALCULATETABLE(m_prestamos)) RETURN IF(ISBLANK(b), \"Sin préstamo\", b)",
            "lineageTag": "640a0d6c-a83f-4a65-aea8-3c15ea15977b",
            "sortByColumn": "Orden Banda Cliente",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Orden Banda Cliente",
            "dataType": "int64",
            "expression": "VAR o = CALCULATE(MAX(m_prestamos[orden_banda]), CALCULATETABLE(m_prestamos)) RETURN IF(ISBLANK(o), 5, o)",
            "isHidden": true,
            "lineageTag": "93a0c58c-b8d7-4ffb-9535-c17849e3a24b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Alerta de Saturacion",
            "dataType": "string",
            "expression": "VAR i = [Indice Saturacion] RETURN SWITCH(TRUE(), ISBLANK(i), \"Sin órdenes\", i > 1, \"Crítica (> 1)\", i > 0.5, \"Alta (> 0.5)\", \"Normal\")",
            "lineageTag": "5956308f-3e3f-4cf3-ab42-d40d28dfa44f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Primera Oferta",
            "dataType": "string",
            "expression": "VAR x = CALCULATE(MAX(m_recomendacion_producto[producto]), m_recomendacion_producto[sistema] = \"Demográfico\", m_recomendacion_producto[posicion] = 1) RETURN IF(ISBLANK(x), \"Sin recomendación\", x)",
            "lineageTag": "a6ef13da-ec03-48cb-8a78-8c42d5bea806",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Prestamo Recomendado",
            "dataType": "string",
            "expression": "IF(CALCULATE(COUNTROWS(m_capacidad_prestamo)) = 0, \"Sin cuenta propia\", IF(CALCULATE(COUNTROWS(m_capacidad_prestamo), m_capacidad_prestamo[prestamo_recomendado] = TRUE()) > 0, \"Sí\", \"No\"))",
            "lineageTag": "41a71c19-19a3-42fb-8911-eab518d65275",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "a49430de-c774-4aab-928c-6b13b93b32ee",
        "partitions": [
          {
            "name": "m_clientes",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = MongoFinancial,",
                "    Tabla = Origen{[Name=\"m_clientes\"]}[Value],",
                "    Columnas = Table.SelectColumns(Tabla, {\"id_cliente\", \"cliente\", \"sexo\", \"edad_corte\", \"tipo_disposicion\", \"segmento_edad\", \"arquetipo_demografico\", \"calificacion_pago\", \"orden_segmento\"}),",
                "    Tipos = Table.TransformColumnTypes(Columnas, {{\"id_cliente\", Int64.Type}, {\"cliente\", type text}, {\"sexo\", type text}, {\"edad_corte\", Int64.Type}, {\"tipo_disposicion\", type text}, {\"segmento_edad\", type text}, {\"arquetipo_demografico\", type text}, {\"calificacion_pago\", type text}, {\"orden_segmento\", Int64.Type}}, \"en-US\")",
                "in",
                "    Tipos"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "m_cuentas",
        "columns": [
          {
            "name": "id_cuenta",
            "dataType": "int64",
            "lineageTag": "3e36f132-3d20-4ba4-87c9-27e9f406f674",
            "sourceColumn": "id_cuenta",
            "summarizeBy": "none"
          },
          {
            "name": "frecuencia_extracto",
            "dataType": "string",
            "lineageTag": "b9934734-e2a6-4717-b12e-6f73c00e12a3",
            "sourceColumn": "frecuencia_extracto",
            "summarizeBy": "none"
          },
          {
            "name": "fecha_apertura",
            "dataType": "dateTime",
            "formatString": "dd/mm/yyyy",
            "lineageTag": "28304574-804a-49ba-bf58-fd67b4a43b27",
            "sourceColumn": "fecha_apertura",
            "summarizeBy": "none"
          },
          {
            "name": "tiene_credito_externo",
            "dataType": "boolean",
            "lineageTag": "e9b9b33f-b296-4312-af30-490c01e05a3c",
            "sourceColumn": "tiene_credito_externo",
            "summarizeBy": "none"
          },
          {
            "name": "monto_credito_externo",
            "dataType": "double",
            "formatString": "\"$\"#,0",
            "lineageTag": "7ae99bb4-9db4-4ed2-969c-1c1a9ac0e064",
            "sourceColumn": "monto_credito_externo",
            "summarizeBy": "none"
          },
          {
            "name": "cuenta",
            "dataType": "string",
            "expression": "\"Cuenta \" & m_cuentas[id_cuenta]",
            "lineageTag": "e01161e0-1b58-40c5-827d-a737fdf35bf7",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "e0e08852-b711-4da2-a917-70bf89b4c641",
        "partitions": [
          {
            "name": "m_cuentas",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = MongoFinancial,",
                "    Tabla = Origen{[Name=\"m_cuentas\"]}[Value],",
                "    Columnas = Table.SelectColumns(Tabla, {\"id_cuenta\", \"frecuencia_extracto\", \"fecha_apertura\", \"tiene_credito_externo\", \"monto_credito_externo\"}),",
                "    Tipos = Table.TransformColumnTypes(Columnas, {{\"id_cuenta\", Int64.Type}, {\"frecuencia_extracto\", type text}, {\"fecha_apertura\", type datetime}, {\"tiene_credito_externo\", type logical}, {\"monto_credito_externo\", type number}}, \"en-US\")",
                "in",
                "    Tipos"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "m_anios",
        "columns": [
          {
            "name": "anio",
            "dataType": "int64",
            "lineageTag": "5630bee5-cbdd-435a-8a14-afa2ef65d5bf",
            "sourceColumn": "anio",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "a9c188c0-c0c0-4fa7-a134-d26054375ce6",
        "partitions": [
          {
            "name": "m_anios",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = MongoFinancial,",
                "    Tabla = Origen{[Name=\"m_anios\"]}[Value],",
                "    Columnas = Table.SelectColumns(Tabla, {\"anio\"}),",
                "    Tipos = Table.TransformColumnTypes(Columnas, {{\"anio\", Int64.Type}}, \"en-US\")",
                "in",
                "    Tipos"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "m_meses",
        "columns": [
          {
            "name": "fecha_mes",
            "dataType": "dateTime",
            "formatString": "dd/mm/yyyy",
            "lineageTag": "f0e3a0da-0d30-4720-8f96-bf8d1d1388be",
            "sourceColumn": "fecha_mes",
            "summarizeBy": "none"
          },
          {
            "name": "anio",
            "dataType": "int64",
            "lineageTag": "d1bdeaf1-74c3-4f1b-a0f9-5b7417675bd6",
            "sourceColumn": "anio",
            "summarizeBy": "none"
          },
          {
            "name": "mes",
            "dataType": "int64",
            "lineageTag": "d677357e-f71c-4122-93dc-8850bd498687",
            "sourceColumn": "mes",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "1ab76276-2fd6-4939-b3f9-b4f3ced3e158",
        "partitions": [
          {
            "name": "m_meses",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = MongoFinancial,",
                "    Tabla = Origen{[Name=\"m_meses\"]}[Value],",
                "    Columnas = Table.SelectColumns(Tabla, {\"fecha_mes\", \"anio\", \"mes\"}),",
                "    Tipos = Table.TransformColumnTypes(Columnas, {{\"fecha_mes\", type datetime}, {\"anio\", Int64.Type}, {\"mes\", Int64.Type}}, \"en-US\")",
                "in",
                "    Tipos"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "m_prestamos",
        "columns": [
          {
            "name": "id_prestamo",
            "dataType": "int64",
            "lineageTag": "c718e455-5ef6-4c89-8d05-a3c54c26bcab",
            "sourceColumn": "id_prestamo",
            "summarizeBy": "none"
          },
          {
            "name": "id_cuenta",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "63f982ca-1139-4b87-bb59-c9e6b096ba44",
            "sourceColumn": "id_cuenta",
            "summarizeBy": "none"
          },
          {
            "name": "id_cliente",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "cff6dc68-68f4-49b2-b65f-6ef34975bdd2",
            "sourceColumn": "id_cliente",
            "summarizeBy": "none"
          },
          {
            "name": "id_distrito",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "f0b776fe-9cc9-4db7-b7df-9bc4450b194e",
            "sourceColumn": "id_distrito",
            "summarizeBy": "none"
          },
          {
            "name": "fecha_otorgamiento",
            "dataType": "dateTime",
            "formatString": "dd/mm/yyyy",
            "lineageTag": "7209acb0-b30e-447b-a0e8-09d5206b2639",
            "sourceColumn": "fecha_otorgamiento",
            "summarizeBy": "none"
          },
          {
            "name": "anio",
            "dataType": "int64",
            "lineageTag": "1df8eeb7-2353-457b-b042-9d743a3fd939",
            "sourceColumn": "anio",
            "summarizeBy": "none"
          },
          {
            "name": "monto_prestamo",
            "dataType": "double",
            "formatString": "\"$\"#,0",
            "lineageTag": "f686bd10-86df-400e-94a3-6108134d832c",
            "sourceColumn": "monto_prestamo",
            "summarizeBy": "none"
          },
          {
            "name": "plazo_meses",
            "dataType": "int64",
            "lineageTag": "42a7114d-777e-4752-8db3-4cfe4018de5f",
            "sourceColumn": "plazo_meses",
            "summarizeBy": "none"
          },
          {
            "name": "pago_mensual",
            "dataType": "double",
            "formatString": "\"$\"#,0",
            "lineageTag": "d8f8cfb1-b972-4786-9349-793d83ffcdaf",
            "sourceColumn": "pago_mensual",
            "summarizeBy": "none"
          },
          {
            "name": "saldo_pendiente_estimado",
            "dataType": "double",
            "formatString": "\"$\"#,0",
            "lineageTag": "d91d3516-b866-47c4-a5aa-cf1ce22b27bc",
            "sourceColumn": "saldo_pendiente_estimado",
            "summarizeBy": "none"
          },
          {
            "name": "meses_transcurridos_al_corte",
            "dataType": "int64",
            "lineageTag": "ebe24ae2-3403-453d-a85a-995d8827447d",
            "sourceColumn": "meses_transcurridos_al_corte",
            "summarizeBy": "none"
          },
          {
            "name": "codigo_estado",
            "dataType": "string",
            "lineageTag": "d1092c34-3754-4293-b6bc-d6601219a900",
            "sourceColumn": "codigo_estado",
            "summarizeBy": "none"
          },
          {
            "name": "condicion",
            "dataType": "string",
            "lineageTag": "9ce74996-c3d3-4e42-9a1e-63a899a08032",
            "sourceColumn": "condicion",
            "summarizeBy": "none"
          },
          {
            "name": "descripcion_estado",
            "dataType": "string",
            "lineageTag": "c77102f2-ac69-4d30-86de-a9b994920540",
            "sourceColumn": "descripcion_estado",
            "summarizeBy": "none"
          },
          {
            "name": "saldo_promedio_previo",
            "dataType": "double",
            "formatString": "\"$\"#,0",
            "lineageTag": "cddf30a4-c1b0-42a0-8177-db0751936432",
            "sourceColumn": "saldo_promedio_previo",
            "summarizeBy": "none"
          },
          {
            "name": "ratio_cuota_saldo_previo",
            "dataType": "double",
            "formatString": "0.00%",
            "lineageTag": "82d6c844-9d67-4f1c-83e2-16e76c6d86e3",
            "sourceColumn": "ratio_cuota_saldo_previo",
            "summarizeBy": "none"
          },
          {
            "name": "banda_capacidad",
            "dataType": "string",
            "lineageTag": "4aabdcf0-83d0-41da-9978-b3136dacb505",
            "sortByColumn": "orden_banda",
            "sourceColumn": "banda_capacidad",
            "summarizeBy": "none"
          },
          {
            "name": "orden_banda",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "34591170-bd6d-48d2-89db-863a64bd0f0e",
            "sourceColumn": "orden_banda",
            "summarizeBy": "none"
          },
          {
            "name": "estado",
            "dataType": "string",
            "expression": "SWITCH(m_prestamos[codigo_estado], \"A\", \"A · Cerrado al día\", \"B\", \"B · Cerrado con deuda\", \"C\", \"C · Vigente al día\", \"D\", \"D · Vigente en mora\")",
            "lineageTag": "48940a2c-ea89-443f-b226-ccff6a37c455",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "301b8f4b-ce21-432c-86a7-a781bba76065",
        "partitions": [
          {
            "name": "m_prestamos",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = MongoFinancial,",
                "    Tabla = Origen{[Name=\"m_prestamos\"]}[Value],",
                "    Columnas = Table.SelectColumns(Tabla, {\"id_prestamo\", \"id_cuenta\", \"id_cliente\", \"id_distrito\", \"fecha_otorgamiento\", \"anio\", \"monto_prestamo\", \"plazo_meses\", \"pago_mensual\", \"saldo_pendiente_estimado\", \"meses_transcurridos_al_corte\", \"codigo_estado\", \"condicion\", \"descripcion_estado\", \"saldo_promedio_previo\", \"ratio_cuota_saldo_previo\", \"banda_capacidad\", \"orden_banda\"}),",
                "    Tipos = Table.TransformColumnTypes(Columnas, {{\"id_prestamo\", Int64.Type}, {\"id_cuenta\", Int64.Type}, {\"id_cliente\", Int64.Type}, {\"id_distrito\", Int64.Type}, {\"fecha_otorgamiento\", type datetime}, {\"anio\", Int64.Type}, {\"monto_prestamo\", type number}, {\"plazo_meses\", Int64.Type}, {\"pago_mensual\", type number}, {\"saldo_pendiente_estimado\", type number}, {\"meses_transcurridos_al_corte\", Int64.Type}, {\"codigo_estado\", type text}, {\"condicion\", type text}, {\"descripcion_estado\", type text}, {\"saldo_promedio_previo\", type number}, {\"ratio_cuota_saldo_previo\", type number}, {\"banda_capacidad\", type text}, {\"orden_banda\", Int64.Type}}, \"en-US\")",
                "in",
                "    Tipos"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "m_ordenes",
        "columns": [
          {
            "name": "id_orden",
            "dataType": "int64",
            "lineageTag": "a62cef89-c325-43c1-9fe0-e038d4bff2db",
            "sourceColumn": "id_orden",
            "summarizeBy": "none"
          },
          {
            "name": "id_cuenta",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "ba504473-fe7a-4319-bd3a-b7b8f79a38c3",
            "sourceColumn": "id_cuenta",
            "summarizeBy": "none"
          },
          {
            "name": "id_cliente",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "566409da-f048-438a-a463-59eb86f52601",
            "sourceColumn": "id_cliente",
            "summarizeBy": "none"
          },
          {
            "name": "id_distrito",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "26998deb-06e1-4cfd-905a-7e9ffe7f8ce2",
            "sourceColumn": "id_distrito",
            "summarizeBy": "none"
          },
          {
            "name": "k_symbol",
            "dataType": "string",
            "lineageTag": "7e42ffcb-9b23-4191-bd7f-33a9eb184a0e",
            "sourceColumn": "k_symbol",
            "summarizeBy": "none"
          },
          {
            "name": "categoria_orden",
            "dataType": "string",
            "lineageTag": "12bd46c6-5c57-4a74-b4d9-b3106a72f0f1",
            "sourceColumn": "categoria_orden",
            "summarizeBy": "none"
          },
          {
            "name": "monto_orden",
            "dataType": "double",
            "formatString": "\"$\"#,0",
            "lineageTag": "d085a902-0db0-4235-addd-7a90d5fcc5cd",
            "sourceColumn": "monto_orden",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "3f5f8c43-341e-4e4c-9fe4-c906c8d5287a",
        "partitions": [
          {
            "name": "m_ordenes",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = MongoFinancial,",
                "    Tabla = Origen{[Name=\"m_ordenes\"]}[Value],",
                "    Columnas = Table.SelectColumns(Tabla, {\"id_orden\", \"id_cuenta\", \"id_cliente\", \"id_distrito\", \"k_symbol\", \"categoria_orden\", \"monto_orden\"}),",
                "    Tipos = Table.TransformColumnTypes(Columnas, {{\"id_orden\", Int64.Type}, {\"id_cuenta\", Int64.Type}, {\"id_cliente\", Int64.Type}, {\"id_distrito\", Int64.Type}, {\"k_symbol\", type text}, {\"categoria_orden\", type text}, {\"monto_orden\", type number}}, \"en-US\")",
                "in",
                "    Tipos"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "m_trans_anual",
        "columns": [
          {
            "name": "id_cuenta",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "9c47c5e0-02bc-43b5-9b63-6f18cd85b1bd",
            "sourceColumn": "id_cuenta",
            "summarizeBy": "none"
          },
          {
            "name": "id_cliente",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "b25ec65d-b765-4204-98a1-b4ae98f46a64",
            "sourceColumn": "id_cliente",
            "summarizeBy": "none"
          },
          {
            "name": "id_distrito",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "cc1b5701-a79b-4ad8-8fe8-e97bab9e46f4",
            "sourceColumn": "id_distrito",
            "summarizeBy": "none"
          },
          {
            "name": "anio",
            "dataType": "int64",
            "lineageTag": "428eeae2-bbb5-4b14-8ced-9685e4a70400",
            "sourceColumn": "anio",
            "summarizeBy": "none"
          },
          {
            "name": "categoria_analitica",
            "dataType": "string",
            "lineageTag": "f632c442-8e71-43c4-b284-25caa33a9db1",
            "sourceColumn": "categoria_analitica",
            "summarizeBy": "none"
          },
          {
            "name": "num_transacciones",
            "dataType": "int64",
            "lineageTag": "2b4f32ac-5cb6-493f-a716-cf75dcfd38c8",
            "sourceColumn": "num_transacciones",
            "summarizeBy": "none"
          },
          {
            "name": "monto_total",
            "dataType": "double",
            "formatString": "\"$\"#,0",
            "lineageTag": "fb240d4a-7d46-468f-9e02-59d2441d4ff6",
            "sourceColumn": "monto_total",
            "summarizeBy": "none"
          },
          {
            "name": "suma_cuadrados",
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "d7b0881b-7fa1-49cf-aba6-e35642e0566a",
            "sourceColumn": "suma_cuadrados",
            "summarizeBy": "none"
          },
          {
            "name": "saldo_promedio",
            "dataType": "double",
            "formatString": "\"$\"#,0",
            "lineageTag": "c12551a0-fe1b-45f4-9fe3-6cd06cba526f",
            "sourceColumn": "saldo_promedio",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "47a6491c-3f5a-4320-b8b7-75bbc10aa540",
        "partitions": [
          {
            "name": "m_trans_anual",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = MongoFinancial,",
                "    Tabla = Origen{[Name=\"m_trans_anual\"]}[Value],",
                "    Columnas = Table.SelectColumns(Tabla, {\"id_cuenta\", \"id_cliente\", \"id_distrito\", \"anio\", \"categoria_analitica\", \"num_transacciones\", \"monto_total\", \"suma_cuadrados\", \"saldo_promedio\"}),",
                "    Tipos = Table.TransformColumnTypes(Columnas, {{\"id_cuenta\", Int64.Type}, {\"id_cliente\", Int64.Type}, {\"id_distrito\", Int64.Type}, {\"anio\", Int64.Type}, {\"categoria_analitica\", type text}, {\"num_transacciones\", Int64.Type}, {\"monto_total\", type number}, {\"suma_cuadrados\", type number}, {\"saldo_promedio\", type number}}, \"en-US\")",
                "in",
                "    Tipos"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "m_saldo_mensual",
        "columns": [
          {
            "name": "id_cuenta",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "74858e91-94cc-4965-8a82-c99ef4c36423",
            "sourceColumn": "id_cuenta",
            "summarizeBy": "none"
          },
          {
            "name": "id_cliente",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "4d5ea052-47ea-4419-a248-588670cb6199",
            "sourceColumn": "id_cliente",
            "summarizeBy": "none"
          },
          {
            "name": "id_distrito",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "366f326c-1914-40a4-a4ff-78fb5b9d9728",
            "sourceColumn": "id_distrito",
            "summarizeBy": "none"
          },
          {
            "name": "anio",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "9c5cb86f-e5fd-407c-bc75-649cd2de7b26",
            "sourceColumn": "anio",
            "summarizeBy": "none"
          },
          {
            "name": "mes",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "d5057c93-04cd-4672-9ded-a5347724da0e",
            "sourceColumn": "mes",
            "summarizeBy": "none"
          },
          {
            "name": "fecha_mes",
            "dataType": "dateTime",
            "formatString": "dd/mm/yyyy",
            "lineageTag": "c756bd0a-db4c-4fa4-b7f3-5ee20d151d74",
            "sourceColumn": "fecha_mes",
            "summarizeBy": "none"
          },
          {
            "name": "saldo_fin_mes",
            "dataType": "double",
            "formatString": "\"$\"#,0",
            "lineageTag": "598e02f8-80e8-44e1-bfdb-0ebdc27e0ca0",
            "sourceColumn": "saldo_fin_mes",
            "summarizeBy": "none"
          },
          {
            "name": "saldo_promedio_mes",
            "dataType": "double",
            "formatString": "\"$\"#,0",
            "lineageTag": "1aa20f62-b227-4287-a06a-021b0c9eaf54",
            "sourceColumn": "saldo_promedio_mes",
            "summarizeBy": "none"
          },
          {
            "name": "num_movimientos_mes",
            "dataType": "int64",
            "lineageTag": "24dac482-c2b5-496c-ab77-b423042e8364",
            "sourceColumn": "num_movimientos_mes",
            "summarizeBy": "none"
          },
          {
            "name": "en_sobregiro",
            "dataType": "boolean",
            "lineageTag": "55a580a8-3cf2-49c8-8453-7f71f4af9c5f",
            "sourceColumn": "en_sobregiro",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "8da79bb4-e042-4c62-9008-bc1054e358a0",
        "partitions": [
          {
            "name": "m_saldo_mensual",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = MongoFinancial,",
                "    Tabla = Origen{[Name=\"m_saldo_mensual\"]}[Value],",
                "    Columnas = Table.SelectColumns(Tabla, {\"id_cuenta\", \"id_cliente\", \"id_distrito\", \"anio\", \"mes\", \"fecha_mes\", \"saldo_fin_mes\", \"saldo_promedio_mes\", \"num_movimientos_mes\", \"en_sobregiro\"}),",
                "    Tipos = Table.TransformColumnTypes(Columnas, {{\"id_cuenta\", Int64.Type}, {\"id_cliente\", Int64.Type}, {\"id_distrito\", Int64.Type}, {\"anio\", Int64.Type}, {\"mes\", Int64.Type}, {\"fecha_mes\", type datetime}, {\"saldo_fin_mes\", type number}, {\"saldo_promedio_mes\", type number}, {\"num_movimientos_mes\", Int64.Type}, {\"en_sobregiro\", type logical}}, \"en-US\")",
                "in",
                "    Tipos"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "m_recomendaciones",
        "columns": [
          {
            "name": "id_cuenta",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "6a9290bd-c844-42b7-a2fb-09759845eb70",
            "sourceColumn": "id_cuenta",
            "summarizeBy": "none"
          },
          {
            "name": "id_cliente",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "392a09dd-a800-4d76-9d98-d693e5a26cd2",
            "sourceColumn": "id_cliente",
            "summarizeBy": "none"
          },
          {
            "name": "modelo",
            "dataType": "string",
            "lineageTag": "94103274-f608-4786-8d8c-064dc8652b01",
            "sourceColumn": "modelo",
            "summarizeBy": "none"
          },
          {
            "name": "recomendacion_1",
            "dataType": "string",
            "lineageTag": "0e88499f-01b7-4849-8df5-e6c57a2ad0b5",
            "sourceColumn": "recomendacion_1",
            "summarizeBy": "none"
          },
          {
            "name": "recomendacion_2",
            "dataType": "string",
            "lineageTag": "1ac66c4f-18c7-4f76-8b33-d4321fad0d65",
            "sourceColumn": "recomendacion_2",
            "summarizeBy": "none"
          },
          {
            "name": "recomendacion_3",
            "dataType": "string",
            "lineageTag": "0e99b649-89b6-4382-b10c-d1fe6a75c8e2",
            "sourceColumn": "recomendacion_3",
            "summarizeBy": "none"
          },
          {
            "name": "prestamo_cuota_maxima",
            "dataType": "double",
            "formatString": "\"$\"#,0",
            "lineageTag": "d25a82f0-be10-4be3-a6f8-569f60f9d704",
            "sourceColumn": "prestamo_cuota_maxima",
            "summarizeBy": "none"
          },
          {
            "name": "prestamo_monto_maximo_36m",
            "dataType": "double",
            "formatString": "\"$\"#,0",
            "lineageTag": "3a01a98a-f2a5-4978-9e63-3d931552dbcf",
            "sourceColumn": "prestamo_monto_maximo_36m",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "1eb2603f-9d36-4ae9-9dd0-f887fd6ae7ce",
        "partitions": [
          {
            "name": "m_recomendaciones",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = MongoFinancial,",
                "    Tabla = Origen{[Name=\"m_recomendaciones\"]}[Value],",
                "    Columnas = Table.SelectColumns(Tabla, {\"id_cuenta\", \"id_cliente\", \"modelo\", \"recomendacion_1\", \"recomendacion_2\", \"recomendacion_3\", \"prestamo_cuota_maxima\", \"prestamo_monto_maximo_36m\"}),",
                "    Tipos = Table.TransformColumnTypes(Columnas, {{\"id_cuenta\", Int64.Type}, {\"id_cliente\", Int64.Type}, {\"modelo\", type text}, {\"recomendacion_1\", type text}, {\"recomendacion_2\", type text}, {\"recomendacion_3\", type text}, {\"prestamo_cuota_maxima\", type number}, {\"prestamo_monto_maximo_36m\", type number}}, \"en-US\")",
                "in",
                "    Tipos"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "m_dim_producto",
        "columns": [
          {
            "name": "producto",
            "dataType": "string",
            "lineageTag": "3f356d5c-c042-4aff-87a9-24b0a33624f7",
            "sortByColumn": "orden",
            "sourceColumn": "producto",
            "summarizeBy": "none"
          },
          {
            "name": "codigo",
            "dataType": "string",
            "lineageTag": "7b38c365-c96e-47e3-9845-330a5f041912",
            "sourceColumn": "codigo",
            "summarizeBy": "none"
          },
          {
            "name": "descripcion",
            "dataType": "string",
            "lineageTag": "1b04a6dd-9351-4b3e-9229-01c19dd5e3f9",
            "sourceColumn": "descripcion",
            "summarizeBy": "none"
          },
          {
            "name": "penetracion",
            "dataType": "double",
            "formatString": "0.00%",
            "lineageTag": "4f20c626-d497-4060-9c28-091f9c2122c2",
            "sourceColumn": "penetracion",
            "summarizeBy": "none"
          },
          {
            "name": "orden",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "821b51bd-3e07-49ce-9caa-a50968b9efe8",
            "sourceColumn": "orden",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "8331771c-9198-45be-b3a5-745e23867507",
        "partitions": [
          {
            "name": "m_dim_producto",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = MongoFinancial,",
                "    Tabla = Origen{[Name=\"m_dim_producto\"]}[Value],",
                "    Columnas = Table.SelectColumns(Tabla, {\"producto\", \"codigo\", \"descripcion\", \"penetracion\", \"orden\"}),",
                "    Tipos = Table.TransformColumnTypes(Columnas, {{\"producto\", type text}, {\"codigo\", type text}, {\"descripcion\", type text}, {\"penetracion\", type number}, {\"orden\", Int64.Type}}, \"en-US\")",
                "in",
                "    Tipos"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "m_recomendacion_producto",
        "columns": [
          {
            "name": "id_cuenta",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "8d19fdf0-9164-4ee7-83e3-c83947d72292",
            "sourceColumn": "id_cuenta",
            "summarizeBy": "none"
          },
          {
            "name": "id_cliente",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "69acb6e5-6c1d-4c01-82e5-b5d52d4bafa2",
            "sourceColumn": "id_cliente",
            "summarizeBy": "none"
          },
          {
            "name": "id_distrito",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "3f5b06b3-d2c8-4b86-863c-7f94970afe6c",
            "sourceColumn": "id_distrito",
            "summarizeBy": "none"
          },
          {
            "name": "sistema",
            "dataType": "string",
            "lineageTag": "0afef547-cb2a-4042-b8bf-9ac57bce7963",
            "sourceColumn": "sistema",
            "summarizeBy": "none"
          },
          {
            "name": "producto",
            "dataType": "string",
            "lineageTag": "e942757b-ae75-4b4b-abc9-2e25e938482d",
            "sourceColumn": "producto",
            "summarizeBy": "none"
          },
          {
            "name": "posicion",
            "dataType": "int64",
            "lineageTag": "4ab40e2c-16c4-43db-aae4-8038a79688d6",
            "sourceColumn": "posicion",
            "summarizeBy": "none"
          },
          {
            "name": "puntaje",
            "dataType": "double",
            "formatString": "0.0000",
            "lineageTag": "9ad2451f-0748-4178-a21e-367961e3b5c5",
            "sourceColumn": "puntaje",
            "summarizeBy": "none"
          },
          {
            "name": "es_descubrimiento",
            "dataType": "boolean",
            "lineageTag": "258e9a1d-3e7e-4b71-bcbc-aa43edf72ce3",
            "sourceColumn": "es_descubrimiento",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "872c5946-99ad-4411-a9c7-b23b65febd21",
        "partitions": [
          {
            "name": "m_recomendacion_producto",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = MongoFinancial,",
                "    Tabla = Origen{[Name=\"m_recomendacion_producto\"]}[Value],",
                "    Columnas = Table.SelectColumns(Tabla, {\"id_cuenta\", \"id_cliente\", \"id_distrito\", \"sistema\", \"producto\", \"posicion\", \"puntaje\", \"es_descubrimiento\"}),",
                "    Tipos = Table.TransformColumnTypes(Columnas, {{\"id_cuenta\", Int64.Type}, {\"id_cliente\", Int64.Type}, {\"id_distrito\", Int64.Type}, {\"sistema\", type text}, {\"producto\", type text}, {\"posicion\", Int64.Type}, {\"puntaje\", type number}, {\"es_descubrimiento\", type logical}}, \"en-US\")",
                "in",
                "    Tipos"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "m_adopcion_producto",
        "columns": [
          {
            "name": "id_cuenta",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "307f29b4-93a2-4d33-9c0d-bedbb5b71740",
            "sourceColumn": "id_cuenta",
            "summarizeBy": "none"
          },
          {
            "name": "id_cliente",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "3deecd77-16b7-4247-b4cc-b37328cd5244",
            "sourceColumn": "id_cliente",
            "summarizeBy": "none"
          },
          {
            "name": "id_distrito",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "7bec3963-eddf-4169-b4f3-c657a6161beb",
            "sourceColumn": "id_distrito",
            "summarizeBy": "none"
          },
          {
            "name": "producto",
            "dataType": "string",
            "lineageTag": "56c88960-2452-49e8-a25f-a56311854a17",
            "sourceColumn": "producto",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "a1629c89-a9ca-4221-9add-149c7a302710",
        "partitions": [
          {
            "name": "m_adopcion_producto",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = MongoFinancial,",
                "    Tabla = Origen{[Name=\"m_adopcion_producto\"]}[Value],",
                "    Columnas = Table.SelectColumns(Tabla, {\"id_cuenta\", \"id_cliente\", \"id_distrito\", \"producto\"}),",
                "    Tipos = Table.TransformColumnTypes(Columnas, {{\"id_cuenta\", Int64.Type}, {\"id_cliente\", Int64.Type}, {\"id_distrito\", Int64.Type}, {\"producto\", type text}}, \"en-US\")",
                "in",
                "    Tipos"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "m_capacidad_prestamo",
        "columns": [
          {
            "name": "id_cuenta",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "e7e2fbdc-10e7-473f-acff-7fb2d56a7854",
            "sourceColumn": "id_cuenta",
            "summarizeBy": "none"
          },
          {
            "name": "id_cliente",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "76a305ab-b480-49e0-848c-232092b542eb",
            "sourceColumn": "id_cliente",
            "summarizeBy": "none"
          },
          {
            "name": "id_distrito",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "ce7ae45c-e238-4775-9350-a491ac79ce68",
            "sourceColumn": "id_distrito",
            "summarizeBy": "none"
          },
          {
            "name": "tiene_prestamo",
            "dataType": "boolean",
            "lineageTag": "e12f42be-5b13-4d44-9375-30da8ed6815e",
            "sourceColumn": "tiene_prestamo",
            "summarizeBy": "none"
          },
          {
            "name": "saldo_promedio",
            "dataType": "double",
            "formatString": "\"$\"#,0",
            "lineageTag": "7924a0e9-7c5d-451f-883f-8e52bfed11c4",
            "sourceColumn": "saldo_promedio",
            "summarizeBy": "none"
          },
          {
            "name": "cuota_prudente",
            "dataType": "double",
            "formatString": "\"$\"#,0",
            "lineageTag": "69208fbe-ef84-477e-aa0c-548797155d32",
            "sourceColumn": "cuota_prudente",
            "summarizeBy": "none"
          },
          {
            "name": "monto_maximo_12m",
            "dataType": "double",
            "formatString": "\"$\"#,0",
            "lineageTag": "02d46c0c-2ede-4d61-9944-14014ceaf1b8",
            "sourceColumn": "monto_maximo_12m",
            "summarizeBy": "none"
          },
          {
            "name": "monto_maximo_36m",
            "dataType": "double",
            "formatString": "\"$\"#,0",
            "lineageTag": "637e6aa3-da4a-41cf-8e04-a9b5c57f64bb",
            "sourceColumn": "monto_maximo_36m",
            "summarizeBy": "none"
          },
          {
            "name": "monto_maximo_60m",
            "dataType": "double",
            "formatString": "\"$\"#,0",
            "lineageTag": "8fc6ca87-1b4d-4226-aafc-63df28e86abd",
            "sourceColumn": "monto_maximo_60m",
            "summarizeBy": "none"
          },
          {
            "name": "tramo_monto_36m",
            "dataType": "string",
            "lineageTag": "df0914a6-2b16-4aa7-95ac-610c965e1e08",
            "sortByColumn": "orden_tramo",
            "sourceColumn": "tramo_monto_36m",
            "summarizeBy": "none"
          },
          {
            "name": "orden_tramo",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "ff7de297-53d1-4d20-ba07-32da76a863c3",
            "sourceColumn": "orden_tramo",
            "summarizeBy": "none"
          },
          {
            "name": "puede_pagar_prestamo_tipico",
            "dataType": "boolean",
            "lineageTag": "e35be02a-0c54-4b91-ac8e-3aee786d825b",
            "sourceColumn": "puede_pagar_prestamo_tipico",
            "summarizeBy": "none"
          },
          {
            "name": "prestamo_recomendado",
            "dataType": "boolean",
            "lineageTag": "f8e6e824-e78b-449f-b6aa-765b1e0f7de3",
            "sourceColumn": "prestamo_recomendado",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "9f7b18b8-59b8-4bfa-880b-a21707d7d780",
        "partitions": [
          {
            "name": "m_capacidad_prestamo",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = MongoFinancial,",
                "    Tabla = Origen{[Name=\"m_capacidad_prestamo\"]}[Value],",
                "    Columnas = Table.SelectColumns(Tabla, {\"id_cuenta\", \"id_cliente\", \"id_distrito\", \"tiene_prestamo\", \"saldo_promedio\", \"cuota_prudente\", \"monto_maximo_12m\", \"monto_maximo_36m\", \"monto_maximo_60m\", \"tramo_monto_36m\", \"orden_tramo\", \"puede_pagar_prestamo_tipico\", \"prestamo_recomendado\"}),",
                "    Tipos = Table.TransformColumnTypes(Columnas, {{\"id_cuenta\", Int64.Type}, {\"id_cliente\", Int64.Type}, {\"id_distrito\", Int64.Type}, {\"tiene_prestamo\", type logical}, {\"saldo_promedio\", type number}, {\"cuota_prudente\", type number}, {\"monto_maximo_12m\", type number}, {\"monto_maximo_36m\", type number}, {\"monto_maximo_60m\", type number}, {\"tramo_monto_36m\", type text}, {\"orden_tramo\", Int64.Type}, {\"puede_pagar_prestamo_tipico\", type logical}, {\"prestamo_recomendado\", type logical}}, \"en-US\")",
                "in",
                "    Tipos"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "m_evaluacion_recomendador",
        "columns": [
          {
            "name": "modelo",
            "dataType": "string",
            "lineageTag": "f9b72d80-f442-4c7e-9ef2-6395e7072274",
            "sortByColumn": "orden",
            "sourceColumn": "modelo",
            "summarizeBy": "none"
          },
          {
            "name": "familia",
            "dataType": "string",
            "lineageTag": "41469dd1-2e12-4d0d-b7e8-8b12cba083b0",
            "sourceColumn": "familia",
            "summarizeBy": "none"
          },
          {
            "name": "rol",
            "dataType": "string",
            "lineageTag": "62f6b88f-3ea7-4435-a2ad-2c1b80fff6a9",
            "sourceColumn": "rol",
            "summarizeBy": "none"
          },
          {
            "name": "hit_1",
            "dataType": "double",
            "formatString": "0.00%",
            "lineageTag": "6b40e037-7521-4abe-bb34-facf1e8c2863",
            "sourceColumn": "hit_1",
            "summarizeBy": "none"
          },
          {
            "name": "hit_3",
            "dataType": "double",
            "formatString": "0.00%",
            "lineageTag": "a1d8ca6f-7898-4864-801e-f0e7bce915b4",
            "sourceColumn": "hit_3",
            "summarizeBy": "none"
          },
          {
            "name": "mrr",
            "dataType": "double",
            "formatString": "0.000",
            "lineageTag": "64d75b8c-453e-442e-b547-478e962bfa76",
            "sourceColumn": "mrr",
            "summarizeBy": "none"
          },
          {
            "name": "hit_1_cola_larga",
            "dataType": "double",
            "formatString": "0.00%",
            "lineageTag": "c49c604e-e636-42eb-88df-0730a11dd834",
            "sourceColumn": "hit_1_cola_larga",
            "summarizeBy": "none"
          },
          {
            "name": "mrr_confirmacion",
            "dataType": "double",
            "formatString": "0.000",
            "lineageTag": "56821e06-c684-4b16-95ae-95688e9f0749",
            "sourceColumn": "mrr_confirmacion",
            "summarizeBy": "none"
          },
          {
            "name": "orden",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "abd72cce-9a91-4bac-9ba8-61884377ea25",
            "sourceColumn": "orden",
            "summarizeBy": "none"
          },
          {
            "name": "elegido",
            "dataType": "boolean",
            "lineageTag": "7f16970c-20fa-4679-82e9-98fcca1f5035",
            "sourceColumn": "elegido",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "653b77de-3944-4ce2-ab52-b169dc116c73",
        "partitions": [
          {
            "name": "m_evaluacion_recomendador",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = MongoFinancial,",
                "    Tabla = Origen{[Name=\"m_evaluacion_recomendador\"]}[Value],",
                "    Columnas = Table.SelectColumns(Tabla, {\"modelo\", \"familia\", \"rol\", \"hit_1\", \"hit_3\", \"mrr\", \"hit_1_cola_larga\", \"mrr_confirmacion\", \"orden\", \"elegido\"}),",
                "    Tipos = Table.TransformColumnTypes(Columnas, {{\"modelo\", type text}, {\"familia\", type text}, {\"rol\", type text}, {\"hit_1\", type number}, {\"hit_3\", type number}, {\"mrr\", type number}, {\"hit_1_cola_larga\", type number}, {\"mrr_confirmacion\", type number}, {\"orden\", Int64.Type}, {\"elegido\", type logical}}, \"en-US\")",
                "in",
                "    Tipos"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "m_asociacion_producto",
        "columns": [
          {
            "name": "producto_origen",
            "dataType": "string",
            "lineageTag": "2a6234ea-88e5-4a25-b8b4-4e24d5a578c9",
            "sourceColumn": "producto_origen",
            "summarizeBy": "none"
          },
          {
            "name": "producto_destino",
            "dataType": "string",
            "lineageTag": "295415a0-9a78-4731-8873-0517f444fc71",
            "sourceColumn": "producto_destino",
            "summarizeBy": "none"
          },
          {
            "name": "p_destino_dado_origen",
            "dataType": "double",
            "formatString": "0.00%",
            "lineageTag": "e88c94b4-490e-4bbb-ae26-e31c8a338279",
            "sourceColumn": "p_destino_dado_origen",
            "summarizeBy": "none"
          },
          {
            "name": "lift",
            "dataType": "double",
            "formatString": "0.00",
            "lineageTag": "54517f78-7b7d-492b-89a9-857f98dff76f",
            "sourceColumn": "lift",
            "summarizeBy": "none"
          },
          {
            "name": "cuentas_ambos",
            "dataType": "int64",
            "lineageTag": "d50efe20-81f7-497d-8b7b-86ee6bfc4c06",
            "sourceColumn": "cuentas_ambos",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "2db85186-4ced-4372-bee6-034781109bc4",
        "partitions": [
          {
            "name": "m_asociacion_producto",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = MongoFinancial,",
                "    Tabla = Origen{[Name=\"m_asociacion_producto\"]}[Value],",
                "    Columnas = Table.SelectColumns(Tabla, {\"producto_origen\", \"producto_destino\", \"p_destino_dado_origen\", \"lift\", \"cuentas_ambos\"}),",
                "    Tipos = Table.TransformColumnTypes(Columnas, {{\"producto_origen\", type text}, {\"producto_destino\", type text}, {\"p_destino_dado_origen\", type number}, {\"lift\", type number}, {\"cuentas_ambos\", Int64.Type}}, \"en-US\")",
                "in",
                "    Tipos"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "m_regla_capacidad",
        "columns": [
          {
            "name": "regla",
            "dataType": "string",
            "lineageTag": "946724dd-a95c-41b5-b5f6-94b94129bd88",
            "sourceColumn": "regla",
            "summarizeBy": "none"
          },
          {
            "name": "tramo",
            "dataType": "string",
            "lineageTag": "33e7eeab-1957-4063-bd6a-ecd1c8b81a0b",
            "sortByColumn": "orden",
            "sourceColumn": "tramo",
            "summarizeBy": "none"
          },
          {
            "name": "orden",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "085b7cc9-cf17-4d12-b6e6-960f792eeeaa",
            "sourceColumn": "orden",
            "summarizeBy": "none"
          },
          {
            "name": "prestamos",
            "dataType": "int64",
            "lineageTag": "138f374d-5029-4bc4-bbc6-f7479b68f5ef",
            "sourceColumn": "prestamos",
            "summarizeBy": "none"
          },
          {
            "name": "impagos",
            "dataType": "int64",
            "lineageTag": "bd947942-a426-4b61-8fea-e969df6347d0",
            "sourceColumn": "impagos",
            "summarizeBy": "none"
          },
          {
            "name": "tasa_impago",
            "dataType": "double",
            "formatString": "0.00%",
            "lineageTag": "f61ec3a1-1caa-4bb1-944f-05f87888f4f1",
            "sourceColumn": "tasa_impago",
            "summarizeBy": "none"
          },
          {
            "name": "auc",
            "dataType": "double",
            "formatString": "0.000",
            "lineageTag": "13bc1b51-6530-4a54-9583-117f59ce7752",
            "sourceColumn": "auc",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "d89727f7-e8f8-4590-990a-55681d5d626f",
        "partitions": [
          {
            "name": "m_regla_capacidad",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = MongoFinancial,",
                "    Tabla = Origen{[Name=\"m_regla_capacidad\"]}[Value],",
                "    Columnas = Table.SelectColumns(Tabla, {\"regla\", \"tramo\", \"orden\", \"prestamos\", \"impagos\", \"tasa_impago\", \"auc\"}),",
                "    Tipos = Table.TransformColumnTypes(Columnas, {{\"regla\", type text}, {\"tramo\", type text}, {\"orden\", Int64.Type}, {\"prestamos\", Int64.Type}, {\"impagos\", Int64.Type}, {\"tasa_impago\", type number}, {\"auc\", type number}}, \"en-US\")",
                "in",
                "    Tipos"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Composicion_Liquidez",
        "columns": [
          {
            "name": "concepto",
            "dataType": "string",
            "lineageTag": "5d266b11-22b6-4c58-87d0-ff49e76419f9",
            "sortByColumn": "orden",
            "sourceColumn": "concepto",
            "summarizeBy": "none"
          },
          {
            "name": "orden",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "0448befd-50b1-4ed5-bafb-af066d05fd99",
            "sourceColumn": "orden",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "1e367c95-9cf5-4e2d-b6e8-ac54efddc747",
        "partitions": [
          {
            "name": "Composicion_Liquidez",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = #table(type table [concepto = text, orden = Int64.Type], {{\"Saldo neto al corte\", 1}, {\"Cartera vigente\", 2}})",
                "in",
                "    Origen"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "_Medidas",
        "columns": [
          {
            "name": "Medidas",
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "047eda2e-e340-4f25-8366-fe088d9d05f5",
            "sourceColumn": "Medidas",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "58b5c70a-89eb-4b38-a92b-9dbe74609cca",
        "measures": [
          {
            "name": "Num Prestamos",
            "description": "Préstamos otorgados (682)",
            "expression": "COUNTROWS(m_prestamos)",
            "formatString": "#,0",
            "lineageTag": "674c4686-0853-4cdb-97cf-d9a59397f5e4"
          },
          {
            "name": "Prestamos en Mora",
            "description": "Vigentes en mora, estado D (45)",
            "expression": "CALCULATE([Num Prestamos], m_prestamos[codigo_estado] = \"D\")",
            "formatString": "#,0",
            "lineageTag": "d8058c21-ffce-4efc-94d9-07a0c6381535"
          },
          {
            "name": "Prestamos Vigentes",
            "description": "Estados C + D (448)",
            "expression": "CALCULATE([Num Prestamos], m_prestamos[codigo_estado] IN {\"C\", \"D\"})",
            "formatString": "#,0",
            "lineageTag": "937e73d9-7729-44f9-9046-d867c6b117dd"
          },
          {
            "name": "Prestamos Incumplidos",
            "description": "Cerrados con deuda, estado B (31)",
            "expression": "CALCULATE([Num Prestamos], m_prestamos[codigo_estado] = \"B\")",
            "formatString": "#,0",
            "lineageTag": "e1ab34b8-0c46-4124-8b9c-2f26779ae36f"
          },
          {
            "name": "Prestamos Cerrados",
            "description": "Estados A + B (234)",
            "expression": "CALCULATE([Num Prestamos], m_prestamos[codigo_estado] IN {\"A\", \"B\"})",
            "formatString": "#,0",
            "lineageTag": "caab6281-f572-4159-a5e9-82f800d55b37"
          },
          {
            "name": "Prestamos con Impago",
            "description": "Estados B + D (76)",
            "expression": "CALCULATE([Num Prestamos], m_prestamos[codigo_estado] IN {\"B\", \"D\"})",
            "formatString": "#,0",
            "lineageTag": "ca180a47-da8e-4a09-8324-4900069cb761"
          },
          {
            "name": "Tasa Mora Vigente",
            "description": "D / (C + D) = 10.04%; 0% (no vacío) si hay vigentes sin mora, p. ej. north Bohemia 0/41",
            "expression": "IF([Prestamos Vigentes] > 0, DIVIDE([Prestamos en Mora] + 0, [Prestamos Vigentes]))",
            "formatString": "0.00%",
            "lineageTag": "a347aeca-8039-4e68-aa85-54f136de35e3"
          },
          {
            "name": "Tasa Incumplimiento",
            "description": "B / (A + B) = 13.25%",
            "expression": "IF([Prestamos Cerrados] > 0, DIVIDE([Prestamos Incumplidos] + 0, [Prestamos Cerrados]))",
            "formatString": "0.00%",
            "lineageTag": "ca66ea07-8f37-4ec3-9ba0-9a5cee51436d"
          },
          {
            "name": "Tasa Impago",
            "description": "(B + D) / total = 11.14%; es la tasa de P6 por banda de capacidad",
            "expression": "IF([Num Prestamos] > 0, DIVIDE([Prestamos con Impago] + 0, [Num Prestamos]))",
            "formatString": "0.00%",
            "lineageTag": "c433af54-623a-4918-aed3-5e33aa61803b"
          },
          {
            "name": "Mora Wilson Inferior",
            "description": "Límite inferior de Wilson (z = 1) de mora",
            "expression": "VAR n = [Prestamos Vigentes] VAR p = DIVIDE([Prestamos en Mora] + 0, n) VAR c = DIVIDE(p + 1 / (2 * n), 1 + 1 / n) VAR m = DIVIDE(1, 1 + 1 / n) * SQRT(p * (1 - p) / n + 1 / (4 * n * n)) RETURN IF(n > 0, c - m)",
            "formatString": "0.00%",
            "lineageTag": "be0e8967-1efb-4fde-9a6d-f340018a6ee6"
          },
          {
            "name": "Mora Wilson Superior",
            "description": "Límite superior de Wilson (z = 1) de mora",
            "expression": "VAR n = [Prestamos Vigentes] VAR p = DIVIDE([Prestamos en Mora] + 0, n) VAR c = DIVIDE(p + 1 / (2 * n), 1 + 1 / n) VAR m = DIVIDE(1, 1 + 1 / n) * SQRT(p * (1 - p) / n + 1 / (4 * n * n)) RETURN IF(n > 0, c + m)",
            "formatString": "0.00%",
            "lineageTag": "5e92b08a-6957-470b-a005-b9ccfdf08836"
          },
          {
            "name": "Incumplimiento Wilson Inferior",
            "description": "Límite inferior de Wilson (z = 1) de incumplimiento",
            "expression": "VAR n = [Prestamos Cerrados] VAR p = DIVIDE([Prestamos Incumplidos] + 0, n) VAR c = DIVIDE(p + 1 / (2 * n), 1 + 1 / n) VAR m = DIVIDE(1, 1 + 1 / n) * SQRT(p * (1 - p) / n + 1 / (4 * n * n)) RETURN IF(n > 0, c - m)",
            "formatString": "0.00%",
            "lineageTag": "55c5054e-f903-46aa-8433-28a0dd681976"
          },
          {
            "name": "Incumplimiento Wilson Superior",
            "description": "Límite superior de Wilson (z = 1) de incumplimiento",
            "expression": "VAR n = [Prestamos Cerrados] VAR p = DIVIDE([Prestamos Incumplidos] + 0, n) VAR c = DIVIDE(p + 1 / (2 * n), 1 + 1 / n) VAR m = DIVIDE(1, 1 + 1 / n) * SQRT(p * (1 - p) / n + 1 / (4 * n * n)) RETURN IF(n > 0, c + m)",
            "formatString": "0.00%",
            "lineageTag": "a56113a3-7245-4300-95d0-afef24fa162a"
          },
          {
            "name": "Impago Wilson Inferior",
            "description": "Límite inferior de Wilson (z = 1) de impago",
            "expression": "VAR n = [Num Prestamos] VAR p = DIVIDE([Prestamos con Impago] + 0, n) VAR c = DIVIDE(p + 1 / (2 * n), 1 + 1 / n) VAR m = DIVIDE(1, 1 + 1 / n) * SQRT(p * (1 - p) / n + 1 / (4 * n * n)) RETURN IF(n > 0, c - m)",
            "formatString": "0.00%",
            "lineageTag": "e8c38cb9-c5b2-49f1-b282-876ce821aa89"
          },
          {
            "name": "Impago Wilson Superior",
            "description": "Límite superior de Wilson (z = 1) de impago",
            "expression": "VAR n = [Num Prestamos] VAR p = DIVIDE([Prestamos con Impago] + 0, n) VAR c = DIVIDE(p + 1 / (2 * n), 1 + 1 / n) VAR m = DIVIDE(1, 1 + 1 / n) * SQRT(p * (1 - p) / n + 1 / (4 * n * n)) RETURN IF(n > 0, c + m)",
            "formatString": "0.00%",
            "lineageTag": "fc96c64c-9895-4bca-ba0f-b880a3efcd0f"
          },
          {
            "name": "Tasa Mora Banco",
            "description": "Referencia de P2: la tasa del banco, sin el filtro de distrito",
            "expression": "CALCULATE([Tasa Mora Vigente], REMOVEFILTERS(m_distritos))",
            "formatString": "0.00%",
            "lineageTag": "6a2174a0-3aa6-4f9c-bcd7-b6a2feee6757"
          },
          {
            "name": "Tasa Impago Banco",
            "description": "Referencia de P6: impago de todas las bandas",
            "expression": "CALCULATE([Tasa Impago], REMOVEFILTERS(m_prestamos[banda_capacidad], m_prestamos[orden_banda]))",
            "formatString": "0.00%",
            "lineageTag": "e7c23a1c-fd84-4266-8e25-8e532d5b9ca8"
          },
          {
            "name": "Tasa Incumplimiento Banco",
            "description": "Referencia de P6: incumplimiento de todos los segmentos de edad",
            "expression": "CALCULATE([Tasa Incumplimiento], REMOVEFILTERS(m_clientes))",
            "formatString": "0.00%",
            "lineageTag": "f156c6cd-35d7-49e5-8ce2-de33c5e93c8b"
          },
          {
            "name": "Tasa Impago Banda Baja",
            "description": "Impago de la banda Baja (2.92%); KEEPFILTERS respeta los demás filtros",
            "expression": "CALCULATE([Tasa Impago], KEEPFILTERS(m_prestamos[banda_capacidad] = \"Baja\"))",
            "formatString": "0.00%",
            "lineageTag": "966dece3-5d5d-4e59-b6cb-ed19fbd95a0b"
          },
          {
            "name": "Tasa Impago Banda Alta",
            "description": "Impago de la banda Alta (23.26%)",
            "expression": "CALCULATE([Tasa Impago], KEEPFILTERS(m_prestamos[banda_capacidad] = \"Alta\"))",
            "formatString": "0.00%",
            "lineageTag": "1bcd6eae-a4bc-4e2d-a96c-9e62fa2663e0"
          },
          {
            "name": "Cartera Total",
            "description": "Monto original de todos los préstamos ($103,261,740)",
            "expression": "SUM(m_prestamos[monto_prestamo])",
            "formatString": "\"$\"#,0",
            "lineageTag": "25bc73a7-a91d-44ba-8386-803663caf130"
          },
          {
            "name": "Cartera Vigente",
            "description": "Monto original C + D ($80,296,176)",
            "expression": "CALCULATE([Cartera Total], m_prestamos[codigo_estado] IN {\"C\", \"D\"})",
            "formatString": "\"$\"#,0",
            "lineageTag": "5d3cbe3f-00fa-4db5-b73d-13b2bbeeb1cb"
          },
          {
            "name": "Saldo por Cobrar Estimado",
            "description": "Capital pendiente estimado de la cartera vigente ($46,620,926)",
            "expression": "CALCULATE(SUM(m_prestamos[saldo_pendiente_estimado]), m_prestamos[codigo_estado] IN {\"C\", \"D\"})",
            "formatString": "\"$\"#,0",
            "lineageTag": "d13eb7a1-a7a6-403d-85d9-9e6b6ee3705e"
          },
          {
            "name": "Monto Original en Riesgo",
            "description": "Monto original de los préstamos B + D ($15,580,152)",
            "expression": "CALCULATE([Cartera Total], m_prestamos[codigo_estado] IN {\"B\", \"D\"})",
            "formatString": "\"$\"#,0",
            "lineageTag": "6e4e3cad-d83c-4615-9298-00455bf29480"
          },
          {
            "name": "Monto Incumplido",
            "description": "Monto original de los préstamos B",
            "expression": "CALCULATE([Cartera Total], m_prestamos[codigo_estado] = \"B\")",
            "formatString": "\"$\"#,0",
            "lineageTag": "ba4e932f-3dbc-48f0-9205-59c1469efedd"
          },
          {
            "name": "Cuota Mensual",
            "description": "Cuota mensual de los préstamos del contexto",
            "expression": "SUM(m_prestamos[pago_mensual])",
            "formatString": "\"$\"#,0",
            "lineageTag": "169f1115-17bf-4f79-aed4-b8a50635e7bd"
          },
          {
            "name": "Clientes con Impago",
            "description": "Titulares con préstamo B (31): lista de denegación",
            "expression": "CALCULATE(DISTINCTCOUNT(m_prestamos[id_cliente]), m_prestamos[codigo_estado] = \"B\")",
            "formatString": "#,0",
            "lineageTag": "a5adf418-6980-406f-9f80-0ac4c168939f"
          },
          {
            "name": "Cartera Distritos Sobre Mora Banco",
            "description": "CALCULATE + FILTER: cartera vigente de los distritos con mora sobre la del banco",
            "expression": "VAR moraBanco = CALCULATE([Tasa Mora Vigente], REMOVEFILTERS(m_distritos)) RETURN CALCULATE([Cartera Vigente], FILTER(VALUES(m_distritos[nombre_distrito]), [Tasa Mora Vigente] > moraBanco))",
            "formatString": "\"$\"#,0",
            "lineageTag": "7aff02b9-6c45-4089-af0a-29c143d1aa56"
          },
          {
            "name": "Distritos Sobre Mora Banco",
            "description": "Distritos con tasa de mora vigente sobre la del banco",
            "expression": "VAR moraBanco = CALCULATE([Tasa Mora Vigente], REMOVEFILTERS(m_distritos)) RETURN COUNTROWS(FILTER(VALUES(m_distritos[nombre_distrito]), [Tasa Mora Vigente] > moraBanco))",
            "formatString": "#,0",
            "lineageTag": "d596de5f-97e6-4165-aaa5-ea666aaa3e75"
          },
          {
            "name": "Region Mayor Mora",
            "description": "north Moravia · 15.8%",
            "expression": "VAR r = TOPN(1, FILTER(VALUES(m_distritos[region]), [Prestamos Vigentes] > 0), [Tasa Mora Vigente], DESC) RETURN CONCATENATEX(r, m_distritos[region] & \" · \" & FORMAT([Tasa Mora Vigente], \"0.0%\"), \", \")",
            "lineageTag": "9dc093d9-8a67-41d1-8d1a-8fbd2941add9"
          },
          {
            "name": "Distrito Mayor Morosos",
            "description": "Hl.m. Praha · 4 en mora",
            "expression": "VAR d = TOPN(1, FILTER(VALUES(m_distritos[nombre_distrito]), [Prestamos en Mora] > 0), [Prestamos en Mora], DESC) RETURN CONCATENATEX(d, m_distritos[nombre_distrito] & \" · \" & [Prestamos en Mora] & \" en mora\", \", \")",
            "lineageTag": "00895a49-3f2b-49a6-bc19-b0199c6e22de"
          },
          {
            "name": "Estado Prestamo",
            "description": "Estado del préstamo del cliente o de la cuenta (fichas)",
            "expression": "IF([Num Prestamos] > 0, CALCULATE(CONCATENATEX(VALUES(m_prestamos[estado]), m_prestamos[estado], \", \"), m_prestamos))",
            "lineageTag": "3ddc37aa-811f-4428-83a2-10e21155a950"
          },
          {
            "name": "Banda Capacidad",
            "description": "Banda de capacidad de pago (ratio cuota / saldo previo)",
            "expression": "IF([Num Prestamos] > 0, CONCATENATEX(VALUES(m_prestamos[banda_capacidad]), m_prestamos[banda_capacidad], \", \"))",
            "lineageTag": "935ad268-0b31-4a7e-936a-fa03d559b28e"
          },
          {
            "name": "Distrito Prestamo",
            "description": "Distrito de la cuenta del préstamo",
            "expression": "IF([Num Prestamos] > 0, CALCULATE(CONCATENATEX(VALUES(m_distritos[nombre_distrito]), m_distritos[nombre_distrito], \", \"), m_prestamos))",
            "lineageTag": "65b56a32-1986-4229-8f5b-82019acfad5e"
          },
          {
            "name": "Banda Capacidad Impago",
            "description": "Banda del préstamo B (lista de P6)",
            "expression": "CALCULATE([Banda Capacidad], m_prestamos[codigo_estado] = \"B\")",
            "lineageTag": "b11deff6-a50f-4a06-9fe9-0177ccfb8809"
          },
          {
            "name": "Distrito Impago",
            "description": "Distrito del préstamo B (lista de P6)",
            "expression": "CALCULATE([Distrito Prestamo], m_prestamos[codigo_estado] = \"B\")",
            "lineageTag": "d6c88769-6ac5-413d-a25b-7984709b1739"
          },
          {
            "name": "Saldo Neto Corte",
            "description": "Saldo al cierre del último mes del contexto ($197,140,434 en dic-1998)",
            "expression": "VAR ultimoMes = CALCULATE(MAX(m_meses[fecha_mes]), m_saldo_mensual) RETURN CALCULATE(SUM(m_saldo_mensual[saldo_fin_mes]), FILTER(ALL(m_meses), m_meses[fecha_mes] = ultimoMes))",
            "formatString": "\"$\"#,0",
            "lineageTag": "cefaedc4-b1f7-4628-b91e-5b1e8bd96fa5"
          },
          {
            "name": "Cuentas Activas Corte",
            "description": "Cuentas con foto en el último mes del contexto (4,500 en dic-1998)",
            "expression": "VAR ultimoMes = CALCULATE(MAX(m_meses[fecha_mes]), m_saldo_mensual) RETURN CALCULATE(COUNTROWS(m_saldo_mensual), FILTER(ALL(m_meses), m_meses[fecha_mes] = ultimoMes))",
            "formatString": "#,0",
            "lineageTag": "4fa53c8f-887e-4c08-8495-967c1956275e"
          },
          {
            "name": "Cuentas en Sobregiro",
            "description": "Cuentas con saldo negativo al cierre del último mes (39 en dic-1998)",
            "expression": "VAR ultimoMes = CALCULATE(MAX(m_meses[fecha_mes]), m_saldo_mensual) RETURN CALCULATE(CALCULATE(COUNTROWS(m_saldo_mensual), m_saldo_mensual[en_sobregiro] = TRUE()), FILTER(ALL(m_meses), m_meses[fecha_mes] = ultimoMes))",
            "formatString": "#,0",
            "lineageTag": "2168e6c7-5040-40c0-9375-8f1e33cb85d5"
          },
          {
            "name": "Saldo Promedio por Cuenta",
            "description": "Saldo por cuenta activa: aísla el crecimiento por apertura de cuentas",
            "expression": "DIVIDE([Saldo Neto Corte], [Cuentas Activas Corte])",
            "formatString": "\"$\"#,0",
            "lineageTag": "19dd150b-861f-46d9-ad35-07901022d911"
          },
          {
            "name": "Saldo Promedio Banco",
            "description": "Referencia gris de D1",
            "expression": "CALCULATE([Saldo Promedio por Cuenta], REMOVEFILTERS(m_distritos))",
            "formatString": "\"$\"#,0",
            "lineageTag": "ef614694-231d-4a30-9809-439c1c73be8c"
          },
          {
            "name": "Umbral Sobregiro",
            "description": "Línea en 0 de la ficha D2",
            "expression": "IF(NOT ISBLANK([Saldo Neto Corte]), 0)",
            "formatString": "\"$\"#,0.00",
            "lineageTag": "c6c330d2-6970-4b48-acb7-ef1f01c8fcf7"
          },
          {
            "name": "Saldo Neto Corte Total",
            "description": "Saldo al corte dic-1998, sin importar el año elegido",
            "expression": "CALCULATE([Saldo Neto Corte], REMOVEFILTERS(m_anios), REMOVEFILTERS(m_meses))",
            "formatString": "\"$\"#,0",
            "lineageTag": "42f14463-6db1-493b-8061-6f5d5df7e06b"
          },
          {
            "name": "Cartera Vigente Corte",
            "description": "Cartera vigente al corte, sin importar el año elegido",
            "expression": "CALCULATE([Cartera Vigente], REMOVEFILTERS(m_anios), REMOVEFILTERS(m_meses))",
            "formatString": "\"$\"#,0",
            "lineageTag": "5dd1afe5-af87-4381-97f8-ffc775c27a3e"
          },
          {
            "name": "Absorcion Vigente",
            "description": "KPI de liquidez de la Carta v8: cartera vigente / saldo neto al corte (40.73%)",
            "expression": "DIVIDE([Cartera Vigente Corte], [Saldo Neto Corte Total])",
            "formatString": "0.00%",
            "lineageTag": "cd81bd78-fecb-43d7-a227-8b8a1243c559"
          },
          {
            "name": "Absorcion Cartera Total",
            "description": "Referencia histórica: cartera total / saldo neto (52.38%)",
            "expression": "DIVIDE(CALCULATE([Cartera Total], REMOVEFILTERS(m_anios), REMOVEFILTERS(m_meses)), [Saldo Neto Corte Total])",
            "formatString": "0.00%",
            "lineageTag": "d79d3dbc-b6e5-4401-bfd1-f90b343fc720"
          },
          {
            "name": "Absorcion Banco",
            "description": "Referencia de P3: absorción del banco",
            "expression": "CALCULATE([Absorcion Vigente], REMOVEFILTERS(m_distritos))",
            "formatString": "0.00%",
            "lineageTag": "2dd5b517-4021-4b9c-b01e-34efcd4d322d"
          },
          {
            "name": "Liquidez Libre",
            "description": "Saldo que no respalda cartera vigente ($116,844,258)",
            "expression": "[Saldo Neto Corte Total] - [Cartera Vigente Corte]",
            "formatString": "\"$\"#,0",
            "lineageTag": "436541e0-4e4a-48d5-b098-f0719966ddd4"
          },
          {
            "name": "Valor Composicion Liquidez",
            "description": "Cascada de P3; el total es la liquidez libre",
            "expression": "SWITCH(SELECTEDVALUE(Composicion_Liquidez[concepto]), \"Saldo neto al corte\", [Saldo Neto Corte Total], \"Cartera vigente\", -[Cartera Vigente Corte])",
            "formatString": "\"$\"#,0",
            "lineageTag": "ef767489-d533-4579-969b-68eac7d0e1ca"
          },
          {
            "name": "Volumen Transaccionado",
            "description": "$6,257,862,197",
            "expression": "SUM(m_trans_anual[monto_total])",
            "formatString": "\"$\"#,0",
            "lineageTag": "1b792711-e8f8-49e2-9918-91e1244334e1"
          },
          {
            "name": "Num Transacciones",
            "description": "1,056,320",
            "expression": "SUM(m_trans_anual[num_transacciones])",
            "formatString": "#,0",
            "lineageTag": "3c03870f-de65-42f8-b529-40b36409cce7"
          },
          {
            "name": "Ticket Promedio",
            "description": "Monto promedio por movimiento",
            "expression": "DIVIDE([Volumen Transaccionado], [Num Transacciones])",
            "formatString": "\"$\"#,0.00",
            "lineageTag": "7a5ae067-8ac2-481a-ab3c-9ad3edd91021"
          },
          {
            "name": "Desv Est Transaccion",
            "description": "σ muestral exacta desde la suma y la suma de cuadrados",
            "expression": "VAR n = [Num Transacciones] VAR s = [Volumen Transaccionado] VAR sq = SUM(m_trans_anual[suma_cuadrados]) RETURN IF(n > 1, SQRT(DIVIDE(sq - s * s / n, n - 1)))",
            "formatString": "\"$\"#,0.00",
            "lineageTag": "021ed67d-5806-4934-aa97-675878ab3bc5"
          },
          {
            "name": "Ticket Limite Superior",
            "description": "Promedio + 1σ",
            "expression": "[Ticket Promedio] + [Desv Est Transaccion]",
            "formatString": "\"$\"#,0.00",
            "lineageTag": "e12ab31e-8363-4178-ba8b-e0f205557f95"
          },
          {
            "name": "Ticket Limite Inferior",
            "description": "Promedio − 1σ (no negativo)",
            "expression": "MAX(0, [Ticket Promedio] - [Desv Est Transaccion])",
            "formatString": "\"$\"#,0.00",
            "lineageTag": "1b549492-118a-4ee7-a4eb-2b55ea67ceda"
          },
          {
            "name": "EE Ticket",
            "description": "Error estándar (tooltip)",
            "expression": "DIVIDE([Desv Est Transaccion], SQRT([Num Transacciones]))",
            "formatString": "\"$\"#,0.00",
            "lineageTag": "964cffae-61f1-4604-9854-374d4afe4e13"
          },
          {
            "name": "Saldo Promedio Historico",
            "description": "Saldo promedio de la cuenta ponderado por movimientos",
            "expression": "DIVIDE(SUMX(m_trans_anual, m_trans_anual[saldo_promedio] * m_trans_anual[num_transacciones]), [Num Transacciones])",
            "formatString": "\"$\"#,0",
            "lineageTag": "441b184f-cea4-4626-b938-1a263a9fd7d0"
          },
          {
            "name": "Compromiso Ordenes",
            "description": "Órdenes fijas mensuales ($21,229,041)",
            "expression": "SUM(m_ordenes[monto_orden])",
            "formatString": "\"$\"#,0",
            "lineageTag": "312a2887-7641-4898-8270-9286ced78103"
          },
          {
            "name": "Num Ordenes",
            "description": "6,471 órdenes",
            "expression": "COUNTROWS(m_ordenes)",
            "formatString": "#,0",
            "lineageTag": "995ab581-be6e-473d-a8ec-0218d069cb0a"
          },
          {
            "name": "Pct Ordenes",
            "description": "Participación de cada propósito",
            "expression": "DIVIDE([Num Ordenes], CALCULATE([Num Ordenes], REMOVEFILTERS(m_ordenes[categoria_orden])))",
            "formatString": "0.00%",
            "lineageTag": "784dc8af-3336-446a-ac1a-4d8f83a85715"
          },
          {
            "name": "Indice Saturacion",
            "description": "Órdenes mensuales / saldo promedio histórico de la cuenta (cuenta 2335: 2.14)",
            "expression": "DIVIDE([Compromiso Ordenes], CALCULATE([Saldo Promedio Historico], REMOVEFILTERS(m_anios), REMOVEFILTERS(m_meses), REMOVEFILTERS(m_trans_anual[categoria_analitica])))",
            "formatString": "0.00",
            "lineageTag": "a03330a0-1f66-4c2a-a3c9-6a0211f3a6fb"
          },
          {
            "name": "Cuentas Saturadas",
            "description": "CALCULATE + FILTER: cuentas con índice > 0.5 (47)",
            "expression": "COUNTROWS(FILTER(VALUES(m_cuentas[id_cuenta]), [Indice Saturacion] > 0.5))",
            "formatString": "#,0",
            "lineageTag": "de03ce4e-07ff-45fe-9794-639c048fd638"
          },
          {
            "name": "Cuentas Sobre Saldo",
            "description": "Cuentas cuyas órdenes superan su saldo promedio (1)",
            "expression": "COUNTROWS(FILTER(VALUES(m_cuentas[id_cuenta]), [Indice Saturacion] > 1))",
            "formatString": "#,0",
            "lineageTag": "72796b0a-0b5e-4e79-b73c-7e89983c9c21"
          },
          {
            "name": "Cuentas con Credito Externo",
            "description": "Cuentas que pagan un préstamo a otra entidad (35)",
            "expression": "CALCULATE(DISTINCTCOUNT(m_ordenes[id_cuenta]), m_cuentas[tiene_credito_externo] = TRUE())",
            "formatString": "#,0",
            "lineageTag": "4abe2f96-9d59-4122-9987-3542a598160d"
          },
          {
            "name": "Credito Externo Mensual",
            "description": "Cuotas mensuales a otras entidades ($177,154)",
            "expression": "CALCULATE([Compromiso Ordenes], m_cuentas[tiene_credito_externo] = TRUE(), m_ordenes[k_symbol] = \"UVER\")",
            "formatString": "\"$\"#,0",
            "lineageTag": "97798bf2-4b52-44a8-a031-5fb69e4adcec"
          },
          {
            "name": "Indice Saturacion Alerta",
            "description": "Solo cuentas en alerta",
            "expression": "VAR i = [Indice Saturacion] RETURN IF(i > 0.5, i)",
            "formatString": "0.00",
            "lineageTag": "a6ba8aa2-7119-4d8a-a3f4-c333e50e941d"
          },
          {
            "name": "Compromiso Alerta",
            "description": "Solo cuentas en alerta",
            "expression": "IF([Indice Saturacion] > 0.5, [Compromiso Ordenes])",
            "formatString": "\"$\"#,0",
            "lineageTag": "83b253d6-4198-436a-8ae0-79f3226be83a"
          },
          {
            "name": "Saldo Promedio Alerta",
            "description": "Solo cuentas en alerta",
            "expression": "IF([Indice Saturacion] > 0.5, CALCULATE([Saldo Promedio Historico], REMOVEFILTERS(m_anios), REMOVEFILTERS(m_meses), REMOVEFILTERS(m_trans_anual[categoria_analitica])))",
            "formatString": "\"$\"#,0",
            "lineageTag": "6a14cef0-d593-4f3d-8aaf-6031fcf019fc"
          },
          {
            "name": "Credito Externo Alerta",
            "description": "Solo cuentas en alerta",
            "expression": "IF([Indice Saturacion] > 0.5, [Credito Externo Mensual])",
            "formatString": "\"$\"#,0",
            "lineageTag": "f102de96-102c-4f20-8045-ac71a10dd372"
          },
          {
            "name": "Cliente Titular Alerta",
            "description": "Solo cuentas en alerta",
            "expression": "IF([Indice Saturacion] > 0.5, CALCULATE(SELECTEDVALUE(m_clientes[cliente]), m_saldo_mensual))",
            "lineageTag": "a8ccf598-1e97-49e6-a62a-720756ef34d7"
          },
          {
            "name": "Cuenta Alerta",
            "description": "Cuenta del titular en alerta",
            "expression": "IF([Indice Saturacion] > 0.5, CALCULATE(SELECTEDVALUE(m_cuentas[cuenta]), m_saldo_mensual))",
            "lineageTag": "8b7aeb6c-4d52-41eb-8574-ed9d4bbb3367"
          },
          {
            "name": "Titulo Distrito",
            "description": "Título dinámico de D1",
            "expression": "\"Distrito: \" & SELECTEDVALUE(m_distritos[nombre_distrito], \"(varios)\") & \" (\" & SELECTEDVALUE(m_distritos[region], \"varias regiones\") & \")\"",
            "lineageTag": "8530436f-b3b7-4a00-8d96-d614557f2109"
          },
          {
            "name": "Region del Distrito",
            "description": "Región del distrito (tooltip del treemap de P2)",
            "expression": "SELECTEDVALUE(m_distritos[region])",
            "lineageTag": "290cba28-c722-4639-9dd6-c58742df32b8"
          },
          {
            "name": "Poblacion Distrito",
            "description": "Habitantes",
            "expression": "SELECTEDVALUE(m_distritos[poblacion])",
            "formatString": "#,0",
            "lineageTag": "27e3daf8-3b08-4b58-b5c9-ac10fe6881ff"
          },
          {
            "name": "Salario Promedio Distrito",
            "description": "Salario promedio",
            "expression": "SELECTEDVALUE(m_distritos[salario_promedio])",
            "formatString": "\"$\"#,0",
            "lineageTag": "676ef77b-f1e7-4bb2-9c9d-c8ae22197901"
          },
          {
            "name": "Desempleo Distrito 1995",
            "description": "Tasa de desempleo 1995 (%)",
            "expression": "SELECTEDVALUE(m_distritos[tasa_desempleo])",
            "formatString": "0.00",
            "lineageTag": "81242598-6bde-4bc8-8e3f-75399bb65908"
          },
          {
            "name": "Origen Indicadores",
            "description": "Marca el distrito 69 con indicadores imputados",
            "expression": "IF(HASONEVALUE(m_distritos[es_imputado]), IF(VALUES(m_distritos[es_imputado]), \"Imputado (Informe 10)\", \"Fuente original\"))",
            "lineageTag": "b16c6aba-67e8-44d0-acc0-fc100328ef61"
          },
          {
            "name": "Cliente Ficha",
            "description": "Titular de la cuenta (vale si se llega por cliente o por cuenta)",
            "expression": "CALCULATE(SELECTEDVALUE(m_clientes[cliente]), m_saldo_mensual)",
            "lineageTag": "39bab30c-e7ed-4ec8-b329-8387cbdddf97"
          },
          {
            "name": "Cuenta Ficha",
            "description": "Cuenta del titular",
            "expression": "CALCULATE(SELECTEDVALUE(m_cuentas[cuenta]), m_saldo_mensual)",
            "lineageTag": "d1f8178e-e74d-4ac9-ac21-bfa649ca392c"
          },
          {
            "name": "Titulo Cliente",
            "description": "Título dinámico de D2",
            "expression": "\"Ficha 360 · \" & COALESCE([Cliente Ficha], SELECTEDVALUE(m_clientes[cliente], \"(varios clientes)\")) & \" · \" & COALESCE([Cuenta Ficha], \"sin cuenta propia\")",
            "lineageTag": "0378b54b-d98f-4109-b192-12ee60e432b0"
          },
          {
            "name": "Edad Cliente",
            "description": "Edad al 31/12/1998",
            "expression": "CALCULATE(SELECTEDVALUE(m_clientes[edad_corte]), m_saldo_mensual)",
            "formatString": "#,0",
            "lineageTag": "ff6c39ea-e54b-4f0a-a9eb-b5f48fcd5fe5"
          },
          {
            "name": "Segmento Cliente",
            "description": "Segmento de edad (3 grupos del Data Mart)",
            "expression": "CALCULATE(SELECTEDVALUE(m_clientes[segmento_edad]), m_saldo_mensual)",
            "lineageTag": "6b8ac353-acd6-4334-be3e-bc420be69ab8"
          },
          {
            "name": "Arquetipo Cliente",
            "description": "Macro-región y segmento",
            "expression": "CALCULATE(SELECTEDVALUE(m_clientes[arquetipo_demografico]), m_saldo_mensual)",
            "lineageTag": "9b6d95d9-e6c4-4ce3-9ef2-6279c17ed4f8"
          },
          {
            "name": "Calificacion Cliente",
            "description": "Buen / Mal pagador / Sin evaluar",
            "expression": "CALCULATE(SELECTEDVALUE(m_clientes[calificacion_pago]), m_saldo_mensual)",
            "lineageTag": "6b6a7f0e-3e25-44b2-a695-6083a768f91f"
          },
          {
            "name": "Distrito Cuenta",
            "description": "Distrito de la cuenta",
            "expression": "CALCULATE(SELECTEDVALUE(m_distritos[nombre_distrito]), m_saldo_mensual)",
            "lineageTag": "88c4112b-222e-40a8-95cb-704ff2c6656b"
          },
          {
            "name": "Cuota Maxima Prudente",
            "description": "Cuota que deja el ratio en la banda Baja (Informe 04)",
            "expression": "SUM(m_recomendaciones[prestamo_cuota_maxima])",
            "formatString": "\"$\"#,0",
            "lineageTag": "163ddb75-7be1-4d03-8b28-0ff78c430e32"
          },
          {
            "name": "Monto Maximo Prudente",
            "description": "Monto a 36 meses con esa cuota (Informe 04)",
            "expression": "SUM(m_recomendaciones[prestamo_monto_maximo_36m])",
            "formatString": "\"$\"#,0",
            "lineageTag": "56c5f910-a0a7-4b40-a709-a76e33f390ad"
          },
          {
            "name": "Recomendaciones Demograficas",
            "description": "Productos en el top 3 del recomendador demográfico (el más preciso: Hit@1 66.0%)",
            "expression": "CALCULATE(COUNTROWS(m_recomendacion_producto), m_recomendacion_producto[sistema] = \"Demográfico\")",
            "formatString": "#,0",
            "lineageTag": "18d59d56-4086-41e8-ac9b-175c2e19608e"
          },
          {
            "name": "Primera Opcion",
            "description": "Veces que el producto es la primera recomendación",
            "expression": "CALCULATE([Recomendaciones Demograficas], m_recomendacion_producto[posicion] = 1)",
            "formatString": "#,0",
            "lineageTag": "127edb80-d2d6-4e15-b0f5-c82d1952d02e"
          },
          {
            "name": "Recomendaciones kNN",
            "description": "Productos en el top 3 del kNN por perfil exógeno",
            "expression": "CALCULATE(COUNTROWS(m_recomendacion_producto), m_recomendacion_producto[sistema] = \"kNN perfil\")",
            "formatString": "#,0",
            "lineageTag": "57ccb0aa-460b-48e2-826e-dc1f95e16a6c"
          },
          {
            "name": "Descubrimientos kNN",
            "description": "Ofertas del kNN que el demográfico no tiene en su top 3 (2,731)",
            "expression": "CALCULATE([Recomendaciones kNN], m_recomendacion_producto[es_descubrimiento] = TRUE())",
            "formatString": "#,0",
            "lineageTag": "a2a18ef1-8cc6-409e-85f8-a35d1e6af7e4"
          },
          {
            "name": "Clientes con Recomendacion",
            "description": "Titulares con al menos una recomendación",
            "expression": "CALCULATE(DISTINCTCOUNT(m_recomendacion_producto[id_cuenta]), m_recomendacion_producto[sistema] = \"Demográfico\")",
            "formatString": "#,0",
            "lineageTag": "7c911c99-b31b-4902-ae90-674c18729a95"
          },
          {
            "name": "Cuentas que ya lo Usan",
            "description": "Cuentas que ya usan el producto (adopción actual)",
            "expression": "COUNTROWS(m_adopcion_producto)",
            "formatString": "#,0",
            "lineageTag": "2477c564-96b9-4a45-827f-8e59bfd4657a"
          },
          {
            "name": "Titulares",
            "description": "Titulares (una cuenta cada uno: 4,500)",
            "expression": "COUNTROWS(m_capacidad_prestamo)",
            "formatString": "#,0",
            "lineageTag": "2f025a11-880b-48c8-98aa-b591469c3fbd"
          },
          {
            "name": "Penetracion Actual",
            "description": "Cuentas que ya usan el producto / titulares del contexto",
            "expression": "DIVIDE([Cuentas que ya lo Usan], [Titulares])",
            "formatString": "0.00%",
            "lineageTag": "05399f15-24a3-41e5-aac2-a7b97d3b0a59"
          },
          {
            "name": "Producto Mas Recomendado",
            "description": "Primera recomendación más frecuente en el contexto",
            "expression": "VAR x = TOPN(1, VALUES(m_dim_producto[producto]), [Primera Opcion], DESC) RETURN CONCATENATEX(x, m_dim_producto[producto] & \" · \" & FORMAT([Primera Opcion], \"#,0\"), \", \")",
            "lineageTag": "4f7ff124-c709-4480-9b43-e00721740e64"
          },
          {
            "name": "Recomendacion 1",
            "description": "Primera recomendación del titular",
            "expression": "CALCULATE(SELECTEDVALUE(m_recomendacion_producto[producto]), m_recomendacion_producto[sistema] = \"Demográfico\", m_recomendacion_producto[posicion] = 1)",
            "lineageTag": "02a5ff0f-1934-4c56-bc5d-1affb62fdf21"
          },
          {
            "name": "Recomendacion 2",
            "description": "Segunda recomendación del titular",
            "expression": "CALCULATE(SELECTEDVALUE(m_recomendacion_producto[producto]), m_recomendacion_producto[sistema] = \"Demográfico\", m_recomendacion_producto[posicion] = 2)",
            "lineageTag": "baba5f6d-e33e-4731-98de-49cfd577e014"
          },
          {
            "name": "Recomendacion 3",
            "description": "Tercera recomendación del titular",
            "expression": "CALCULATE(SELECTEDVALUE(m_recomendacion_producto[producto]), m_recomendacion_producto[sistema] = \"Demográfico\", m_recomendacion_producto[posicion] = 3)",
            "lineageTag": "b9c81d06-a48d-40b8-b930-d36e05326d1f"
          },
          {
            "name": "Descubrimiento kNN",
            "description": "Productos que el kNN añade para el titular",
            "expression": "CALCULATE(CONCATENATEX(VALUES(m_recomendacion_producto[producto]), m_recomendacion_producto[producto], \", \"), m_recomendacion_producto[sistema] = \"kNN perfil\", m_recomendacion_producto[es_descubrimiento] = TRUE())",
            "lineageTag": "9f1443ff-47ca-4df3-ba2b-b2a93e5d4ec1"
          },
          {
            "name": "Acierto Elegido",
            "description": "Hit@1 del demográfico (66.0%, semilla 42)",
            "expression": "CALCULATE(MAX(m_evaluacion_recomendador[hit_1]), m_evaluacion_recomendador[modelo] = \"Demográfico (arquetipo)\")",
            "formatString": "0.00%",
            "lineageTag": "394e5f06-670b-4183-8928-3c3760a17326"
          },
          {
            "name": "Acierto Popularidad",
            "description": "Hit@1 de recomendar lo más popular (58.5%): la línea base",
            "expression": "CALCULATE(MAX(m_evaluacion_recomendador[hit_1]), m_evaluacion_recomendador[modelo] = \"Popularidad\")",
            "formatString": "0.00%",
            "lineageTag": "7d56bff9-9244-48aa-a676-1ca95e9b516d"
          },
          {
            "name": "Acierto Cola Larga kNN",
            "description": "Hit@1 del kNN en productos poco comunes (37.2%)",
            "expression": "CALCULATE(MAX(m_evaluacion_recomendador[hit_1_cola_larga]), m_evaluacion_recomendador[modelo] = \"kNN usuario-usuario (perfil exógeno)\")",
            "formatString": "0.00%",
            "lineageTag": "2df00d15-7cc5-4a5e-b1a2-a6924c87c07d"
          },
          {
            "name": "Acierto Cola Larga Popularidad",
            "description": "Hit@1 de la popularidad en productos poco comunes (6.3%)",
            "expression": "CALCULATE(MAX(m_evaluacion_recomendador[hit_1_cola_larga]), m_evaluacion_recomendador[modelo] = \"Popularidad\")",
            "formatString": "0.00%",
            "lineageTag": "1496aa74-f7b3-40f0-885b-bce53613ffee"
          },
          {
            "name": "Acierto Hit1",
            "description": "Hit@1 del modelo (gráfico comparativo)",
            "expression": "SUM(m_evaluacion_recomendador[hit_1])",
            "formatString": "0.00%",
            "lineageTag": "fe30cbe7-4a64-480b-b207-5a936235c08b"
          },
          {
            "name": "Acierto Cola Larga",
            "description": "Hit@1 en la cola larga (gráfico comparativo)",
            "expression": "SUM(m_evaluacion_recomendador[hit_1_cola_larga])",
            "formatString": "0.00%",
            "lineageTag": "5623333f-342a-4c17-8cc8-d14e101c7a9e"
          },
          {
            "name": "MRR Modelo",
            "description": "Rango recíproco medio",
            "expression": "SUM(m_evaluacion_recomendador[mrr])",
            "formatString": "0.000",
            "lineageTag": "f9fb4e64-582c-4c49-ab1f-1488d6dab4ea"
          },
          {
            "name": "MRR Confirmacion",
            "description": "MRR con la semilla 2026",
            "expression": "SUM(m_evaluacion_recomendador[mrr_confirmacion])",
            "formatString": "0.000",
            "lineageTag": "3fc6adce-4b1d-4402-90e4-5d78fb30f3ec"
          },
          {
            "name": "Titulares sin Prestamo",
            "description": "3,818",
            "expression": "CALCULATE([Titulares], m_capacidad_prestamo[tiene_prestamo] = FALSE())",
            "formatString": "#,0",
            "lineageTag": "e90a1164-ec31-4432-b148-955c88a6ac98"
          },
          {
            "name": "Prestamos Prudentes Recomendados",
            "description": "Titulares con préstamo en su top 3 (1,721)",
            "expression": "CALCULATE([Titulares], m_capacidad_prestamo[prestamo_recomendado] = TRUE())",
            "formatString": "#,0",
            "lineageTag": "e3d961de-2b91-4702-9629-6a88d091bedb"
          },
          {
            "name": "Cuota Prudente Mediana",
            "description": "5.7% del saldo promedio, mediana de los titulares sin préstamo (1,873)",
            "expression": "CALCULATE(MEDIAN(m_capacidad_prestamo[cuota_prudente]), m_capacidad_prestamo[tiene_prestamo] = FALSE())",
            "formatString": "\"$\"#,0.00",
            "lineageTag": "2fa0a48f-c116-461f-98ce-8c834d9c683c"
          },
          {
            "name": "Pueden Pagar Prestamo Tipico",
            "description": "Titulares sin préstamo cuya cuota prudente cubre la cuota mediana otorgada (71)",
            "expression": "CALCULATE([Titulares], m_capacidad_prestamo[puede_pagar_prestamo_tipico] = TRUE())",
            "formatString": "#,0",
            "lineageTag": "a38bbc2c-3fe0-4547-9445-f86fd8f98f65"
          },
          {
            "name": "Monto Prudente Ofrecible 36m",
            "description": "Suma de montos máximos a 36 meses de los préstamos recomendados",
            "expression": "CALCULATE(SUM(m_capacidad_prestamo[monto_maximo_36m]), m_capacidad_prestamo[prestamo_recomendado] = TRUE())",
            "formatString": "\"$\"#,0",
            "lineageTag": "35c1e073-d578-40b9-98f0-0fa0ff699f79"
          },
          {
            "name": "Saldo Promedio Oferta",
            "description": "Saldo promedio del titular con préstamo recomendado",
            "expression": "CALCULATE(SUM(m_capacidad_prestamo[saldo_promedio]), m_capacidad_prestamo[prestamo_recomendado] = TRUE())",
            "formatString": "\"$\"#,0",
            "lineageTag": "c3c259b6-a226-4c2d-b35b-22724f1fa9eb"
          },
          {
            "name": "Cuota Prudente Oferta",
            "description": "Cuota prudente del titular con préstamo recomendado",
            "expression": "CALCULATE(SUM(m_capacidad_prestamo[cuota_prudente]), m_capacidad_prestamo[prestamo_recomendado] = TRUE())",
            "formatString": "\"$\"#,0",
            "lineageTag": "10e99faf-23ca-4daf-8ee2-0d8c7c9feb4a"
          },
          {
            "name": "Monto 12m Oferta",
            "description": "Monto máximo a 12 meses",
            "expression": "CALCULATE(SUM(m_capacidad_prestamo[monto_maximo_12m]), m_capacidad_prestamo[prestamo_recomendado] = TRUE())",
            "formatString": "\"$\"#,0",
            "lineageTag": "6e58f1df-4d33-4afc-8a75-beea3c15c5cb"
          },
          {
            "name": "Monto 36m Oferta",
            "description": "Monto máximo a 36 meses",
            "expression": "CALCULATE(SUM(m_capacidad_prestamo[monto_maximo_36m]), m_capacidad_prestamo[prestamo_recomendado] = TRUE())",
            "formatString": "\"$\"#,0",
            "lineageTag": "7d2cca59-3039-4666-9da8-d9a343fb3fb4"
          },
          {
            "name": "Monto 60m Oferta",
            "description": "Monto máximo a 60 meses",
            "expression": "CALCULATE(SUM(m_capacidad_prestamo[monto_maximo_60m]), m_capacidad_prestamo[prestamo_recomendado] = TRUE())",
            "formatString": "\"$\"#,0",
            "lineageTag": "2b638bda-aadf-4d00-90d9-3c906a91820d"
          },
          {
            "name": "AUC Regla",
            "description": "AUC de la regla para predecir el impago",
            "expression": "MAX(m_regla_capacidad[auc])",
            "formatString": "0.000",
            "lineageTag": "5172364f-a799-42a0-9346-f15118b36e15"
          },
          {
            "name": "AUC Regla Elegida",
            "description": "0.717",
            "expression": "CALCULATE([AUC Regla], m_regla_capacidad[regla] = \"Carta v8: cuota / saldo previo\")",
            "formatString": "0.000",
            "lineageTag": "f8ec12b4-f3ac-4f05-8c24-aa5d48f62820"
          },
          {
            "name": "AUC Regla Anterior",
            "description": "0.659",
            "expression": "CALCULATE([AUC Regla], m_regla_capacidad[regla] = \"Anterior: cuota / salario del distrito\")",
            "formatString": "0.000",
            "lineageTag": "3e9d86f3-a5bf-4e60-973a-848b70cf8e06"
          },
          {
            "name": "P Destino dado Origen",
            "description": "De quienes tienen el producto de origen, % que también tiene el de destino",
            "expression": "SUM(m_asociacion_producto[p_destino_dado_origen])",
            "formatString": "0.00%",
            "lineageTag": "0bbaa8f9-0ccb-4730-8382-4805a287860f"
          },
          {
            "name": "Lift Asociacion",
            "description": "Lift: > 1 van juntos más de lo esperado por azar",
            "expression": "SUM(m_asociacion_producto[lift])",
            "formatString": "0.00",
            "lineageTag": "7e5d6698-97c0-43c2-8971-b4862daf39ca"
          },
          {
            "name": "Regla Mas Fuerte",
            "description": "Par con mayor lift (al menos 100 cuentas), en la dirección de mayor P(j|i): Seguro → Transferencias 99.8%",
            "expression": "VAR x = TOPN(1, FILTER(m_asociacion_producto, m_asociacion_producto[cuentas_ambos] >= 100), m_asociacion_producto[lift], DESC, m_asociacion_producto[p_destino_dado_origen], DESC) RETURN CONCATENATEX(x, m_asociacion_producto[producto_origen] & \" → \" & m_asociacion_producto[producto_destino] & \" · \" & FORMAT(m_asociacion_producto[p_destino_dado_origen], \"0.0%\"), \", \")",
            "lineageTag": "7c004287-8ff9-4070-a524-f64e23dc898a"
          },
          {
            "name": "Color Mora",
            "description": "Treemap de P2: escala secuencial blanco → bermellón por tasa de mora",
            "expression": "VAR x = [Tasa Mora Vigente] RETURN SWITCH(TRUE(), ISBLANK(x), \"#FFFFFF\", x < 0.05, \"#FBE3D3\", x < 0.10, \"#F2B48C\", x < 0.15, \"#E5813F\", \"#D55E00\")",
            "lineageTag": "d7fb11c6-3906-42e1-b388-8d0431b0dc3a"
          },
          {
            "name": "Color Saturacion",
            "description": "Dispersión de P5: bermellón > 1, naranja > 0.5, gris el resto",
            "expression": "VAR x = [Indice Saturacion] RETURN IF(x > 1, \"#D55E00\", IF(x > 0.5, \"#E69F00\", \"#7F7F7F\"))",
            "lineageTag": "f0f5ab34-eb81-4d03-82c3-7d7317b26544"
          },
          {
            "name": "Color Modelo",
            "description": "R1: modelos elegidos en azul, el resto en gris",
            "expression": "IF(SELECTEDVALUE(m_evaluacion_recomendador[elegido]) = TRUE(), \"#0072B2\", \"#BDBDBD\")",
            "lineageTag": "801035a1-802c-49c8-9768-d29953307bfe"
          },
          {
            "name": "Color Regla",
            "description": "R2: regla elegida en azul",
            "expression": "IF(SELECTEDVALUE(m_regla_capacidad[regla]) = \"Carta v8: cuota / saldo previo\", \"#0072B2\", \"#BDBDBD\")",
            "lineageTag": "a18b7059-c5e7-43d5-885a-7537ec5d6478"
          }
        ],
        "partitions": [
          {
            "name": "_Medidas",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = #table(type table [Medidas = text], {{\"Guía 07 v4\"}})",
                "in",
                "    Origen"
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}