{
  "name": "Dashboard_Financial_Mongo",
  "compatibilityLevel": 1606,
  "model": {
    "culture": "es-ES",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "es-ES",
    "tables": [
      {
        "name": "m_distritos",
        "columns": [
          {
            "name": "id_distrito",
            "dataType": "int64",
            "sourceColumn": "id_distrito",
            "summarizeBy": "none"
          },
          {
            "name": "nombre_distrito",
            "dataType": "string",
            "sourceColumn": "nombre_distrito",
            "summarizeBy": "none"
          },
          {
            "name": "region",
            "dataType": "string",
            "sourceColumn": "region",
            "summarizeBy": "none"
          },
          {
            "name": "poblacion",
            "dataType": "int64",
            "sourceColumn": "poblacion",
            "summarizeBy": "none"
          },
          {
            "name": "salario_promedio",
            "dataType": "double",
            "sourceColumn": "salario_promedio",
            "summarizeBy": "none",
            "formatString": "\"$\"#,0"
          },
          {
            "name": "tasa_desempleo",
            "dataType": "double",
            "sourceColumn": "tasa_desempleo",
            "summarizeBy": "none",
            "formatString": "0.00"
          },
          {
            "name": "tasa_criminalidad",
            "dataType": "double",
            "sourceColumn": "tasa_criminalidad",
            "summarizeBy": "none",
            "formatString": "0.00"
          },
          {
            "name": "es_imputado",
            "dataType": "boolean",
            "sourceColumn": "es_imputado",
            "summarizeBy": "none"
          },
          {
            "name": "macro_region",
            "dataType": "string",
            "sourceColumn": "macro_region",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "m_distritos",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Origen = MongoFinancial,",
                "    Tabla = Origen{[Name=\"m_distritos\"]}[Value],",
                "    Columnas = Table.SelectColumns(Tabla, {\"id_distrito\", \"nombre_distrito\", \"region\", \"poblacion\", \"salario_promedio\", \"tasa_desempleo\", \"tasa_criminalidad\", \"es_imputado\", \"macro_region\"}),",
                "    Tipos = Table.TransformColumnTypes(Columnas, {{\"id_distrito\", Int64.Type}, {\"nombre_distrito\", type text}, {\"region\", type text}, {\"poblacion\", Int64.Type}, {\"salario_promedio\", type number}, {\"tasa_desempleo\", type number}, {\"tasa_criminalidad\", type number}, {\"es_imputado\", type logical}, {\"macro_region\", type text}}, \"en-US\")",
                "in",
                "    Tipos"
              ]
            }
          }
        ]
      },
      {
        "name": "m_clientes",
        "columns": [
          {
            "name": "id_cliente",
            "dataType": "int64",
            "sourceColumn": "id_cliente",
            "summarizeBy": "none"
          },
          {
            "name": "cliente",
            "dataType": "string",
            "sourceColumn": "cliente",
            "summarizeBy": "none"
          },
          {
            "name": "sexo",
            "dataType": "string",
            "sourceColumn": "sexo",
            "summarizeBy": "none"
          },
          {
            "name": "edad_corte",
            "dataType": "int64",
            "sourceColumn": "edad_corte",
            "summarizeBy": "none"
          },
          {
            "name": "tipo_disposicion",
            "dataType": "string",
            "sourceColumn": "tipo_disposicion",
            "summarizeBy": "none"
          },
          {
            "name": "segmento_edad",
            "dataType": "string",
            "sourceColumn": "segmento_edad",
            "summarizeBy": "none",
            "sortByColumn": "orden_segmento"
          },
          {
            "name": "arquetipo_demografico",
            "dataType": "string",
            "sourceColumn": "arquetipo_demografico",
            "summarizeBy": "none"
          },
          {
            "name": "calificacion_pago",
            "dataType": "string",
            "sourceColumn": "calificacion_pago",
            "summarizeBy": "none"
          },
          {
            "name": "orden_segmento",
            "dataType": "int64",
            "sourceColumn": "orden_segmento",
            "summarizeBy": "none",
            "isHidden": true
          }
        ],
        "partitions": [
          {
            "name": "m_clientes",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Origen = MongoFinancial,",
                "    Tabla = Origen{[Name=\"m_clientes\"]}[Value],",
                "    Columnas = Table.SelectColumns(Tabla, {\"id_cliente\", \"cliente\", \"sexo\", \"edad_corte\", \"tipo_disposicion\", \"segmento_edad\", \"arquetipo_demografico\", \"calificacion_pago\", \"orden_segmento\"}),",
                "    Tipos = Table.TransformColumnTypes(Columnas, {{\"id_cliente\", Int64.Type}, {\"cliente\", type text}, {\"sexo\", type text}, {\"edad_corte\", Int64.Type}, {\"tipo_disposicion\", type text}, {\"segmento_edad\", type text}, {\"arquetipo_demografico\", type text}, {\"calificacion_pago\", type text}, {\"orden_segmento\", Int64.Type}}, \"en-US\")",
                "in",
                "    Tipos"
              ]
            }
          }
        ]
      },
      {
        "name": "m_cuentas",
        "columns": [
          {
            "name": "id_cuenta",
            "dataType": "int64",
            "sourceColumn": "id_cuenta",
            "summarizeBy": "none"
          },
          {
            "name": "frecuencia_extracto",
            "dataType": "string",
            "sourceColumn": "frecuencia_extracto",
            "summarizeBy": "none"
          },
          {
            "name": "fecha_apertura",
            "dataType": "dateTime",
            "sourceColumn": "fecha_apertura",
            "summarizeBy": "none",
            "formatString": "dd/mm/yyyy"
          },
          {
            "name": "tiene_credito_externo",
            "dataType": "boolean",
            "sourceColumn": "tiene_credito_externo",
            "summarizeBy": "none"
          },
          {
            "name": "monto_credito_externo",
            "dataType": "double",
            "sourceColumn": "monto_credito_externo",
            "summarizeBy": "none",
            "formatString": "\"$\"#,0"
          },
          {
            "type": "calculated",
            "name": "cuenta",
            "dataType": "string",
            "expression": "\"Cuenta \" & m_cuentas[id_cuenta]",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "m_cuentas",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Origen = MongoFinancial,",
                "    Tabla = Origen{[Name=\"m_cuentas\"]}[Value],",
                "    Columnas = Table.SelectColumns(Tabla, {\"id_cuenta\", \"frecuencia_extracto\", \"fecha_apertura\", \"tiene_credito_externo\", \"monto_credito_externo\"}),",
                "    Tipos = Table.TransformColumnTypes(Columnas, {{\"id_cuenta\", Int64.Type}, {\"frecuencia_extracto\", type text}, {\"fecha_apertura\", type datetime}, {\"tiene_credito_externo\", type logical}, {\"monto_credito_externo\", type number}}, \"en-US\")",
                "in",
                "    Tipos"
              ]
            }
          }
        ]
      },
      {
        "name": "m_anios",
        "columns": [
          {
            "name": "anio",
            "dataType": "int64",
            "sourceColumn": "anio",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "m_anios",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Origen = MongoFinancial,",
                "    Tabla = Origen{[Name=\"m_anios\"]}[Value],",
                "    Columnas = Table.SelectColumns(Tabla, {\"anio\"}),",
                "    Tipos = Table.TransformColumnTypes(Columnas, {{\"anio\", Int64.Type}}, \"en-US\")",
                "in",
                "    Tipos"
              ]
            }
          }
        ]
      },
      {
        "name": "m_meses",
        "columns": [
          {
            "name": "fecha_mes",
            "dataType": "dateTime",
            "sourceColumn": "fecha_mes",
            "summarizeBy": "none",
            "formatString": "dd/mm/yyyy"
          },
          {
            "name": "anio",
            "dataType": "int64",
            "sourceColumn": "anio",
            "summarizeBy": "none"
          },
          {
            "name": "mes",
            "dataType": "int64",
            "sourceColumn": "mes",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "m_meses",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Origen = MongoFinancial,",
                "    Tabla = Origen{[Name=\"m_meses\"]}[Value],",
                "    Columnas = Table.SelectColumns(Tabla, {\"fecha_mes\", \"anio\", \"mes\"}),",
                "    Tipos = Table.TransformColumnTypes(Columnas, {{\"fecha_mes\", type datetime}, {\"anio\", Int64.Type}, {\"mes\", Int64.Type}}, \"en-US\")",
                "in",
                "    Tipos"
              ]
            }
          }
        ]
      },
      {
        "name": "m_prestamos",
        "columns": [
          {
            "name": "id_prestamo",
            "dataType": "int64",
            "sourceColumn": "id_prestamo",
            "summarizeBy": "none"
          },
          {
            "name": "id_cuenta",
            "dataType": "int64",
            "sourceColumn": "id_cuenta",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "id_cliente",
            "dataType": "int64",
            "sourceColumn": "id_cliente",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "id_distrito",
            "dataType": "int64",
            "sourceColumn": "id_distrito",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "fecha_otorgamiento",
            "dataType": "dateTime",
            "sourceColumn": "fecha_otorgamiento",
            "summarizeBy": "none",
            "formatString": "dd/mm/yyyy"
          },
          {
            "name": "anio",
            "dataType": "int64",
            "sourceColumn": "anio",
            "summarizeBy": "none"
          },
          {
            "name": "monto_prestamo",
            "dataType": "double",
            "sourceColumn": "monto_prestamo",
            "summarizeBy": "none",
            "formatString": "\"$\"#,0"
          },
          {
            "name": "plazo_meses",
            "dataType": "int64",
            "sourceColumn": "plazo_meses",
            "summarizeBy": "none"
          },
          {
            "name": "pago_mensual",
            "dataType": "double",
            "sourceColumn": "pago_mensual",
            "summarizeBy": "none",
            "formatString": "\"$\"#,0"
          },
          {
            "name": "saldo_pendiente_estimado",
            "dataType": "double",
            "sourceColumn": "saldo_pendiente_estimado",
            "summarizeBy": "none",
            "formatString": "\"$\"#,0"
          },
          {
            "name": "meses_transcurridos_al_corte",
            "dataType": "int64",
            "sourceColumn": "meses_transcurridos_al_corte",
            "summarizeBy": "none"
          },
          {
            "name": "codigo_estado",
            "dataType": "string",
            "sourceColumn": "codigo_estado",
            "summarizeBy": "none"
          },
          {
            "name": "condicion",
            "dataType": "string",
            "sourceColumn": "condicion",
            "summarizeBy": "none"
          },
          {
            "name": "descripcion_estado",
            "dataType": "string",
            "sourceColumn": "descripcion_estado",
            "summarizeBy": "none"
          },
          {
            "name": "saldo_promedio_previo",
            "dataType": "double",
            "sourceColumn": "saldo_promedio_previo",
            "summarizeBy": "none",
            "formatString": "\"$\"#,0"
          },
          {
            "name": "ratio_cuota_saldo_previo",
            "dataType": "double",
            "sourceColumn": "ratio_cuota_saldo_previo",
            "summarizeBy": "none",
            "formatString": "0.00%"
          },
          {
            "name": "banda_capacidad",
            "dataType": "string",
            "sourceColumn": "banda_capacidad",
            "summarizeBy": "none",
            "sortByColumn": "orden_banda"
          },
          {
            "name": "orden_banda",
            "dataType": "int64",
            "sourceColumn": "orden_banda",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "type": "calculated",
            "name": "estado",
            "dataType": "string",
            "expression": "SWITCH(m_prestamos[codigo_estado], \"A\", \"A · Cerrado al día\", \"B\", \"B · Cerrado con deuda\", \"C\", \"C · Vigente al día\", \"D\", \"D · Vigente en mora\")",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "m_prestamos",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Origen = MongoFinancial,",
                "    Tabla = Origen{[Name=\"m_prestamos\"]}[Value],",
                "    Columnas = Table.SelectColumns(Tabla, {\"id_prestamo\", \"id_cuenta\", \"id_cliente\", \"id_distrito\", \"fecha_otorgamiento\", \"anio\", \"monto_prestamo\", \"plazo_meses\", \"pago_mensual\", \"saldo_pendiente_estimado\", \"meses_transcurridos_al_corte\", \"codigo_estado\", \"condicion\", \"descripcion_estado\", \"saldo_promedio_previo\", \"ratio_cuota_saldo_previo\", \"banda_capacidad\", \"orden_banda\"}),",
                "    Tipos = Table.TransformColumnTypes(Columnas, {{\"id_prestamo\", Int64.Type}, {\"id_cuenta\", Int64.Type}, {\"id_cliente\", Int64.Type}, {\"id_distrito\", Int64.Type}, {\"fecha_otorgamiento\", type datetime}, {\"anio\", Int64.Type}, {\"monto_prestamo\", type number}, {\"plazo_meses\", Int64.Type}, {\"pago_mensual\", type number}, {\"saldo_pendiente_estimado\", type number}, {\"meses_transcurridos_al_corte\", Int64.Type}, {\"codigo_estado\", type text}, {\"condicion\", type text}, {\"descripcion_estado\", type text}, {\"saldo_promedio_previo\", type number}, {\"ratio_cuota_saldo_previo\", type number}, {\"banda_capacidad\", type text}, {\"orden_banda\", Int64.Type}}, \"en-US\")",
                "in",
                "    Tipos"
              ]
            }
          }
        ]
      },
      {
        "name": "m_ordenes",
        "columns": [
          {
            "name": "id_orden",
            "dataType": "int64",
            "sourceColumn": "id_orden",
            "summarizeBy": "none"
          },
          {
            "name": "id_cuenta",
            "dataType": "int64",
            "sourceColumn": "id_cuenta",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "id_cliente",
            "dataType": "int64",
            "sourceColumn": "id_cliente",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "id_distrito",
            "dataType": "int64",
            "sourceColumn": "id_distrito",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "k_symbol",
            "dataType": "string",
            "sourceColumn": "k_symbol",
            "summarizeBy": "none"
          },
          {
            "name": "categoria_orden",
            "dataType": "string",
            "sourceColumn": "categoria_orden",
            "summarizeBy": "none"
          },
          {
            "name": "monto_orden",
            "dataType": "double",
            "sourceColumn": "monto_orden",
            "summarizeBy": "none",
            "formatString": "\"$\"#,0"
          }
        ],
        "partitions": [
          {
            "name": "m_ordenes",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Origen = MongoFinancial,",
                "    Tabla = Origen{[Name=\"m_ordenes\"]}[Value],",
                "    Columnas = Table.SelectColumns(Tabla, {\"id_orden\", \"id_cuenta\", \"id_cliente\", \"id_distrito\", \"k_symbol\", \"categoria_orden\", \"monto_orden\"}),",
                "    Tipos = Table.TransformColumnTypes(Columnas, {{\"id_orden\", Int64.Type}, {\"id_cuenta\", Int64.Type}, {\"id_cliente\", Int64.Type}, {\"id_distrito\", Int64.Type}, {\"k_symbol\", type text}, {\"categoria_orden\", type text}, {\"monto_orden\", type number}}, \"en-US\")",
                "in",
                "    Tipos"
              ]
            }
          }
        ]
      },
      {
        "name": "m_trans_anual",
        "columns": [
          {
            "name": "id_cuenta",
            "dataType": "int64",
            "sourceColumn": "id_cuenta",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "id_cliente",
            "dataType": "int64",
            "sourceColumn": "id_cliente",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "id_distrito",
            "dataType": "int64",
            "sourceColumn": "id_distrito",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "anio",
            "dataType": "int64",
            "sourceColumn": "anio",
            "summarizeBy": "none"
          },
          {
            "name": "categoria_analitica",
            "dataType": "string",
            "sourceColumn": "categoria_analitica",
            "summarizeBy": "none"
          },
          {
            "name": "num_transacciones",
            "dataType": "int64",
            "sourceColumn": "num_transacciones",
            "summarizeBy": "none"
          },
          {
            "name": "monto_total",
            "dataType": "double",
            "sourceColumn": "monto_total",
            "summarizeBy": "none",
            "formatString": "\"$\"#,0"
          },
          {
            "name": "suma_cuadrados",
            "dataType": "double",
            "sourceColumn": "suma_cuadrados",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "saldo_promedio",
            "dataType": "double",
            "sourceColumn": "saldo_promedio",
            "summarizeBy": "none",
            "formatString": "\"$\"#,0"
          }
        ],
        "partitions": [
          {
            "name": "m_trans_anual",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Origen = MongoFinancial,",
                "    Tabla = Origen{[Name=\"m_trans_anual\"]}[Value],",
                "    Columnas = Table.SelectColumns(Tabla, {\"id_cuenta\", \"id_cliente\", \"id_distrito\", \"anio\", \"categoria_analitica\", \"num_transacciones\", \"monto_total\", \"suma_cuadrados\", \"saldo_promedio\"}),",
                "    Tipos = Table.TransformColumnTypes(Columnas, {{\"id_cuenta\", Int64.Type}, {\"id_cliente\", Int64.Type}, {\"id_distrito\", Int64.Type}, {\"anio\", Int64.Type}, {\"categoria_analitica\", type text}, {\"num_transacciones\", Int64.Type}, {\"monto_total\", type number}, {\"suma_cuadrados\", type number}, {\"saldo_promedio\", type number}}, \"en-US\")",
                "in",
                "    Tipos"
              ]
            }
          }
        ]
      },
      {
        "name": "m_saldo_mensual",
        "columns": [
          {
            "name": "id_cuenta",
            "dataType": "int64",
            "sourceColumn": "id_cuenta",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "id_cliente",
            "dataType": "int64",
            "sourceColumn": "id_cliente",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "id_distrito",
            "dataType": "int64",
            "sourceColumn": "id_distrito",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "anio",
            "dataType": "int64",
            "sourceColumn": "anio",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "mes",
            "dataType": "int64",
            "sourceColumn": "mes",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "fecha_mes",
            "dataType": "dateTime",
            "sourceColumn": "fecha_mes",
            "summarizeBy": "none",
            "formatString": "dd/mm/yyyy"
          },
          {
            "name": "saldo_fin_mes",
            "dataType": "double",
            "sourceColumn": "saldo_fin_mes",
            "summarizeBy": "none",
            "formatString": "\"$\"#,0"
          },
          {
            "name": "saldo_promedio_mes",
            "dataType": "double",
            "sourceColumn": "saldo_promedio_mes",
            "summarizeBy": "none",
            "formatString": "\"$\"#,0"
          },
          {
            "name": "num_movimientos_mes",
            "dataType": "int64",
            "sourceColumn": "num_movimientos_mes",
            "summarizeBy": "none"
          },
          {
            "name": "en_sobregiro",
            "dataType": "boolean",
            "sourceColumn": "en_sobregiro",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "m_saldo_mensual",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Origen = MongoFinancial,",
                "    Tabla = Origen{[Name=\"m_saldo_mensual\"]}[Value],",
                "    Columnas = Table.SelectColumns(Tabla, {\"id_cuenta\", \"id_cliente\", \"id_distrito\", \"anio\", \"mes\", \"fecha_mes\", \"saldo_fin_mes\", \"saldo_promedio_mes\", \"num_movimientos_mes\", \"en_sobregiro\"}),",
                "    Tipos = Table.TransformColumnTypes(Columnas, {{\"id_cuenta\", Int64.Type}, {\"id_cliente\", Int64.Type}, {\"id_distrito\", Int64.Type}, {\"anio\", Int64.Type}, {\"mes\", Int64.Type}, {\"fecha_mes\", type datetime}, {\"saldo_fin_mes\", type number}, {\"saldo_promedio_mes\", type number}, {\"num_movimientos_mes\", Int64.Type}, {\"en_sobregiro\", type logical}}, \"en-US\")",
                "in",
                "    Tipos"
              ]
            }
          }
        ]
      },
      {
        "name": "m_recomendaciones",
        "columns": [
          {
            "name": "id_cuenta",
            "dataType": "int64",
            "sourceColumn": "id_cuenta",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "id_cliente",
            "dataType": "int64",
            "sourceColumn": "id_cliente",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "modelo",
            "dataType": "string",
            "sourceColumn": "modelo",
            "summarizeBy": "none"
          },
          {
            "name": "recomendacion_1",
            "dataType": "string",
            "sourceColumn": "recomendacion_1",
            "summarizeBy": "none"
          },
          {
            "name": "recomendacion_2",
            "dataType": "string",
            "sourceColumn": "recomendacion_2",
            "summarizeBy": "none"
          },
          {
            "name": "recomendacion_3",
            "dataType": "string",
            "sourceColumn": "recomendacion_3",
            "summarizeBy": "none"
          },
          {
            "name": "prestamo_cuota_maxima",
            "dataType": "double",
            "sourceColumn": "prestamo_cuota_maxima",
            "summarizeBy": "none",
            "formatString": "\"$\"#,0"
          },
          {
            "name": "prestamo_monto_maximo_36m",
            "dataType": "double",
            "sourceColumn": "prestamo_monto_maximo_36m",
            "summarizeBy": "none",
            "formatString": "\"$\"#,0"
          }
        ],
        "partitions": [
          {
            "name": "m_recomendaciones",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Origen = MongoFinancial,",
                "    Tabla = Origen{[Name=\"m_recomendaciones\"]}[Value],",
                "    Columnas = Table.SelectColumns(Tabla, {\"id_cuenta\", \"id_cliente\", \"modelo\", \"recomendacion_1\", \"recomendacion_2\", \"recomendacion_3\", \"prestamo_cuota_maxima\", \"prestamo_monto_maximo_36m\"}),",
                "    Tipos = Table.TransformColumnTypes(Columnas, {{\"id_cuenta\", Int64.Type}, {\"id_cliente\", Int64.Type}, {\"modelo\", type text}, {\"recomendacion_1\", type text}, {\"recomendacion_2\", type text}, {\"recomendacion_3\", type text}, {\"prestamo_cuota_maxima\", type number}, {\"prestamo_monto_maximo_36m\", type number}}, \"en-US\")",
                "in",
                "    Tipos"
              ]
            }
          }
        ]
      },
      {
        "name": "Composicion_Liquidez",
        "columns": [
          {
            "name": "concepto",
            "dataType": "string",
            "sourceColumn": "concepto",
            "summarizeBy": "none",
            "sortByColumn": "orden"
          },
          {
            "name": "orden",
            "dataType": "int64",
            "sourceColumn": "orden",
            "summarizeBy": "none",
            "isHidden": true
          }
        ],
        "partitions": [
          {
            "name": "Composicion_Liquidez",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Origen = #table(type table [concepto = text, orden = Int64.Type], {{\"Saldo neto al corte\", 1}, {\"Cartera vigente\", 2}})",
                "in",
                "    Origen"
              ]
            }
          }
        ]
      },
      {
        "name": "_Medidas",
        "columns": [
          {
            "name": "Medidas",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Medidas",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "_Medidas",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Origen = #table(type table [Medidas = text], {{\"Guía 07 v4\"}})",
                "in",
                "    Origen"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Num Prestamos",
            "expression": "COUNTROWS(m_prestamos)",
            "description": "Préstamos otorgados (682)",
            "formatString": "#,0"
          },
          {
            "name": "Prestamos en Mora",
            "expression": "CALCULATE([Num Prestamos], m_prestamos[codigo_estado] = \"D\")",
            "description": "Vigentes en mora, estado D (45)",
            "formatString": "#,0"
          },
          {
            "name": "Prestamos Vigentes",
            "expression": "CALCULATE([Num Prestamos], m_prestamos[codigo_estado] IN {\"C\", \"D\"})",
            "description": "Estados C + D (448)",
            "formatString": "#,0"
          },
          {
            "name": "Prestamos Incumplidos",
            "expression": "CALCULATE([Num Prestamos], m_prestamos[codigo_estado] = \"B\")",
            "description": "Cerrados con deuda, estado B (31)",
            "formatString": "#,0"
          },
          {
            "name": "Prestamos Cerrados",
            "expression": "CALCULATE([Num Prestamos], m_prestamos[codigo_estado] IN {\"A\", \"B\"})",
            "description": "Estados A + B (234)",
            "formatString": "#,0"
          },
          {
            "name": "Prestamos con Impago",
            "expression": "CALCULATE([Num Prestamos], m_prestamos[codigo_estado] IN {\"B\", \"D\"})",
            "description": "Estados B + D (76)",
            "formatString": "#,0"
          },
          {
            "name": "Tasa Mora Vigente",
            "expression": "IF([Prestamos Vigentes] > 0, DIVIDE([Prestamos en Mora] + 0, [Prestamos Vigentes]))",
            "description": "D / (C + D) = 10.04%; 0% (no vacío) si hay vigentes sin mora, p. ej. north Bohemia 0/41",
            "formatString": "0.00%"
          },
          {
            "name": "Tasa Incumplimiento",
            "expression": "IF([Prestamos Cerrados] > 0, DIVIDE([Prestamos Incumplidos] + 0, [Prestamos Cerrados]))",
            "description": "B / (A + B) = 13.25%",
            "formatString": "0.00%"
          },
          {
            "name": "Tasa Impago",
            "expression": "IF([Num Prestamos] > 0, DIVIDE([Prestamos con Impago] + 0, [Num Prestamos]))",
            "description": "(B + D) / total = 11.14%; es la tasa de P6 por banda de capacidad",
            "formatString": "0.00%"
          },
          {
            "name": "Mora Wilson Inferior",
            "expression": "VAR n = [Prestamos Vigentes] VAR p = DIVIDE([Prestamos en Mora] + 0, n) VAR c = DIVIDE(p + 1 / (2 * n), 1 + 1 / n) VAR m = DIVIDE(1, 1 + 1 / n) * SQRT(p * (1 - p) / n + 1 / (4 * n * n)) RETURN IF(n > 0, c - m)",
            "description": "Límite inferior de Wilson (z = 1) de mora",
            "formatString": "0.00%"
          },
          {
            "name": "Mora Wilson Superior",
            "expression": "VAR n = [Prestamos Vigentes] VAR p = DIVIDE([Prestamos en Mora] + 0, n) VAR c = DIVIDE(p + 1 / (2 * n), 1 + 1 / n) VAR m = DIVIDE(1, 1 + 1 / n) * SQRT(p * (1 - p) / n + 1 / (4 * n * n)) RETURN IF(n > 0, c + m)",
            "description": "Límite superior de Wilson (z = 1) de mora",
            "formatString": "0.00%"
          },
          {
            "name": "Incumplimiento Wilson Inferior",
            "expression": "VAR n = [Prestamos Cerrados] VAR p = DIVIDE([Prestamos Incumplidos] + 0, n) VAR c = DIVIDE(p + 1 / (2 * n), 1 + 1 / n) VAR m = DIVIDE(1, 1 + 1 / n) * SQRT(p * (1 - p) / n + 1 / (4 * n * n)) RETURN IF(n > 0, c - m)",
            "description": "Límite inferior de Wilson (z = 1) de incumplimiento",
            "formatString": "0.00%"
          },
          {
            "name": "Incumplimiento Wilson Superior",
            "expression": "VAR n = [Prestamos Cerrados] VAR p = DIVIDE([Prestamos Incumplidos] + 0, n) VAR c = DIVIDE(p + 1 / (2 * n), 1 + 1 / n) VAR m = DIVIDE(1, 1 + 1 / n) * SQRT(p * (1 - p) / n + 1 / (4 * n * n)) RETURN IF(n > 0, c + m)",
            "description": "Límite superior de Wilson (z = 1) de incumplimiento",
            "formatString": "0.00%"
          },
          {
            "name": "Impago Wilson Inferior",
            "expression": "VAR n = [Num Prestamos] VAR p = DIVIDE([Prestamos con Impago] + 0, n) VAR c = DIVIDE(p + 1 / (2 * n), 1 + 1 / n) VAR m = DIVIDE(1, 1 + 1 / n) * SQRT(p * (1 - p) / n + 1 / (4 * n * n)) RETURN IF(n > 0, c - m)",
            "description": "Límite inferior de Wilson (z = 1) de impago",
            "formatString": "0.00%"
          },
          {
            "name": "Impago Wilson Superior",
            "expression": "VAR n = [Num Prestamos] VAR p = DIVIDE([Prestamos con Impago] + 0, n) VAR c = DIVIDE(p + 1 / (2 * n), 1 + 1 / n) VAR m = DIVIDE(1, 1 + 1 / n) * SQRT(p * (1 - p) / n + 1 / (4 * n * n)) RETURN IF(n > 0, c + m)",
            "description": "Límite superior de Wilson (z = 1) de impago",
            "formatString": "0.00%"
          },
          {
            "name": "Tasa Mora Banco",
            "expression": "CALCULATE([Tasa Mora Vigente], REMOVEFILTERS(m_distritos))",
            "description": "Referencia de P2: la tasa del banco, sin el filtro de distrito",
            "formatString": "0.00%"
          },
          {
            "name": "Tasa Impago Banco",
            "expression": "CALCULATE([Tasa Impago], REMOVEFILTERS(m_prestamos[banda_capacidad], m_prestamos[orden_banda]))",
            "description": "Referencia de P6: impago de todas las bandas",
            "formatString": "0.00%"
          },
          {
            "name": "Tasa Incumplimiento Banco",
            "expression": "CALCULATE([Tasa Incumplimiento], REMOVEFILTERS(m_clientes))",
            "description": "Referencia de P6: incumplimiento de todos los segmentos de edad",
            "formatString": "0.00%"
          },
          {
            "name": "Tasa Impago Banda Baja",
            "expression": "CALCULATE([Tasa Impago], KEEPFILTERS(m_prestamos[banda_capacidad] = \"Baja\"))",
            "description": "Impago de la banda Baja (2.92%); KEEPFILTERS respeta los demás filtros",
            "formatString": "0.00%"
          },
          {
            "name": "Tasa Impago Banda Alta",
            "expression": "CALCULATE([Tasa Impago], KEEPFILTERS(m_prestamos[banda_capacidad] = \"Alta\"))",
            "description": "Impago de la banda Alta (23.26%)",
            "formatString": "0.00%"
          },
          {
            "name": "Cartera Total",
            "expression": "SUM(m_prestamos[monto_prestamo])",
            "description": "Monto original de todos los préstamos ($103,261,740)",
            "formatString": "\"$\"#,0"
          },
          {
            "name": "Cartera Vigente",
            "expression": "CALCULATE([Cartera Total], m_prestamos[codigo_estado] IN {\"C\", \"D\"})",
            "description": "Monto original C + D ($80,296,176)",
            "formatString": "\"$\"#,0"
          },
          {
            "name": "Saldo por Cobrar Estimado",
            "expression": "CALCULATE(SUM(m_prestamos[saldo_pendiente_estimado]), m_prestamos[codigo_estado] IN {\"C\", \"D\"})",
            "description": "Capital pendiente estimado de la cartera vigente ($46,620,926)",
            "formatString": "\"$\"#,0"
          },
          {
            "name": "Monto Original en Riesgo",
            "expression": "CALCULATE([Cartera Total], m_prestamos[codigo_estado] IN {\"B\", \"D\"})",
            "description": "Monto original de los préstamos B + D ($15,580,152)",
            "formatString": "\"$\"#,0"
          },
          {
            "name": "Monto Incumplido",
            "expression": "CALCULATE([Cartera Total], m_prestamos[codigo_estado] = \"B\")",
            "description": "Monto original de los préstamos B",
            "formatString": "\"$\"#,0"
          },
          {
            "name": "Cuota Mensual",
            "expression": "SUM(m_prestamos[pago_mensual])",
            "description": "Cuota mensual de los préstamos del contexto",
            "formatString": "\"$\"#,0"
          },
          {
            "name": "Clientes con Impago",
            "expression": "CALCULATE(DISTINCTCOUNT(m_prestamos[id_cliente]), m_prestamos[codigo_estado] = \"B\")",
            "description": "Titulares con préstamo B (31): lista de denegación",
            "formatString": "#,0"
          },
          {
            "name": "Cartera Distritos Sobre Mora Banco",
            "expression": "VAR moraBanco = CALCULATE([Tasa Mora Vigente], REMOVEFILTERS(m_distritos)) RETURN CALCULATE([Cartera Vigente], FILTER(VALUES(m_distritos[nombre_distrito]), [Tasa Mora Vigente] > moraBanco))",
            "description": "CALCULATE + FILTER: cartera vigente de los distritos con mora sobre la del banco",
            "formatString": "\"$\"#,0"
          },
          {
            "name": "Distritos Sobre Mora Banco",
            "expression": "VAR moraBanco = CALCULATE([Tasa Mora Vigente], REMOVEFILTERS(m_distritos)) RETURN COUNTROWS(FILTER(VALUES(m_distritos[nombre_distrito]), [Tasa Mora Vigente] > moraBanco))",
            "description": "Distritos con tasa de mora vigente sobre la del banco",
            "formatString": "#,0"
          },
          {
            "name": "Region Mayor Mora",
            "expression": "VAR r = TOPN(1, FILTER(VALUES(m_distritos[region]), [Prestamos Vigentes] > 0), [Tasa Mora Vigente], DESC) RETURN CONCATENATEX(r, m_distritos[region] & \" · \" & FORMAT([Tasa Mora Vigente], \"0.0%\"), \", \")",
            "description": "north Moravia · 15.8%"
          },
          {
            "name": "Distrito Mayor Morosos",
            "expression": "VAR d = TOPN(1, FILTER(VALUES(m_distritos[nombre_distrito]), [Prestamos en Mora] > 0), [Prestamos en Mora], DESC) RETURN CONCATENATEX(d, m_distritos[nombre_distrito] & \" · \" & [Prestamos en Mora] & \" en mora\", \", \")",
            "description": "Hl.m. Praha · 4 en mora"
          },
          {
            "name": "Estado Prestamo",
            "expression": "IF([Num Prestamos] > 0, CALCULATE(CONCATENATEX(VALUES(m_prestamos[estado]), m_prestamos[estado], \", \"), m_prestamos))",
            "description": "Estado del préstamo del cliente o de la cuenta (fichas)"
          },
          {
            "name": "Banda Capacidad",
            "expression": "IF([Num Prestamos] > 0, CONCATENATEX(VALUES(m_prestamos[banda_capacidad]), m_prestamos[banda_capacidad], \", \"))",
            "description": "Banda de capacidad de pago (ratio cuota / saldo previo)"
          },
          {
            "name": "Distrito Prestamo",
            "expression": "IF([Num Prestamos] > 0, CALCULATE(CONCATENATEX(VALUES(m_distritos[nombre_distrito]), m_distritos[nombre_distrito], \", \"), m_prestamos))",
            "description": "Distrito de la cuenta del préstamo"
          },
          {
            "name": "Banda Capacidad Impago",
            "expression": "CALCULATE([Banda Capacidad], m_prestamos[codigo_estado] = \"B\")",
            "description": "Banda del préstamo B (lista de P6)"
          },
          {
            "name": "Distrito Impago",
            "expression": "CALCULATE([Distrito Prestamo], m_prestamos[codigo_estado] = \"B\")",
            "description": "Distrito del préstamo B (lista de P6)"
          },
          {
            "name": "Saldo Neto Corte",
            "expression": "VAR ultimoMes = CALCULATE(MAX(m_meses[fecha_mes]), m_saldo_mensual) RETURN CALCULATE(SUM(m_saldo_mensual[saldo_fin_mes]), FILTER(ALL(m_meses), m_meses[fecha_mes] = ultimoMes))",
            "description": "Saldo al cierre del último mes del contexto ($197,140,434 en dic-1998)",
            "formatString": "\"$\"#,0"
          },
          {
            "name": "Cuentas Activas Corte",
            "expression": "VAR ultimoMes = CALCULATE(MAX(m_meses[fecha_mes]), m_saldo_mensual) RETURN CALCULATE(COUNTROWS(m_saldo_mensual), FILTER(ALL(m_meses), m_meses[fecha_mes] = ultimoMes))",
            "description": "Cuentas con foto en el último mes del contexto (4,500 en dic-1998)",
            "formatString": "#,0"
          },
          {
            "name": "Cuentas en Sobregiro",
            "expression": "VAR ultimoMes = CALCULATE(MAX(m_meses[fecha_mes]), m_saldo_mensual) RETURN CALCULATE(CALCULATE(COUNTROWS(m_saldo_mensual), m_saldo_mensual[en_sobregiro] = TRUE()), FILTER(ALL(m_meses), m_meses[fecha_mes] = ultimoMes))",
            "description": "Cuentas con saldo negativo al cierre del último mes (39 en dic-1998)",
            "formatString": "#,0"
          },
          {
            "name": "Saldo Promedio por Cuenta",
            "expression": "DIVIDE([Saldo Neto Corte], [Cuentas Activas Corte])",
            "description": "Saldo por cuenta activa: aísla el crecimiento por apertura de cuentas",
            "formatString": "\"$\"#,0"
          },
          {
            "name": "Saldo Promedio Banco",
            "expression": "CALCULATE([Saldo Promedio por Cuenta], REMOVEFILTERS(m_distritos))",
            "description": "Referencia gris de D1",
            "formatString": "\"$\"#,0"
          },
          {
            "name": "Umbral Sobregiro",
            "expression": "IF(NOT ISBLANK([Saldo Neto Corte]), 0)",
            "description": "Línea en 0 de la ficha D2",
            "formatString": "\"$\"#,0.00"
          },
          {
            "name": "Saldo Neto Corte Total",
            "expression": "CALCULATE([Saldo Neto Corte], REMOVEFILTERS(m_anios), REMOVEFILTERS(m_meses))",
            "description": "Saldo al corte dic-1998, sin importar el año elegido",
            "formatString": "\"$\"#,0"
          },
          {
            "name": "Cartera Vigente Corte",
            "expression": "CALCULATE([Cartera Vigente], REMOVEFILTERS(m_anios), REMOVEFILTERS(m_meses))",
            "description": "Cartera vigente al corte, sin importar el año elegido",
            "formatString": "\"$\"#,0"
          },
          {
            "name": "Absorcion Vigente",
            "expression": "DIVIDE([Cartera Vigente Corte], [Saldo Neto Corte Total])",
            "description": "KPI de liquidez de la Carta v8: cartera vigente / saldo neto al corte (40.73%)",
            "formatString": "0.00%"
          },
          {
            "name": "Absorcion Cartera Total",
            "expression": "DIVIDE(CALCULATE([Cartera Total], REMOVEFILTERS(m_anios), REMOVEFILTERS(m_meses)), [Saldo Neto Corte Total])",
            "description": "Referencia histórica: cartera total / saldo neto (52.38%)",
            "formatString": "0.00%"
          },
          {
            "name": "Absorcion Banco",
            "expression": "CALCULATE([Absorcion Vigente], REMOVEFILTERS(m_distritos))",
            "description": "Referencia de P3: absorción del banco",
            "formatString": "0.00%"
          },
          {
            "name": "Liquidez Libre",
            "expression": "[Saldo Neto Corte Total] - [Cartera Vigente Corte]",
            "description": "Saldo que no respalda cartera vigente ($116,844,258)",
            "formatString": "\"$\"#,0"
          },
          {
            "name": "Valor Composicion Liquidez",
            "expression": "SWITCH(SELECTEDVALUE(Composicion_Liquidez[concepto]), \"Saldo neto al corte\", [Saldo Neto Corte Total], \"Cartera vigente\", -[Cartera Vigente Corte])",
            "description": "Cascada de P3; el total es la liquidez libre",
            "formatString": "\"$\"#,0"
          },
          {
            "name": "Volumen Transaccionado",
            "expression": "SUM(m_trans_anual[monto_total])",
            "description": "$6,257,862,197",
            "formatString": "\"$\"#,0"
          },
          {
            "name": "Num Transacciones",
            "expression": "SUM(m_trans_anual[num_transacciones])",
            "description": "1,056,320",
            "formatString": "#,0"
          },
          {
            "name": "Ticket Promedio",
            "expression": "DIVIDE([Volumen Transaccionado], [Num Transacciones])",
            "description": "Monto promedio por movimiento",
            "formatString": "\"$\"#,0.00"
          },
          {
            "name": "Desv Est Transaccion",
            "expression": "VAR n = [Num Transacciones] VAR s = [Volumen Transaccionado] VAR sq = SUM(m_trans_anual[suma_cuadrados]) RETURN IF(n > 1, SQRT(DIVIDE(sq - s * s / n, n - 1)))",
            "description": "σ muestral exacta desde la suma y la suma de cuadrados",
            "formatString": "\"$\"#,0.00"
          },
          {
            "name": "Ticket Limite Superior",
            "expression": "[Ticket Promedio] + [Desv Est Transaccion]",
            "description": "Promedio + 1σ",
            "formatString": "\"$\"#,0.00"
          },
          {
            "name": "Ticket Limite Inferior",
            "expression": "MAX(0, [Ticket Promedio] - [Desv Est Transaccion])",
            "description": "Promedio − 1σ (no negativo)",
            "formatString": "\"$\"#,0.00"
          },
          {
            "name": "EE Ticket",
            "expression": "DIVIDE([Desv Est Transaccion], SQRT([Num Transacciones]))",
            "description": "Error estándar (tooltip)",
            "formatString": "\"$\"#,0.00"
          },
          {
            "name": "Saldo Promedio Historico",
            "expression": "DIVIDE(SUMX(m_trans_anual, m_trans_anual[saldo_promedio] * m_trans_anual[num_transacciones]), [Num Transacciones])",
            "description": "Saldo promedio de la cuenta ponderado por movimientos",
            "formatString": "\"$\"#,0"
          },
          {
            "name": "Compromiso Ordenes",
            "expression": "SUM(m_ordenes[monto_orden])",
            "description": "Órdenes fijas mensuales ($21,229,041)",
            "formatString": "\"$\"#,0"
          },
          {
            "name": "Num Ordenes",
            "expression": "COUNTROWS(m_ordenes)",
            "description": "6,471 órdenes",
            "formatString": "#,0"
          },
          {
            "name": "Pct Ordenes",
            "expression": "DIVIDE([Num Ordenes], CALCULATE([Num Ordenes], REMOVEFILTERS(m_ordenes[categoria_orden])))",
            "description": "Participación de cada propósito",
            "formatString": "0.00%"
          },
          {
            "name": "Indice Saturacion",
            "expression": "DIVIDE([Compromiso Ordenes], CALCULATE([Saldo Promedio Historico], REMOVEFILTERS(m_anios), REMOVEFILTERS(m_meses), REMOVEFILTERS(m_trans_anual[categoria_analitica])))",
            "description": "Órdenes mensuales / saldo promedio histórico de la cuenta (cuenta 2335: 2.14)",
            "formatString": "0.00"
          },
          {
            "name": "Cuentas Saturadas",
            "expression": "COUNTROWS(FILTER(VALUES(m_cuentas[id_cuenta]), [Indice Saturacion] > 0.5))",
            "description": "CALCULATE + FILTER: cuentas con índice > 0.5 (47)",
            "formatString": "#,0"
          },
          {
            "name": "Cuentas Sobre Saldo",
            "expression": "COUNTROWS(FILTER(VALUES(m_cuentas[id_cuenta]), [Indice Saturacion] > 1))",
            "description": "Cuentas cuyas órdenes superan su saldo promedio (1)",
            "formatString": "#,0"
          },
          {
            "name": "Cuentas con Credito Externo",
            "expression": "CALCULATE(DISTINCTCOUNT(m_ordenes[id_cuenta]), m_cuentas[tiene_credito_externo] = TRUE())",
            "description": "Cuentas que pagan un préstamo a otra entidad (35)",
            "formatString": "#,0"
          },
          {
            "name": "Credito Externo Mensual",
            "expression": "CALCULATE([Compromiso Ordenes], m_cuentas[tiene_credito_externo] = TRUE(), m_ordenes[k_symbol] = \"UVER\")",
            "description": "Cuotas mensuales a otras entidades ($177,154)",
            "formatString": "\"$\"#,0"
          },
          {
            "name": "Indice Saturacion Alerta",
            "expression": "VAR i = [Indice Saturacion] RETURN IF(i > 0.5, i)",
            "description": "Solo cuentas en alerta",
            "formatString": "0.00"
          },
          {
            "name": "Compromiso Alerta",
            "expression": "IF([Indice Saturacion] > 0.5, [Compromiso Ordenes])",
            "description": "Solo cuentas en alerta",
            "formatString": "\"$\"#,0"
          },
          {
            "name": "Saldo Promedio Alerta",
            "expression": "IF([Indice Saturacion] > 0.5, CALCULATE([Saldo Promedio Historico], REMOVEFILTERS(m_anios), REMOVEFILTERS(m_meses), REMOVEFILTERS(m_trans_anual[categoria_analitica])))",
            "description": "Solo cuentas en alerta",
            "formatString": "\"$\"#,0"
          },
          {
            "name": "Credito Externo Alerta",
            "expression": "IF([Indice Saturacion] > 0.5, [Credito Externo Mensual])",
            "description": "Solo cuentas en alerta",
            "formatString": "\"$\"#,0"
          },
          {
            "name": "Cliente Titular Alerta",
            "expression": "IF([Indice Saturacion] > 0.5, CALCULATE(SELECTEDVALUE(m_clientes[cliente]), m_saldo_mensual))",
            "description": "Solo cuentas en alerta"
          },
          {
            "name": "Titulo Distrito",
            "expression": "\"Distrito: \" & SELECTEDVALUE(m_distritos[nombre_distrito], \"(varios)\") & \" (\" & SELECTEDVALUE(m_distritos[region], \"varias regiones\") & \")\"",
            "description": "Título dinámico de D1"
          },
          {
            "name": "Poblacion Distrito",
            "expression": "SELECTEDVALUE(m_distritos[poblacion])",
            "description": "Habitantes",
            "formatString": "#,0"
          },
          {
            "name": "Salario Promedio Distrito",
            "expression": "SELECTEDVALUE(m_distritos[salario_promedio])",
            "description": "Salario promedio",
            "formatString": "\"$\"#,0"
          },
          {
            "name": "Desempleo Distrito 1995",
            "expression": "SELECTEDVALUE(m_distritos[tasa_desempleo])",
            "description": "Tasa de desempleo 1995 (%)",
            "formatString": "0.00"
          },
          {
            "name": "Origen Indicadores",
            "expression": "IF(HASONEVALUE(m_distritos[es_imputado]), IF(VALUES(m_distritos[es_imputado]), \"Imputado (Informe 10)\", \"Fuente original\"))",
            "description": "Marca el distrito 69 con indicadores imputados"
          },
          {
            "name": "Cliente Ficha",
            "expression": "CALCULATE(SELECTEDVALUE(m_clientes[cliente]), m_saldo_mensual)",
            "description": "Titular de la cuenta (vale si se llega por cliente o por cuenta)"
          },
          {
            "name": "Cuenta Ficha",
            "expression": "CALCULATE(SELECTEDVALUE(m_cuentas[cuenta]), m_saldo_mensual)",
            "description": "Cuenta del titular"
          },
          {
            "name": "Titulo Cliente",
            "expression": "\"Ficha 360 · \" & COALESCE([Cliente Ficha], SELECTEDVALUE(m_clientes[cliente], \"(varios clientes)\")) & \" · \" & COALESCE([Cuenta Ficha], \"sin cuenta propia\")",
            "description": "Título dinámico de D2"
          },
          {
            "name": "Edad Cliente",
            "expression": "CALCULATE(SELECTEDVALUE(m_clientes[edad_corte]), m_saldo_mensual)",
            "description": "Edad al 31/12/1998",
            "formatString": "#,0"
          },
          {
            "name": "Segmento Cliente",
            "expression": "CALCULATE(SELECTEDVALUE(m_clientes[segmento_edad]), m_saldo_mensual)",
            "description": "Segmento de edad (3 grupos del Data Mart)"
          },
          {
            "name": "Arquetipo Cliente",
            "expression": "CALCULATE(SELECTEDVALUE(m_clientes[arquetipo_demografico]), m_saldo_mensual)",
            "description": "Macro-región y segmento"
          },
          {
            "name": "Calificacion Cliente",
            "expression": "CALCULATE(SELECTEDVALUE(m_clientes[calificacion_pago]), m_saldo_mensual)",
            "description": "Buen / Mal pagador / Sin evaluar"
          },
          {
            "name": "Distrito Cuenta",
            "expression": "CALCULATE(SELECTEDVALUE(m_distritos[nombre_distrito]), m_saldo_mensual)",
            "description": "Distrito de la cuenta"
          },
          {
            "name": "Cuota Maxima Prudente",
            "expression": "SUM(m_recomendaciones[prestamo_cuota_maxima])",
            "description": "Cuota que deja el ratio en la banda Baja (Informe 04)",
            "formatString": "\"$\"#,0"
          },
          {
            "name": "Monto Maximo Prudente",
            "expression": "SUM(m_recomendaciones[prestamo_monto_maximo_36m])",
            "description": "Monto a 36 meses con esa cuota (Informe 04)",
            "formatString": "\"$\"#,0"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "ccfd1686-3f3d-54ff-92c3-909777769fb4",
        "fromTable": "m_prestamos",
        "fromColumn": "id_distrito",
        "toTable": "m_distritos",
        "toColumn": "id_distrito"
      },
      {
        "name": "dc395a79-c617-57dd-9974-7fe68c0212e8",
        "fromTable": "m_prestamos",
        "fromColumn": "id_cliente",
        "toTable": "m_clientes",
        "toColumn": "id_cliente"
      },
      {
        "name": "bfbef033-10b6-5ed6-b6b5-cf6c9a98602f",
        "fromTable": "m_prestamos",
        "fromColumn": "id_cuenta",
        "toTable": "m_cuentas",
        "toColumn": "id_cuenta"
      },
      {
        "name": "b5db8dde-0944-5db4-bb17-d1363237647c",
        "fromTable": "m_ordenes",
        "fromColumn": "id_distrito",
        "toTable": "m_distritos",
        "toColumn": "id_distrito"
      },
      {
        "name": "89407216-f1b9-5356-b36a-b25e2766f75e",
        "fromTable": "m_ordenes",
        "fromColumn": "id_cliente",
        "toTable": "m_clientes",
        "toColumn": "id_cliente"
      },
      {
        "name": "7b0de087-a93f-508c-9ec4-b1e688e13b82",
        "fromTable": "m_ordenes",
        "fromColumn": "id_cuenta",
        "toTable": "m_cuentas",
        "toColumn": "id_cuenta"
      },
      {
        "name": "acbc0c28-7838-51c5-ad2d-c28a2b5c3788",
        "fromTable": "m_trans_anual",
        "fromColumn": "id_distrito",
        "toTable": "m_distritos",
        "toColumn": "id_distrito"
      },
      {
        "name": "59e4f306-68b4-5338-b1db-dde585c17cef",
        "fromTable": "m_trans_anual",
        "fromColumn": "id_cliente",
        "toTable": "m_clientes",
        "toColumn": "id_cliente"
      },
      {
        "name": "021ab3cc-68f0-5844-8870-7664757bf485",
        "fromTable": "m_trans_anual",
        "fromColumn": "id_cuenta",
        "toTable": "m_cuentas",
        "toColumn": "id_cuenta"
      },
      {
        "name": "18eb1775-fc7a-54c5-b65b-caff6dac8d04",
        "fromTable": "m_saldo_mensual",
        "fromColumn": "id_distrito",
        "toTable": "m_distritos",
        "toColumn": "id_distrito"
      },
      {
        "name": "ef991d89-1861-571d-ae10-0675c7e70ad5",
        "fromTable": "m_saldo_mensual",
        "fromColumn": "id_cliente",
        "toTable": "m_clientes",
        "toColumn": "id_cliente"
      },
      {
        "name": "01c79f9c-9b80-5264-9c0f-71bfc1472d20",
        "fromTable": "m_saldo_mensual",
        "fromColumn": "id_cuenta",
        "toTable": "m_cuentas",
        "toColumn": "id_cuenta"
      },
      {
        "name": "3134aef8-9ae9-58bd-b3d0-322762c06c56",
        "fromTable": "m_prestamos",
        "fromColumn": "anio",
        "toTable": "m_anios",
        "toColumn": "anio"
      },
      {
        "name": "08e82454-92f8-512a-a7ed-4b560d010664",
        "fromTable": "m_trans_anual",
        "fromColumn": "anio",
        "toTable": "m_anios",
        "toColumn": "anio"
      },
      {
        "name": "9a2ab26c-0fe3-5704-abf1-888d3ab58885",
        "fromTable": "m_saldo_mensual",
        "fromColumn": "fecha_mes",
        "toTable": "m_meses",
        "toColumn": "fecha_mes"
      },
      {
        "name": "3493831f-136e-5d57-8175-8525d9bac77b",
        "fromTable": "m_meses",
        "fromColumn": "anio",
        "toTable": "m_anios",
        "toColumn": "anio"
      },
      {
        "name": "b5efc4fc-b6ba-5770-9c55-6ef5d4a3325b",
        "fromTable": "m_recomendaciones",
        "fromColumn": "id_cuenta",
        "toTable": "m_cuentas",
        "toColumn": "id_cuenta"
      },
      {
        "name": "a2208bfe-ae88-5b79-9765-8b0cf9d3cc23",
        "fromTable": "m_recomendaciones",
        "fromColumn": "id_cliente",
        "toTable": "m_clientes",
        "toColumn": "id_cliente"
      }
    ],
    "expressions": [
      {
        "name": "MongoFinancial",
        "kind": "m",
        "expression": [
          "let",
          "    Origen = Python.Execute(\"\"\"\"\"\"\"#(lf)==============================================================================#(lf)UNIVERSIDAD TÉCNICA DE AMBATO - Inteligencia de Negocios#(lf)AUTORES: Alison Marcela Cobos Taco / Henry Daniel Lagua Flores#(lf)==============================================================================#(lf)ARCHIVO: 26_powerbi_mongo_dashboard.py   (Guía 07 v4)#(lf)USO EN POWER BI: el script 30 lo incrusta en la consulta MongoFinancial del#(lf)                 proyecto Dashboard_Financial_Mongo.pbip. También se puede#(lf)                 ejecutar suelto para revisar las tablas.#(lf)#(lf)Construye, desde la base documental 'Financial' (cargada por el script 35 y#(lf)completada por el 42), las mismas tablas que el modelo Kimball, con los mismos#(lf)nombres de columnas, para que las medidas DAX sean idénticas:#(lf)#(lf)  m_distritos         77   (Dim_Distrito)#(lf)  m_clientes       5,369   (Dim_Cliente)#(lf)  m_cuentas        4,500   (Dim_Cuenta)#(lf)  m_anios              6   (Dim_Anio)#(lf)  m_meses             72   (meses de la foto de saldos)#(lf)  m_prestamos        682   (Fact_Prestamos)#(lf)  m_ordenes        6,471   (Fact_Ordenes)#(lf)  m_trans_anual   54,298   (vw_PBI_Trans_Anual_Cuenta: agregado en MongoDB con $group)#(lf)  m_saldo_mensual 185,615  (Fact_Saldo_Cuenta_Mensual)#(lf)  m_recomendaciones 4,500  (Recomendacion_Cuenta)#(lf)==============================================================================#(lf)\"\"\"\"\"\"#(lf)import pandas as pd#(lf)import pymongo#(lf)#(lf)MONGO_URI = \"\"mongodb://localhost:27017/\"\"#(lf)DB_NAME = \"\"Financial\"\"#(lf)#(lf)client = pymongo.MongoClient(MONGO_URI)#(lf)db = client[DB_NAME]#(lf)#(lf)#(lf)def macro(region):#(lf)    return \"\"Praga\"\" if region == \"\"Prague\"\" else (\"\"Moravia\"\" if \"\"Moravia\"\" in str(region) else \"\"Bohemia\"\")#(lf)#(lf)#(lf)# ---- Dimensiones ----#(lf)m_distritos = pd.DataFrame([{#(lf)    \"\"id_distrito\"\": d[\"\"id_distrito\"\"], \"\"nombre_distrito\"\": d[\"\"nombre\"\"], \"\"region\"\": d[\"\"region\"\"], \"\"poblacion\"\": d[\"\"poblacion\"\"],#(lf)    \"\"salario_promedio\"\": d[\"\"salario_promedio\"\"], \"\"tasa_desempleo\"\": d[\"\"indicadores_1995\"\"][\"\"tasa_desempleo\"\"],#(lf)    \"\"tasa_criminalidad\"\": d[\"\"indicadores_1995\"\"][\"\"tasa_criminalidad\"\"], \"\"es_imputado\"\": d[\"\"auditoria\"\"][\"\"es_imputado\"\"],#(lf)} for d in db.distritos.find({})])#(lf)m_distritos[\"\"macro_region\"\"] = m_distritos.region.map(macro)#(lf)#(lf)filas_cli, filas_cta = [], {}#(lf)for c in db.FinancialMongo.find({}, {\"\"ordenes_recurrentes\"\": 0, \"\"prestamo_asociado\"\": 0}):#(lf)    filas_cli.append({#(lf)        \"\"id_cliente\"\": c[\"\"id_cliente\"\"], \"\"cliente\"\": f\"\"Cliente {c['id_cliente']}\"\", \"\"sexo\"\": c[\"\"datos_personales\"\"][\"\"sexo\"\"],#(lf)        \"\"edad_corte\"\": c[\"\"datos_personales\"\"][\"\"edad_al_corte_1998\"\"], \"\"tipo_disposicion\"\": c[\"\"datos_personales\"\"][\"\"tipo_disposicion\"\"],#(lf)        \"\"segmento_edad\"\": c[\"\"perfil_analitico\"\"][\"\"segmento_edad\"\"], \"\"arquetipo_demografico\"\": c[\"\"perfil_analitico\"\"][\"\"arquetipo_demografico\"\"],#(lf)        \"\"calificacion_pago\"\": c[\"\"evaluacion_crediticia\"\"][\"\"calificacion\"\"]})#(lf)    cta = c[\"\"cuenta\"\"]#(lf)    filas_cta[cta[\"\"id_cuenta\"\"]] = {\"\"id_cuenta\"\": cta[\"\"id_cuenta\"\"], \"\"frecuencia_extracto\"\": cta[\"\"frecuencia_extracto\"\"],#(lf)                                   \"\"fecha_apertura\"\": cta[\"\"fecha_apertura\"\"], \"\"tiene_credito_externo\"\": cta[\"\"tiene_credito_externo\"\"],#(lf)                                   \"\"monto_credito_externo\"\": cta[\"\"monto_credito_externo\"\"]}#(lf)m_clientes = pd.DataFrame(filas_cli)#(lf)# Columnas de orden de las categorías ordinales (Power BI ordena por ellas, no alfabéticamente)#(lf)m_clientes[\"\"orden_segmento\"\"] = m_clientes.segmento_edad.map(#(lf)    lambda s: 1 if \"\"Joven\"\" in s else (3 if \"\"Mayor\"\" in s else 2)).astype(\"\"int64\"\")#(lf)m_cuentas = pd.DataFrame(list(filas_cta.values()))#(lf)m_cuentas[\"\"fecha_apertura\"\"] = pd.to_datetime(m_cuentas.fecha_apertura)#(lf)m_anios = pd.DataFrame({\"\"anio\"\": range(1993, 1999)})#(lf)m_meses = pd.DataFrame({\"\"fecha_mes\"\": pd.date_range(\"\"1993-01-31\"\", \"\"1998-12-31\"\", freq=\"\"ME\"\")})#(lf)m_meses[\"\"anio\"\"] = m_meses.fecha_mes.dt.year#(lf)m_meses[\"\"mes\"\"] = m_meses.fecha_mes.dt.month#(lf)#(lf)# ---- Hechos ----#(lf)m_prestamos = pd.DataFrame([{#(lf)    \"\"id_prestamo\"\": p[\"\"id_prestamo\"\"], \"\"id_cuenta\"\": p[\"\"id_cuenta\"\"], \"\"id_cliente\"\": p[\"\"id_cliente\"\"], \"\"id_distrito\"\": p[\"\"id_distrito\"\"],#(lf)    \"\"fecha_otorgamiento\"\": p[\"\"condiciones\"\"][\"\"fecha_otorgamiento\"\"], \"\"anio\"\": p[\"\"anio\"\"], \"\"monto_prestamo\"\": p[\"\"condiciones\"\"][\"\"monto\"\"],#(lf)    \"\"plazo_meses\"\": p[\"\"condiciones\"\"][\"\"plazo_meses\"\"], \"\"pago_mensual\"\": p[\"\"condiciones\"\"][\"\"cuota_mensual\"\"],#(lf)    \"\"saldo_pendiente_estimado\"\": p[\"\"condiciones\"\"][\"\"saldo_pendiente_estimado\"\"],#(lf)    \"\"meses_transcurridos_al_corte\"\": p[\"\"condiciones\"\"][\"\"meses_transcurridos_al_corte\"\"],#(lf)    \"\"codigo_estado\"\": p[\"\"evaluacion_riesgo\"\"][\"\"codigo_estado\"\"], \"\"condicion\"\": p[\"\"evaluacion_riesgo\"\"][\"\"condicion\"\"],#(lf)    \"\"descripcion_estado\"\": p[\"\"evaluacion_riesgo\"\"][\"\"descripcion\"\"],#(lf)    \"\"saldo_promedio_previo\"\": p[\"\"capacidad_pago\"\"][\"\"saldo_promedio_previo\"\"],#(lf)    \"\"ratio_cuota_saldo_previo\"\": p[\"\"capacidad_pago\"\"][\"\"ratio_cuota_saldo_previo\"\"],#(lf)    \"\"banda_capacidad\"\": p[\"\"capacidad_pago\"\"][\"\"banda_capacidad\"\"],#(lf)} for p in db.prestamos.find({})])#(lf)m_prestamos[\"\"fecha_otorgamiento\"\"] = pd.to_datetime(m_prestamos.fecha_otorgamiento)#(lf)m_prestamos[\"\"orden_banda\"\"] = m_prestamos.banda_capacidad.map({\"\"Baja\"\": 1, \"\"Media-baja\"\": 2, \"\"Media-alta\"\": 3, \"\"Alta\"\": 4}).astype(\"\"int64\"\")#(lf)#(lf)m_ordenes = pd.DataFrame([{#(lf)    \"\"id_orden\"\": o[\"\"id_orden\"\"], \"\"id_cuenta\"\": o[\"\"id_cuenta\"\"], \"\"id_cliente\"\": o[\"\"id_cliente\"\"], \"\"id_distrito\"\": o[\"\"id_distrito\"\"],#(lf)    \"\"k_symbol\"\": o[\"\"categoria_pago\"\"][\"\"codigo\"\"], \"\"categoria_orden\"\": o[\"\"categoria_pago\"\"][\"\"descripcion\"\"], \"\"monto_orden\"\": o[\"\"monto_mensual\"\"],#(lf)} for o in db.ordenes.find({})])#(lf)#(lf)# Agregado anual por cuenta y categoría, calculado DENTRO de MongoDB#(lf)m_trans_anual = pd.json_normalize(list(db.transacciones.aggregate([#(lf)    {\"\"$group\"\": {\"\"_id\"\": {\"\"id_cuenta\"\": \"\"$id_cuenta\"\", \"\"anio\"\": \"\"$anio\"\", \"\"categoria_analitica\"\": \"\"$tipo_operacion_traducido\"\"},#(lf)                \"\"id_cliente\"\": {\"\"$first\"\": \"\"$id_cliente\"\"}, \"\"id_distrito\"\": {\"\"$first\"\": \"\"$id_distrito\"\"},#(lf)                \"\"num_transacciones\"\": {\"\"$sum\"\": 1}, \"\"monto_total\"\": {\"\"$sum\"\": \"\"$monto_transaccion\"\"},#(lf)                \"\"suma_cuadrados\"\": {\"\"$sum\"\": {\"\"$multiply\"\": [\"\"$monto_transaccion\"\", \"\"$monto_transaccion\"\"]}},#(lf)                \"\"saldo_promedio\"\": {\"\"$avg\"\": \"\"$saldo_cuenta\"\"}}}], allowDiskUse=True)))#(lf)m_trans_anual.columns = [c.replace(\"\"_id.\"\", \"\"\"\") for c in m_trans_anual.columns]#(lf)#(lf)m_saldo_mensual = pd.DataFrame(list(db.saldos_mensuales.find({}, {\"\"_id\"\": 0})))#(lf)m_saldo_mensual[\"\"fecha_mes\"\"] = pd.to_datetime(dict(year=m_saldo_mensual.anio, month=m_saldo_mensual.mes, day=1)) + pd.offsets.MonthEnd(0)#(lf)m_saldo_mensual[\"\"en_sobregiro\"\"] = m_saldo_mensual.en_sobregiro.astype(bool)#(lf)#(lf)m_recomendaciones = pd.DataFrame([{#(lf)    \"\"id_cuenta\"\": r[\"\"id_cuenta\"\"], \"\"id_cliente\"\": r[\"\"id_cliente\"\"], \"\"modelo\"\": r[\"\"modelo\"\"],#(lf)    \"\"recomendacion_1\"\": (r[\"\"recomendaciones\"\"] + [None] * 3)[0], \"\"recomendacion_2\"\": (r[\"\"recomendaciones\"\"] + [None] * 3)[1],#(lf)    \"\"recomendacion_3\"\": (r[\"\"recomendaciones\"\"] + [None] * 3)[2],#(lf)    \"\"prestamo_cuota_maxima\"\": r[\"\"prestamo_cuota_maxima\"\"], \"\"prestamo_monto_maximo_36m\"\": r[\"\"prestamo_monto_maximo_36m\"\"],#(lf)} for r in db.recomendaciones.find({})])#(lf)#(lf)# El puente Python de Power BI no reconoce StringDtype (pandas >= 3) ni fechas en microsegundos#(lf)for df in (m_meses, m_distritos, m_clientes, m_cuentas, m_prestamos, m_ordenes, m_trans_anual, m_saldo_mensual, m_recomendaciones):#(lf)    for col in df.columns:#(lf)        if pd.api.types.is_string_dtype(df[col]) and not pd.api.types.is_object_dtype(df[col]):#(lf)            df[col] = df[col].astype(object)#(lf)        elif pd.api.types.is_datetime64_any_dtype(df[col]):#(lf)            df[col] = df[col].astype(\"\"datetime64[ns]\"\")   # resolución que espera el puente de Power BI#(lf)#(lf)client.close()#(lf)#(lf)print(\"\"Tablas MongoDB listas para Power BI:\"\")#(lf)for nombre in [\"\"m_distritos\"\", \"\"m_clientes\"\", \"\"m_cuentas\"\", \"\"m_anios\"\", \"\"m_meses\"\", \"\"m_prestamos\"\", \"\"m_ordenes\"\",#(lf)               \"\"m_trans_anual\"\", \"\"m_saldo_mensual\"\", \"\"m_recomendaciones\"\"]:#(lf)    print(f\"\"  - {nombre:<18} {len(globals()[nombre]):>8,} filas\"\")#(lf)\")",
          "in",
          "    Origen"
        ]
      }
    ],
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      }
    ]
  }
}